### ISSUE TITLE
【Feature】bee-table 组件支持用户可动态展示列数据

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper-bee#103]
### Bug 报告

- __Package version(s)__: (版本号) v1.1.2

#### 期望的行为:

bee-table 组件支持用户可动态展示列数据

**Comment by jonyshi** [comment]
bee-table 1.1.7 版本已经支持了。

参考示例

[代码](https://github.com/tinper-bee/bee-table/blob/master/demo/demolist/Demo21.js)
