### ISSUE TITLE
希望bee-table组件支持列数据过长时只部分显示，并可查看完整内容

### ISSUE THREAD

**Issue by guooooooo** [iuap-design/tinper-bee#107]
### Bug 报告

- __Package version(s)__: (版本号)tinper-bee: 1.3.2

#### 描述这个问题:

希望table组件支持列数据过长时只部分显示，并可查看完整内容

#### 当前的行为:

table组件当某一列数据过长时，会使该列所占宽度过大，而导致table后面部分列被挤压出去无法显示

#### 期望的行为:

希望table组件支持列数据过长时只部分显示，并可查看完整内容

**Comment by kvkens** [comment]
@jonyshi 给出解决方案或示例

**Comment by jonyshi** [comment]
已经给出示例了。

具体代码参考。
@guooooooo 
@kvkens 
@GuoYongfeng 

https://github.com/tinper-bee/bee-table/blob/master/demo/demolist/Demo1.js
