### ISSUE TITLE
Table组件行双击事件未屏蔽行单击事件[贵冶]

### ISSUE THREAD

**Issue by liuzhengithub** [iuap-design/tinper-bee#108]
### Bug 报告

- __Package version(s)__: (版本号)

#### 当前的行为:

Table组件行双击事件未屏蔽行单击事件

#### 期望的行为:

Table组件行双击事件和行单击事件相互独立，互不干涉

**Comment by jonyshi** [comment]
组件已经做了升级。
单独升级bee-table 版本>=1.1.3即可。
