### ISSUE TITLE
bee-modal 当backdrop={false } 时，点击窗口以外的内容，无法关闭掉当前的窗口。

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#109]
### Bug 报告

- __Package version(s)__: (版本号)  1.0.3

#### 描述这个问题: 
<Modal
                    show={ this.state.showModal }
                    backdrop={false } >
                    <Modal.Header closeButton>
                        <Modal.Title > 我来组成头部 </Modal.Title>
                    </Modal.Header >
                    <Modal.Body >
                        <h4> 这是一个沉默的标题 </h4> 
                    </Modal.Body>
                    <Modal.Footer>
                      
                    </Modal.Footer>
                </Modal>

#### 当前的行为:

当我们把 backdrop={false }  的时候，我们点击窗口以外的内容，无法关闭掉当前的窗口。

#### 期望的行为:

把 backdrop={false }  的时候，我们点击窗口以外的内容，可以把前的窗口关掉。

**Comment by kvkens** [comment]
似乎有一个看不见的div在阻挡人类发展文明。
