### ISSUE TITLE
表格Table控件-贵冶

### ISSUE THREAD

**Issue by feiyue227** [iuap-design/tinper-bee#114]
#### 当前的行为：selectedList能获取到选中数据，但是第一列选中框未显示选中
<img width="400" alt="2018-05-08 1 58 40" src="https://user-images.githubusercontent.com/20714349/39740381-f25e8d86-52c7-11e8-9875-861698c74d15.png">

**Comment by kvkens** [comment]
让赵沛来帮你解决，这个他那边就没问题，本身没有问题，要考虑应用场景。

**Comment by jonyshi** [comment]
麻烦你把问题描述清楚一下，到底是table的bug还是tabs的bug？
