### ISSUE TITLE
Carousel 轮播图组件不能使用

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#116]
### Bug 报告

- __Package version(s)__: (版本号)1.3.7

#### 描述这个问题:
按照文档使用报错

![image](https://user-images.githubusercontent.com/3817644/39951889-d7700918-55c0-11e8-8697-985bba4522bb.png)

**Comment by kvkens** [comment]
我现在npm下载最新1.4.0在测试下。

**Comment by kvkens** [comment]
自行解决，发现只能按照官网那样的例子路径去找那个js，自己去解构的方式不可以。

我单独安装了npm版本的bee，临时解决，但是无法使用CDN的方式。

**Comment by BoyuZhou** [comment]
使用`import Carousel from 'tinper-bee/lib/Carousel';`这样的方式引用可以
