### ISSUE TITLE
表格拖拽调整列宽时，影响其他列的宽度

### ISSUE THREAD

**Issue by zhaopei12138** [iuap-design/tinper-bee#118]
### Bug 报告

- __Package version(s)__: (版本号) @1.3.7

#### 描述这个问题:

表格拖拽调整列宽时，影响其他列的宽度

#### 当前的行为:

官网例子中，调整性别一列的宽度，姓名和年龄列宽度会变小

#### 期望的行为:

表格拖拽调整列宽时，只有当前列宽度改变，其他列的宽度不变

**Comment by BoyuZhou** [comment]
@zhaopei12138 表格拖拽调整列宽时，只有当前列宽度改变，其他列的宽度不变。这样做的话，整个表格的宽度就会改变

**Comment by kvkens** [comment]
试着一些columns的`width:110px`和`width:20%`这样去设置呢？

**Comment by BoyuZhou** [comment]
@zhaopei12138 @kvkens 添加一个这个属性scroll={{x:700}}，x为你的table的宽度
