### ISSUE TITLE
表格设置固定列后，会盖住非固定列[贵冶]

### ISSUE THREAD

**Issue by zhaopei12138** [iuap-design/tinper-bee#119]
### Bug 报告

- __Package version(s)__: (版本号) @1.3.7

#### 描述这个问题:

表格设置固定列时，非固定列左边的数据会被固定列盖住，无法显示

#### 当前的行为:

官网例子中，设置表格固定列，先固定Full Name列，再固定Column 1及之后的任意列，此时，age列被该固定列盖住了，age列无法显示，并且该固定列会左右出现两个
#### 期望的行为:

固定列不会盖住非固定列，固定列后，该列不在非固定列出现

**Comment by BoyuZhou** [comment]
@zhaopei12138  两种解决方案，一：有一个或多个列不设置具体宽度（可设置最小宽度）；二：如果每一个列都有宽度，可设置scroll={{x:1000}},x是你所有列宽度的和。这样就不会出现覆盖了
