### ISSUE TITLE
关于开发框架的讨论

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper-bee#12]
# 关于开发框架的讨论

## 背景

我们已经形成了开发工具uba和组件库bee，但是，基于react的技术栈，在路由和数据处理层面的技术和方案很多。并且基于redux的生态就比较复杂，如何提供一个开发框架让开发者快速进行应用开发成为了一个关键的问题。

## 需求

- 易上手，概念少
- 操作数据方便
- 后续可扩展性好
- 持续的生态要好

## 初步考虑

- 将 `react\react-dom\react-router\react-router-redux\redux\redux-saga\redux-thunk\redux-observable` 等封装起来，将这些类库本身提供的接口暴露，使用的时候方式不变，这样也是减少了开发者一上来就下载一堆包的烦恼。
- 做数据层能力增强、规范和约束，形成数据到UI的规范写法
- rxjs的引入有待考虑

## 思考

**我的部分想法：** 重新造一个框架，概念、实现、推广都是成本；而且 redux 社区有足够丰富的方案，可以拥抱社区红利；后续可扩展，单独的方案也可以加进来。

## 框架名字

agen ? 大家可以积极讨论。

**Comment by BoyuZhou** [comment]
redux-saga\redux-thunk\redux-observable这个三个感觉功能有一些重复啊，是不是要选一个

**Comment by GuoYongfeng** [comment]
已经提供 ucf-web
