### ISSUE TITLE
表格组件使用useFixedHeader无法固定表头

### ISSUE THREAD

**Issue by jrt8** [iuap-design/tinper-bee#120]
Bug 报告
Package version(s): (1.3.2)
描述这个问题:
Table组件使用useFixedHeader无法固定表头。

#### 当前的行为:

useFixedHeader无法固定表头，而使用scroll={y} 却可以固定

**Comment by whizbz11** [comment]
固定表头请使用scroll属性设置y的值{{y:true}}即可
