### ISSUE TITLE
提供checktable组件，同时支持列进行过滤、交换表头的顺序、拖拽调整列的宽度、动态设置固定取消固定列 [贵冶]

### ISSUE THREAD

**Issue by zhaopei12138** [iuap-design/tinper-bee#121]
### Bug 报告

- __Package version(s)__: (版本号)@1.3.7

#### 期望的行为:

提供checktable组件，支持列进行过滤、交换表头的顺序、拖拽调整列的宽度、动态设置固定取消固定列，可以通过属性控制。全选列也可以通过属性控制，显示为普通table或checktable

**Comment by kvkens** [comment]
已经沟通过，几个HOC嵌套使用即可。
