### ISSUE TITLE
部分组件的onBlur事件（需求）

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#123]
### 业务需求：某个控件鼠标离开时候出发onBlur事件，控件渲染浏览态文字。
涉及到控件：DataPicker、checkbox、radio、switch
已完成控件有onBlur（参照，select（些许bug），formControl、Number等）
需要：onBlur事件时候第一个参数为当前value值。onBlur: (val) => { console.log(‘当前值为：’’+ value) }

**Comment by jonyshi** [comment]
DataPicker，formControl 已经有onBlur和onFocus 。 
checkbox、radio、switch  这几个不太清楚你的意思，麻烦明确下。

**Comment by jonyshi** [comment]
@yang123guo

**Comment by GuoYongfeng** [comment]
1. Radio 组件：没有提供onBlur组件属性（function）
2. Checkbox 组件：没有提供onBlur组件属性（function）【紧急】。
3. Input：
4. Select：
5. DataPicker：没有提供onBlur组件属性（function）
6. Switch：提供 onActive 组件属性（type 为 function，function的传参应该是switch的值），switch组件处于被激活状态。

**Comment by yang123guo** [comment]
已经自己完成。不需要iuap的支持了。
