### ISSUE TITLE
Table组件列表头表体错位问题

### ISSUE THREAD

**Issue by Zander829** [iuap-design/tinper-bee#125]
版本号："bee-table": "^1.1.5",
现象：
scroll={{ y: 200 }}
添加参数scroll 横向或纵向支持滚动，也可用于指定滚动区域的宽高度：{ x: true, y: 300 } object {}
导致列 表头和表体错位

**Comment by jonyshi** [comment]
@Zander829  麻烦你把代码贴一下。

**Comment by jonyshi** [comment]
目前我们出现表头错位的解决办法有几种。
1. columns的数组里面，所有列都加width，最后一列不设置即可，可以避免列错位。
如果有横向滚动条的话，需要x 的值等于所有列宽度的和。

**Comment by jonyshi** [comment]
1. 在mac 下 滚动条是不占用宽度。
2. window 下，我们也没有包含这个宽度，所以导致表头错位。后续将会解决此问题【项目中可以使用css覆盖的方式，先处理】

**Comment by whizbz11** [comment]
升级下最新版本，这个问题已解决
