### ISSUE TITLE
upload组件问题

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#126]
### 需求

- __Package version(s)__: 最新 

1、upload上传过程中的 ajax.abort() 功能。
图： 
![1071528425113_ pic](https://user-images.githubusercontent.com/17383237/41136475-0525791c-6b09-11e8-9ec7-f8ae8459ce50.jpg)

2、上传失败以后，重新续传功能（继续上传）
图：
![1091528425175_ pic](https://user-images.githubusercontent.com/17383237/41136482-0cbd9132-6b09-11e8-88c4-4257f5b25f45.jpg)

#### 疑似bug  
上传中xhr2返回的progress不同步 ，具体表现为percent为100以后，过一段时间才抛出status为done

图：
![animation](https://user-images.githubusercontent.com/17383237/41137012-99a22926-6b0b-11e8-86bb-5777878b02d9.gif)

**Comment by yang123guo** [comment]
顶一下，还没有人回复。

**Comment by kvkens** [comment]
你这个很专业啊，我先观望下。

**Comment by kvkens** [comment]
国强兄，可否约战下代码？贴几段可以展示的代码，比如自行处理ajax相关操作，是否替换了内部的xmlhttprequest等

**Comment by kvkens** [comment]
备忘参考：https://www.jianshu.com/p/0d1421df0e0d

**Comment by yang123guo** [comment]
@kvkens  第一个是没有把xhr对象或者禁止方法或者上传时候没有钩子函数传出来，我没有机会参与。没有替换内部的xhr。
第二个是因为自动上传不是手动上传，失败了以后webFile没有保存，我也没法干预。
第三个进度问题，我也是读取的。这三处我都是读取属性然后操作，没有机会或者钩子函数操作xmlhttprequest。  至于代码和Demo差不多，没有特别的。
