### ISSUE TITLE
Table 动态列 filterColumn 会影响其他按钮事件

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#128]
### Bug 报告

- __Package version(s)__: (版本号)1.5.0

#### 描述这个问题:
```js
import filterColumn from "tinper-bee/lib/filterColumn";
```
使用后会导致我的按钮莫名其妙也被触发此事件.
先点击列，然后在点击我的按钮，就会把列显示出来。

![image](https://user-images.githubusercontent.com/3817644/41393436-63efe620-6fd8-11e8-914b-24e3e659d805.png)

![image](https://user-images.githubusercontent.com/3817644/41393467-8f76b24c-6fd8-11e8-87fc-fd959bf3f673.png)

还有一个BUG，动态列还跟我抢title的位置，导致显示错位

**Comment by jonyshi** [comment]
以及解决

**Comment by kvkens** [comment]
@jonyshi 解决方式不说下吗？我这更新组价库就好了？
