### ISSUE TITLE
upload组件多文件上传

### ISSUE THREAD

**Issue by lyx9439** [iuap-design/tinper-bee#130]

**Comment by kvkens** [comment]
这个需要手动上传的方式，首先阻止beforeUpload事件
```js
beforeUpload: (file) => {
                console.log(file);
                this.setState(({ fileList }) => ({
                    fileList: [...fileList, file],
                }));
                return false;
            }
```

然后自己去实现filelist，再用FormData手动维护这个对象，ajax post的时候放在参数上

```js
    startUploadClick = async () => {
        console.log(this.state.fileList);
        const { fileList } = this.state;
        const formData = new FormData();
        const data = this.props.data;
        fileList.forEach((file) => {
            formData.append(this.props.name, file);
        });
        for (let key in data) {
            formData.append(key, data[key]);
        }
        let result = await axios.post(this.props.action, formData);
    }

```

上面的代码是我自己在做应用组件部分代码，还没有实现完，主要的逻辑都在这里，注意一下
`formData.append(this.props.name, file);`这句，key就是后端接收的那个参数，一般是'files[]'注意是数组后端才会收到。

参考的文档给你看下：https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

**Comment by kvkens** [comment]
![image](https://user-images.githubusercontent.com/3817644/41910022-1800e280-797b-11e8-9c05-28cdb3cfe5bf.png)

这样的话，4张图片使用一次ajax提交，还可以附加一些参数过去。

**Comment by kvkens** [comment]
![image](https://user-images.githubusercontent.com/3817644/41910129-590300e2-797b-11e8-8903-26c77042e99e.png)
