### ISSUE TITLE
InputNumber 放在Table里面后，设置宽度后Input和微调就分家了

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#131]
### Bug 报告

- __Package version(s)__: (版本号)1.5.0

#### 描述这个问题:
![image](https://user-images.githubusercontent.com/3817644/41461012-fe53e390-70c0-11e8-84a0-edac9ed85668.png)

**Comment by BoyuZhou** [comment]
发布了tinper-bee@1.5.1，解决了这个问题

**Comment by kvkens** [comment]
@BoyuZhou 棒棒哒💯
