### ISSUE TITLE
Message组件，直接调用Message.create()会报错

### ISSUE THREAD

**Issue by lyx9439** [iuap-design/tinper-bee#133]
Message组件

在button的点击事件中调用Message.create({
    content: '123'
})是好使的

但是直接调用就会报错
render () {
    return <div>{Message.create({content: '123})}</div>
}

![image](https://user-images.githubusercontent.com/25003211/41657119-dfd81596-74c4-11e8-937c-01ee4e32b124.png)

**Comment by BoyuZhou** [comment]
Message并不能这么使用，只支持事件调用
