### ISSUE TITLE
dragColumn 表格的拖拽调整列的宽度失效

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#134]
### 详情

dragColumn 表格的拖拽调整列的宽度   
遇到 固定表头useFixedHeader失效，
遇到scroll失效  
遇到多表头失效（下图为我说的多表头）
![image](https://user-images.githubusercontent.com/17383237/42024276-5d4661f6-7af4-11e8-8bb0-66dfccf8205d.png)

**Comment by yang123guo** [comment]
遇到scroll失效的情况是 scroll中参数x和y同时存在时候有问题。

**Comment by jonyshi** [comment]
@yang123guo  目前此table 的拖拽宽度api限于组件设计初衷，只支持基础table的基础拖拽。

[基础组价拖拽demo](https://github.com/tinper-bee/bee-table/blob/master/demo/demolist/Demo23.js)

[拖拽组合应用](https://github.com/tinper-bee/bee-table/blob/master/demo/demolist/Demo25.js)

**Comment by jonyshi** [comment]
后续会出一个table的高级组件，将会支持。
