### ISSUE TITLE
DropDown 禁用启用需求。

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#135]
### 涉及到的组件 
     DropDown

#### 期望的行为:

就是在某些场景下，dropDown是不能通过预置的trigger触发的，
所以需要一个类似于按钮一样的不可点击效果(disabled = {true})，或者有什么方法控制吗？
通过控制true/false来使得DropDown 禁用启用、

**Comment by yang123guo** [comment]
@jonyshi

**Comment by yang123guo** [comment]
dropDown点击以后的钩子函数也需要。

**Comment by lucian55** [comment]
bee-dropdown@2.0.5 可用 disabled属性。
dropDown点击以后的钩子函数：dropdown的child元素配置onClick
