### ISSUE TITLE
bee-modal 组件的z-index过高，导致无法被Loading组件遮挡

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#137]
使用Loading组件在遮挡Modal的时候，发现Loading是被盖在了下面，无法实现操作等待，需要处理Loading和Modal的z-index之间的数值关系

**Comment by jonyshi** [comment]
因为modal 里面有考虑多层弹出的，所以在设置z-index的时候，如果出现这种遮挡，需要自己在业务里面控制z-index。
@kvkens

**Comment by kvkens** [comment]
这样做好苦逼，还要自己维护z-index
