### ISSUE TITLE
组件库样式总体讨论

### ISSUE THREAD

**Issue by BoyuZhou** [iuap-design/tinper-bee#14]
考量组件库整体可定制能力，和一致性效果。
讨论一下组件库整体样式的一些配置。
包括但不限于：

### 颜色

- 主题色及应用
- 辅助色及应用
- 场景色及应用
- succsee,danger,warning,info等颜色及应用的组件
- 阴影颜色、大小及应用
- 边框色设定
- 灰色背景色值设定

### 样式

- padding值设定
- 圆角设定
- 反馈组件交互动画
- 组件focus、hover及active反馈效果
- 组件内置icon使用

### 定制功能设置的变量提取

主体参考bootstrap
其他增加可配置项。
组件移动端相关适配。

**Comment by cavenliu** [comment]
常用色板：

![default](https://cloud.githubusercontent.com/assets/19646244/21636551/17e22e4c-d29e-11e6-95f2-5cf1f37c5a8c.png)


语义色彩：

信息 info
成功 success
警告色 warning
危险色 danger

![image](https://cloud.githubusercontent.com/assets/19646244/21473913/c574560a-cb52-11e6-9880-88e93cd28b05.png)


配色分为：dark    light两种，默认使用dark。

关联控件：

1、按钮 button
2、标记 badge
3、标签 tag
4、模态对话框 Dialog
5、通知 Notification
6、消息提示 Message 
7、进度条 Progress 
8、警告提示 Alert
9、气泡消息确认对话框 Popconfirm
10、面板 panels
11、评分 Star Rating 
12、开关 Switch

**Comment by cavenliu** [comment]
形状：圆角（3px）、直角、圆形

![image](https://cloud.githubusercontent.com/assets/19646244/21474230/35aa2130-cb57-11e6-86d0-f595ca939603.png)


关联控件：
1、按钮 button
2、标记 badge
3、标签 tag
4、开关 Switch 
5、选择器 Combo Select
6、输入框 Input 
7、滑块 sliders

**Comment by cavenliu** [comment]
主题色：primary

关联控件：

1、按钮 button
2、标记 badge
3、标签 tag
4、评分 Star Rating 
5、开关 Switch 
6、单选框
7、复选框
8、选项卡 tab

**Comment by cavenliu** [comment]
### Botton 按钮
通过点击执行一个具体的行为或动作。


#### 何时使用：
当用户需要触发某个业务行为逻辑时，使用按钮。


#### 按钮的类型：
基础按钮、颜色按钮、描边按钮（幽灵按钮）、图标按钮、按钮组、圆形按钮、加载按钮、下拉按钮


#### 易用性：

1. 提供不同尺寸满足不同场景
3. 按钮点击需要有动画效果
4. 两个以上按钮横排时，间距为15px
5. 按钮hover、点击时，包含动画效果
6. 对于动作按钮，如果存在操作上的级别区分，则统一所有一级操作的按钮样式。
7. 有最小宽度
8. 可以自适应文字宽度
9. 可以100%充满栅格宽度
10. 按钮尺寸包含boder 1px

#### UI规范：
1、文字14px
2、文字左右边距15px，包含图标的按钮文字与图标间距10px
3、按钮组中：默认文字按钮最小宽度58px；默认图标按钮最小宽度46px
4、常用按钮，默认尺寸最小宽度86px，例如：模态窗口的确定与取消


![default](https://cloud.githubusercontent.com/assets/19646244/21643534/c744819e-d2c3-11e6-9bc5-ed3d90f1720e.png)


#### 最佳实践

**Comment by cavenliu** [comment]
Notification通知

## Notification通知

> 用于显示全局通知的面板。

***

### 何时使用

1. 当需要用户获取系统主动推送的通知消息时。
2. 通知内容较为复杂时。
3. 通知可能带有交互（比如按钮确认反馈）。
4. 适用于即时消息的弹出。
5. 邮件通知
6. 问答通知
---

### UI特性
1. Notification通知不同于操作类型的信息反馈，是一种主动推送的信息。
比如：你收到了新邮件／你有新的任务
2. 默认显示在页面右侧，自下而上、自上而下可配置。
3. 距离页面边缘30px
4. 尺寸：固定宽度300px，不限制高度
（宽度的响应问题遗留）
5.有标题
6.有图标
7. 根据场景选择退出方式：自动关闭退出时长4.5s、可点击关闭。
8. 通知显示原则：多条显示，逐条叠加
#### 位置规则
1. 提供6个位置
2. 位置互斥，只能设置一个颜色
3. 默认显示位置位置：右下部


![image](https://cloud.githubusercontent.com/assets/19646244/21517067/db2bf564-cd16-11e6-84b0-34bf351f9300.png)

预置及默认位置
![image](https://cloud.githubusercontent.com/assets/19646244/21537456/c4b2cde2-cdcc-11e6-96be-0ccc56936230.png)

**Comment by cavenliu** [comment]
消息的语意色彩：

![image](https://cloud.githubusercontent.com/assets/19646244/21535001/4ad5c49c-cdaa-11e6-86f8-ba9fbaf82abe.png)


消息示例：
![image](https://cloud.githubusercontent.com/assets/19646244/21537415/3bfdf29c-cdcc-11e6-8b8d-44960baab4aa.png)

图标：

![image](https://cloud.githubusercontent.com/assets/19646244/21537419/484fcaa2-cdcc-11e6-8938-fbe9f7ea0d82.png)


消息右侧多行显示

![image](https://cloud.githubusercontent.com/assets/19646244/21537989/06cb1e04-cdd3-11e6-9848-aa555f3ec136.png)

**Comment by cavenliu** [comment]
消息显示位置（默认、预置）：

![image](https://cloud.githubusercontent.com/assets/19646244/21537784/aadc51e6-cdd0-11e6-9772-51d36593ed17.png)

**Comment by cavenliu** [comment]
信息类的语意图标：

![image](https://cloud.githubusercontent.com/assets/19646244/21535974/82f11aea-cdb7-11e6-92fd-f7fc5c860f5d.png)

**Comment by cavenliu** [comment]
tooltip 位置

![image](https://cloud.githubusercontent.com/assets/19646244/21537700/f3e36fc4-cdcf-11e6-86ad-65f2005f6de4.png)

**Comment by cavenliu** [comment]
alter色彩

![image](https://cloud.githubusercontent.com/assets/19646244/21538286/49d4fa46-cdd6-11e6-8ffc-27bb0098eb2e.png)

示例页面：

![image](https://cloud.githubusercontent.com/assets/19646244/21538319/bfa28b6c-cdd6-11e6-97a3-9aebb10fabcb.png)

**Comment by cavenliu** [comment]
气泡确认框 Popconfirm

![image](https://cloud.githubusercontent.com/assets/19646244/21598737/d049597c-d19c-11e6-85f4-a1fc181527a2.png)


示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21598877/2d33a492-d19f-11e6-8d75-9c27de9d530d.png)

**Comment by cavenliu** [comment]
loading

![image](https://cloud.githubusercontent.com/assets/19646244/21599091/f9817b12-d1a1-11e6-80df-18931d8f9f63.png)


应用示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21599141/fecb5e2a-d1a2-11e6-9cbb-0101922bb690.png)

**Comment by cavenliu** [comment]
badge标记

![image](https://cloud.githubusercontent.com/assets/19646244/21599408/3ab523d6-d1a7-11e6-9202-2cdfca29f3cf.png)

示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21599455/90c6d396-d1a7-11e6-9d48-a8f94963c7c2.png)

**Comment by cavenliu** [comment]
磁贴

![image](https://cloud.githubusercontent.com/assets/19646244/21600525/b19fe15a-d1b8-11e6-8fd7-69419d0dbe86.png)

卡片：
![image](https://cloud.githubusercontent.com/assets/19646244/21706921/85349062-d405-11e6-8eed-82dedfff41b2.png)

示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21600534/f3a72554-d1b8-11e6-8452-0eca06479468.png)

**Comment by cavenliu** [comment]
按钮组

![image](https://cloud.githubusercontent.com/assets/19646244/21601379/f086f6f4-d1c4-11e6-8c3a-265b2f5e8cce.png)

示例：见标记示例

**Comment by cavenliu** [comment]
状态按钮 Loadingstate

![image](https://cloud.githubusercontent.com/assets/19646244/21601788/ce6cbf00-d1c8-11e6-8a8d-f7ec995a6111.png)

**Comment by cavenliu** [comment]
时间－－－年选择：

![image](https://cloud.githubusercontent.com/assets/19646244/21633193/ecc36bce-d287-11e6-9508-71ef9eacb7f8.png)

**Comment by cavenliu** [comment]
时间－－月选择

![Uploading image.png…]()

**Comment by cavenliu** [comment]
时间－－月选择
![image](https://cloud.githubusercontent.com/assets/19646244/21633460/61454290-d28a-11e6-850a-d99007075437.png)

**Comment by cavenliu** [comment]
时间－－24小时模式时间选择

![image](https://cloud.githubusercontent.com/assets/19646244/21633471/79f9dcba-d28a-11e6-932e-f9b025e455cc.png)

时间－－12小时模式时间选择
![image](https://cloud.githubusercontent.com/assets/19646244/21633648/018d6916-d28c-11e6-8aa0-07c6c5d0b48d.png)

**Comment by cavenliu** [comment]
时间－－－年月日选择
带分割线
![image](https://cloud.githubusercontent.com/assets/19646244/21633490/9c849298-d28a-11e6-9a6f-3503e3a83af9.png)

不带分割线
![image](https://cloud.githubusercontent.com/assets/19646244/21633510/d8dcc7c4-d28a-11e6-9748-6adad742b6b3.png)


大跨度选择年
![image](https://cloud.githubusercontent.com/assets/19646244/21633504/cc60aa24-d28a-11e6-811b-e5632bdeead2.png)

大跨度选择月

![image](https://cloud.githubusercontent.com/assets/19646244/21633520/e82852f2-d28a-11e6-9dc4-fd9ab02d6538.png)

**Comment by cavenliu** [comment]
年月日＋时间段

![image](https://cloud.githubusercontent.com/assets/19646244/21633573/4d7cff68-d28b-11e6-911a-eab98c390129.png)

**Comment by cavenliu** [comment]
时间－年月日时分秒选择

![image](https://cloud.githubusercontent.com/assets/19646244/21633682/48234e7c-d28c-11e6-80d5-bac6047b3ea8.png)

**Comment by cavenliu** [comment]
时间－年月日时分秒选择输入＋时间段

![image](https://cloud.githubusercontent.com/assets/19646244/21633708/95e9a3ae-d28c-11e6-847c-7c21eea2a25e.png)

**Comment by cavenliu** [comment]
跨月选择

![image](https://cloud.githubusercontent.com/assets/19646244/21634128/bd6700fe-d28f-11e6-975c-ef9def0841b8.png)



![image](https://cloud.githubusercontent.com/assets/19646244/21634151/dd48cccc-d28f-11e6-9b4d-8f1f39462739.png)

**Comment by cavenliu** [comment]
input 输入框

输入框配色

![image](https://cloud.githubusercontent.com/assets/19646244/21635582/989af26c-d299-11e6-8e98-a01643bd6d29.png)


![default](https://cloud.githubusercontent.com/assets/19646244/21634871/20ca1e92-d295-11e6-928b-93bdcc5b14dd.png)

![a](https://cloud.githubusercontent.com/assets/19646244/21634872/20ca863e-d295-11e6-893d-3df75484a9ed.png)

**Comment by cavenliu** [comment]
输入框组

![default](https://cloud.githubusercontent.com/assets/19646244/21636223/b1bf2fb2-d29c-11e6-9672-1390828057bb.png)


示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21644173/31fcb31e-d2c7-11e6-96a8-0f6fc5e05b4a.png)

**Comment by cavenliu** [comment]
日期选择示例

![image](https://cloud.githubusercontent.com/assets/19646244/21644035/704932a6-d2c6-11e6-9927-93c96160da0c.png)

**Comment by cavenliu** [comment]
下拉菜单

![default](https://cloud.githubusercontent.com/assets/19646244/21671118/283e323e-d354-11e6-96b2-f2e6dfac962a.png)


![default](https://cloud.githubusercontent.com/assets/19646244/21670946/25071ae6-d353-11e6-96fb-eb6123fcc6f9.png)


## 下拉菜单 Dropdown

> 以条形菜单栏和菜单栏中每个菜单项的弹出菜单窗口两部分组成，一般作为应用系统的主菜单使用。

- 下拉菜单与下拉组合的差别是，前者点击按钮触发并伴随跳转动作；后置点击输入框触发，用于信息采集。

***

### 何时使用

1. 次级导航需要隐藏呼出时
2. 主要用于顶部导航，侧边导航使用navbar的menu


---



### UI特性


1. 宽度高度：默认100%，宽度根据内容撑开，需要用户自定义宽度和高度。
2. padding：7px 10px
3. 字号1.4rem（14px）
4. line－hight：1.5   高度：约35px
5. hover背景色：bg-grey-100    #f5f5f5
6. 分割线：#e0e0e0   .bg-grey-300
7. 外边框：#e0e0e0   .bg-grey-300
8. 圆角：3px
9. 投影：x0 y1 blue5  ＃bg-grey-300    
10. 选中态与hover态暂时不做区分。
11. 面板与按钮间距5px。

**Comment by cavenliu** [comment]
模态对话框

![dialog modal](https://cloud.githubusercontent.com/assets/19646244/21674203/a8e4c048-d367-11e6-83bc-68348060a638.png)

**Comment by cavenliu** [comment]
树

![image](https://cloud.githubusercontent.com/assets/19646244/21684890/67fa0eb6-d39a-11e6-8a7d-23288843e476.png)

**Comment by cavenliu** [comment]
顶部导航

![image](https://cloud.githubusercontent.com/assets/19646244/21684929/96d84dce-d39a-11e6-8aaf-531930a5cbfc.png)
侧边导航
![image](https://cloud.githubusercontent.com/assets/19646244/21705485/2ba4e89e-d3fb-11e6-937e-437c8b57fed7.png)

示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21705664/4324f972-d3fc-11e6-964b-45b0e0a076ec.png)

**Comment by cavenliu** [comment]
面包屑

![image](https://cloud.githubusercontent.com/assets/19646244/21704653/a7325b28-d3f5-11e6-8538-dcdaeeb79bd0.png)

示例：
![image](https://cloud.githubusercontent.com/assets/19646244/21704759/4829db5a-d3f6-11e6-9b03-f8e21cd5f485.png)

**Comment by cavenliu** [comment]
分页
![image](https://cloud.githubusercontent.com/assets/19646244/21704994/e248ccc2-d3f7-11e6-8973-4cb3702800f8.png)

示例：
![image](https://cloud.githubusercontent.com/assets/19646244/21705019/0a04f6a0-d3f8-11e6-83c1-99ba90d32307.png)

**Comment by cavenliu** [comment]
tab选项卡（标签页）

![tab](https://cloud.githubusercontent.com/assets/19646244/21705172/389fe384-d3f9-11e6-9061-71b0947367dd.png)

示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21705241/a9f6ebea-d3f9-11e6-8c03-2e2685c95e7c.png)

**Comment by cavenliu** [comment]
上传

![image](https://cloud.githubusercontent.com/assets/19646244/21706584/4d1cba3a-d403-11e6-95ba-6be735b7c797.png)


多文件上传：

![image](https://cloud.githubusercontent.com/assets/19646244/21706602/77f99976-d403-11e6-93e1-a323a03279b8.png)

**Comment by cavenliu** [comment]
标签

![tag](https://cloud.githubusercontent.com/assets/19646244/21707084/2ca2a25c-d407-11e6-953e-19a8065f6f06.png)

**Comment by cavenliu** [comment]
滑块

![default](https://cloud.githubusercontent.com/assets/19646244/21709278/b963af48-d41a-11e6-9b0a-72476457d950.png)


示例：

![image](https://cloud.githubusercontent.com/assets/19646244/21709522/8b49cd3e-d41c-11e6-8bec-3f69786fd4fe.png)

**Comment by cavenliu** [comment]
单选

![default](https://cloud.githubusercontent.com/assets/19646244/21709675/f25a1f78-d41d-11e6-855f-3d11b8bd4979.png)

**Comment by cavenliu** [comment]
复选

![default](https://cloud.githubusercontent.com/assets/19646244/21709807/ed4453cc-d41e-11e6-9422-ecf3a60fedd0.png)
