### ISSUE TITLE
InputNumber 无法输入小数问题

### ISSUE THREAD

**Issue by crazy-lulu-edu** [iuap-design/tinper-bee#140]
### Bug 报告
InputNumber 控件无法直接输入小数,例如输入4.23这样的数字的时候,在输入 "."的时候,数据就会变成0.00;
InputNumber 控件默认展示0.00,无法通过删除0.00直接输入数字
- __Package version(s)__: (版本号)
tinper-bee 1.5.0
#### 描述这个问题:

InputNumber 控件无法直接输入小数,例如输入4.23这样的数字的时候,在输入 "."的时候,数据就会变成0.00;
InputNumber 控件默认展示0.00,无法通过删除0.00直接输入数字

#### 当前的行为:

目前无法输入完整的小数;
0.00 无法删除

#### 期望的行为:
希望可以删除0.00 直接输入小数,方便录入;

**Comment by lucian55** [comment]
tinper-bee新版已解决
