### ISSUE TITLE
分公司遇到的一些问题和需要优化的地方

### ISSUE THREAD

**Issue by fridaydream** [iuap-design/tinper-bee#142]
### 分公司遇到的一些问题和需要优化的地方

- __Package version(s)__: table:1.6.18

#### 描述这个问题:

1. table的性能问题，125条数据就很卡，编辑的时候，有1-2秒的延迟
2. uba的启动时间问题，多个节点在电脑，改一个地方要等2-3分钟才能刷新页面，经常出现内存不足，直接闪退。
3. 如果有一个接口是每个页面都需要的，需要在modal.js和service.js中都配置。太麻烦了。(mirror的清空机制)modal.js可能需要几个js文件(代码生成器)
4. 合计和小计和右侧的合计。
5. 图片的上传希望有预览
6. 多个页签切换的时候，改动一个，点击另一个，希望刷新页面。(平台页签)
7. 进入详情页面发送2次接口(代码生成器)
8. table 选中行，自动勾选
9. 返回的方法 用history的goback不好(代码生成器)
10. 合计中需要千分位
11. 全选table有换行的时候出现错位(与左侧的多选)

#### 期望的行为:

在现场时需求变化很多，有时优化一些小问题，可能对现场开发速度提升更快。

**Comment by zhaoyuchief** [comment]
3.如果有一个接口是每个页面都需要的，需要在modal.js和service.js中都配置。太麻烦了。(mirror的清空机制)modal.js可能需要几个js文件(代码生成器)
这个可以抽取通用的组件出来。

**Comment by zhaoyuchief** [comment]
2.uba的启动时间问题，多个节点在电脑，改一个地方要等2-3分钟才能刷新页面，经常出现内存不足，直接闪退。
可以修改入口文件数量，构建单个节点，提高编译效率。

**Comment by fridaydream** [comment]
第三条怎么抽取通用组件？ @zhaoyuchief

**Comment by whizbz11** [comment]
1、table的性能问题，125条数据就很卡，编辑的时候，有1-2秒的延迟，升级最新版本的table，使用bigData高阶函数实现数据量场景，参考[官网大数据加载](http://bee.tinper.org/bee-table/),编辑时使用syncHover属性

**Comment by whizbz11** [comment]
4、合计和小计和右侧的合计，这个是什么场景，8、table 选中行，自动勾选.这个问题可以选中时触发onRowClick，调用下selectedRow处理即可。10合计中需要千分位。这个后续提供API，

**Comment by fridaydream** [comment]
> 4、合计和小计和右侧的合计，这个是什么场景，8、table 选中行，自动勾选.这个问题可以选中时触发onRowClick，调用下selectedRow处理即可。10合计中需要千分位。这个后续提供API，

第4条，需求量不大，右侧的合计可能需要联动，而且计算合计的时候可以需要权重不同进行相加，如 金额与完成度进行相加时，会出现权重问题的相加。而且中间可能有合并单元格。

**Comment by fridaydream** [comment]
第5，6条问题需要更细的讨论。其他的都有了解决方案。
