### ISSUE TITLE
主题规范

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#143]
### 主题样式介绍。

- minxin-variables 【组件直接调用文件】， 定义各组件中抽离出来的默认变量
  如下：
    - 默认字体
    - 默认颜色
    - 字体大小和粗细
    - 波纹效果
    - 贝塞尔曲线动画
    - 阴影
    - 常用z-index值设定
    - UI组件的预设

- minxin-mixins
该文件定义了很多可复用的功能模块，比如说border-radius和box-shadow等。

- minxin-palette
    1. 设置根据minxin-colors的颜色生成背景颜色和字体颜色
    2. 一般在组件的Demo 示例中使用该文件中的定义。 

- minxin-themeColors
为了方便定制，将一些样式变量提取了出来，放在 minxin-themeColors.scss 文件中。设置主色、辅色等 tinper-bee 中最常用的通用变量，即主题定制时可供用户配置的样式变量。

## 二、tinper-bee-core 调用关系图。
![](http://iuap-design-cdn.oss-cn-beijing.aliyuncs.com/static/jony/1002.png)
![](http://iuap-design-cdn.oss-cn-beijing.aliyuncs.com/static/jony/1001.png)

### 调试准备：
1. 下载 bee-core 代码到本地（theme分支）：https://github.com/tinper-bee/tinper-bee-core/tree/theme
2. 在 bee-button 根目录下，安装本地的bee-core至node_modules，以方便调试
> npm i -S "tinper-bee-core的相对路径"
```
> npm i -S ../tinper-bee-core-theme/tinper-bee-core
```
3. 安装好后，bee-button/package.json中如下所示

![image](https://user-images.githubusercontent.com/33412781/51292541-0e368e00-1a46-11e9-8844-02aed24a8b2a.png)

### 以Button为例，抽取组件的背景色变量
Button.scss文件：
```
// 主按钮
.u-button {
  background: $button-default-color;     //背景色
}
```

### 修改 minxin-variables.scss 文件
- 找到上诉样式变量定义的地方

tinper-bee-core/minxin-variables.scss：
```
// UButton

// Button 基础背景色.
$button-default-color: $brand-default;
```

- 继续查找 $brand-default 变量
```
// 品牌色
$brand-default: $gray-lighter;
```

- 修改 $brand-default 的定义，改用主题文件中的样式变量赋值

修改后：
```
// 品牌色
$brand-default: unquote("rgb(#{$color-primary})");
```

备注：$color-primary 是主题文件中定义的主题色，修改 $color-primary 的色值，即可修改按钮默认的背景色。

### 查看 minxin-themeColors 主题样式文件
- $color-primary 变量是用户定制的主题色，其值 $palette-blue-600 取自色板文件（minxin-colors.scss）
- 组件的样式变量最终指向以下这些属性，就能保证自定义主题文件后，组件样式随之改变
```
@import "minxin-colors";

// 默认色
$default-color: $palette-grey-300;
$default-color-dark:  $palette-grey-400;
$default-color-light: $palette-grey-200;

// 主题色
$primary-color: $palette-blue-600 !default;
$primary-color-dark: $palette-blue-800 !default;
$primary-color-light: $palette-blue-400 !default;

// 向下兼容
$color-primary: $palette-blue-600 !default;
$color-primary-dark: $palette-blue-800 !default;
$color-primary-light: $palette-blue-400 !default;

// 字体
$font-family-primary: "Open Sans", "Helvetica Neue", Arial, "Hiragino Sans GB", "Microsoft YaHei", sans-serif !default;
// 主字号
$font-size-base: 14px !default;
// 主文本色，包括主按钮的文字色
$text-color-base: $color-dark-contrast !default;  

// 圆角，包括：button、select等
$border-radius: 3px !default;
// 边框色，包括button、select、bee-form-control、cascader、timepicker、datepicker、upload、badge、autocomplete、pagination、tooltip、bee-input-number、bee-city-select
$border-color: $palette-grey-400 !default;
// 条目hover背景色，包括：select、dropdown、table、datepicker、tree、menu、calendar、autocomplete
$item-hover-bg-color-base: $palette-blue-50 !default;
// 条目selected背景色，包括：select、menu等
$item-selected-bg-color-base: "247,247,247" !default;

// Button 细化样式变量:
// 次按钮背景色
$secondary-color: $palette-grey-300 !default;
$secondary-color-dark: $palette-grey-400 !default;
$secondary-color-light: $palette-grey-200 !default;
// 次按钮文本色
$button-secondary-text-color: $color-light-contrast !default;

// Table 细化样式变量：
// 表头背景色
$table-header-background-color: "247,247,247";
// 表头文字颜色
$table-header-text-color: "102, 102, 102";
// 表格分割线颜色
$table-border-color-base: "233,233,233";
// 表格行hover背景色
$table-row-hover-bg-color: "235, 236, 240";
// 表头字体的粗细
$table-head-font-weight: normal;

// 辅色，暂未使用
$color-accent: $palette-green-600 !default;
$color-accent-dark: $palette-green-800 !default;
$color-accent-light: $palette-green-400 !default;
// ...

```

## 四、如何按照新主题来修改一个组件的样式提取。
![image](https://user-images.githubusercontent.com/33412781/51095440-b6064e80-17ef-11e9-9181-1f8d261c424d.png)

**Comment by yangchch6** [comment]
##  tinper-bee 主题样式文件（主题定制面板）
```
/* 全局样式 */
$default-color               // 默认色
$primary-color               // 主题色（#F53C32）
$font-family-primary         // 字体
$font-size-base              // 字号
$text-color-base             // 字体颜色
$border-radius               // 圆角
$border-color                // 边框色（#a5adba）
$item-hover-bg-color-base    //条目hover背景色
$item-selected-bg-color-base //条目selected背景色

/* 按钮细化样式 */
$secondary-color                 // 次按钮背景色
$button-secondary-text-color     // 次按钮字体色

/*表格细化样式*/
$table-header-background-color   // 表头背景色
$table-header-text-color         // 表头文字颜色
$table-border-color-base         // 表格分割线颜色
```

## 样式变量依赖关系
![image](https://user-images.githubusercontent.com/33412781/51101878-997e0c80-1817-11e9-913a-60d353993664.png)

**Comment by yangchch6** [comment]
# tinper-bee-core 整体文档
tinper-bee组件库的核心样式及公用方法库

## 核心样式
放在scss文件夹下，由index.scss统一导出
包括
- 重置浏览器样式
- 全局样式设置
- 图标样式
- 波纹效果、阴影样式、文本及字体样式
- 主辅色及常用颜色设置

## 工具方法库

### set-global
- 设置body字体及颜色
- 设置图表间距
- 设置显隐u-visible u-not-visible
- 设置边框u-border-top...



### set-normalize
- 重置css样式

### set-resets
- 选择时删除文本阴影，及设置默认选中颜色
- html5标签的跨浏览器样式适配

### util-iconfont
- 图标设定

### util-ripple
- 波动动画设定

### util-shadow
- 阴影样式设定

### util-utilities
- 垂直对齐样式
- display样式
- 文本换行，浅色
- 文本位置
- 文本大小写
- 字体粗度
- 字体大小
- 清除浮动及左右浮动
- 显示隐藏
- 宽高常用预设样式
- 常用margin，padding预设样式
- visible，hidden的适配预设

### minxin-colors
- 调色板
- [文档链接](http://tinper.org/dist/neoui/global/color.html)

### minxin-mixins
- 该文件定义了很多可复用的功能模块，比如说border-radius和box-shadow等组合样式。

### minxin-palette
- 设置根据minxin-colors的颜色生成背景颜色和字体颜色
- 在组件的Demo 示例中可直接添加该文件中的定义className。

### minxin-themeColors
- 设置主色和辅色等tinper-bee 中最常用的通用变量，即主题定制时可供用户配置的样式变量

### minxin-variables
- 默认变量
    - 默认字体
    - 默认颜色
    - 字体大小和粗细
    - 波纹效果
    - 贝塞尔曲线动画
    - 阴影
    - 常用z-index值设定
    - UI组件的预设



### js方法

#### keyCode对象

引入方法：

```
import keyCode from 'tinper-bee-core/lib/keyCode';

//或者

import { keyCode } from 'tinper-bee-core';

```

方法：

- isTextModifyingKeyEvent 验证是否是特殊按键或组合按键

```
handleKeyDown = (e) => {
if(keyCode.isTextModifyingKeyEvent(e)){
 //一些操作
}
}
...

<Input onKeyDown={this.handleKeyDown} />
```

- isCharacterKey 验证是否是文本键
```
handleKeyDown = (e) => {
if(keyCode.isCharacterKey(e)){
 //一些操作
}
}
...

<Input onKeyDown={this.handleKeyDown} />
```

#### toArray 将数组安全的转换为react element 数组

#### splitComponentProps 通过父组件的propTypes拆分分别传给父子组件的props


```
const propTypes = {
    color: PropTypes.string,
    size: PropTypes.string
}
class ParentClass extends React.Component{
    render() {
        let props = this.props;
        let [parentProps, childProps] = splitComponentProps(props);

        return (
            <div>
                <ChildrenClass {...childProps} />
            </div>
        )
    }
}

ParentClass.propTypes = propTypes;

```

#### createChainedFunction 创建链式调用方法


#### contains 检验是否包含

**Comment by kvkens** [comment]
占地提个组件库的警告提示⚠️需要改成向上兼容的"^15.6.2"这样不要指定匹配版本，有些组件我修改过了，但是有的没下载仓库😁

![image](https://user-images.githubusercontent.com/3817644/51292553-20b0c780-1a46-11e9-93e5-3ed008665204.png)

**Comment by yangchch6** [comment]
## 1. 禁用状态

名称 | 色值
---|---
背景色 | #F7F9FB
描边色 | #DFE1E6  
文字色 | #909090
图标色 | #C1C7D0 



## 2. hover背景色

变量名称 | 色值
---|---
$hover-bg-color-base |  #ebecf0

## 3. selected背景色
变量名称 | 色值
---|---
$selected-bg-color-base |  #FFF7E7


## 4. 圆角

变量名称 | 大小
---|---
$border-radius-base  |  3px

## 5. 边框色

变量名称 | 色值
---|---
$border-color-base  |  #a5adba


## 6. 主文本色
#### 色值
- #212121

## 7. 图标字体

使用场景 | 色值
---|---
浅色背景下 | #505F79
深色背景下 | #ffffff
禁用态下 | #C1C7D0

**Comment by yangchch6** [comment]
# tinper-bee组件依赖关系
![image](https://user-images.githubusercontent.com/33412781/54254789-229f8e80-4590-11e9-9666-50b698e9cc1a.png)
