### ISSUE TITLE
你们的源码是抄的RC组件吧，抄也要留别人的名字啊

### ISSUE THREAD

**Issue by chenlizan** [iuap-design/tinper-bee#144]
### Bug 报告

- __Package version(s)__: (版本号)

**Comment by GuoYongfeng** [comment]
@chenlizan 

经查，tinper-bee 中部分子组件（主要为导航类组件）为 fork 的 rc 2016 年版本的部分代码，后独立维护、演进。您指出的问题，我们高度重视，tinper-bee 本身也是开源的技术类输出，将遵循 MIT 协议对代码进行完善：

1、检查涉及的组件源码，保留作者署名；
2、检查涉及的组件源码，保留原MIT协议。

最后，请继续监督指正。以上修改会在新的版本进行修改发布。
