### ISSUE TITLE
RangePicker的disabled属性不可用的问题

### ISSUE THREAD

**Issue by liuzhengithub** [iuap-design/tinper-bee#146]
### Bug 报告

- __Package version(s)__: (版本号)

#### 当前的行为:
RangePicker的disabled属性不可用

#### 期望的行为:
RangePicker的disabled属性可用

**Comment by lucian55** [comment]
使用 bee-datepicker@1.3.21  或者 bee-datepicker@2.0.7 版本即可解决问题
