### ISSUE TITLE
Table内嵌Select组件

### ISSUE THREAD

**Issue by liuzhengithub** [iuap-design/tinper-bee#147]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:
Table组件当没有fixed列时，select组件选择正常；当有fixed列时，Select组件的选择出现跳闪的问题

#### 当前的行为:
Table当有fixed（right or left）列时，column内嵌的select组件下拉时，鼠标在行间hover时会跳闪，很难选中

#### 期望的行为:
Table当有fixed（right or left）列时，没有跳闪，正常选中

**Comment by whizbz11** [comment]
请升级bee-table，当编辑时，给Table传入syncHover属性，值为false即可。当syncHover为false时，就不会导致hover导致的重绘问题。
