### ISSUE TITLE
两个固钉同时使用时，滚动到一定程度以后，固钉失效，top会被改变

### ISSUE THREAD

**Issue by Mendege** [iuap-design/tinper-bee#148]
[

### Bug  #报告

@- __Package version(s)__: (版本号)

#### 期望的行为:

- [ ] 

`1. `

**Comment by yangchch6** [comment]
> [
> 
> ### Bug #报告
> @- **Package version(s)**: (版本号)
> 
> #### 描述这个问题:
> #### 当前的行为:
> #### 期望的行为:
> * [ ]
> 
> `1. `


本地没有复现，麻烦描述下滚动到什么程度会出现这个问题吧
