### ISSUE TITLE
bee-notification参数无效

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#150]
### Bug 报告

- __Package version(s)__:  bee-notification@2.0.0

#### 描述这个问题:

`color`参数只有`dark`和`light`生效
demo地址：https://codesandbox.io/s/x9oxv1ypyz

#### 当前的行为:

参数无效

#### 期望的行为:

参数生效

**Comment by yangchch6** [comment]
> ### Bug 报告
> * **Package version(s)**:  bee-notification@2.0.0
> 
> #### 描述这个问题:
> `color`参数只有`dark`和`light`生效
> demo地址：https://codesandbox.io/s/x9oxv1ypyz
> 
> #### 当前的行为:
> 参数无效
> 
> #### 期望的行为:
> 参数生效

你可以Message组件，设置 `position` 属性和 `color` 属性。即可达到想要的效果。
```
Message.create({content: 'This is a success message', position: 'bottomRight',color: 'success'});
```
