### ISSUE TITLE
Modal组件官方文档

### ISSUE THREAD

**Issue by Hzy0913** [iuap-design/tinper-bee#152]
## 环境及版本信息

- `tinper-bee` 版本号:  V2.0.7
<img width="792" alt="WX20190424-112553@2x" src="https://user-images.githubusercontent.com/22450881/56630379-cbf39d00-6683-11e9-9371-4f22c77cbe58.png">

**Comment by yangchch6** [comment]
> ## 环境及版本信息
> * `tinper-bee` 版本号:  V2.0.7
> 
> <img alt="WX20190424-112553@2x" width="792" src="https://user-images.githubusercontent.com/22450881/56630379-cbf39d00-6683-11e9-9371-4f22c77cbe58.png">

文档已修改，本周更新官网时会上线
