### ISSUE TITLE
table 的 fixed 问题

### ISSUE THREAD

**Issue by HaoGeShuoHuaNiHaoHaoTing** [iuap-design/tinper-bee#153]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.7

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8

- 所使用的操作系统：window

- 所使用的浏览器：chrome

## 描述这个问题: 
1. table 中设置 height， 对于字数很多的列，不生效，此列依然会被撑开（此列有固定宽度的时候）；
2. fixed 列的高度 是设置的高度，就有 fixed 列 与 普通列 错位现象；

**Comment by whizbz11** [comment]
首先height是针对单行数据，如果业务中不确定内容多少，可以使用bodyDisplayInRow属性，将内容设置到一行。这个属性在bee-table@2.0.15中实现。tinper-bee中还没有集成这个属性。稍后会发新版2.0.8

**Comment by whizbz11** [comment]
建议行高是根据内容撑开的，如果要固定行高请确保内容是在一行上
