### ISSUE TITLE
Select组件的onChange事件如何获取合成事件参数e

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#155]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.7

- 当前项目中`react`的版本号：
16.4.2

- 所使用的操作系统：
MACOS

- 所使用的浏览器：
Chrome 73.0

## 描述这个问题:
  `Select`组件直接的`onChange`事件参数`e`直接是`Option`的`value`值，我想拿到像`onClick`触发时的e该如何做？

**Comment by lucian55** [comment]
onChange第一个参数是value值，第二个参数是 Option对象。如果你想拿Option对象，取第二个参数即可
