### ISSUE TITLE
Popover positionTop positionLeft 不生效

### ISSUE THREAD

**Issue by utopiaGYB** [iuap-design/tinper-bee#158]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.9

- 当前项目中`react`的版本号：
16.8.6

- 所使用的操作系统：
MAC

- 所使用的浏览器：
chome

## 描述这个问题:
Popover positionTop positionLeft 不生效

### 代码
<Popover
                    placement="topRight"
                    positionLeft="20px"
                    content={createMoreMenu(hideMenu)}
                    trigger="click"
                    id="leftBottom"
                    show={moreVisible}>
                    <Button key={'showMoreButton'} className='action-btn'  onClick={()=>{console.log('点击更多按钮123')}} style={baseStyleMap}>更多</Button>
                </Popover>

**Comment by yangchch6** [comment]
> ## 环境及版本信息
> * `tinper-bee` 版本号:
>   2.0.9
> * 当前项目中`react`的版本号：
>   16.8.6
> * 所使用的操作系统：
>   MAC
> * 所使用的浏览器：
>   chome
> 
> ## 描述这个问题:
> Popover positionTop positionLeft 不生效
> 
> ### 代码
> 
> <Button key={'showMoreButton'} className='action-btn' onClick={()=>{console.log('点击更多按钮123')}} style={baseStyleMap}>更多

- bee-popover@2.0.2
    - [Fixbug]解决设置`positionLeft`和`positionTop`属性无效的问题
- tinper-bee 发布v2.0.10后，可直接从tinper-bee中引入该组件
