### ISSUE TITLE
日历组件文件夹名字写错了

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#162]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.7

- 当前项目中`react`的版本号：
16.4.2

- 所使用的操作系统：
MacOS

## 描述这个问题:
在使用日历组件的时候，文档给的引入方式是`import { Calendar } from 'tinper-bee/lib/Calendar'`
实际上`tinper-bee/lib`下的`Calendar`是`Calender`，文件夹名字弄错了

## 期望的行为:
`lib`下面的日历组件文件夹名字改一下吧

**Comment by yangchch6** [comment]
tinper-bee v2.0.10版本已经修正
