### ISSUE TITLE
InputNumber组件设置了min={0}还是可以输入负号

### ISSUE THREAD

**Issue by xiaozhoulin** [iuap-design/tinper-bee#165]
## 环境及版本信息

- 若使用单个组件，请标明该组件版本号：
"bee-input-number": "^2.0.7",

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
先随便输入一个小数，然后可以在前面加负号

### 截图
![image](https://user-images.githubusercontent.com/50358376/57284549-fa419580-70e3-11e9-9773-746fe6488164.png)
![image](https://user-images.githubusercontent.com/50358376/57284614-17766400-70e4-11e9-968c-e28569d98506.png)

## 期望:
设置了min={0}的时候不能输入负号或输入负号后把值重置为0

**Comment by lucian55** [comment]
bee-input-number@2.0.9   修复此问题
