### ISSUE TITLE
bee-datepicker添加控制hover icon 的属性

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#166]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

bee-datepicker@2.0.32
- 当前项目中`react`的版本号：

react@16.3.2
- 所使用的操作系统：

windows
- 所使用的浏览器：

chrome@71
## 描述这个问题:
bee-datepicker添加控制hover icon 的属性

**Comment by lucian55** [comment]
bee-datepicker@2.0.33  

| closeIcon |鼠标划过清空内容的icon|Function| () => <Icon type="uf-close-c" />|
