### ISSUE TITLE
参照的查询功能无法使用

### ISSUE THREAD

**Issue by wldjgs** [iuap-design/tinper-bee#167]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：
Windows

- 所使用的浏览器：
所有浏览器都一样

## 描述这个问题:
如果是正常打开的参照，参照上的筛选框是可以使用的，但是如果是在弹出层上打开的参照，那么筛选框就无法使用了
### 代码

![image](https://user-images.githubusercontent.com/46013610/57427577-131e8800-7257-11e9-919e-b8784329c35e.png)
![image](https://user-images.githubusercontent.com/46013610/57427596-26315800-7257-11e9-9a48-92c1e32d0718.png)
![image](https://user-images.githubusercontent.com/46013610/57427621-39dcbe80-7257-11e9-9034-4889f2c4b054.png)

**Comment by lucian55** [comment]
请说明 参照版本，tinper-bee 版本号，若使用单个组件，请标明该组件版本号、当前项目中react的版本号

**Comment by wldjgs** [comment]
您好版本号我怎么查

**Comment by wldjgs** [comment]
tinper-bee: "1.5.0"
react: "^16.6.0",

**Comment by lucian55** [comment]
请说明 参照版本，formcontrol版本号

**Comment by wldjgs** [comment]
yyuap-ref: "^1.1.32"
FormControl用的就是tinper-bee的

**Comment by lucian55** [comment]
已解决
