### ISSUE TITLE
Menu.Item中嵌套Menu.Item hover时报错onItemHover is not a function

### ISSUE THREAD

**Issue by Hzy0913** [iuap-design/tinper-bee#169]
## 环境及版本信息

- `tinper-bee` 版本号:  @2.0.9

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
Menu.Item中嵌套Menu.Item,    在hover时报错onItemHover is not a function，应该有个短路运算吧

`onItemHover && onItemHover()`
### 报错信息
`Uncaught TypeError:  onItemHover is not a function`

## 当前的行为：效果（可截图说明）及动作描述

![WX20190513-102604](https://user-images.githubusercontent.com/22450881/57592765-f93cb800-756a-11e9-8f0b-cdedbaad196b.png)

![WX20190513-102841](https://user-images.githubusercontent.com/22450881/57592701-ab27b480-756a-11e9-8188-f9d4dfe241f3.png)

**Comment by Hzy0913** [comment]
嵌套以后还有个警告：
`Warning: validateDOMNesting(...): <li> cannot appear as a descendant of <li>. See Registration > li >`
看了下是li标签里嵌套了li标签，
可能`<Item>`嵌套`<Item>`这个思路不太对，还是手写一下实现

**Comment by lucian55** [comment]
多级嵌套菜单，使用 SubMenu嵌套。  
[参考示例](https://github.com/tinper-bee/bee-menus/blob/master/demo/demolist/Demo9.js)
