### ISSUE TITLE
bee-select新需求:支持自定义输入

### ISSUE THREAD

**Issue by HuaYJ1996** [iuap-design/tinper-bee#170]
## bee-select新需求
带输入的下拉框在可支持自定义的输入.
目前情况为,带输入的下拉框只能通过select事件改变value,输入的值会在组件失去焦点后清空.

**Comment by lucian55** [comment]
bee-select@2.0.12版本支持此功能
设置如下属性

|参数|说明|类型|默认值|
|:---|:----|:---|:------|
|supportWrite|输入搜索查询时是否支持自定义输入，需配合showSearch使用，否则无效|bool|false|
