### ISSUE TITLE
客户案例统计

### ISSUE THREAD

**Issue by lucian55** [iuap-design/tinper-bee#172]
> 为了更好的提升组件库能力,了解项目情况,做此统计,希望您可以写一下, 直接编辑此issue即可。如果可以提供logo，我们将展示到官网上

## 项目统计表格

| 项目名称 |  所属公司 | 项目链接(如果可以在线访问)  | logo | 备注 |
|:---|:----|:---|:------|:------|
| 2019用友企业云服务开发者大赛 | 用友网络 | https://iuapdc.yonyoucloud.com | ![iuapdc](https://design.yonyoucloud.com/static/developer/navbar.svg) | - | 
| IUAP Design 官网 | 用友网络 | http://design.yonyoucloud.com |  ![design](https://design.yonyoucloud.com/static/tinper-bee/logo/iuapdesign.svg)  | - |
| 用友网络nccloud | 用友网络 | - |  ![nccloud](https://design.yonyoucloud.com/static/tinper-bee/logo/nccloud.png)  | - | 
| 中兴通讯 | 用友网络 | - |  ![zxtx](https://design.yonyoucloud.com/static/tinper-bee/logo/zxtx.png)  | - | 
| 三一重工 | 用友网络 | - |  ![sany](https://design.yonyoucloud.com/static/tinper-bee/logo/sany.png)  | - | 
| 象屿集团 | 用友网络 | - |  ![xyjt](https://design.yonyoucloud.com/static/tinper-bee/logo/xyjt.png)  | - | 
| 郎酒CRM平台 | 用友网络 | - |  ![ljCRM](https://design.yonyoucloud.com/static/tinper-bee/logo/ljCRM.png)  | - | 
| 杭州绿城 | 用友网络 | - |  ![hzlc](https://design.yonyoucloud.com/static/tinper-bee/logo/hzlc.png)  | - | 
| 台湾华新丽华-MES 系统 | 用友网络 | - |  ![hxlh](https://design.yonyoucloud.com/static/tinper-bee/logo/hxlh.png)  | - | 
| 杭州路桥 | 用友网络 | - |  ![hzlq](https://design.yonyoucloud.com/static/tinper-bee/logo/hzlq.png)  | - | 
| 江铜贵溪冶炼厂-智能工厂 | 用友网络 | - |  ![gyzngc](https://design.yonyoucloud.com/static/tinper-bee/logo/gyzngc.png)  | - | 
| 用友网络-U8Cloud 数据中心 | 用友网络 | - |  ![U8Cloud](https://design.yonyoucloud.com/static/tinper-bee/logo/U8Cloud.png)  | - | 
| 尚层装饰 | 用友网络 | - |  ![sczs](https://design.yonyoucloud.com/static/tinper-bee/logo/sczs.png)  | - | 
| 四维图新 | 用友网络 | - |  ![swtx](https://design.yonyoucloud.com/static/tinper-bee/logo/swtx.png)  | - | 
| 全友数字营销系统 | 用友网络 | - |  ![qyszyxxt](https://design.yonyoucloud.com/static/tinper-bee/logo/qyszyxxt.png)  | - | 
| 南通化轻物流系统 | 用友网络 | - |  ![nthqwlxt](https://design.yonyoucloud.com/static/tinper-bee/logo/nthqwlxt.png)  | - | 
| 用友网络-精智IOT 后台管理系统 | 用友网络 | - |  ![jzIOT](https://design.yonyoucloud.com/static/tinper-bee/logo/jzIOT.png)  | - | 
| 用友网络-开发者中心 | 用友网络 | https://developer.yonyoucloud.com |  ![kfzzx](https://design.yonyoucloud.com/static/tinper-bee/logo/kfzzx.png)  | - | 
| 用友网络-专属云应用平台 | 用友网络 | - |  ![zsyyypt](https://design.yonyoucloud.com/static/tinper-bee/logo/zsyyypt.png)  | - | 
| 用友网络-开放平台 | 用友网络 | - |  ![kfpt](https://design.yonyoucloud.com/static/tinper-bee/logo/kfpt.png)  | - | 
| 用友网络-企业账号中心 | 用友网络 | - |  ![qyzhzx](https://design.yonyoucloud.com/static/tinper-bee/logo/qyzhzx.png)  | - | 
| 用友网络-微服务治理平台 | 用友网络 | - |  ![wfwzlpt](https://design.yonyoucloud.com/static/tinper-bee/logo/wfwzlpt.png)  | - | 
| 用友网络-diwork 工作台 | 用友网络 | https://www.diwork.com/#/ |  ![diwork](https://design.yonyoucloud.com/static/tinper-bee/logo/diwork.png)  | - | 
| 用友网络-NC 工程云 | 用友网络 | - |  ![NCgcy](https://design.yonyoucloud.com/static/tinper-bee/logo/NCgcy.png)  | - | 
| 用友网络-NC 司库云 | 用友网络 | - |  ![NCsky](https://design.yonyoucloud.com/static/tinper-bee/logo/NCsky.png)  | - | 
| 用友网络-用友云平台官网 | 用友网络 | https://www.yonyoucloud.com/ |  ![yptui](https://design.yonyoucloud.com/static/tinper-bee/logo/yptui.png)  | - |

**Comment by pengshaomin** [comment]
不错
