### ISSUE TITLE
tooltip组件，当鼠标移入文字提示框时候，提示框消失的问题

### ISSUE THREAD

**Issue by xiaoxuzh** [iuap-design/tinper-bee#174]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
目前现象：当鼠标移入目标元素时候，弹出文字提示框，这时候正常；
                  当鼠标从目标元素进入文字提示框时候，文字提示框消失了，tinper-bee给出的例子是
                  鼠标移出文字提示框时候提示框才消失，想要实现例子中的效果。
### 代码

<NCTooltip
	inverse
	overlay={‘提示信息’}
	placement="bottom"
>
	<div
	style={{ width: lengthWidth }}
	          className={`${spanPre ? 'spanPre' : ''} ${spanNext? 'spanNext': ''} base-width start- 
                  end`}
	/>
</NCTooltip>
## 当前的行为：效果（可截图说明）及动作描述

 当鼠标从目标元素进入文字提示框时候，文字提示框消失了
## 期望的行为:

鼠标移出文字提示框时候提示框才消失

**Comment by yangchch6** [comment]
相关的使用代码麻烦截全一点吧，标签都是一半的，最好保留下代码格式
