### ISSUE TITLE
Table . 组件 dataIndex 希望可以支持 'a.a' 带点的key值

### ISSUE THREAD

**Issue by simplealittle** [iuap-design/tinper-bee#177]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:Table . 组件 dataIndex 希望可以支持 'a.a' 带点的key值

const columns = [
  { title: "员工编号", dataIndex: "a.a", key: "a.a", width: 150 },
  { title: "员工姓名", dataIndex: "b", key: "b", width:100},
  { title: "性别", dataIndex: "c", key: "c", width: 100},
  { title: "部门", dataIndex: "d", key: "d", width: 100 },
  { title: "职级", dataIndex: "e", key: "e", width: 100 }
];

const data = [
  { 'a.a': "ASVAL_20190328", b: "小张", c: "男", d: "财务二科", e: "M1", key: "1" },
  { 'a.a': "ASVAL_20190320", b: "小明", c: "男", d: "财务一科", e: "T1", key: "2" },
  { 'a.a': "ASVAL_20190312", b: "小红", c: "女", d: "财务一科", e: "T2", key: "3" }
];
希望可以支持 'a.a'  我试了'a/a'这种可以，为什么要屏蔽点呢。
在后端数据中 很多是带点的

**Comment by jonyshi** [comment]
暂时无法提供此需求，后期考虑！
