### ISSUE TITLE
【需求】触摸屏需要table支持左右滚动按钮的扩展

### ISSUE THREAD

**Issue by caizx666** [iuap-design/tinper-bee#178]
## 描述这个问题:

![微信图片_20190516090240](https://user-images.githubusercontent.com/18454416/57819078-634a9c80-77b9-11e9-874a-f1b22552a140.png)

## 期望的行为:
能提供扩展上面图片那样提供扩展左右两侧按钮，按钮是用来点击滚动列（触摸屏需求）

**Comment by yangchch6** [comment]
1、需要确认下：在触摸屏上该页面初始化的时候，是否会出现表体下面的滚动条？
2、出现滚动条的话，手指滑动表体就能滚动列。
3、通过左右两侧按钮滚动和滚动条本质上功能是相同的，二者选一种解决方案即可。
