### ISSUE TITLE
RangePicker 日期控件，showOk, showToday 属性设置false不显示，不生效

### ISSUE THREAD

**Issue by HaoGeShuoHuaNiHaoHaoTing** [iuap-design/tinper-bee#179]
## 环境及版本信息

- `tinper-bee` 版本号:  

@2.0.9
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

import * as DatePicker from "tinper-bee/lib/Datepicker";
import moment from "moment";
require('bee-datepicker/build/DatePicker.css');

              <RangePicker
                placeholder={'开始 ~ 结束'}
                dateInputPlaceholder={['开始', '结束']}
                showClear={true}
                showOk={false}
                showToday={false}
                format='YYYY-MM-DD'
                onChange={this.onDateChange}
                className='billRangePicker'
                defaultValue={[moment(), moment()]}
              />
### 报错信息

底部的确定按钮，返回今天，依然存在

**Comment by lucian55** [comment]
bee-datepicker@2.0.34  已解决此问题
