### ISSUE TITLE
问题反馈：Modal相关

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#18]
### 需求

- __Package version(s)__: (0.5.3)

#### 描述这个问题:
- Modal组件需要右上角关闭的一个按钮，可以增加设置属性来显示或关闭此按钮。
- Modal 下面Footer需要增加参数可以设置“左”、“中”、“右”按钮组显示。

**Comment by ahua52** [comment]
回复
第一问题：closeButton[bool] 可控制是否限制关闭按钮
第二问题：默认footer 按钮居右，可自行定义扩展className
