### ISSUE TITLE
日期范围控件enter无法把时间带回输入框

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#183]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker：2.0.36

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
日期范围的组件，输完一次日期之后，再次打开，手动输入结束时间，按enter，无法把输入的时间带回输入框，还是显示第一次的时间，官网可复现

**Comment by lucian55** [comment]
bee-datepicker@2.0.39 已解决
