### ISSUE TITLE
使用Modal组件，报candidates.find is not a function错误

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#184]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：Windows

- 所使用的浏览器：T+浏览器，使用的44.0.2403.130内核

## 描述这个问题:
![image](https://user-images.githubusercontent.com/25068905/58154546-73c0b280-7ca4-11e9-8c18-7624a086321d.png)

**Comment by yangchch6** [comment]
在 T+ 浏览器的控制台中，看到源码都没有进行编译，都还是 ES6 代码。包括上面提的错误信息：“Uncaught TypeError: candidates.find is not a function”，也是未识别 ES6 导致的。可以看下你们是否引入了 polyfill，用了哪些 plugin，是否编译成 ES5。

**Comment by yangchch6** [comment]
tinper-bee@2.1.1-beta.0 解决了这个问题，下周会发正式版本。
