### ISSUE TITLE
table组件中的id问题

### ISSUE THREAD

**Issue by simplealittle** [iuap-design/tinper-bee#185]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
table组件中出现相同的id

### 代码

![image](https://user-images.githubusercontent.com/42159337/58155683-efbbfa00-7ca6-11e9-973d-c5254b3fbcc1.png)

## 期望的行为:

虽然不至于有错误 ，但是感觉这样以后有可能产生未知的错误

**Comment by yangchch6** [comment]
bee-table 去掉了重复的 id，tinper-bee 发布 2.0.13 版本的时候，会同步最新代码
