### ISSUE TITLE
日期范围控件快捷键支持

### ISSUE THREAD

**Issue by 1039958384** [iuap-design/tinper-bee#186]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker：2.0.36

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 期望的行为:

（1）点击“下键”打开日期范围面板且焦点落在开始时间，开始时间录入完整8位数后，光标应该直接跳到结束日期里；若没录完8位数想输入结束日期；“右键/enter键”跳到结束时间。
（2）“tab”跳到数字日期区域，再“tab”跳到函数区域(tab到函数区可自行实现，但是**目前日期范围面板的tab顺序是：开始时间录入框-左侧数字日期区域-结束时间录入框-右侧数字日期区域-函数区域；期望的tab顺序是：开始时间录入框-中间数字日期区域-函数区域**)，
（3）“enter”确认，“esc”关闭面板。
（4） 焦点在数字日期区域：“上下左右”移动焦点，“enter”选中。
（5） 焦点在录入区域：“左右”移动焦点，光标如果在起始日期末尾，“右左”可在起始结束间跳动。
（6）焦点在函数区域：“上下左右”移动焦点，**“enter”选中**（上下左右移动焦点如何能解决与数字日期区域上下左右移动焦点的冲突，enter选中函数如何解决与原有enter键的冲突，需要考虑）。

**Comment by lucian55** [comment]
bee-datepicker @2.0.37 版本
2，3，4，5，6需求已完成
