### ISSUE TITLE
版本相同bee-table开启scroll滚动时表现行为不一致

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#187]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.11

- 当前项目中`react`的版本号：
与`react`版本无关

## 描述这个问题:

`Table`开启scroll纵向滚动时，行为正常时`u-table-header`的内联样式为`margin-bottom: -8px`，在另外一个工程里`u-table-header`的内联样式为`margin-bottom: 0px`，导致出现错位。
正常表现
![image](https://user-images.githubusercontent.com/19931582/58169435-4f280300-7cc3-11e9-816e-5b5db0364189.png)
异常表现
![image](https://user-images.githubusercontent.com/19931582/58169483-6cf56800-7cc3-11e9-82eb-a934047da520.png)

**Comment by whizbz11** [comment]
在模态框中使用table，计算滚动条的宽度算法进行了调整，发了测试包bee-table@2.0.25-beta.0
