### ISSUE TITLE
表格行拖拽，无法拖拽到第一行

### ISSUE THREAD

**Issue by sunshine887** [iuap-design/tinper-bee#188]
## 环境及版本信息

- `tinper-bee` 版本号:  V2.0.11

- 若使用单个组件，请标明该组件版本号：v2.0.14

- 当前项目中`react`的版本号：

- 所使用的操作系统：mac

- 所使用的浏览器：chrome 

### 代码
官网demo中也是这样子。

## 期望的行为:
行拖拽可以拖拽到表格的第一行。

**Comment by yangchch6** [comment]
tinper-bee 2.0.12 发包后，升级即可
