### ISSUE TITLE
table组件扩展行的图标不支持用户扩展

### ISSUE THREAD

**Issue by wangbow** [iuap-design/tinper-bee#19]
### Bug 报告

- tinper-bee："version": "0.5.4",

#### 描述这个问题:
我想更换这个+号图标，现在是不能进行更换的，下面是截图

#### 当前的行为:

![v 4e34dztp2o 9yujao2si3](https://user-images.githubusercontent.com/21334770/28956354-eae2f98a-791e-11e7-826b-d9c09ab656fc.png)

#### 期望的行为:

![7b_w 8 l lft9yij7 855hi](https://user-images.githubusercontent.com/21334770/28956310-9f7827b8-791e-11e7-9ee0-3cbac006b4c6.png)

**Comment by jonyshi** [comment]
需求已经确认。【需要显示用户Icon】
解决方案：增加一列显示图像即可。
