### ISSUE TITLE
使用了CheckboxGroup之后，单独设置内部的checkbox disabled属性，不生效

### ISSUE THREAD

**Issue by HaoGeShuoHuaNiHaoHaoTing** [iuap-design/tinper-bee#190]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.9

- 若使用单个组件，请标明该组件版本号：引用的tinper-bee

- 当前项目中`react`的版本号：16.8

- 所使用的操作系统：window

- 所使用的浏览器：chrome

## 描述这个问题:
使用了CheckboxGroup之后，单独设置内部的checkbox disabled属性，不生效
### 报错信息

![image](https://user-images.githubusercontent.com/28486250/58300568-a3db9300-7e15-11e9-9276-b0730306c2a7.png)

**Comment by yangchch6** [comment]
bee-checkbox@2.0.6 解决了这个问题。
