### ISSUE TITLE
Radio 组件中，动态绑定数据，数据集合长度为1报错，大于1以上没有问题。

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#191]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：Windows

- 所使用的浏览器：Chrome

### 代码

![image](https://user-images.githubusercontent.com/25068905/58312449-e022e980-7e3d-11e9-9b02-0d8551202640.png)

### 报错信息

报错信息见截图

**Comment by lucian55** [comment]
代码贴一下吧

**Comment by lucian55** [comment]
bee-radio@2.0.9  已解决
