### ISSUE TITLE
checkbox的defaultChecked 用变量控制不生效

### ISSUE THREAD

**Issue by houjjb** [iuap-design/tinper-bee#192]
## 环境及版本信息

- `tinper-bee` 版本号:  

1.4.2
- 若使用单个组件，请标明该组件版本号：

checkbox
- 当前项目中`react`的版本号：

16.3.2
- 所使用的操作系统：

win10
- 所使用的浏览器：

谷歌
![image](https://user-images.githubusercontent.com/50894649/58312519-06e12000-7e3e-11e9-9ead-84da29ebf586.png)

## 描述这个问题:
checkbox的默认值defaultChecked={变量} 不生效，但是直接写死defaultChecked={true}会生效
### 代码

![image](https://user-images.githubusercontent.com/50894649/58312604-3728be80-7e3e-11e9-857a-e03a13784d20.png)

## 当前的行为：效果（可截图说明）及动作描述

defaultChecked={orderRow.arriveflag == 1 ? true : false}中orderRow.arriveflag == 1 ? true : false值为true,但是界面还是没有勾选状态

![image](https://user-images.githubusercontent.com/50894649/58312309-9f2ad500-7e3d-11e9-8afe-c0af2a51963e.png)

**Comment by lucian55** [comment]
defaultChecked 只在组件初始化时候设置值，并且不会改变。你的值应该是接口返回的，接口返回时组件已经初始化完成。所以不会改变值。  你可以使用 checked 代替 defaultChecked 即可
