### ISSUE TITLE
表格模态框修改数据，createForm is not a function

### ISSUE THREAD

**Issue by lmhhhhs** [iuap-design/tinper-bee#193]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

const RefEditCell = Form.createForm()(
class RefComponentWarpper extends PureComponent {
constructor(props, context) {
super(props);
}

### 报错信息

![d9939741ccdd120031fcfef0cc23dda](https://user-images.githubusercontent.com/39038870/58382593-c54ba300-7ffe-11e9-916c-e8ed54f95a7f.png)

**Comment by lucian55** [comment]
使用参照的时候，如果你需要form校验的话，需要将form传进参照里
参照新增参数  form={this.props.form}
