### ISSUE TITLE
组件表格-固定表头-当y轴没有滚动条，对行做选中操作，右侧有空白

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#194]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：Windows

- 所使用的浏览器：Chrome

## 当前的行为：效果（可截图说明）及动作描述
![image](https://user-images.githubusercontent.com/25068905/58390557-5bfe7b00-8064-11e9-82bf-f9bd6ffb7f37.png)

上图为实际应用场景，选中行之后，右侧有空白。

**Comment by whizbz11** [comment]
这个问题已经解决，发了测试包bee-table@2.0.26-beta.0,这周五会发tinper-bee 的新包
