### ISSUE TITLE
设置一个按钮，点击按钮时候，动态的合并或者拆分Table的单元格，其他单元格位置不受影响

### ISSUE THREAD

**Issue by xiaoxuzh** [iuap-design/tinper-bee#196]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

table的版本为2.0.8
- 当前项目中`react`的版本号：

- 所使用的操作系统：

w10
- 所使用的浏览器：

Chrome 74.0.3729.157
## 描述这个问题:
点击页面上一个按钮，动态改变Table的单元格，使其被选中的单元格进行合并或者拆分，其他未选中的单元格位置，内容不发生变化
### 代码

{
				title: j,
				dataIndex: i + 'unit-' + j + 'room',
				key: i + 'unit-' + j + 'room',
				width: baseWidth,
				className: 'rowClassName',
				// render: (text, record, index) => <RefEditCell colName="1" value={text} />
				render: (text, record, index) => {
					const obj = {
						children: createRefEditCell.call(this, this.props, {
							colName: '1',
							value: text
						}),
						props: { colSpan: onColSpan.call(this) || 1 }
					};
					return obj;
				}
			}
在上述代码中，colSpan的值是onColSpan()方法动态返回的一个值，页面上有个按钮，点击按钮，可以改变onColSpan的返回值，页面刷新了，但是Table的单元格并没有发生变化
## 期望的行为:

期望的效果：Table的单元格可以动态的合并单元格（合并列或者合并行都有需要），拆分单元格（拆分行或者拆分列），单元格进行合并，拆分的时候，其他单元格位置，数据不发生变化

**Comment by whizbz11** [comment]
需要确认两个问题1、点击按钮，更改column后，有没有触发render；2、传入给Table组件的column内容是否正确

**Comment by xiaoxuzh** [comment]
点击按钮之后，主页面有setState() 进行刷新
传给Table的值应该正确，表格能正常渲染，就是没有达到想要的合并拆分效果

**Comment by whizbz11** [comment]
column中对应的render方法，props属性对应colSpan值是否正确，表格中根据colSpan值合并单元格的。如何检查都正确，可以写下具体的代码，我这边本地无法重现
