### ISSUE TITLE
tinper编译报提示找不到sourcemap文件的警告

### ISSUE THREAD

**Issue by utopiaGYB** [iuap-design/tinper-bee#197]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.0.12

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

Mac
- 所使用的浏览器：

### 报错信息
WARNING in ./node_modules/tinper-bee/dist/Select/index.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'performance-now.js.map': Error: Can't resolve './performance-now.js.map'in '/Users/gengyuanbiao/frontend/FrontEnd/portalTouch/node_modules/tinper-bee/dist/Select'

WARNING in ./node_modules/tinper-bee/dist/Table/index.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'performance-now.js.map': Error: Can't resolve './performance-now.js.map'in '/Users/gengyuanbiao/frontend/FrontEnd/portalTouch/node_modules/tinper-bee/dist/Table'

WARNING in ./node_modules/tinper-bee/dist/Modal/index.js
(Emitted value instead of an instance of Error) Cannot find SourceMap 'react-draggable.js.map': Error: Can't resolve './react-draggable.js.map'in '/Users/gengyuanbiao/frontend/FrontEnd/portalTouch/node_modules/tinper-bee/dist/Modal'

## 当前的行为：效果（可截图说明）及动作描述
编译工程时报的错误

## 期望的行为:
去除这些警告信息

**Comment by yangchch6** [comment]
是执行 npm run build 的时候，出现的警告吗？具体场景可以再描述下，我用一个工程测试了下，打包时没有重现上述问题，可以详细说下是什么工程。
