### ISSUE TITLE
popover关闭时间较长  建议优化下

### ISSUE THREAD

**Issue by utopiaGYB** [iuap-design/tinper-bee#198]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 当前的行为：效果（可截图说明）及动作描述
popover  关闭的时间比较长啊
官网的demo就很慢

## 期望的行为:
能够快速关闭

**Comment by yangchch6** [comment]
bee-popover@3.0.0 解决了这个问题，本周五会发布 tinper-bee
