### ISSUE TITLE
table 表格行拖拽支持触摸屏

### ISSUE THREAD

**Issue by sunshine887** [iuap-design/tinper-bee#199]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
新需求：
表格行拖拽功能：支持触摸屏版，现在支持pc版

**Comment by yangchch6** [comment]
bee-table@2.1.4-beta.0，行拖拽功能支持触摸屏。
tinper-bee 下次发版会把这个特性加进去。
