### ISSUE TITLE
bee-timepicker  格式化时间问题

### ISSUE THREAD

**Issue by taislung** [iuap-design/tinper-bee#202]
- bee-timepicker：

## 描述这个问题:
文档和demo 没有提这个format问题，如果用format("hh:mm:ss") 格式化完以后是12小时的格式，所以我觉得文档format部分最好给一个默认值（HH大写，才能保证是24小时格式），参考antd如下：
format | 展示的时间格式 | string | "HH:mm:ss"

**Comment by yangchch6** [comment]
bee-timepicker@2.0.4，format 默认取值 “h:mm:ss a”。可与 showHour 、 showMinute 和 showSecond 组合使用。
