### ISSUE TITLE
 modal在配置拖拽大小和位置后，header子元素除了button，其他绑定的事件都不触发

### ISSUE THREAD

**Issue by Lucialiuxi** [iuap-design/tinper-bee#204]
## 环境及版本信息

- `tinper-bee` 版本号:  v1.6.3

- 若使用单个组件，请标明该组件版本号：bee-modal：v2.0.10

- 当前项目中`react`的版本号：v16.3.2

- 所使用的操作系统：Windows

- 所使用的浏览器：chrome 版本号74.0.3729.169

## 描述这个问题:
     modal在配置拖拽大小和位置时。header里放除button外的元素，元素绑定的事件不会触发

### 代码
import React, { Component } from 'react';
import { Button } from 'tinper-bee';
import Modal from "bee-modal";
import Checkbox from 'bee-checkbox';

export default class Demo13 extends Component {
    constructor(props) {
        super(props);
        this.state = {
            showModal: false
        };
        this.close = this.close.bind(this);
        this.open = this.open.bind(this);
    }

    close() {
        this.setState({
            showModal: false
        });
    }
    open() {
        this.setState({
            showModal: true
        });
    }
    onResizeStart = (e, dir, elementRef) => {
        console.log("onResizeStart", e, dir, elementRef)
    }
    onResize = (e, dir, elementRef, delta) => {
        console.log("onResize", e, dir, elementRef, delta)
    }
    onResizeStop = (e, dir, elementRef, delta) => {
        console.log("onResizeStop", e, dir, elementRef, delta)
    }

    changeCheck=()=> {
      this.setState({checked:!this.state.checked});
    }
    changeDisabled=()=> {
      this.setState({disabled:!this.state.disabled});
    }
    render () {
        const label = `${this.state.checked ? 'Checked' : 'Unchecked'}-${this.state.disabled ? 'Disabled' : 'Enabled'}`;
        return (
        <div>
            <Button
            colors = "primary"
            className="demo-margin"
            onClick = { this.open }>
                打开模态框
            </Button>​
            <Modal
            show = { this.state.showModal }
            draggable={true}
            backdropClosable={false}
            resizable={true}
            resizeClassName="resize-box"
            maxWidth={"1000"}
            maxHeight={"500px"}
            minWidth={300}
            minHeight={150}
            onResizeStart={this.onResizeStart}
            onResize={this.onResize}
            onResizeStop={this.onResizeStop}
            onHide = { this.close } >
                <Modal.Header closeButton>
                    <Modal.Title>
                      <span>标题</span>
                      <Checkbox 
                        checked={this.state.checked} 
                        disabled={this.state.disabled} 
                        onChange={this.changeCheck}
                      >
                        {label }
                      </Checkbox>
                    </Modal.Title>
                </Modal.Header>

                <Modal.Body>
                    <p>Some contents...</p>
                    <p>Some contents...</p>
                    <p>Some contents...</p>
                    <p>
                      <Button 
                        colors="secondary" 
                        onClick={this.changeCheck.bind(this)}
                        style={{marginRight:"8px"}}
                      >
                        {!this.state.checked ? 'Check' : 'Uncheck'}
                      </Button>
                      <Button 
                        colors="secondary" 
                        onClick={this.changeDisabled.bind(this)}
                      >
                        {!this.state.disabled ? 'Disable' : 'Enable'}
                      </Button>
                    </p>
                </Modal.Body>

                <Modal.Footer>
                    <Button onClick={ this.close } colors="secondary" style={{marginRight: 8}}>取消</Button>
                    <Button onClick={ this.close } colors="primary">确认</Button>
                </Modal.Footer>
           </Modal>
        </div>
        )
    }
}

### 报错信息
无

## 当前的行为：
点击header里的复选框，没有触发onChange事件

## 期望的行为:
希望支持拖拽之后，不阻止modal的header里各个元素绑定的事件正常触发

**Comment by yangchch6** [comment]
给模态框标题内，需要绑定事件的元素，添加一个 className="dnd-cancel"，即可正常触发相应事件。
具体代码如下：
```
              <Modal.Header closeButton>
                    <Modal.Title>
                    <Checkbox 
                        className="dnd-cancel"
                        checked={this.state.checked}  
                        onChange={this.changeCheck}
                    >
                        可勾选的标题
                    </Checkbox>
                    </Modal.Title>
                </Modal.Header>
```
