### ISSUE TITLE
RangePicker设置open属性不能控制展开

### ISSUE THREAD

**Issue by bbqin** [iuap-design/tinper-bee#205]
## 环境及版本信息

- `tinper-bee` 版本号:   1.6.3

- 若使用单个组件，请标明该组件版本号： "bee-datepicker": "2.0.38",

- 当前项目中`react`的版本号："react": "16.8.6",

- 所使用的操作系统：windows

- 所使用的浏览器：chrome

## 描述这个问题:
RangePicker设置open属性未能生效，或许尚未支持。
### 代码

```
<RangePicker
     dropdownClassName={dropdownClassName}
    className="nc-input"
    format={format}
    open={open || false}
/>
```

## 当前的行为：效果（可截图说明）及动作描述

不支持open属性控制展开。
## 期望的行为:

建议可以添加open属性，效果如同datepicker的open。

**Comment by yangchch6** [comment]
收到~，请问下你们是哪个项目组的呀？

**Comment by yangchch6** [comment]
- bee-datepicker@2.0.40
    - [Feature]RangePicker增加 `open` 属性和 `onOpenChange` 回调函数

周五发布 tinper-bee 的时候，会把这个新属性加进去
