### ISSUE TITLE
组件传入className时tinper-bee自身的样式权重会更高

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#206]
## 环境及版本信息

- `tinper-bee` 版本号:  
`2.0.11`

- 若使用单个组件，请标明该组件版本号：
无单组件

- 当前项目中`react`的版本号：
`16.4.2`

- 所使用的操作系统：
MacOS

- 所使用的浏览器：
Chrome 74

## 描述这个问题:
手动引入`tinper-bee.css`，使用组件的`className`属性时，本地调试时`tinper-bee`的样式权重要高于传入`className`权重。本地开启了`css module`。

以引入`Tree `组件为例，手动传入`className``leftTree`，编译之后`Tree`组件本身的样式权重会高于`leftTree`的权重

![image](https://user-images.githubusercontent.com/19931582/58546507-15617a00-8238-11e9-8e18-c6de8c08480e.png)

### 报错信息
无报错

## 期望的行为:
组件`className`传入样式可以准确覆盖组件自身样式

**Comment by whizbz11** [comment]
你看下你的样式引用顺序，组件库的样式里面没有特殊配置，
![image](https://user-images.githubusercontent.com/13316317/58547180-7d649000-8239-11e9-9b73-d6a74f25a087.png)
