### ISSUE TITLE
table空数据时，表头不要滚动条

### ISSUE THREAD

**Issue by HaoGeShuoHuaNiHaoHaoTing** [iuap-design/tinper-bee#207]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.12

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8

- 所使用的操作系统：window

- 所使用的浏览器：chrome

## 描述这个问题:
在使用tinper-bee@2.0.9时，空数据时，表头是不会出现滚动条的，这样的效果很好。
但是升级到 2.0.12时，空数据时，表头就出现了滚动条，看起来很不好。
我使用的表格中，左侧列固定，右侧设置滚动；
表格中有数据的时候，表头的滚动条就会被遮住；空数据时，就遮不住
### 代码

![image](https://user-images.githubusercontent.com/28486250/58601677-83e81b80-82bc-11e9-95db-4e83e3e3a905.png)

**Comment by whizbz11** [comment]
1、没有数据时列比较宽时，需要有横向滚动条，否则后面的列不显示；2、如果有数据时，滚动条会在表体中出现。后续可以优化一下，没有数据时滚动条在表体中出现

**Comment by yangchch6** [comment]
Table 会根据列宽，自动显示和隐藏滚动条，否则表格列会显示不全。如果需要去掉无数据时的滚动条，给 .u-table-header 这个类设置 `margin-bottom: -8px` 即可。

**Comment by yangchch6** [comment]
发了新包 bee-table@2.1.6-beta.0，table 无数据时，支持通过设置 `hideHeaderScroll=true` ，达到隐藏表头滚动条的效果。
