### ISSUE TITLE
Modal可拖拽后内部可拖拽组件卡顿

### ISSUE THREAD

**Issue by chern1992** [iuap-design/tinper-bee#208]
我们原来有个modal是自己写的，后来UE这边要求统一Modal及拖拽，就打算换成你们的Modal,但是我们在Modal.body里面有用antv-g6实现的可拖拽流程图，现在就是拖拽我里面流程图的时候，会被你们的modal认为是在拖拽modal,能支持下Modal里面仍然有可拖拽元素的情况吗

**Comment by yangchch6** [comment]
你是即需要拖拽调整 Modal 大小，又需要在 Modal.body 里面加可拖拽元素是吗？

**Comment by chern1992** [comment]
对

**Comment by chern1992** [comment]
那个可拖拽宽度是交互统一定的，让我们跟着统一，里面以后可图拽元素是我们的业务需求

**Comment by yangchch6** [comment]
目前拖拽功能使用了第三方插件，我们看下后续是否能优化下

**Comment by yangchch6** [comment]
升级至最新版验证 ok
