### ISSUE TITLE
Tree组件添加`checkedKeys`属性后`check`功能失效

### ISSUE THREAD

**Issue by GRAMMAC1** [iuap-design/tinper-bee#209]
## 环境及版本信息

- `tinper-bee` 版本号:  
`2.0.12`

- 若使用单个组件，请标明该组件版本号：
无

- 当前项目中`react`的版本号：
`16.4.2`

## 描述这个问题:
使用`Tree`组件添加`checkedKeys`属性手动指定选中项后正常的勾选功能失效
[![Edit Tree bug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pjq4rmv4jq?autoresize=1&fontsize=14)
在线demo可以复现

## 期望的行为:
添加`checkKeys`属性后依然可以正常勾选

**Comment by whizbz11** [comment]
onCheck后需要将checkedKeys同步过来，传递给Tree组件
