### ISSUE TITLE
抽屉关闭图标支持

### ISSUE THREAD

**Issue by simplealittle** [iuap-design/tinper-bee#210]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.0.12
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
抽屉组件中 删除图标支持
### 代码

![image](https://user-images.githubusercontent.com/42159337/58683488-2b417d00-83a7-11e9-8c49-b8d4803817cb.png)
关闭图标希望可以替换成我们自己的
## 期望的行为:

期望可以修改关闭图标 ，我看你们的图标是手写的X
![image](https://user-images.githubusercontent.com/42159337/58683525-5035f000-83a7-11e9-8126-03ca710fa028.png)
感觉不是很好

**Comment by yangchch6** [comment]
您好，请问下您是哪个项目组的？

**Comment by simplealittle** [comment]
> 您好，请问下您是哪个项目组的？

畅捷通 t+

**Comment by yangchch6** [comment]
bee-drawer@0.0.3，将关闭图标替换为 Icon 组件。

**Comment by simplealittle** [comment]
> bee-drawer@0.0.3，将关闭图标替换为 Icon 组件。
我换成3了  还是X啊  ；
文档可以更新一下吗  ？我想用我们自己的图标。。

**Comment by yangchch6** [comment]
你是想自定义关闭图标啊，我以为是把 X 换成 Icon 组件。。。
那我加个 API 吧

**Comment by yangchch6** [comment]
bee-drawer@0.0.4，增加了 `closeIcon` 属性，支持自定义关闭图标。使用方法如下：
```
                <Drawer closeIcon={<Icon type="uf-close-c"/>} showClose={true} className={'demo1'} title={title} show={showDrawer} placement={placement} onClose={this.fCloseDrawer}>
                    <div className="con">
                        <p>这是第一行文字</p>
                        <p>这是第二行文字</p>
                        <p>这是第三行文字，啦啦啦~</p>                                                 
                    </div>
                </Drawer>
```
