### ISSUE TITLE
抽屉的渲染与否

### ISSUE THREAD

**Issue by simplealittle** [iuap-design/tinper-bee#211]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.0.12
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
抽屉不支持api调用，只能在初始化页面的时候把抽屉组件铺出来；
我看了一下现象，visble为false的时候，抽屉内部的dom已经渲染了 只不过不显示。
所以我做了这样的处理

让visible为false的时候不渲染dom；

## 期望的行为:

我期望 抽屉组件可以通过一个param   控制visible为false时是删除内部dom还是display：none；
这样对于首页加载速度或者抽屉弹出是否重新渲染的取舍由用户（我们一线）决定；
另：或者提供提供类似 message 一样的api调用来解决页面初始化时不渲染抽屉，但是并不建议这样。

**Comment by yangchch6** [comment]
目前已经有一个 `destroyOnClose` 参数，设置关闭时候是否销毁抽屉的内容。具体可以查看官网的文档说明。

**Comment by simplealittle** [comment]
> destroy

> 目前已经有一个 `destroyOnClose` 参数，设置关闭时候是否销毁抽屉的内容。具体可以查看官网的文档说明。

嗯 还真是，看文档我以为只是关闭时  删除dom呢。。
