### ISSUE TITLE
日期组件问题

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#212]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"bee-datepicker": "2.0.39"
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
日期组件和日期范围组件都需要适配format支持传数组，但是在moment中应该取数组的第一个
### 代码

![image](https://user-images.githubusercontent.com/19504234/58687044-123ec900-83b3-11e9-8d91-3080992a0ef6.png)

**Comment by lucian55** [comment]
日期组件datepicker已支持，可以升级使用，日期范围目前没有

**Comment by max-well** [comment]
这个是datepicker所传的属性
![image](https://user-images.githubusercontent.com/19504234/58786384-00ab2a80-861a-11e9-9db2-5b7bc872b96f.png)
这个是rangepicker所传的属性
![image](https://user-images.githubusercontent.com/19504234/58786447-2c2e1500-861a-11e9-9ab9-cd8651037a19.png)

 会报很多这种错
![image](https://user-images.githubusercontent.com/19504234/58786480-410aa880-861a-11e9-9219-e3a98129d180.png)

**Comment by yangchch6** [comment]
RangePicker 也支持 format 传入数组
