### ISSUE TITLE
下拉参照 RefCombobox增加数据返回字段

### ISSUE THREAD

**Issue by houjjb** [iuap-design/tinper-bee#213]
## 环境及版本信息

- `tinper-bee` 版本号:  

无
- 若使用单个组件，请标明该组件版本号：

下拉参照 RefCombobox v2.0.4
- 当前项目中`react`的版本号：

无
- 所使用的操作系统：

windows
- 所使用的浏览器：

chrome
## 描述这个问题:
传给组件的storeData，当我选中一条数据时，我需要拿到整条数据的所有字段，而不是只有refname,refpk  ,另外，能否支持多选，显示的时候，依然只显示refname

**Comment by XYooo** [comment]
ref-combobox@2.1.0
添加多选以及单个标签删除功能。

注意事项：
onChange返回数组格式，不再是字符串'{"refname":"","refpk":''}'
onClickItemInner函数，返回参数依次是selectedArray,item,status，selectedArray表示当前selector框内所有数据，item是当前选中/删除的数据，status表示状态是删除还是选中

**Comment by XYooo** [comment]
ref-combobox@2.1.0
添加多选以及单个标签删除功能。

注意事项：
onChange返回数组格式，不再是字符串'{"refname":"","refpk":''}'
onClickItemInner函数，返回参数依次是selectedArray,item,status，selectedArray表示当前selector框内所有数据，item是当前选中/删除的数据，status表示状态是删除还是选中
