### ISSUE TITLE
RangePicker 在有值情况下点击面板上的清除icon,在选择日期时报错，页面无法显示

### ISSUE THREAD

**Issue by wjchmr** [iuap-design/tinper-bee#216]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
"bee-datepicker": "^2.0.37",

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

![image](https://user-images.githubusercontent.com/18568858/58872862-8650d800-86f7-11e9-820d-b94ca4e79998.png)

**Comment by yangchch6** [comment]
没有复现，贴下具体代码吧，然后你再看下这个 'length' of null，到底是哪里 length，定位下是组件问题，还是业务逻辑问题。
可以先注释掉业务逻辑，用最简单的 Demo 测试下，看还有没有问题。
