### ISSUE TITLE
Table组件，列属性width值，默认最后一列撑开最后的空间。希望这个列可以自定义，而不是默认成最后一列

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#219]
## 环境及版本信息

- `tinper-bee` 版本号:  v2.0.13

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：Windows

- 所使用的浏览器：Chrome

## 期望的行为:
希望对table中撑开剩余宽度的列可以自定义设置，而不是默认成最后一列。

**Comment by yangchch6** [comment]
需要撑开宽度的列，给其设置 width 为百分比，代码：
```
const columns = [
  { title: "员工编号", dataIndex: "a", key: "a" },
  { title: "员工姓名", dataIndex: "b", key: "b", width:"60%"},
  { title: "性别", dataIndex: "c", key: "c" },
  { title: "部门", dataIndex: "d", key: "d" },
  { title: "职级", dataIndex: "e", key: "e" }
];
```
效果图：
![image](https://user-images.githubusercontent.com/33412781/59181193-5a22d480-8b99-11e9-9195-8d3e1a6d91bf.png)
