### ISSUE TITLE
Upload组件上传文件后的删除按钮英文的问题

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#22]
### Bug 报告

- __Package version(s)__: (版本号)0.6.2

#### 描述这个问题:Upload组件上传文件后的删除按钮英文的问题

![image](https://user-images.githubusercontent.com/3817644/30424717-5fac066a-9979-11e7-80ae-3ca7438c9739.png)

**Comment by jonyshi** [comment]
已经修正
