### ISSUE TITLE
dropdown支持设置延迟显示

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#220]
## 环境及版本信息
- `tinper-bee` 版本号:   单引组件

- 若使用单个组件，请标明该组件版本号：bee-dropdown@1.0.6

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：window 10 

- 所使用的浏览器：chrome 72

## 描述这个问题:
dropdown 组件设置overlay延迟1秒显示 看文档也没找到相关可以处理的属性
## 期望的行为: 

期望可以控制弹出层的延迟

**Comment by lucian55** [comment]
bee-dropdown@2.0.7  新增如下api


|参数|说明|类型|默认值|
|:--|:---|:----|:---|
|delay|延迟显示隐藏时间，单位毫秒|number|-|
|delayShow|延迟显示时间，单位毫秒|number|-|
|delayHide|延迟隐藏时间，单位毫秒|number|-|
