### ISSUE TITLE
rangpicker 快速点击3次及以上同一天会清空值

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#221]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker@2.0.43

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：window 10

- 所使用的浏览器：chrome 75

## 描述这个问题: 
rangerpicker 选择一组值
再点开面板，对同一天快速点击会清空值

## 期望的行为:

对同一天快速点击时，不清空值，触发DoubleClick时不清空值

**Comment by bbqin** [comment]
该问题在tinper官方示例上可以重现。
[问题演示视频](https://drive.google.com/file/d/1EPcMHx6Kb_etjYDzdxqPU51tLSSEwfSn/view)

**Comment by yangchch6** [comment]
升级 bee-datepicker@2.1.2，已解决该问题。
