### ISSUE TITLE
Upload组件上传时间过长报错

### ISSUE THREAD

**Issue by chern1992** [iuap-design/tinper-bee#222]
使用Upload组件导入文件，当导入时间超过2min后报错，无法显示导入结果信息
环境及账号信息：
10.11.117.68:6004 
ncc1909jgy20190604/1@orcl_20.10.130.222 
jj1\123456a
NCC bug号：NCCLOUD-133294

**Comment by yangchch6** [comment]
我这里没有权限看 Bug 信息，需要提供下复现的操作步骤，或者截图出来
