### ISSUE TITLE
日期组件弹出层位置优化

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#224]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker@2.0.43

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：windows 10

- 所使用的浏览器：chrome 75

## 描述这个问题:

当页面余下位置不足以展示日期弹出层时，日期组件弹出层还是向下弹出，用户需要滚动才能选择日期。

## 期望的行为:

对日期弹出层优化处理：
余下空间小于弹出层高度时，建议向上弹出
或者撑滚动条，让滚动条向下滚动一个弹出层高度(放在各种模态框种可能存在问题）
建议处理为弹出层为向上弹出吧

**Comment by lucian55** [comment]
向上向下弹出是根据整个文档的高度，这部分逻辑在依赖组件里，无法修改为根据当前窗口高度。 
提供以下属性，你可以自行处理弹出位置

|参数|说明|类型|默认值|
|:---|:-----|:----|:------|
| placement | 日期面板弹出位置，可选 `bottomLeft/bottomRight/topRight/topLeft` | string |  bottomLeft  |
