### ISSUE TITLE
datepicker 组件 open 传 false 不生效

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#226]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker@2.0.43

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：window 10 

- 所使用的浏览器：chrome 75

## 描述这个问题:
日期组件open传false，依旧可以点开日期面板。之前版本是可以控制的。

### 代码

![image](https://user-images.githubusercontent.com/16048628/59575684-1b3bd400-90ef-11e9-836b-e8b0557ee2e4.png)

## 期望的行为:

open 属性 传 false 可以控制 日期组件弹出

**Comment by lucian55** [comment]
bee-datepicker @2.0.45 已解决
