### ISSUE TITLE
bee-tree 选择完节点后滑动到底部再点加号或旁边的空白处会重新滚动到顶部

### ISSUE THREAD

**Issue by jim422** [iuap-design/tinper-bee#229]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-tree@2.0.10-beta.1

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：mac

- 所使用的浏览器：

### 代码

代码位置
![image](https://user-images.githubusercontent.com/18412346/59988468-b68ff480-966d-11e9-8af2-c6cf62fea00a.png)
看着是图中红色区域引起的
## 当前的行为：效果（可截图说明）及动作描述
[视频](https://drive.google.com/file/d/1CmKES_FdwSip2LDxMSTCF42JCWlJJGN9/view)

**Comment by whizbz11** [comment]
升级最新版本2.0.15
