### ISSUE TITLE
moda拖拽的边界限制

### ISSUE THREAD

**Issue by Lucialiuxi** [iuap-design/tinper-bee#230]
## 环境及版本信息

- `tinper-bee` 版本号:  v1.6.3

- 若使用单个组件，请标明该组件版本号：v2.0.14

- 当前项目中`react`的版本号：v16.8.6

- 所使用的操作系统：Win 7

- 所使用的浏览器：chrome v75.0.3770.100（正式版本）

## 描述这个问题:
 modal拖拽Header移动位置，上移已经处理了不能拖拽出可视区，右移、下移超出可视区出现滚动条。问题是：往左边拖动到可视区边界既没有阻止，也不会出现横向滚动条，会导致modal往左侧拖出可视区，鼠标放开后modal丢失。

### 代码
用官网的倒数第三个demo可复现

### 报错信息
无

## 期望的行为:
希望可拖拽header上下左右移动，但不超出可视区

**Comment by lucian55** [comment]
bee-modal @2.0.18 已解决。 通过 bounds 设置可拖拽范围，可参考 [示例11](https://github.com/tinper-bee/bee-modal/blob/master/demo/demolist/Demo11.js)

|参数|说明|类型|默认值|
|:--|:----|:---|:----|
|bounds|设置拖拽范围,可输入{top:xxx,bottom:xxx,left:xxx,right:xxx}或者选择器(例如 "#app")|object/string|{top:-20}|
