### ISSUE TITLE
bee-table滚动后高度出现问题

### ISSUE THREAD

**Issue by bbqin** [iuap-design/tinper-bee#231]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号：2.0.8

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：win 10

- 所使用的浏览器：chrome

## 描述这个问题:
二层弹窗内的树状表，滚动之后表格高度计算出现问题，第一行变得特别高出现大面积空白。
我检查了源码，我们这边没有在滚动时对高度做过操作。

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/48541050/59997634-20b99100-9690-11e9-8d83-9539e3c74a6f.png)

## 期望的行为:

表格滚动后高度正常。

**Comment by yangchch6** [comment]
升级至最新版的 Table 后，是否还有同样问题出现？

**Comment by bbqin** [comment]
新版本目前测试已经不能重现了，非常感谢。
