### ISSUE TITLE
【需求】bee-tree 快捷键操作节点状态扩展

### ISSUE THREAD

**Issue by bbqin** [iuap-design/tinper-bee#232]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号：bee-tree: 2.0.10-beta.1

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：win 10

- 所使用的浏览器：chrome  ie11+  firefox

## 描述这个问题:
bee-tree 快捷键上下操作时状态只有selected一种，这样就不能看到上一次选中的项。
### 代码

![image](https://user-images.githubusercontent.com/48541050/60004827-e8ba4a00-969f-11e9-8445-efc8b62f99f4.png)
![image](https://user-images.githubusercontent.com/48541050/60004860-f7086600-969f-11e9-8b96-5e89846f9842.png)

## 期望的行为:

目前状态存在重叠，应该区分一下以下三种状态

选中状态（根据换肤的选中颜色）、

移动状态（悬停颜色）、

移动到选中状态时（如下图）：选中颜色+边框色1px dashed #B1B1B1

**Comment by yangchch6** [comment]
bee-tree@2.0.16-beta.0，增加了快捷键移动状态
