### ISSUE TITLE
bee-table 行出现错位

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#233]
## 环境及版本信息

- `tinper-bee` 版本号:  

bee-table 2.0.8
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
表格出现竖向滚动条，并且不出横向滚动条时，使用dragborder，拖动使列变宽，从而出现横向滚动条，导致固定列与非固定列错位
### 代码

![image](https://user-images.githubusercontent.com/19504234/60005925-08527200-96a2-11e9-8583-d5996ffb65f3.png)

**Comment by yangchch6** [comment]
最新版本的 table 已经解决了这个问题，建议升级后使用

**Comment by jonyshi** [comment]
1.请使用最新版本 bee-table@2.0.8-nc.4。
 基于2.0.8-nc.3 、2.0.8-nc.0 修改了补丁，解决了拖拽表格宽度不够，断裂的问题。
2. 如果是新版本的bee-table 请使用最新版本的，也修复了这个bug。

@max-well
