### ISSUE TITLE
表格拖动缩小列宽，断开问题

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#234]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

![image](https://user-images.githubusercontent.com/19504234/60006293-b3fbc200-96a2-11e9-9c45-3e55398179d3.png)

**Comment by yangchch6** [comment]
bee-table@2.1.4-alpha.4，已解决该问题。
