### ISSUE TITLE
YearPicker 多时区问题

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#235]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker@2.0.43

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：window 10

- 所使用的浏览器：chrome 75

## 描述这个问题:
yearpicker 年份传 2019 年 ，切换时区为UTC以西的时区之后，年份转为2018年

### 代码

![image](https://user-images.githubusercontent.com/16048628/60017370-8ae02080-9613-11e9-9278-4b75fc2ac208.png)
![image](https://user-images.githubusercontent.com/16048628/60017457-b2cf8400-9613-11e9-8512-abcce607018c.png)
![image](https://user-images.githubusercontent.com/16048628/60017396-93d0f200-9613-11e9-9a57-46054c47ed8f.png)
![image](https://user-images.githubusercontent.com/16048628/60017417-a1867780-9613-11e9-999c-1e776c1a5354.png)

## 期望的行为:

看下是moment.js  引用问题还是，内部处理问题，还是不支持多时区的选择

**Comment by lucian55** [comment]
问题是moment时区切换问题，可以参考  https://blog.csdn.net/littlebearGreat/article/details/80996346
