### ISSUE TITLE
RangePicker组件配合form使用报错

### ISSUE THREAD

**Issue by wjchmr** [iuap-design/tinper-bee#236]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
"bee-datepicker": "^2.0.44",

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
RangePicker组件配合form getFieldProps使用，面板内部清除icon,清除日期后组件报错
### 代码

![image](https://user-images.githubusercontent.com/18568858/60147610-afe5b680-9800-11e9-8c80-5cc24c94dcfb.png)
![image](https://user-images.githubusercontent.com/18568858/60147625-c55ae080-9800-11e9-89c1-96e87f5bd490.png)
![image](https://user-images.githubusercontent.com/18568858/60147725-2a163b00-9801-11e9-9f3d-280b74ba3595.png)

**Comment by lucian55** [comment]
bee-datepicker@2.0.46 解决此问题
