### ISSUE TITLE
【需求】bee-tree 禁用时也禁用了展开

### ISSUE THREAD

**Issue by bbqin** [iuap-design/tinper-bee#237]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号：bee-tree: 2.0.10-beta.1

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：win 10

- 所使用的浏览器：chrome ie11+ firefox

## 描述这个问题:
bee-tree 禁用时也禁用了展开
## 期望的行为:

bee-tree 禁用时可以控制不禁用展开。

**Comment by whizbz11** [comment]
bee-tree@2.0.14增加mustExpandable属性支持disabled的节点可以自定义展开收起，默认disabled的节点不可以展开收起
