### ISSUE TITLE
在Drawer里使用Dnd 数据集合拖拽列表排序的定位问题

### ISSUE THREAD

**Issue by Lucialiuxi** [iuap-design/tinper-bee#238]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
Drawer：v0.0.2
Dnd：v1.0.7

- 当前项目中`react`的版本号：v16.8.6

- 所使用的操作系统：win7 

- 所使用的浏览器：chrome v75.0.3770.100

## 描述这个问题:
在Drawer里使用Dnd ，数据集合拖拽列表排序；
拖拽元素，元素应该变为灰色跟随鼠标移动才对，但是定位有问题，元素在可视区之外；
只要把侧拉的宽度调整为100%，拖拽就是正常的；
侧拉是正常的话可以按住鼠标，往左拖动，鼠标拖动到大概屏幕中间的位置，拖拽元素会从右边出来。

## 期望的行为:
在Drawer里使用Dnd 数据集合拖拽列表排序,拖拽的元素跟随鼠标移动

**Comment by lucian55** [comment]
bee-drawer@0.0.5 已解决 增加dnd适配
