### ISSUE TITLE
dropdown组件计算overlay的宽度问题

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#239]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-dropdown@2.0.7

- 当前项目中`react`的版本号：react@16.8.6

- 所使用的操作系统：windows 10

- 所使用的浏览器：chrome 75

## 描述这个问题:
![image](https://user-images.githubusercontent.com/16048628/60321784-4906ff80-99b0-11e9-8747-88b2b049f377.png)
目前dropdown组件会 根据 热区的宽度计算 overlay 下拉层的最小宽度。

## 期望的行为:

现在不希望dropdown组件计算宽度，并给通过行内样式overlay 注入最小宽度，希望参数控制是否采用计算最小宽度的逻辑。

**Comment by lucian55** [comment]
为什么不要计算宽度？

**Comment by summerboys** [comment]
> 为什么不要计算宽度？

不希望下拉宽度和热区等宽  当鼠标移入多余的区域时导致不会收起
![image](https://user-images.githubusercontent.com/16048628/60326924-3a731500-99bd-11e9-8cc7-4baee49d0078.png)
![image](https://user-images.githubusercontent.com/16048628/60326967-51196c00-99bd-11e9-8fab-f2fb7a738124.png)
![image](https://user-images.githubusercontent.com/16048628/60326990-61c9e200-99bd-11e9-8381-0ebc0e9b62c8.png)

**Comment by lucian55** [comment]
这个属性已经存在。
设置 minOverlayWidthMatchTrigger={false}  就不会计算最小宽度
