### ISSUE TITLE
需求增加：bee-progress-bar 增加另一种进度条展现方式！

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#24]
### 需求报告
@wangbow 指定波波同学完成此需求，参考效果：

[nprogress 的源码](https://github.com/rstacruz/nprogress)
建议封装到`bee-progress-bar`里面，增加一个参数，以及对应的函数`start`和`end`类似：
```js
NProgress.start();
NProgress.done();
```

具体效果如下网址顶部：

[点我看效果，注意顶部加载进度](http://ricostacruz.com/nprogress/)

![image](https://user-images.githubusercontent.com/3817644/31366119-0e085dfc-ad35-11e7-8564-15c8ba699911.png)

**Comment by kvkens** [comment]
问题得到了转机。

> 我通过npm安装此插件自行调用解决了问题。

1. npm install --save nprogress
2. 引用 import NProgress from 'nprogress';
3. 样式 import 'nprogress/nprogress.css';
4. 调用

```js

componentDidMount() {
    NProgress.start();
    setTimeout(()=>{NProgress.done()},2000);
    this.init({
      search : this.state.search,
      pageSize : this.state.pageSize,
      pageNum : this.state.pageNum
    });
  }
```

**Comment by GuoYongfeng** [comment]
如果 bee-progress-bar 组件需要依赖 nprogress 才能实现，那应该作为组件本身的依赖，而不是在外部加载。

**Comment by HuYuee** [comment]
bee-progress-bar v1.0.4已支持
