### ISSUE TITLE
表格图标问题

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#240]
## 环境及版本信息
bee-table 2.1.4-alpha.3
- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 报错信息

tubiao图标上能不能不加 !important ,会覆盖我们的图标 

![image](https://user-images.githubusercontent.com/19504234/60380938-f7c64100-9a7f-11e9-99e8-957795763f09.png)

**Comment by yangchch6** [comment]
bee-table@2.1.4-alpha.4，去掉了图标样式上的 !important。
