### ISSUE TITLE
拖拽 Dnd 组件问题

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#241]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
往下拖动的时候，会盖住拖动的元素
### 报错信息

往下拖动的时候，会盖住拖动的元素
ncc环境 账号密码 ：lm 123456a

![image](https://user-images.githubusercontent.com/19504234/60407916-2dd60300-9bef-11e9-9558-c0fbcc51ca84.png)

**Comment by yangchch6** [comment]
这是哪个功能节点？

**Comment by max-well** [comment]
这个问题已经和刘绍振说过了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: yangchch6 <notifications@github.com>
发送时间: 2019年7月2日 14:03
收件人: iuap-design/tinper-bee <tinper-bee@noreply.github.com>
抄送: MaxWell <864577133@qq.com>, Author <author@noreply.github.com>
主题: 回复：[iuap-design/tinper-bee] 拖拽 Dnd 组件问题 (#241)




这是哪个功能节点？

**Comment by lucian55** [comment]
@max-well  bee-dnd基于react-beautiful-dnd组件，react-beautiful-dnd存在这个问题，
解决方案参考 https://github.com/atlassian/react-beautiful-dnd/issues/757

https://github.com/atlassian/react-beautiful-dnd/issues/1267

https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/patterns/using-a-portal.md
