### ISSUE TITLE
table拖拽改变列宽度 onDropBorder 回调中返回的width值不正确

### ISSUE THREAD

**Issue by HaoGeShuoHuaNiHaoHaoTing** [iuap-design/tinper-bee#242]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.0

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8.4

- 所使用的操作系统：window

- 所使用的浏览器：chrome

## 描述这个问题:
table拖拽改变列宽度，onDropBorder 回调中返回的width不正确，甚至有负数情况；
e.target是鼠标抬起时，所处的位置上的元素，不稳定；
### 代码

![image](https://user-images.githubusercontent.com/28486250/60409473-56adc680-9bf6-11e9-9e1a-3c2e755b1d2d.png)

## 当前的行为：效果（可截图说明）及动作描述

复现：这个宽度，与鼠标抬起的位置有关
![image](https://user-images.githubusercontent.com/28486250/60409692-48ac7580-9bf7-11e9-92ec-526d9f6f81de.png)
1 与 2 都是拖动单据日期，鼠标抬起位置不一样，返回宽度就不一样
![image](https://user-images.githubusercontent.com/28486250/60409702-4f3aed00-9bf7-11e9-80e8-ad7445f85ba1.png)

## 期望的行为:

我希望 onDropBorder 能返回 columns 名称，with 宽度，实现表格拖拽记忆的功能；
场景：我要记住每次宽度的改变，存在后台，下次再进来的时候，是用户改好的宽度；

**Comment by yangchch6** [comment]
bee-table@2.1.4-alpha.5，在能拖拽的指定区域内，能返回正确的宽度和表头信息。

![image](https://user-images.githubusercontent.com/33412781/60422339-66410580-9c1e-11e9-84df-a875393fc3da.png)
