### ISSUE TITLE
ucf-web

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#243]
## 环境及版本信息

- ucf-webapp

 
## 描述这个问题:
  目前ucf-web 里面的脚手架工具，把IP写死在启动文件中了，部分项目反馈需要把IP，端口都暴露出来，或者ip 是  '0.0.0.0'  都可以。
 
## 期望的行为:

端口都暴露出来，或者ip 是  '0.0.0.0'  都可以。

**Comment by jonyshi** [comment]
@kvkens

**Comment by kvkens** [comment]
已经支持!

https://www.yuque.com/ucf-web/book/zfy8x1#Jro00
