### ISSUE TITLE
RangePicker组件显示错误

### ISSUE THREAD

**Issue by wjchmr** [iuap-design/tinper-bee#244]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
bee-datepicker:2.0.46

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
RangePicker组件，在搜索面板中，选择起止日期正常显示，再次选择只选一个开始日期，显示为空，点击搜索面板中的搜索进行表单校验，会显示正常选择时的旧值

**Comment by yangchch6** [comment]
bee-datepicker@2.1.1 已解决这个问题，在只选择开始日期，并关闭日期面板的时候，不会清空输入框中的值。保证 UI 和真实数据一致。
