### ISSUE TITLE
树参照只有末级可选问题

### ISSUE THREAD

**Issue by taislung** [iuap-design/tinper-bee#245]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.0

- 若使用单个组件，请标明该组件版本号：

- ref-tree": "2.0.2",

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows

- 所使用的浏览器：Chrome

### 代码

目前树形参照，可以选择任意节点，但是我们需求有一个“只能选择末级功能”，期望大前端开发同事能给予帮助，增加此功能。
## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/12135071/60480489-4c560000-9cbc-11e9-94f7-5e21cb3b3eb8.png)

**Comment by XYooo** [comment]
treeNodeDisabledKey
ref-tree@2.1.1 
指定树参照根据数据中哪个字段来决定该节点是否可选。该字段值应为true或者false
