### ISSUE TITLE
FormControl通过ref拿到后，内部ref对象没有包含原始的input对象

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#25]
### Bug 报告
需求是通过点击一个按钮，另一处的FormControl自动获得焦点来获得输入，但是我通过获得ref真实DOM后，并没有在ref里拿到真实的input。
我通过查询得知，antd里是支持的。

[官网文档有说明这点](http://www.css88.com/react/docs/refs-and-the-dom.html)
[相关问题](https://segmentfault.com/q/1010000007931844/a-1020000007932902)
[演示](https://codepen.io/yesmeck/pen/LbKbGb?editors=001)

![image](https://user-images.githubusercontent.com/3817644/31375643-d5218b2a-ad67-11e7-9a83-3733a6105919.png)

- __Package version(s)__: (版本号)0.6.2

#### 描述这个问题:

```js
<FormControl
                ref={c => this.inputRef = c}
                disabled={this.state.disabled}
                onClick={this.handlerInputClick}
                onChange={this.handlerValue}
                value={this.state.text}
                placeholder="请输入业务联系名称" size="lg"/>
```

通过ref拿到真实的元素

```js
<Button onClick={this.handlerEdit} colors="success">编辑</Button>
```
通过点击编辑

```js
  handlerEdit = (e) => {
    this.setState({
      disabled : false,
      isEdit : false
    });
    console.log(this.inputRef.refs);//这里的refs为空对象，而antd的并不是空，而是this.inputRef.refs.input
  }
```

#### 当前的行为:
无法通过ref拿到真实的input无法设置focus.

#### 期望的行为:
能够通过ref拿到真实的input

this.inputRef.refs.input

**Comment by kvkens** [comment]
```js
<FormControl readonly value={this.state.signature} onChange={this.handlerF4} className="step-input-activate" placeholder=""/>
```
不支持`readyonly`

**Comment by jonyshi** [comment]
1、通过ref获取对象句柄已经修正。
2、如果设置文本框焦点事件 autoFocus 属性，可以直接设置 autoFocus 属性即可。
