### ISSUE TITLE
华新丽华项目：Grid的header最后一栏当有排序功能的时候，排序按钮被遮挡问题

### ISSUE THREAD

**Issue by hepingyang** [iuap-design/tinper-bee#250]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

 bee-complex-grid  2.0.20
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

chrome
## 描述这个问题:
 有竖向滚动条的时候，没有遮挡，在没有竖向滚动条的时候，会有遮挡
### 代码

![image](https://user-images.githubusercontent.com/44887629/60641608-21f07800-9e5f-11e9-9406-b6adc9edaf95.png)
![image](https://user-images.githubusercontent.com/44887629/60641653-49474500-9e5f-11e9-8e4c-8642f6e43330.png)
![image](https://user-images.githubusercontent.com/44887629/60641660-55330700-9e5f-11e9-8e39-6ab65696dfa0.png)

## 期望的行为:

客户期望展示出完整的按钮
![image](https://user-images.githubusercontent.com/44887629/60642076-29188580-9e61-11e9-8383-4c2fbae1bf71.png)

**Comment by yangchch6** [comment]
@hepingyang ，本地测试了下，在无竖向滚动条和无数据时，均未出现图标被遮挡的现象。
可以再确认下项目中是否有样式影响了。

![image](https://user-images.githubusercontent.com/33412781/60652733-52dea600-9e7b-11e9-9114-bbe4950550cf.png)

![image](https://user-images.githubusercontent.com/33412781/60652828-76a1ec00-9e7b-11e9-9ec8-98b1e2a6989e.png)

**Comment by yangchch6** [comment]
bee-complex-grid@2.0.21 已经解决了这个问题
