### ISSUE TITLE
ie浏览器，表头会出现滚动条

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#251]
## 环境及版本信息
bee-table 2.1.4
- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

jira 问题单号  IFNC-801，有环境可以复现

![0703002](https://user-images.githubusercontent.com/19504234/60668534-c7770c00-9e9e-11e9-940f-24873e4d0d8b.png)

**Comment by yangchch6** [comment]
ie兼容性问题。该现象是由于 ie 浏览器对于“overflow：auto”这个CSS样式的处理与其他浏览器不同。如果做特殊处理隐藏掉滚动条的话，当表头内容过多时，表头高度会有问题。
