### ISSUE TITLE
参照input需要点击触发事件，现在只支持输入触发

### ISSUE THREAD

**Issue by pengyp** [iuap-design/tinper-bee#255]
参照input需要点击触发事件，现在只支持输入触发

**Comment by pengyp** [comment]
![image](https://user-images.githubusercontent.com/28775795/60881182-bb60c500-a277-11e9-9f71-7848c1195ada.png)

**Comment by XYooo** [comment]
已解决
删除package-lock.json
npm cache clear --force
然后重新npm install 
新增参数selectorOpen
