### ISSUE TITLE
参照input点击下拉弹出每次需要点一下其他区域才消失弹出窗，我们要鼠标离开弹出窗区域就消失弹出窗

### ISSUE THREAD

**Issue by pengyp** [iuap-design/tinper-bee#256]
参照input点击下拉弹出每次需要点一下其他区域才消失弹出窗，我们要鼠标离开弹出窗区域就消失弹出窗

**Comment by pengyp** [comment]
![image](https://user-images.githubusercontent.com/28775795/60880915-31b0f780-a277-11e9-8509-7df3b9c2fb9f.png)

**Comment by XYooo** [comment]
已解决
删除package-lock.json
npm cache clear --force
然后重新npm install 


新增selectorOpen参数，true、false，来控制下拉的关闭或者展示
