### ISSUE TITLE
参照支持多选的：鼠标放到input值上面hover，显示的是refpk值，我们需要显示名称。

### ISSUE THREAD

**Issue by pengyp** [iuap-design/tinper-bee#257]
参照支持多选的：鼠标放到input值上面hover，显示的是refpk值，我们需要显示名称。
![image](https://user-images.githubusercontent.com/28775795/60881461-5ce81680-a278-11e9-9b64-a530a7dd0f99.png)

**Comment by XYooo** [comment]
已解决
删除package-lock.json
npm cache clear --force
然后重新npm install
