### ISSUE TITLE
tingper单独引入布局组件的问题

### ISSUE THREAD

**Issue by yctjb1** [iuap-design/tinper-bee#258]
## 描述这个问题:

cnpm install bee-page-layout --save并且在页面import PageLayout from 'bee-page-layout'
并使用时报错。
解决法子：打开./node_modules/_bee-page-layout@1.0.0@bee-page-layout/build/index.js将第7行的后面替换成了require('./PageLayout'),原本这里是小写的l而不是大写L

**Comment by yctjb1** [comment]
> ## 描述这个问题:
> cnpm install bee-page-layout --save并且在页面import PageLayout from 'bee-page-layout'
> 并使用时报错。
> 解决法子：打开./node_modules/_bee-page-layout@1.0.0@bee-page-layout/build/index.js将第7行的后面替换成了require('./PageLayout'),原本这里是小写的l而不是大写L
除此以外：





> ## 描述这个问题:
> cnpm install bee-page-layout --save并且在页面import PageLayout from 'bee-page-layout'
> 并使用时报错。
> 解决法子：打开./node_modules/_bee-page-layout@1.0.0@bee-page-layout/build/index.js将第7行的后面替换成了require('./PageLayout'),原本这里是小写的l而不是大写L

除此以外：
![image](https://user-images.githubusercontent.com/30720171/60946989-19e27d80-a322-11e9-8311-2674c61af61d.png)

**Comment by yctjb1** [comment]
> ## 描述这个问题:
> cnpm install bee-page-layout --save并且在页面import PageLayout from 'bee-page-layout'
> 并使用时报错。
> 解决法子：打开./node_modules/_bee-page-layout@1.0.0@bee-page-layout/build/index.js将第7行的后面替换成了require('./PageLayout'),原本这里是小写的l而不是大写L

除此以外：
![image](https://user-images.githubusercontent.com/30720171/60947022-31216b00-a322-11e9-93d6-29ac77668607.png)

**Comment by yangchch6** [comment]
- bee-page-layout@1.0.1
    - [Fixbug]入口文件中引用的 “Pagelayout” 的 l 改为大写。
