### ISSUE TITLE
modal需要提供一个上下左右居中的属性

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#259]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
bee-modal 2.0.19

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
modal需要提供一个上下左右居中的属性
自己写的样式，会导致拖动卡住
### 代码

![image](https://user-images.githubusercontent.com/19504234/61017544-28827080-a3c6-11e9-9bf8-8f04664fb39c.png)

**Comment by yangchch6** [comment]
- bee-modal@2.0.20
    - [Fixbug]解决点击模态框 Header 区域，产生错位的问题。
    - [Feature]提供 `centered` 属性，支持垂直居中展示 Modal。
