### ISSUE TITLE
参照组件选中的点的样式不统一问题（目前是3种）

### ISSUE THREAD

**Issue by hytcyjb** [iuap-design/tinper-bee#260]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
ref-multiple-table:"2.1.2" 
（使用的时其中的参照RefMultipleTableWithInput组件）

- 当前项目中`react`的版本号：
react 16.6.3

- 所使用的操作系统：
Mac 

- 所使用的浏览器：
google    版本：75.0.3770.100（正式版本64位）

### 代码
无

### 报错信息
（无错误，只是不同点击显示样式不统一，在当前的行为中有截图）

## 当前的行为：
现在是选中时有3种不同的显示样式，如下图
<p><img src="https://github.com/hytcyjb/111/blob/master/shotscreen/20190711143701.jpg?raw=true" width="600" height="300"></p>
<p><img src="https://github.com/hytcyjb/111/blob/master/shotscreen/20190711143712.png?raw=true" width="600" height="300"></p>
<p><img src="https://github.com/hytcyjb/111/blob/master/shotscreen/20190711143718.png?raw=true" width="600" height="300"></p>

## 期望的行为:
希望选中时的样式只有一个

## 备注：
如果有描述不清的，麻烦联系qq：1457521527

**Comment by yangchch6** [comment]
这三种状态是为了标识当前所在的焦点，因为要支持全键盘操作，交互是这边 UE 定的，这个问题会反馈给他们，看是否需要优化下。

**Comment by yurokn** [comment]
- bee-radio@2.0.16
     - [ Update ] 优化了点的样式不统一问题。
