### ISSUE TITLE
组件库官网 onDataNumSelect 没返回值问题

### ISSUE THREAD

**Issue by quanjj008** [iuap-design/tinper-bee#261]
官网文档如图

![image](https://user-images.githubusercontent.com/21117467/61098101-5b913680-a490-11e9-85cc-8ed28160f8f8.png)

组件库源码

![image](https://user-images.githubusercontent.com/21117467/61098134-7d8ab900-a490-11e9-9264-f06a8121e334.png)

@yangchch6 @GuoYongfeng

**Comment by quanjj008** [comment]
翻页组件

**Comment by yangchch6** [comment]
![image](https://user-images.githubusercontent.com/33412781/61168107-0aaa3c80-a57b-11e9-9603-2c9a04f4dad6.png)

![image](https://user-images.githubusercontent.com/33412781/61168115-36c5bd80-a57b-11e9-8a8a-2c0bde7f1fec.png)
