### ISSUE TITLE
bee-complex-grid  回调函数没有参数和返回值描述 freshData

### ISSUE THREAD

**Issue by quanjj008** [iuap-design/tinper-bee#262]
组件库官网

![image](https://user-images.githubusercontent.com/21117467/61098304-1b7e8380-a491-11e9-8b31-402edcb58ea4.png)
 
![image](https://user-images.githubusercontent.com/21117467/61098334-3d780600-a491-11e9-8eab-21d1f43d5137.png)

整个组件库都没有 freshData 的介绍，其他组件也都会，官网没有一一列出来，麻烦你们自查一下，不然使用的时候还需要去看组件源码，影响效率！！！！

**Comment by quanjj008** [comment]
@yangchch6   @GuoYongfeng

**Comment by yangchch6** [comment]
freshData 会返回对应的页码序号，使用方法如下：

```
freshData = (pageIndex) => {
        this.onPageSelect(pageIndex,0);
}
```
