### ISSUE TITLE
查询searchPanel组件，需要一个隐藏展开按钮的属性，没有更多条件的时候就不要显示展开按钮了

### ISSUE THREAD

**Issue by pengyp** [iuap-design/tinper-bee#265]
![image](https://user-images.githubusercontent.com/28775795/61278722-41848a80-a7e7-11e9-991d-d872bfdd2761.png)

**Comment by yurokn** [comment]
发了新包bee-search-panel@3.0.1,新增属性名isExpandedBtn={true或false}，该属性决定展开按钮是否显示。
