### ISSUE TITLE
日期组件问题

### ISSUE THREAD

**Issue by hepingyang** [iuap-design/tinper-bee#267]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

bee-datepicker  2.2.0
- 当前项目中`react`的版本号：

- 所使用的操作系统：

windows
- 所使用的浏览器：

chrome
## 描述这个问题:
在tinper上点开日期范围组件，手动输入开始日期，在手动输入结束日期，点击其他地方，再次点击日期组件，页面会崩，控制台报错。
### 代码

![image](https://user-images.githubusercontent.com/44887629/61513216-ff4d8a00-aa2e-11e9-80b8-03b4589ff310.png)
![image](https://user-images.githubusercontent.com/44887629/61513250-19876800-aa2f-11e9-8658-0ad4ffe94c6e.png)

**Comment by yangchch6** [comment]
发了新包 bee-datepicker@2.2.3-beta.3
