### ISSUE TITLE
点击dropdown，会触发 键盘的 ‘↓’ 事件

### ISSUE THREAD

**Issue by max-well** [iuap-design/tinper-bee#268]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

bee-menus 2.0.8
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

点击下图中的区域，可以触发 键盘的‘↓’事件

![image](https://user-images.githubusercontent.com/19504234/61612922-7898e700-ac92-11e9-8454-d4e9e3990069.png)

**Comment by yurokn** [comment]
发了bee-menus@2.0.9,周五再发tinper-bee，解决了触发下箭头的问题。全键盘切换焦点按Tab+下箭头。
