### ISSUE TITLE
Grid的title添加为html标签时，当hover才会显示title内容

### ISSUE THREAD

**Issue by YuyaoYan** [iuap-design/tinper-bee#269]
![image](https://user-images.githubusercontent.com/32066567/61758958-5a013000-adf9-11e9-87c6-25470cd67e42.png)
![image](https://user-images.githubusercontent.com/32066567/61758972-70a78700-adf9-11e9-83ae-11aeb5704c05.png)

**Comment by yangchch6** [comment]
- bee-complex-grid@2.0.23
    - [Fixbug]解决表头传入 Icon 图标，未正常显示的问题。
