### ISSUE TITLE
1，希望下拉参照RefCombobox 单选完后，下拉框收缩起,2，下拉参照的弹框需要跟随窗口定位

### ISSUE THREAD

**Issue by houjjb** [iuap-design/tinper-bee#272]
## 环境及版本信息

- `tinper-bee` 版本号:  

1.4.2
- 若使用单个组件，请标明该组件版本号：

 下拉参照"ref-combobox": "2.1.1",
- 当前项目中`react`的版本号：

"2.1.1"
- 所使用的操作系统：

win10
- 所使用的浏览器：

chorme
## 描述这个问题:
1，下拉参照选完数据（单选）后下拉框未自动关闭，2，
下拉参照下拉框在项目中的位置不在输入框的下面，有所偏移
## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/50894649/62114556-77e2ff00-b2e9-11e9-984f-0cfb09b7ce27.png)

## 期望的行为:

1，希望下拉参照单选完后自动关闭下拉框，
2，希望下拉框的位置跟随输入框固定

**Comment by XYooo** [comment]
删除nodeModule和package-lock.json然后重新装包
