### ISSUE TITLE
参照组件上的placeholder提示不能自定义问题

### ISSUE THREAD

**Issue by ggoop** [iuap-design/tinper-bee#274]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.*

- 若使用单个组件，请标明该组件版本号：
"ref-multiple-table": "2.0.4"

- 当前项目中`react`的版本号：
^16.8.6
- 所使用的操作系统：
mac |windows

- 所使用的浏览器：
chrome 75.0.3770.100

## 描述这个问题:
参照组件上的placeholder提示不能自定义问题.
### 代码

![image](https://user-images.githubusercontent.com/6006080/62336814-a38e0100-b504-11e9-9d93-68344a2bf122.png)

## 期望的行为:
希望，能支持自定义placeholder，在弹出的参照中，可以更明确提示用户用哪些字段搜索

**Comment by XYooo** [comment]
ref-multiple-table@2.0.9
searchPlaceholder
