### ISSUE TITLE
城市选择 AcCitySelect不能清空，不能设置disabled

### ISSUE THREAD

**Issue by ggoop** [iuap-design/tinper-bee#275]
## 环境及版本信息

- `tinper-bee` 版本号:  
"tinper-bee": "^2.0.10",

- 当前项目中`react`的版本号：
"react": "^16.8.6",
- 所使用的浏览器：
chrome 75.0.3770.100

## 描述这个问题:
AcCitySelect 组件，在选择具体值后，不能清空，在某些场景下，需要支持disabled状态，目前不支持。

![image](https://user-images.githubusercontent.com/6006080/62336978-3dee4480-b505-11e9-9995-1698d68f9116.png)

## 期望的行为:
1、期望能增加清除功能
2、支持 disabled 状态

**Comment by lwd777** [comment]
区域组件在form表单中,无法赋值, 设置value后报错.
![image](https://user-images.githubusercontent.com/14276812/62443079-7e132880-b78c-11e9-94e4-eba25c33aaa3.png)
![image](https://user-images.githubusercontent.com/14276812/62443117-9edb7e00-b78c-11e9-95b1-0f160c409bcd.png)

**Comment by GuoYongfeng** [comment]
@ggoop 问题已解决，请查看：http://bee.tinper.org/tinper-acs/ac-city-select

@lwd777 你这个是新问题，如果复现还未解决请新开一个 issue。
