### ISSUE TITLE
pap-refer

### ISSUE THREAD

**Issue by quanjj008** [iuap-design/tinper-bee#276]
## 环境及版本信息

- `pap-refer` 1.0.8  

1 参照disabled状态，现在tinper中api有但是在封装后的组件内无效。
2 需要参照清楚的按钮统一，目前参照的清楚按钮不是当鼠标经过时候显示，
3.参照的placeholder 无效
4.placeholder 是combox这个组件无效，disabed 无效

**Comment by XYooo** [comment]
问题1，4 删除node_module和package-lock文件重新装包就可以。pap-refer的版本依然是1.0.8
问题2可以在项目中使用css样式进行覆盖
问题3 树、表、树表、树穿梭均没有问题，有的话可以再联系我
