### ISSUE TITLE
表格行拖拽，触摸屏，当拖拽位置时switch时，报错

### ISSUE THREAD

**Issue by sunshine887** [iuap-design/tinper-bee#277]
## 环境及版本信息
触摸屏
- `tinper-bee` 版本号:  2.1.3

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：win7

- 所使用的浏览器：chrome最新

### 代码

表格行拖拽，触摸屏，当拖拽位置时switch时，报错

现在拖动位置在Switch这列时，会找不到 当前key，只能找到目标key，然后record就是空的，引起报错。

## 期望的行为:

1、行拖拽行为，可以设置鼠标在哪列时，可以执行行拖拽；
2、当鼠标位于表格中的bee-tinper的组件时，支持行拖拽；
3、现在的拖拽行为是，两行进行交换，是否可以支持排序拖动
例如：将e拖动到第二行
拖动前：
a
b
c
d
e
拖动后：
a
e
b
c
d

**Comment by yurokn** [comment]
- bee-table@2.1.13
    - [ Fixbug ] 解决了移动端switch所在行在拖拽问题，需升级switch到最新版本。
    - [ Update ] 优化了拖拽行的功能，把交换行，改成插入行。
