### ISSUE TITLE
bee-form-control的文档希望能增加详细的api文档

### ISSUE THREAD

**Issue by HuYuee** [iuap-design/tinper-bee#28]
bee-form-control的文档希望能增加详细的api文档。希望能增加原生input标签的api或者属性，比如value，autofocus。或者给出链接地址

**Comment by jonyshi** [comment]
已经增加过了，通过refs来获取对象句柄
<FormControl value={this.state.value} ref={(input) => { this.textInput = input; }} />	

onHander = () => {
        
        this.textInput.input.focus();
		// this.refs.test.input.focus();
	}
