### ISSUE TITLE
FormControl组件使用受控组件方式时不可输入

### ISSUE THREAD

**Issue by Hzy0913** [iuap-design/tinper-bee#280]
## 环境及版本信息

- `tinper-bee` 版本号: 2.1.4

- 当前项目中`react`的版本号：16.2.0

## 描述这个问题:
`FormControl`组件使用受控组件方式时，不能输入内容，文档demo中的受控方式亦可复现
<img width="481" alt="WX20190805-120731@2x" src="https://user-images.githubusercontent.com/22450881/62438391-bbba8600-b779-11e9-9061-e9e31bbaf5fe.png">

**Comment by yangchch6** [comment]
tinper-bee@2.1.5 已解决。
