### ISSUE TITLE
Grid表头的过滤面板被modal遮盖

### ISSUE THREAD

**Issue by quanjj008** [iuap-design/tinper-bee#286]
## 环境及版本信息

- `tinper-bee` 版本号:  

![image](https://user-images.githubusercontent.com/21117467/62590152-082ece80-b8fe-11e9-8275-11fc8b4bd6ad.png)
表格的表头筛选的弹出被遮住

**Comment by yangchch6** [comment]
发了新包 bee-complex-grid@2.0.24-beta.0 ， 解决了列过滤面板被模态框遮盖的问题。
