### ISSUE TITLE
Grid 组件 设置属性"showHeader:{false}", 在多选框后面出现空白padding

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#287]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.1.5
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

chrome   76.0.3809.87（正式版本） （64 位）
## 描述这个问题:

表格设置 showHeader:{false},同时设置 可以多选(默认); 在多选框后面出现空白padding;

### 代码

![image](https://user-images.githubusercontent.com/10356530/62601934-16441580-b925-11e9-9421-3ee50d0ba2e6.png)
代码:
 <Grid
            ref={el => (this.grid = el)}
            rowKey={(r, i) => i}  //生成行的key
            columns={this.mainColumn}
            showHeader={false}
            data={queryObj.list}
            showFilterMenu={false} //是否显示行过滤菜单
            filterable={filterable} //是否开启过滤数据功能
            getSelectedDataFunc={this.getSelectedDataFunc}
            dragborder={true}
            onFilterChange={_this.onFilterChange} // 触发过滤输入操作以及下拉条件的回调
            onFilterClear={_this.onFilterClear} //清除过滤条件的回调函数，回调参数为清空的字段
            afterRowFilter={_this.afterRowFilter} //控制栏位的显示/隐藏
            sort={sortObj} //排序属性设置
            rowClassName={(record, index, indent) => {
              return selectIndex === index ? "selected" : "";
            }}
            paginationObj={paginationObj}
   />

## 期望的行为:
正常显示表格,不需要多余的padding;

## 项目
金融

**Comment by yangchch6** [comment]
发了新包 bee-complex-grid@2.0.24
