### ISSUE TITLE
下拉参照组件在屏幕的最右侧时,点击展开后,由于参照较宽,显示不全,同时页面会出现横向滚动条,破坏页面布局

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#288]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.1.15
- 若使用单个组件，请标明该组件版本号：

- 所使用的操作系统：

- 所使用的浏览器：

chrome 版本 76.0.3809.87（正式版本） （64 位）

## 描述这个问题:

下拉参照组件在屏幕的最右侧时,点击展开后,由于参照较宽,显示不全,同时页面会出现横向滚动条,破坏页面布局
![image](https://user-images.githubusercontent.com/10356530/62603862-66bd7200-b929-11e9-9c7e-008aa47e51c8.png)

### 代码

                              <RefWalsinCombo
                                    placeholder='投资人'
                                    url='/imfbp-fms-web/common-ref/blobRefTreeGrid'
                                    params={{
                                        refCode: 'financeorg',
                                        clientParam: JSON.stringify({ enable_state: "1" })
                                    }}
                                    {...getFieldProps('pkFinorg', {
                                        initialValue: JSON.stringify({
                                            refname: orderRow.pkFinorgName || '',
                                            refpk: orderRow.pkFinorg || ''
                                        }),
                                        rules: [{
                                            required: true,
                                            message: '请选择投资人'
                                        }]
                                    })}
                                    onClickItem={(record) => {
                                        console.log(12, record)
                                    }}
                                />

## 期望的行为:

增加一个属性,使参照下拉框可以右对齐. 内容还是按之前的显示

**Comment by liangyongming** [comment]
更正: "tinper-bee"版本:"2.1.5",

**Comment by XYooo** [comment]
删除nodeModule和package-lock的文件 npm install
