### ISSUE TITLE
下拉参照  下拉弹出框展开时出现抖动.

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#289]
## 环境及版本信息

- `tinper-bee` 版本号:  

    "tinper-bee": "2.1.5",

- 若使用单个组件，请标明该组件版本号：

 "pap-refer": "^1.0.8",
- 所使用的操作系统：

window
- 所使用的浏览器：

chrome 版本 76.0.3809.87（正式版本） （64 位）

## 描述这个问题:
描述: 点击下拉参照的按钮, 展开下拉框. 但是随后 数据被过滤,导致下拉框变窄,整体感觉,弹出框会出现抖动; 

![image](https://user-images.githubusercontent.com/10356530/62604486-c5372000-b92a-11e9-9d67-28f664b414bd.png)

![image](https://user-images.githubusercontent.com/10356530/62604507-cd8f5b00-b92a-11e9-95c2-dcb4e79d291c.png)

## 期望的行为:
参照下拉框正常展开,不出现抖动现象;

**Comment by XYooo** [comment]
找到class
.ref-slider-slider-down

将它的动画去掉就可以了  animation: slider-down 0.2s infinite; 改成animation:none;或者改写动画slider-down
