### ISSUE TITLE
参照 RefComboBox, 下拉选择值, 然后点击后面的删除Icon, 文本框的值被删除,但是实际选择的值仍然存在.

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#290]
## 环境及版本信息

- 若使用单个组件，请标明该组件版本号：
  "name": "pap-refer",
  "version": "1.0.8",
  RefComboBox 组件;

- 所使用的操作系统：
  Windows

- 所使用的浏览器：

chrome  版本 76.0.3809.100（正式版本） （64 位）
## 描述这个问题:

参照 RefComboBox, 下拉选择值, 然后点击后面的删除Icon, 文本框被清空,但是实际选择的值仍然存在.

## 当前的行为：效果（可截图说明）及动作描述
1.点击展开参照;
2.点击选中下拉框中的某一个值.
3.参照收起.
4.点击 删除的Icon,文本框被清空.
5.点击查询,发现 参照的值任然存在

## 期望的行为:

1.点击删除图标,既可以删除文本框的内容,又删除选中项.

**Comment by XYooo** [comment]
删除nodeModule和package-lock的文件 npm install
