### ISSUE TITLE
AcCitySelect组件的区域显示不对

### ISSUE THREAD

**Issue by limingk** [iuap-design/tinper-bee#291]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
    "ac-city-select": "0.0.1",

- 当前项目中`react`的版本号：

- 所使用的操作系统：
windows

- 所使用的浏览器：
chrome
### 报错信息
http://bee.tinper.org/tinper-acs/ac-city-select
例子上就能看出来有问题，点按钮应该改成长治县，但实际改成了小店区
btnOnClick=()=>{
		this.setState({
			value:{ province:'山西',city:'长治',area:'长治县'}
		})
	}

我这里也是每个省保存后始终显示第一个区，比如北京一直东城区

**Comment by yangchch6** [comment]
发了新包 ac-city-select@0.0.4，解决了赋值 value ，取值不正确的问题。
