### ISSUE TITLE
页面参照选择值后在弹出Alert提示后导致页面无法滑动

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#292]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10",

- 若使用单个组件，请标明该组件版本号：

"ref-multiple-table": "2.0.4",

- 当前项目中`react`的版本号：

"react": "^16.8.6",
- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
选参照后再弹出一个alert后关闭窗口就不能滚动页面了，  好像body 中加了一个style="overflow:hidden" ，在窗口关闭时没有取消掉， 参照弹出 时body中出现 style overflow:hidden   选完值后 overflow:hidden 消失了，在代码中自动将 alert弹出后 没有出现 overflow:hidden   等alert关闭后 又加上了，导致页面不能滚动
### 报错信息

步骤1参照选择
![image](https://user-images.githubusercontent.com/14276812/62686147-b7e76780-b9f6-11e9-9675-21babe0d4443.png)
步骤2，根据上述步骤选择的值判断后给出一个提示
![image](https://user-images.githubusercontent.com/14276812/62686177-c2a1fc80-b9f6-11e9-80bc-6e189f120075.png)
步骤3，上述提示不管是确定还是取消关闭alert后 页面增加了  style="overflow:hidden" 
![image](https://user-images.githubusercontent.com/14276812/62686220-d8afbd00-b9f6-11e9-8b3c-f7498112605f.png)

## 当前的行为：效果（可截图说明）及动作描述

如上
## 期望的行为:

希望连续弹出对话窗口后，仍旧可以滚动页面 不应该有style="overflow:hidden" 的控制

**Comment by XYooo** [comment]
<RefMultipleTableWithInput
          {...childrenProps}
          modalProps={
           {
            onExited:this.onExited,
           }
          }
 />
在使用表参照的时候，传入modalProps，使用 onExited方法（具体含义参考https://design.yonyoucloud.com/tinper-bee/bee-modal），在onExited方法中打开你的Alert信息提示框。
在第一个modal关闭之后再去打开第二个
