### ISSUE TITLE
AcCitySelect控件不能设置默认值或者全部

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#293]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10"
- 若使用单个组件，请标明该组件版本号：

"ac-city-select": "0.0.3",
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
区域控件作为条件筛选项时 希望可以有个全部或者 空值默认值
### 代码

![image](https://user-images.githubusercontent.com/14276812/62749188-14e22c80-ba8e-11e9-9615-34b63f02ac1f.png)

## 期望的行为:

希望可以有个全部选项 或者 空值 默认值

**Comment by yangchch6** [comment]
设置 defaultValue = { province:'', city:'', area:'' }
