### ISSUE TITLE
AcCitySelect控件在form表单中使用无法赋值

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#294]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10"
- 若使用单个组件，请标明该组件版本号：

"ac-city-select": "0.0.3"
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
AcCitySelect控件在form表单中使用时后台加载数据后无法赋值到控件中， 当设置value时，出现maxiNum错误

### 代码

![image](https://user-images.githubusercontent.com/14276812/62752425-131e6600-ba9a-11e9-8d56-b7c93e5122bb.png)

### 报错信息

![image](https://user-images.githubusercontent.com/14276812/62752434-1c0f3780-ba9a-11e9-902e-3ce3db5d7cd9.png)

## 期望的行为:

AcCitySelect控件在form表单中使用时，从后台加载数据后能正常赋值到控件中

**Comment by yangchch6** [comment]
发了新包 ac-city-select@0.0.4
