### ISSUE TITLE
AcCitySelect区域控件空值的时候，可以不显示叉号清除按钮

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#296]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10"
- 若使用单个组件，请标明该组件版本号：

"ac-city-select": "0.0.4"
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

### 代码

![image](https://user-images.githubusercontent.com/14276812/62851285-322a2b80-bd18-11e9-9f81-a31f98a23bbd.png)

## 期望的行为:

区域控件空值的时候，可以不显示叉号清除按钮, 可以直接选择下拉选择

**Comment by yangchch6** [comment]
发了新版本 ac-city-select@0.0.5
