### ISSUE TITLE
[紧急]AcCitySelect控件放在表单中时，下拉菜单无法显示非省会的area信息和表单中赋值问题

### ISSUE THREAD

**Issue by WuJi33** [iuap-design/tinper-bee#297]
## 环境及版本信息

- `tinper-bee` 版本号:  
  tinper-bee": "~2.0.10

- 若使用单个组件，请标明该组件版本号：
 "ac-city-select": "0.0.4"

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码
外层还有FormItem包裹
   ```
<AcCitySelect
    ref="city"
    value={defaultRegion}
    allowClear={true}
    {...getFieldProps("region", {                   
         initialValue: defaultRegion,
    })}
 />

```
### 报错信息
1、当选择非省会城市，如四川，眉山市，area下拉菜单中数据还是成都市的信息
![image](https://user-images.githubusercontent.com/15901319/62987128-f35bb900-be70-11e9-8773-a43167d2c5b9.png)
2、AcCitySelect控件表单中赋值逻辑和其他控件不一致，必须在getFieldProps外部赋值value，且需要在getFieldProps里赋值initialValue才能不报错。
`

## 期望的行为:
1、控件正常显示非省会area区域信息就好
2、统一AcCitySelect表单赋值逻辑，如果能像其他控件支持如下这种最简单形式最好
  ```
<AcCitySelect
       {...getFieldProps(“region”, {  })}
   />
```

**Comment by yangchch6** [comment]
发了新版本 ac-city-select@0.0.5
