### ISSUE TITLE
grid表格需要在浮动列扩展行功能

### ISSUE THREAD

**Issue by pengyp** [iuap-design/tinper-bee#298]
expandIconColumnIndex  ， expandIcon的索引，当expandIconAsCell为false时，将插入哪个列。
grid表格浮动列没有data-line-index属性，在浮动列上就不能用expandedRowRender扩展行

## 项目
营销云-友服务

**Comment by pengyp** [comment]
![image](https://user-images.githubusercontent.com/28775795/62989630-5baf9800-be7b-11e9-83de-2aa27ca28339.png)

**Comment by pengyp** [comment]
![image](https://user-images.githubusercontent.com/28775795/62989746-ec867380-be7b-11e9-8800-89eb5e6590ab.png)

**Comment by pengyp** [comment]
<Grid
            ref={el => (this.grid = el)}
            data={supplementOrderItems}
            rowKey={(r, i) => (r.id ? r.id : r.key)}
            columns={this.detailColumn}
            paginationObj={{
              verticalPosition: "none"
            }}
            columnFilterAble={rowEditStatus}
            showHeaderMenu={rowEditStatus}
            dragborder={rowEditStatus}
            draggable={rowEditStatus}
            syncHover={rowEditStatus}
            multiSelect={!rowEditStatus}
            getSelectedDataFunc={this.getSelectedDataFunc}
            expandedRowRender={this.expandedRowRender}
            expandIconColumnIndex={14}
            bodyDisplayInRow={true}
            expandedIcon={<a href="javascript:">查看补件进度</a>}
            collapsedIcon={<a href="javascript:">查看补件进度</a>}
            onRowClick={this.onRowClick}
            emptyText={() => (
              <Icon
                style={{
                  fontSize: "60px"
                }}
                type="uf-nodata"
              />
            )}
            loading={{
              show: false
            }}
          />

**Comment by pengyp** [comment]
detailColumn = [
    {
      title: "补件编码",
      dataIndex: "supplementCode",
      key: "supplementCode",
      width: 200
    },
    {
      title: "补件名称",
      dataIndex: "supplementName",
      key: "supplementName",
      width: 120
    },
    {
      title: "商品编码",
      dataIndex: "goodsCode",
      key: "goodsCode",
      width: 120
    },
    {
      title: "商品名称",
      dataIndex: "goodsName",
      key: "goodsName",
      width: 120
    },
    {
      title: "数量",
      dataIndex: "supplementNum",
      key: "supplementNum",
      width: 120
    },
    {
      title: "单位",
      dataIndex: "supplementUnitName",
      key: "supplementUnitName",
      width: 120
    },
    {
      title: "建议价",
      dataIndex: "advicePrice",
      key: "advicePrice",
      width: 120,
      textAlign: "right",
      render: (text, record, index) => {
        return <span>{toDecimal2(record.advicePrice)}</span>;
      }
    },
    {
      title: "销售价",
      dataIndex: "salePrice",
      key: "salePrice",
      textAlign: "right",
      width: 120,
      render: (text, record, index) => {
        return <span>{toDecimal2(record.salePrice)}</span>;
      }
    },
    {
      title: "补件金额",
      dataIndex: "amount",
      key: "amount",
      width: 120,
      textAlign: "right",
      render: (text, record, index) => {
        return <span>{toDecimal2(record.amount)}</span>;
      }
    },
    {
      title: "补件描述",
      dataIndex: "supplementDesc",
      key: "supplementDesc",
      width: 120
    },
    {
      title: "顾客",
      dataIndex: "buyer",
      key: "buyer",
      width: 120
    },
    {
      title: "顾客联系电话",
      dataIndex: "buyerPhone",
      key: "buyerPhone",
      width: 120
    },
    {
      title: "已发货数量",
      dataIndex: "totalDeliveryNum",
      key: "totalDeliveryNum",
      width: 120,
      render: (text, record, index) => {
        return <span>{record.totalDeliveryNum || 0}</span>;
      }
    },
    {
      title: "已出库数量",
      dataIndex: "totalOutNum",
      key: "totalOutNum",
      width: 120,
      render: (text, record, index) => {
        return <span>{record.totalOutNum || 0}</span>;
      }
    },
    {
      title: "操作",
      dataIndex: "operation",
      key: "operation",
      width: 200,
      render(text, record, index) {}
    }
  ];

**Comment by pengyp** [comment]
{
title: "操作",
dataIndex: "operation",
key: "operation",
width: 200,
fixed:"right",
render(text, record, index) {}
}
//fixed:"right",这样浮动列就没办法使用扩展行功能

**Comment by yurokn** [comment]
- bee-table@2.2.1
    - [ Fixbug ] 解决了右侧固定列无法使用扩展功能的问题
