### ISSUE TITLE
查询模版，查询数据后点击清空按钮，删除icon没有及时删除。

### ISSUE THREAD

**Issue by YuyaoYan** [iuap-design/tinper-bee#299]
## 环境及版本信息

- 所使用的操作系统：
Mac 10.14

- 所使用的浏览器：
谷歌 76.0.3809.100

## 描述这个问题:
1. 在搜索面板，点击或输入搜索条件
2. 点击查询按钮
3. 点击清空按钮
期望结果： 搜索模版所有搜索内容及清除icon消失
实际结果： 搜索模版搜索内容消失，但清除icon没有消失

截图如下：
![image](https://user-images.githubusercontent.com/32066567/63000250-48182780-bea3-11e9-90b8-51b92489695b.png)

## 项目
金融

**Comment by yurokn** [comment]
- bee-form-control@2.0.7
    - [ Fixbug ]解决了清空value后删除按钮仍然可见的问题。
    - [ Update ] 有value时光标移出后，删除按钮自动隐藏。
