### ISSUE TITLE
bee.tinper.org上面中说明现在最新版本是多少？

### ISSUE THREAD

**Issue by HuYuee** [iuap-design/tinper-bee#30]
bee.tinper.org上面中说明现在最新版本是多少？
并且说明下，如果只引入单个组件，样式得单独自己引入。以及讲解如何引入

**Comment by kvkens** [comment]
版本说明确实没有直观显示出来，我一般都是`npm info tinper-bee`的方式去查看，或者直接去npm官方去查询如：[npm](https://www.npmjs.com/package/tinper-bee)，但是readme里面的版本没有更新及时。

**Comment by BoyuZhou** [comment]
已增加
