### ISSUE TITLE
搜索面板中，点击清除按钮时，级联组件Cascader的值不会被清除。

### ISSUE THREAD

**Issue by YuyaoYan** [iuap-design/tinper-bee#300]
## 环境及版本信息

- `tinper-bee` 版本号:  
bee-cascader 2.1.4

- 所使用的操作系统：
Mac 

- 所使用的浏览器：
Google Chrome 76.0.3809.100

## 描述这个问题:
复现步骤：
1. 搜索模板选择级联组件内容后
2. 点击清楚按钮

期望结果：级联组件内容清空
实际结果：级联组件内容没有被清空

截图如下：
![image](https://user-images.githubusercontent.com/32066567/63017157-2a10ee00-bec8-11e9-93cb-ac2b0e2507e7.png)

### 代码
代码如下：
```
<FormItem>
   <Cascader 
     onChange={this.onChangeArea} 
     changeOnSelect={true} 
     defaultValue={defaultAreaOptions}
     options={areaArr} 
     {...getFieldProps('area')} 
     placeholder="地区分类"/>
</FormItem>
```

tips：下拉参照等组件是通过设置getFieldProps的第二个参数值initialValue值来实现清除功能的，例如下拉参照：
```
<RefWalsinCombo
        placeholder='授信机构(投资方)'
        url='/imfbp-fms-web/fms-ref/getRefPageData'
        params={{
             refCode: 'cooporg',
             clientParam: JSON.stringify({ containsDisable: false })
        }}
        {...getFieldProps('pkOrgCredit', {
              initialValue: JSON.stringify({refname:'',refpk:''})
        })}
/>
```

## 期望的行为:
期望能够实现点击清除按钮清除级联组件内容的效果。

## 领域
金融

**Comment by yurokn** [comment]
- bee-cascader@2.1.5
    - [ Fixbug ] 解决了点击清除按钮时，被包裹在form中的级联组件Cascader的值不会被清除。 #300
