### ISSUE TITLE
表单控件渲染报错。 Objects are not valid as a React child。(found: object with keys {name, })

### ISSUE THREAD

**Issue by WuJi33** [iuap-design/tinper-bee#301]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
表单中有两个ForItem控件，
第一个 getFieldProps("person",{}) 所在控件是参照控件
第二个getFieldProps("person.name",{})所在控件是普通FormControl文本
这样会报错 Objects are not valid as a React child。(found: object with keys {name, })

## 期望的行为:
因为现在已经支持了 a.b.c这种getFieldProps语法，但是又不支持层级重叠的情况，很造成疑惑，希望可以支持解决。

**Comment by yurokn** [comment]
可否把代码粘一下，我和同事没有看明白。
