### ISSUE TITLE
树节点父级节点不可选的时候不能收起

### ISSUE THREAD

**Issue by Sunfloweres** [iuap-design/tinper-bee#302]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 项目
主数据

**Comment by yangchch6** [comment]
可以检查下项目中是否设置了 mustExpandable 属性，设置为 true 的话，disabled的节点可以自定义展开收起。默认disabled的节点不可以展开收起。
