### ISSUE TITLE
bee-datepicker 面板事件会冒泡到外层div上

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#303]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
bee-datepicker 打开日期选择面板 click mouseover 都会 冒泡到 外层div上 。

## 期望的行为:

不要冒泡的外层div

## 项目
NCC

**Comment by yurokn** [comment]
- bee-datepicker@2.2.6
    - [ Fixbug ] 解决了click和mouseover冒泡问题

**Comment by yangchch6** [comment]
bee-datepicker 作为底层基础组件，不应该也不能阻止事件冒泡，外层可以通过判断事件对象来过滤。此问题已经纠正，若升级组件，请自行适配。
