### ISSUE TITLE
tab 页签点击时 onTabClick 事件不生效， 不被触发； 

### ISSUE THREAD

**Issue by yangpengq** [iuap-design/tinper-bee#305]
## 环境及版本信息

- `tinper-bee` 版本号:  V2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 项目
中兴

**Comment by yangchch6** [comment]
发了 bee-tabs@2.1.1，解决onTabClick事件无效的问题。
