### ISSUE TITLE
树形参照需要参数控制是否显示快捷搜索框

### ISSUE THREAD

**Issue by limingk** [iuap-design/tinper-bee#306]
## 环境及版本信息

- `tinper-bee` 版本号:  
    "tinper-bee": "~2.0.10",

- 若使用单个组件，请标明该组件版本号：
  "ref-tree": "2.1.1"

- 当前项目中`react`的版本号：

- 所使用的操作系统：
windows

- 所使用的浏览器：
chrome

## 当前的行为：效果（可截图说明）及动作描述
需要一个参数控制树形参照是否显示快捷录入的搜索框，因为有些场景不需要使用快捷搜索。如果用样式控制的话，又会影响其他树形和表参照

## 期望的行为:
提供一个参数，能单独控制某个树形参照是否显示快捷搜索框

**Comment by XYooo** [comment]
删除node_module和package-lock.json重新安装包就可以，ref-tree本身不用升级，不展示快捷搜索下拉面板传  dropdownDisabled=true就可以
