### ISSUE TITLE
ref-multiple-table升级到2.1.3版本后placeholder设置失效

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#307]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10",

- 若使用单个组件，请标明该组件版本号：

"ref-multiple-table": "2.1.3"
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
参照升级到2.1.3版本后placeholder设置后不起作用
### 报错信息

![image](https://user-images.githubusercontent.com/14276812/63139378-b5959680-c010-11e9-949d-058305ee7f5e.png)

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/14276812/63139382-b9c1b400-c010-11e9-9dcd-f4e5b4417a3c.png)

## 期望的行为:

文本框的 placeholder 可以显示

**Comment by XYooo** [comment]
经确认，初始值设置成[{}]，这种使用表示初始值是有值的，placeholder不展示
