### ISSUE TITLE
Select启用allowClear后清除问题

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#308]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10"
- 若使用单个组件，请标明该组件版本号：

select
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

### 代码

![image](https://user-images.githubusercontent.com/14276812/63141820-c1d22180-c019-11e9-9d54-b970c6c0a55f.png)

### 报错信息

Select组件使用AllowClear=true后关闭按钮 有两个 , 而且需要点击两次才能清空组件的显示值

## 期望的行为:

希望只点击清除一次清空组件数据

## 项目
制造

**Comment by a982027400** [comment]
场景没有复现，请详细说明

**Comment by yangchch6** [comment]
tinper-bee@2.1.2 已经解决这个问题
1、可以升级下 tinper-bee 版本。
2、也可以单独升级 bee-select，然后单独引入。
