### ISSUE TITLE
table组件复选框与内容行样式错行

### ISSUE THREAD

**Issue by likegs9** [iuap-design/tinper-bee#309]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的浏览器：

## 描述这个问题:
当内容行高度变化时，改行对应的复选框高度没有与行内容同步，造成样式错位
### 代码

```
import { Checkbox, FormControl, Table } from "tinper-bee";
import multiSelect from "tinper-bee/lib/multiSelect.js";
let MultiSelectTable = multiSelect(Table, Checkbox);

 <MultiSelectTable
               data={data.content ? data.content : []}
               columns={this.column}
               //paginationObj={paginationObj}
               ref={el => (this.grid = el)}
               emptyText={() => <Icon style={{ fontSize: "60px" }} type="uf-nodata" />}
               getSelectedDataFunc={this.getSelectedDataFunc.bind(this)}
               loading={listLoading}
               scroll={{ y: 550 }}
            />

```

![image](https://user-images.githubusercontent.com/10152771/63147003-67dc5680-c02f-11e9-9091-90f83a3149be.png)

![image](https://user-images.githubusercontent.com/10152771/63147028-7e82ad80-c02f-11e9-8de5-5e2d697891cd.png)

**Comment by yangchch6** [comment]
请问 “内容行高度变化”，指的是通过 css 改变了行高 line-height，还是单元格内容过多超出一行？
1、如果设置了 css 的行高，请改为如下方式：
```
         <Table
          columns={columns}
          data={data}
          height={40} //自定义表格行高
          headerHeight={40} //自定义表头行高
        />
```
可参考官网示例： [自定义行高](http://bee.tinper.org/tinper-bee/bee-table#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%8C%E9%AB%98)
有对应的 API 文档：[api 说明](http://bee.tinper.org/tinper-bee/bee-table#Table%20props)

2、如果是单元格内容过多，请确认项目中 bee-table 组件的版本号：
v2.2.3 之后的版本效果：  
![image](https://user-images.githubusercontent.com/33412781/63908540-116d1000-ca52-11e9-9a43-38a040b08468.png)

v2.2.3 之前的版本效果：
![image](https://user-images.githubusercontent.com/33412781/63908571-39f50a00-ca52-11e9-992c-d53b5e37b75e.png)
