### ISSUE TITLE
每个组件展示新增版本更新说明、链接到github图标

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper-bee#31]
### Bug 报告

- __Package version(s)__: (版本号) 不是BUG，是 Feature

#### 描述这个问题:

 当前 bee.tinper.org 只展示组件描述、示例和API，没法看到每个组件各个阶段的进展以及直接链接到github查看源码。

#### 当前的行为:

 同上。

#### 期望的行为:

 每个组件展示新增版本更新说明、链接到github图标

**Comment by BoyuZhou** [comment]
我觉得bee.tinper.org应该强化的是，整体组件库的概念，不应该强调单个组件。版本更新说明，应该只说明tinper-bee这个包更新了哪些内容

**Comment by kvkens** [comment]
是应该有这么个链接.

**Comment by jonyshi** [comment]
后续会补充历史版本功能

**Comment by GuoYongfeng** [comment]
![image](https://user-images.githubusercontent.com/8686869/34548106-eea14a42-f13a-11e7-947a-f1e325934c4b.png)
