### ISSUE TITLE
 ref-multiple-table 点开参照搜索区后,滚动页面,搜索区内容未固定

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#310]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10",
- 若使用单个组件，请标明该组件版本号：

"ref-multiple-table": "2.1.3"
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
 点开参照搜索区后,滚动页面,搜索区内容未固定
### 代码

![image](https://user-images.githubusercontent.com/14276812/63164812-33cb5a80-c05c-11e9-8f52-13722fd863f1.png)

## 期望的行为:

希望参照自带搜索区固定在参照控件下方

**Comment by XYooo** [comment]
经确认，body的样式影响。body起点应是文档流，出现上述问题是body起点是可视区域，导致下拉搜索跟着滚动而变化。
下拉面板禁用参数：dropdownDisabled，为true表示禁用不展示下拉
