### ISSUE TITLE
grid组件封装 headerHeight={30} 无效

### ISSUE THREAD

**Issue by ranyanchuan** [iuap-design/tinper-bee#311]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by wjchmr** [comment]
表格默认行高为40px(文字行高16px;加上上下padding各12px),无法小于40

**Comment by yurokn** [comment]
headerHeight的设置的确是生效了，w3c规范中tr的height的高度并不代表tr的实际高度，而是tr的最小高度，内部th的高度会把外部tr的实际高度撑开，请按如下进行的css覆盖实现效果。
.u-table td, .u-table th {
    padding: 0;  此处根据实际希望的padding自行设置
}
