### ISSUE TITLE
ref-tree@2.0.12的RefTreeWithInput里的defaultExpandAll设置展开会自动关闭

### ISSUE THREAD

**Issue by johnlin0207** [iuap-design/tinper-bee#312]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.1.0

- 若使用单个组件，请标明该组件版本号：
 "ref-tree": "^2.0.12",

- 当前项目中`react`的版本号：
 "react": "16.6.3",

- 所使用的操作系统：
 Windows

- 所使用的浏览器：
 Chrome 75.0.3770.100（正式版本） （64 位）

## 描述这个问题:
树形参照RefTreeWithInput 的defaultExpandAll属性设置为true后，点开第一个参照树形是展开的没问题，点开第二个就会自动折叠，再点一次第二个才会展开是什么问题？

### 代码
`<RefTreeWithInput
                    {...refTreeValData}
                    {...refModelData}
                    {...optionalProps}
                    matchData={matchData ? matchData : thisMatchData}
                    onSave={_props.onSave || this.reftreeOnSave.bind(null, _props.refName, _props.fieldName)}
                    canClickGoOn={this.reftreeCanClickGoOn.bind(null, _props.refName, _props.fieldName)}
                    onCancel={this.reftreeOnCancel}
                    getRefTreeData={this.getRefTreeData}
                    filterUrlFunc={this.reftreeFilterUrlFunc}
                    disabled={disabled}
                    {...getFieldProps(_props.fieldName, formProps)}
                    treeNodeDisabledKey={_props.treeNodeDisabledKey}
                    defaultExpandAll={true}
                />`

**Comment by johnlin0207** [comment]
![demo](https://user-images.githubusercontent.com/21291240/63234824-89288700-c269-11e9-85eb-f22cd3e4c000.gif)

**Comment by XYooo** [comment]
defaultExpandAll设置为true，但是没有自动展开的那个树参照，有没有设置懒加载

**Comment by johnlin0207** [comment]
> defaultExpandAll设置为true，但是没有自动展开的那个树参照，有没有设置懒加载

没有设置过lazyModal

**Comment by johnlin0207** [comment]
> defaultExpandAll设置为true，但是没有自动展开的那个树参照，有没有设置懒加载

也没有设置过onLoadData

**Comment by johnlin0207** [comment]
调用组件用法有问题；关闭组件时（若有对RefTreeWithInput包装过）需要清除组件的treeData数据，否则对组件会有影响。
