### ISSUE TITLE
需求：树选择 TreeSelect  多选的时候支持搜索

### ISSUE THREAD

**Issue by sunshine887** [iuap-design/tinper-bee#315]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.5

- 若使用单个组件，请标明该组件版本号：无

- 当前项目中`react`的版本号：最新

- 所使用的操作系统：windows10

- 所使用的浏览器：chrome较新版本

## 描述这个问题:
树选择的下拉选项一般都比较多，要定位到具体的分类操作上有难度 
希望增加输入关键字过滤：高亮显示并展开
 

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/16029689/63251497-72515700-c2a0-11e9-8b94-607f3e699ec7.png)

## 期望的行为:

多选，支持搜索，高亮显示并展开

![image](https://user-images.githubusercontent.com/16029689/63251914-5601ea00-c2a1-11e9-883b-84c7248f0f4c.png)

**Comment by yurokn** [comment]
- bee-tree-select@0.0.6
    - [ Feature ]新增了树选择 TreeSelect 多选的时候支持搜索 #315
