### ISSUE TITLE
触摸屏：table的行拖拽，行的数据有switch，如果拖拽点在switch上时，报错

### ISSUE THREAD

**Issue by sunshine887** [iuap-design/tinper-bee#316]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.5

- 若使用单个组件，请标明该组件版本号：无

- 当前项目中`react`的版本号：较新

- 所使用的操作系统：windows

- 所使用的浏览器：较新

## 描述这个问题:
触摸屏：table的行拖拽，行的数据有switch，如果拖拽点在switch上时，报错

### 代码

![image](https://user-images.githubusercontent.com/16029689/63252433-5a7ad280-c2a2-11e9-8523-1d398f34ce0e.png)

### 报错信息

![image](https://user-images.githubusercontent.com/16029689/63252255-14be0a00-c2a2-11e9-981a-888ba98465e7.png)
![image](https://user-images.githubusercontent.com/16029689/63252288-27d0da00-c2a2-11e9-8942-f83d2763b400.png)
## 期望的行为:

希望触摸屏，不报错，能正常运行

**Comment by yangchch6** [comment]
本周发布正式版 tinper-bee
