### ISSUE TITLE
radio 在Form中使用初始值不管用  也无法操作选中其他值

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#317]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

在Form里使用
                <Radio.RadioGroup
                                {
                                ...getFieldProps('vnote', {
                                    initialValue: '1',
                                }
                                ) }
                            >
                                <Radio value="2">是</Radio>
                                <Radio value="1">否</Radio>
                            </Radio.RadioGroup>

### 报错信息

页面上没有否没有被选中  也不能选中是选项

**Comment by a982027400** [comment]
/**
 * @title 不同颜色的radio
 * @description `colors`参数控制背景色
 */

import React, { Component } from 'react'
import Radio from 'bee-radio'
import Form from 'bee-form';
const FormItem = Form.FormItem;


class Demo2 extends Component{
  constructor(props) {
  	super(props);
  	this.state = {
    	selectedValue: '3'
    };
  }
  handleChange = (value) => {
    this.setState({selectedValue: value});
  }

  onSubmit = () => {
		this.props.form.validateFields((err, _values) => {
			console.log(_values);
		});
  }

	onRest = () => {
		this.props.form.resetFields();
		this.props.form.validateFields((err, _values) => {
			console.log(_values);
		});
	}
  render() {
    let { selectedValue } = this.state;
    let { form: { getFieldProps } } = this.props;

    return (
      <FormItem>
        <Radio.RadioGroup
          name="color"
          {...getFieldProps('vnote', { initialValue: selectedValue, })}
          selectedValue={selectedValue}
          onChange={this.handleChange}
        >
            <Radio colors="primary" value="1" >苹果</Radio>
            <Radio colors="success" value="2" >香蕉</Radio>
            <Radio colors="info" value="3" >葡萄</Radio>
            <Radio colors="warning" value="4" >菠萝</Radio>
            <Radio colors="danger" value="5" >梨</Radio>
            <Radio colors="dark" value="6" >石榴</Radio>
        </Radio.RadioGroup>
        <button onClick={this.onSubmit}>提交</button>
        <button onClick={this.onRest}>清空</button>
      </FormItem>
    )
  }
};

export default Form.createForm()(Demo2);



你按这种写法试一下，我这边没问题

**Comment by yurokn** [comment]
- bee-radio@2.0.15
    - [ Fixbug ]解决了当bee-form包裹时，选中项不能显示的问题。
