### ISSUE TITLE
tinper-bee: "^2.1.6",  版本没有提供bee-page-layout的引用

### ISSUE THREAD

**Issue by Dio-Zhu** [iuap-design/tinper-bee#318]
![image](https://user-images.githubusercontent.com/20452648/63491268-58ef1b80-c4e9-11e9-9e3d-4b5d2b6f8221.png)

**Comment by yangchch6** [comment]
发布了 tinper-bee@2.2.0 版本，添加了 bee-page-layout 组件，升级后可直接这样使用：
```
import { PageLayout } from 'tinper-bee';
```
