### ISSUE TITLE
colorPicker白色回显的时候变成none了

### ISSUE THREAD

**Issue by chern1992** [iuap-design/tinper-bee#319]
colorPicker白色回显的时候值变成none了，选中的颜色是红色，能否支持下白色

**Comment by yurokn** [comment]
可否描述下具体操作过程，上面的描述我与同事没大看明白。

**Comment by chern1992** [comment]
背景是白色/空白时，打开选择颜色的界面后，点击【取消】后，变为none，返回值就变成了none

**Comment by yurokn** [comment]
- bee-colorpicker@0.0.13
     - [ Fixbug ]解决了colorPicker白色回显的时候变成none了 #319
