### ISSUE TITLE
组件库按需自动加载的需求

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#32]
### Bug 报告

- __Package version(s)__: (版本号) 0.6.2

#### 描述这个问题:
其他兄弟部门询问是否增加类似babel-import按需自动加载的引用资源方式，以及CSS等。

#### 当前的行为:
不支持

#### 期望的行为:
类似antd的babel-import支持方式，不少同事不是很清楚引用的方式，目前官网只有单独一个组件的方式去引用。

[按需加载](https://ant.design/docs/react/introduce-cn#按需加载)

**Comment by 791045873** [comment]
请问一下，目前我使用其中一个组件的时候，应当怎么引入的所对应的样式

**Comment by BoyuZhou** [comment]
@791045873  

样式引入
```
可以使用link引入build目录下Dropdown.css
<link rel="stylesheet" href="./node_modules/bee-dropdown/build/Dropdown.css">
可以在js中import样式
import "./node_modules/bee-dropdown/src/Dropdown.scss"
//或是
import "./node_modules/bee-dropdown/build/Dropdown.css"
```

**Comment by BoyuZhou** [comment]
@kvkens 
目前我们的组织方式，不支持按需引入样式

**Comment by kvkens** [comment]
@BoyuZhou import方式直接`import 'bee-dropdown/build/Dropdown.css'`不就OK吗.

**Comment by BoyuZhou** [comment]
@kvkens  你说ant的实现是他们是antd整个库的按需加载，自动添加按需加载的样式，我们本身是分库的，在使用整个tinper-bee时，并不能按照antd的按需加载来。如果对于一个一个单个引入组件的，是可以做这样的事情。这个就不算是按需加载，只是做一个插件，帮助开发者省事。

**Comment by BoyuZhou** [comment]
已支持，http://bee.tinper.org/notice
