### ISSUE TITLE
ColorPicker组件的几个问题

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#320]
## 环境及版本信息

- `tinper-bee` 版本号:  V2.1.6

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

1）目前只支持深颜色的调整，颜色选取不全。
2）取色板界面，右侧一些参数的说明只有程序员&设计才能看懂，希望能改进。（测试提出来的问题）
3）感觉弹出来取色不是太好，最好做成悬浮卡片形式的。还有如果要弹出模态的形式，能不能支持调整位置。

![image](https://user-images.githubusercontent.com/25068905/63577295-aab6a500-c5c0-11e9-8f46-7dcbb5f8af0f.png)

**Comment by yurokn** [comment]
- bee-colorpicker@0.0.12
    - [ Feature ]新增了自定义传给modal子组件属性的功能
    - [ Feature ]新增了自定义是否隐藏右侧参数区域的功能
