### ISSUE TITLE
bee-menus mode= horizontal 子菜单渲染bug

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#321]
bee-menus mode= horizontal 子菜单渲染bug
tinper版本 2.1.6
当menu存在子菜单的时候，子菜单的下拉选项宽度第一次渲染和第二次渲染不一样
可查看官网demo 第一个demo进行复现

**Comment by yurokn** [comment]
- bee-menus@2.0.10
    - [ Fixbug ] mode= horizontal 子菜单渲染bug #321
