### ISSUE TITLE
上传 Upload  组件，希望能更改上传文件的名称，随机生成一个，保证上传的资源的名称不重复

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#322]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by yurokn** [comment]
建议前端上传原始文件名，后端接收到原始文件名加时间戳。因为如果在前端修改文件名再上传的话，后端将无法获得原始文件名。
