### ISSUE TITLE
AcMultiTabs的删除Tab页时，未触发onChange事件

### ISSUE THREAD

**Issue by JohnnieCai** [iuap-design/tinper-bee#323]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.0

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码
在使用页面http://bee.tinper.org/tinper-acs/ac-multi-tabs中的示例代码时，增加Tab页正常，但是删除Tab页后，再增加页面则会将删除的页面全部展示，通过跟踪发现无法触发onChange事件。
![image](https://user-images.githubusercontent.com/41809235/63753408-9850aa00-c8e5-11e9-878a-17d357ef110c.png)

无法通过跟踪触发debugger

**Comment by yangchch6** [comment]
升级到 ac-multi-tabs@1.0.1，再试一下
