### ISSUE TITLE
上传组件缩略图增加遮罩，遮罩上面增加删除按钮及放大按钮

### ISSUE THREAD

**Issue by quanjj008** [iuap-design/tinper-bee#326]
## 环境及版本信息

![image](https://user-images.githubusercontent.com/21117467/64103860-ad29b380-cda5-11e9-80a6-22630f49fa9e.png)
![image](https://user-images.githubusercontent.com/21117467/64103906-c7639180-cda5-11e9-87cb-cd811b9d3b69.png)
![image](https://user-images.githubusercontent.com/21117467/64103971-de09e880-cda5-11e9-981c-52166c5f4c39.png)

效果如上图

**Comment by yangchch6** [comment]
- bee-upload@2.0.1
    - [Feature]`listType` API 新增 `picture-card` 类型，支持图片预览及删除功能。
