### ISSUE TITLE
参照问题

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#328]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.11

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
Windows

- 所使用的浏览器：
谷歌：76.0.3809.132（正式版本） （64 位）

## 描述这个问题:
带分页的表参照组件，如果页数过多，在参照弹出框里输入页码跳转后，弹框的样式会被改变

### 代码

![image](https://user-images.githubusercontent.com/53893374/64151162-59c66c80-ce5c-11e9-8622-6612d2956935.png)

**Comment by XYooo** [comment]
请问使用的参照版本是什么？

**Comment by XYooo** [comment]
请使用paginationProps，对象格式，具体参数可以参考bee-pagination
http://bee.tinper.org/tinper-acs/ref-multiple-table
例如：paginationProps={maxButtons:3, first:false,last:false,prev:false, next:false,  showJump=false}
或者使用size='xlg'//模态框宽度增大
