### ISSUE TITLE
需求：checkbox.group加入option接口

### ISSUE THREAD

**Issue by HuaYJ1996** [iuap-design/tinper-bee#329]
在Checkbox.Group中，加入option接口，类型为数组，可直接通过数组渲染一组checkbox。

**Comment by yangchch6** [comment]
- bee-checkbox@2.0.7
    - [Feature]CheckboxGroup 新增 `defaultValue` API，用于设置默认选中的选项。
    - [Feature]CheckboxGroup 新增 `options` API，支持通过传入数组，生成可选项 Checkbox。
