### ISSUE TITLE
关于是否应该支持24栅格的讨论

### ISSUE THREAD

**Issue by BoyuZhou** [iuap-design/tinper-bee#33]
有热心用户反映，希望增加24栅格支持。
我们在这里进行一下是否有必要让栅格布局支持24栅格。

**Comment by lyx9439** [comment]
比如我现在要写一个表单界面，每行显示两个label，label里span和input的长度比为1:3，这样栅格的比例就是1:3:1:3，就是8列布局。如果是12列栅格的话，就要额外套一层col.xs=6，里面再写col.span.xs=3和col.input.xs=9

**Comment by kvkens** [comment]
12栅格里面的一个栅格再继续分12栅格呢?😆

@lyx9439

**Comment by BoyuZhou** [comment]
暂时不支持24栅格
