### ISSUE TITLE
项目级参照多选树参照，单选时，展示有逗号

### ISSUE THREAD

**Issue by yangpengq** [iuap-design/tinper-bee#330]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题: 项目级多选树参照 ，选择之后展示的时候前面多了个分号
![image](https://user-images.githubusercontent.com/53589387/64167160-3828ad80-ce7b-11e9-97e9-2c42f7be9a6a.png)

**Comment by XYooo** [comment]
初始值value设置的不对，初始值value可能出现{refname:'',refpk:'不为空'}

**Comment by wlLeblanc** [comment]
@yangpengq 请问下你这个问题解决了没有？

**Comment by wlLeblanc** [comment]
@XYooo 请问下这个初始值要怎么设置？

**Comment by wlLeblanc** [comment]
@XYooo 大佬请问这个分号的问题怎么解决？

**Comment by yangchch6** [comment]
> @XYooo 大佬请问这个分号的问题怎么解决？

可参考下这个 issue 的回答：https://github.com/iuap-design/tinper-bee/issues/408

**Comment by yangchch6** [comment]
> @XYooo 大佬请问这个分号的问题怎么解决？

可参考下这个 issue 的回答：https://github.com/iuap-design/tinper-bee/issues/408
