### ISSUE TITLE
表格单元格的固定 fixed 和 扩展字表格需要单独设置扩展内容的高度，建议可以自动撑开

### ISSUE THREAD

**Issue by eagleLiying** [iuap-design/tinper-bee#333]
![image](https://user-images.githubusercontent.com/39879019/64319064-169c0300-cfee-11e9-8f4a-24f77da2ebc8.png)

**Comment by yangchch6** [comment]
- bee-table@2.2.11
    - [Update]嵌套表格，扩展行支持高度自适应。
