### ISSUE TITLE
多选表格，  某一行禁用多选，通过RowClick还是可以操作多选框

### ISSUE THREAD

**Issue by ShileiLiu** [iuap-design/tinper-bee#334]
## 环境及版本信息

- `tinper-bee` 版本号:  
v2.2.9

- 当前项目中`react`的版本号：
v16.8.6

- 所使用的操作系统：
Windows

- 所使用的浏览器：
chrome

## 描述这个问题:
多选表格，  某一行禁用多选，通过RowClick还是可以操作多选框
### 代码
无

### 报错信息
无

## 期望的行为:
多选表格，  某一行禁用多选，通过RowClick不能操作多选框

**Comment by yangchch6** [comment]
- bee-table@2.2.11
    - [Fixbug]解决多选表格，某一行禁用多选，通过行点击仍然可以操作多选框的问题。
