### ISSUE TITLE
grid列宽会突然自动收起来

### ISSUE THREAD

**Issue by houjjb** [iuap-design/tinper-bee#335]
## 环境及版本信息

- `tinper-bee` 版本号:  

1.4.2
- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "2.0.13",
- 当前项目中`react`的版本号：

 "react": "16.3.2",
- 所使用的操作系统：

win10
- 所使用的浏览器：

chrome
## 描述这个问题:
grid不知为何列会自动收起来
### 代码

![image](https://user-images.githubusercontent.com/50894649/64421687-c481dd00-d0d4-11e9-8ad0-16e2e7456d64.png)
![image](https://user-images.githubusercontent.com/50894649/64421707-c9df2780-d0d4-11e9-84f9-2fb2aa7dba26.png)

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/50894649/64421722-cd72ae80-d0d4-11e9-8886-915cded810c0.png)

## 期望的行为:

列宽按正常设置的来

**Comment by yangchch6** [comment]
需要提供能复现该问题的充分必要条件。
