### ISSUE TITLE
Upload 组件提供前端禁止点击删除已上传文件功能

### ISSUE THREAD

**Issue by anxLiang** [iuap-design/tinper-bee#336]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
Upload 2.0.0 

- 当前项目中`react`的版本号：
16.9.0

- 所使用的操作系统：
window

- 所使用的浏览器：
chrome 75

## 描述这个问题:
Upload 组件目前没有提供提供前端禁止点击删除已上传文件功能，交互上认为已上传文件列表始终可以点击删除。

## 期望的行为:
Upload 组件提供提供前端禁止点击删除已上传文件功能，提供明确的禁止交互行为。

**Comment by yangchch6** [comment]
- bee-upload@2.0.1
    - [Feature]新增 `disabled` API，用于禁止上传、删除已上传列表行为。
