### ISSUE TITLE
<Tree> 组件使用的时候页面显示节点名称是key问题

### ISSUE THREAD

**Issue by OwenCXP** [iuap-design/tinper-bee#339]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.1.3
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

16.8.2
- 所使用的操作系统：

windows
- 所使用的浏览器：

76.0
## 描述这个问题:
<Tree> 组件使用的时候页面显示节点名称是key问题

**Comment by yangchch6** [comment]
若问题仍然存在，请补全 Tree 组件相关使用代码，重新打开该 issue，方便我们定位复现问题。目前提供的信息不完整，先关闭了。
