### ISSUE TITLE
progressBar 组件缺陷明显，建议重构

### ISSUE THREAD

**Issue by anxLiang** [iuap-design/tinper-bee#341]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
bee-progressBar@2.0.1

## 描述这个问题:
组件功能缺陷明显，进度条表现类型过少，UI样式差强人意。

## 期望的行为:
实现多种进度条样式，线型、环形、仪表盘等，行为样式也进一步美化。

**Comment by yangchch6** [comment]
- bee-progress@0.0.1
    - [Feature]新增 Progress 进度条组件。
