### ISSUE TITLE
DatePicker 兼容服务端渲染

### ISSUE THREAD

**Issue by anxLiang** [iuap-design/tinper-bee#343]
## 环境及版本信息

- `tinper-bee` 版本号:  
bee-datepicker@2.2.7

## 描述这个问题: 
1、RangePicker 与 WeekPicker 存在使用 window.location 情况

2、rangepicker   renderFooter的效果不太对

## 期望的行为:
兼容服务端渲染

**Comment by yangchch6** [comment]
bee-datepicker@3.0.0-mdf.1
