### ISSUE TITLE
pagination 特殊按钮建议添加相应类名方便精准定位修改

### ISSUE THREAD

**Issue by anxLiang** [iuap-design/tinper-bee#344]
## 环境及版本信息

- `tinper-bee` 版本号:  bee-pagination

## 描述这个问题:
分页组件中的特殊按钮没有给予指定类名，当需要针对性进行样式修改时不方便，甚至产生干扰。

## 期望的行为:
建议对分页按钮给予类名方便区分。

**Comment by yangchch6** [comment]
- bee-pagination@2.0.10
    - [Feature]分页条中的特殊按钮添加类名标识。
