### ISSUE TITLE
参照弹窗取消按钮左侧 加复选框

### ISSUE THREAD

**Issue by ssboll** [iuap-design/tinper-bee#345]
## 环境及版本信息

- `tinper-bee` 版本号:  2.1.0

- 若使用单个组件，请标明该组件版本号：

 ref-tree@2.0.12
 ref-multiple-table@2.1.2
 ref-tree-table@2.1.0
- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：

- 所使用的浏览器： chrome  76.0.3809.132

## 描述这个问题:
参照作为查询条件时，需要加两个复选框：是否支持停用（列表和树形参照）   是否包含下级数据（树形参照
### 代码

应可支持不定量的复选框，复选框选中或取消选中事件应可调用

![image](https://user-images.githubusercontent.com/30584512/64760501-6dfd1e80-d56c-11e9-8224-57f0d6d26b1d.png)

**Comment by XYooo** [comment]
ref-multiple-table@2.1.4
ref-tree@2.1.3
使用参数  footerBtnDom，传入dom结构。例如
footerBtnDom={
            <div className="customed-footer">
                <Checkbox colors="primary" onChange={this.checkboxChange}>停用</Checkbox>
                <Checkbox colors="primary" onChange={this.checkboxChange}>包含下级</Checkbox>
            </div>}

**Comment by XYooo** [comment]
"footerBtnDom={
            <div className="customed-footer">
                <Checkbox colors="primary" onChange={this.checkboxChange}>停用</Checkbox>
                <Checkbox colors="primary" onChange={this.checkboxChange}>包含下级</Checkbox>
            </div>}"

**Comment by XYooo** [comment]
'footerBtnDom={ <div className="customed-footer"><Checkbox colors="primary" onChange={this.checkboxChange}>停用</Checkbox><Checkbox colors="primary" onChange{this.checkboxChange}>包含下级</Checkbox></div>}'

**Comment by XYooo** [comment]
`footerBtnDom={
            <div className="customed-footer">
                <Checkbox colors="primary" onChange={this.checkboxChange}>停用</Checkbox>
                <Checkbox colors="primary" onChange={this.checkboxChange}>包含下级</Checkbox>
            </div>}`
