### ISSUE TITLE
制造部门，CN需要彩色图标

### ISSUE THREAD

**Issue by liuchaoty** [iuap-design/tinper-bee#348]
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
制造中台项目中UE设计的是彩色图标，而CN中没有彩色图标只有灰色图片

## 期望的行为:

希望CN中可以选择彩色图标，项目急需，或者提供一个自定义彩色图标的方案，
不要让我自己查！！！！

**Comment by yangchch6** [comment]
方案1：使用 svg 实现，少量图标时，此方法最快。
方案2：项目中维护一套定制化的字体图标，需要自己阅读一下文档！在此给你个链接：https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391&helptype=code

如果部分图标具有通用性，可以融入到 Icon 组件中，这个需要设计把关，可以联系 刘文杰
