### ISSUE TITLE
TreeSelect组件 树节点需要提供API hover显示 tips

### ISSUE THREAD

**Issue by siriuscandy** [iuap-design/tinper-bee#349]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 代码

![screenshot_v1568871960439](https://user-images.githubusercontent.com/10221072/65218727-a90dcd80-dae9-11e9-9cff-f7c850706d4c.png)
目前tips显示和title一样 需要提供API 显示不同字段
## 项目
基础建模

**Comment by yangchch6** [comment]
在传入的数据中自定义 title 字段：

```
const treeData = [{
  title: <span title="root 1">parent 1</span>,
  value: '0-0',
  key: '0-0',
  children: [{
    title: 'Child Node1',
    value: '0-0-1',
    key: '0-0-1',
  }, {
    title: 'Child Node2',
    value: '0-0-2',
    key: '0-0-2',
  }],
}, {
  title: 'Node2',
  value: '0-1',
  key: '0-1',
}];
```
