### ISSUE TITLE
一些小问题和需求

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#35]
### 本地环境
   V-0.6.2
   chorme 58+
   win10

### Bug 报告 :
1、DatePicker 日期时间插件，怎样选取日期以后获取时分秒时间？
2、Tooltip 文字提示插件，默认的opacity为0，默认不显示，需要用户自定义opacity覆盖。
![animation](https://user-images.githubusercontent.com/17383237/32209516-882de6be-be43-11e7-8aa2-4c63c6fe060b.gif)

#### 需求问题 :
1、 table控件，需要单独加一列获得“序号”属性，且“序号”字段用户可自定义叫法。
2、textarea输入框需要添加，且其高度可选随文本变化，或固定，如有可能添加个“剩余字数提示”

**Comment by BoyuZhou** [comment]
1.第一个问题，已经解决。通过传递showTime参数
2.tooltip想要修改默认样式，只能传入className(优先级要高于他本身)或是使用style
3.table序号需求，可以自己定义一个列表示序号
4.textarea暂时没有这个组件，你可以自己封装，后续我们会进行安排开发
