### ISSUE TITLE
表单模态框报React does not recognize the “X” prop on a DOM element警告

### ISSUE THREAD

**Issue by jerrychane** [iuap-design/tinper-bee#350]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "latest"
- 若使用单个组件，请标明该组件版本号：

表单模态框 Modal v2.1.1
- 当前项目中`react`的版本号：

"react": "16.6.3"
- 所使用的操作系统：

Win10
- 所使用的浏览器：

Google Chrome 版本 78.0.3887.7（正式版本） （64 位）
## 描述这个问题:
提示警告：Warning: React does not recognize the `clearCenteredCls` prop on a DOM element.
### 代码

![image](https://user-images.githubusercontent.com/20819267/65226958-63a5cc00-dafa-11e9-94c7-a3176a707bad.png)
### 报错信息

![image](https://user-images.githubusercontent.com/20819267/65226877-3eb15900-dafa-11e9-87cc-4c18b54039ea.png)
## 当前的行为：效果（可截图说明）及动作描述

点击模态窗
## 期望的行为:

修复该错误

## 项目
主数据

**Comment by yangchch6** [comment]
- bee-modal@2.1.2
    - [Fixbug]解决 warning。

**Comment by jerrychane** [comment]
已解决。
