### ISSUE TITLE
grid组件设置标题行高时出现死循环

### ISSUE THREAD

**Issue by wanghobby** [iuap-design/tinper-bee#351]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

    "bee-complex-grid": "2.0.25",
- 当前项目中`react`的版本号：

    "react": "16.3.2",

- 所使用的操作系统：

Mac

- 所使用的浏览器：

Chrome
## 描述这个问题:
我这边是有两级标题，当我设置标题行高时，出现死循环。

### 代码

只是设置标题行高，才出现问题

![image](https://user-images.githubusercontent.com/26377237/65240795-ad9bab80-db14-11e9-94e5-588a22c48291.png)

### 报错信息

![image](https://user-images.githubusercontent.com/26377237/65240858-d15ef180-db14-11e9-84a6-1d92c098007e.png)

**Comment by yangchch6** [comment]
1、headerHeight 应该是 number 类型，应该设置 headerHeight = {40} 这样。官网API文档有说明字段类型：

![image](https://user-images.githubusercontent.com/33412781/65665816-f6041d80-e06e-11e9-8f98-19cbf5ebed74.png)

2、grid 不支持设置小于 40 的高度，原因和解决方法参考：

https://github.com/iuap-design/tinper-bee/issues/311
