### ISSUE TITLE
gird编辑态，输入框获取焦点会触发getSelectedDataFunc ()

### ISSUE THREAD

**Issue by ranyanchuan** [iuap-design/tinper-bee#353]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by yangchch6** [comment]
方案1：阻止输入框的点击/聚焦事件冒泡
方案2：给表格设置 autoCheckedByClickRows={false}
