### ISSUE TITLE
树节点展开鼠标移开后会自动收起来

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#354]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

2.1.3及以上

- 当前项目中`react`的版本号：

因为是团队协作，各人版本有差异，但是都存在这个问题

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
树节点展开鼠标移开后会自动收起来
### 1、代码
代码如下：
<RefTreeBaseUI
searchable={true}
title={this.props.title}
backdrop={true}
showModal={showModal}
multiple={false}
showLoading={showLoading}
lazyModal={true}
treeData={this.state.treeData||[]}
valueField={"classNo"}
onLoadData={this.onLoadData}
onSave={this.onSave}
onCancel={this.onCancel}
defaultExpandAll={true}
getRefTreeData={this.getRefTreeData}
nodeDisplay={(record) => {
return record.className
}}
/>

**Comment by yangchch6** [comment]
- bee-tree@2.1.8
    - [Fixbug]树节点展开鼠标移开后会自动收起来。
