### ISSUE TITLE
期望grid或table的columns列在自定义设置显示某列的基础上，还能支持在浏览器不关闭的状态下，保留自定义列显示效果，直到关闭浏览器才失效

### ISSUE THREAD

**Issue by houjjb** [iuap-design/tinper-bee#355]
## 环境及版本信息

- `tinper-bee` 版本号:  

1.4.2
- 若使用单个组件，请标明该组件版本号：

 "bee-complex-grid": "2.0.25",
- 当前项目中`react`的版本号：

 "react": "16.3.2",
- 所使用的操作系统：

WIN10,WIN7
- 所使用的浏览器：

chrome
## 当前的行为：效果（可截图说明）及动作描述

当前只支持在当前页设置显示某列，页面一跳转就失效了
## 期望的行为:

期望grid或table的columns列在自定义设置显示某列的基础上，还能支持在浏览器不关闭的状态下，保留自定义列显示效果，直到关闭浏览器才失效

**Comment by yangchch6** [comment]
解决方案：
建议自己封一个业务组件，引入grid，参数原样带过去，然后加一个自定义的key作为唯一标识符，在需要的时候将key和columns（value）存进local storage。之后在页面中引入grid就从你需要定义的组件里面引入。

这样实现的话，业务中不需要修改 40 多个节点中的组件，只需修改 grid 引入方式即可。并且可以自定义 grid 的唯一标识，对于 localStorge 的控制也更灵活。
