### ISSUE TITLE
电脑设置屏幕显示百分比为 125%后，Grid td错位

### ISSUE THREAD

**Issue by lilicoder** [iuap-design/tinper-bee#356]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.13

- 若使用单个组件，请标明该组件版本号：
bee-complex-grid@2.0.16

- 当前项目中`react`的版本号：
react@16.9.0

- 所使用的操作系统：
Windows

- 所使用的浏览器：
Google Chrome 
版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
离散制造与U9开发部 IOT项目组

### 1、代码
import Grid from "bee-complex-grid";
import 'bee-complex-grid/build/Grid.css';

  <Grid data={data}
                      columns={this.columns}
                      bordered
                      paginationObj={paginationObj}
                      columnFilterAble={false}
                      showHeaderMenu={false}
                      noBorder={false}
                      gap={true}
                      ref="grid"
                />
![image](https://user-images.githubusercontent.com/24731304/65669282-da504580-e075-11e9-8ec7-7582c0d90e44.png)
![image](https://user-images.githubusercontent.com/24731304/65669309-e63c0780-e075-11e9-84b5-dc677c2c98c8.png)

### 2、报错信息
无

## 当前的行为：效果（可截图说明）及动作描述
1、didmount获取数据(data)
2、表格宽度错位
![image](https://user-images.githubusercontent.com/24731304/65669465-33b87480-e076-11e9-92ec-94b689a0cd15.png)
![image](https://user-images.githubusercontent.com/24731304/65669960-04eece00-e077-11e9-9dbe-2bcb7308a83f.png)

## 期望的行为:
正常显示

**Comment by yangchch6** [comment]
复现条件：电脑设置屏幕显示百分比为 125%

**Comment by yangchch6** [comment]
发了新包 bee-complex-grid@2.0.27
