### ISSUE TITLE
Grid 表头高度错位

### ISSUE THREAD

**Issue by lilicoder** [iuap-design/tinper-bee#357]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.13

- 若使用单个组件，请标明该组件版本号：
bee-complex-grid@2.0.16

- 当前项目中`react`的版本号：
react@16.9.0

- 所使用的操作系统：
Windows

- 所使用的浏览器：
Google Chrome
版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
离散制造与U9开发部 IOT项目组

### 1、代码
use
import Grid from "components/Grid";
![image](https://user-images.githubusercontent.com/24731304/65670296-a7a74c80-e077-11e9-87a6-26c75bfff0ab.png)
Grid
![image](https://user-images.githubusercontent.com/24731304/65670372-d45b6400-e077-11e9-839a-3537a3a5a59e.png)

![image](https://user-images.githubusercontent.com/24731304/65670352-cad1fc00-e077-11e9-9c17-b4148ab23f0a.png)

### 2、报错信息
无

## 期望的行为:
正常显示

**Comment by lilicoder** [comment]
![image](https://user-images.githubusercontent.com/24731304/65827122-95205380-e2c1-11e9-9903-bd040b7fe997.png)

**Comment by yangchch6** [comment]
备注： 此问题找了两台机器没有复现，需要问题提出人找别的电脑测试一下。
