### ISSUE TITLE
RangePicker选择了日期区间后展开，点击日期面板右上角的清空 (X 按钮)，然后再点击日历控件的时候页面空白

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#358]
## 环境及版本信息
@GuoYongfeng @kvkens @yangchch6   
- `tinper-bee` 版本号:  

tinper-bee@2.0.7
- 若使用单个组件，请标明该组件版本号：

bee-datepicker@2.0.28

选完日期后再次点击组件展开面板，点击清空按钮
![attachfilehandler](https://user-images.githubusercontent.com/17866900/65676143-f4902080-e081-11e9-934a-6d1a94ddb91a.png)

清空完之后再点击组件，页面崩溃空白
![attachfilehandler (1)](https://user-images.githubusercontent.com/17866900/65676364-5cdf0200-e082-11e9-91a7-ce74ebca4fb8.png)

**Comment by yangchch6** [comment]
@wangkimi  这个问题已经修复过，请升级 DatePicker 至 2.2.8 版本
