### ISSUE TITLE
select 组件当允许用户清空时，样式问题

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#359]
## 环境及版本信息
@GuoYongfeng @kvkens 
- `tinper-bee` 版本号:  

tinper-bee@2.0.7
- 若使用单个组件，请标明该组件版本号：

bee-select@2.0.9

官网样式正常，但是项目中当允许用户清空时会有两个清空的叉叉且和官网不一致，略丑

![捕获](https://user-images.githubusercontent.com/17866900/65679256-49826580-e087-11e9-8c87-a8799fe7fa5a.JPG)

**Comment by yangchch6** [comment]
@wangkimi  这个问题已经修复过，请升级 tinper-bee@2.1.2 + 或 bee-select @2.0.14 +

**Comment by wangkimi** [comment]
我更新tinper-bee 到2.1.2后 bee-message 样式错乱了
