### ISSUE TITLE
对官网tinper-bee左侧导航栏滚动条重置的问题反馈 

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#36]
#### 描述这个问题:
官网地址： http://bee.tinper.org/bee-datepicker

#### 当前的行为:
当用户在左侧导航栏任意点击一个栏目（以此栏目在右侧会出现滚动条为例），当页面跳转到此栏目对应的页面，会使得window当前的滚动条置位0，此时左侧的导航栏会回复初始状态，用户并不能直观的获取自己所停留的栏目，用起来很不顺手哦。

#### 期望的行为:
希望左侧导航栏和右侧内容区域分开，每次选中的当前栏目会停留在视口内。

**Comment by GuoYongfeng** [comment]
已完成
