### ISSUE TITLE
grid表多级表头在点隐藏按钮时，错乱

### ISSUE THREAD

**Issue by wanghobby** [iuap-design/tinper-bee#360]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

    "bee-complex-grid": "2.0.25",
- 当前项目中`react`的版本号：

     "react": "16.3.2",
- 所使用的操作系统：

     Mac
- 所使用的浏览器：

    Chrome 76.0.3809.132（正式版本） （64 位）
## 您所在的领域、行业或项目组：

   开发三部，贵冶项目，王光杨
## 描述这个问题:
我在设置多级表头时，点击右上角的可以隐藏列的功能按钮时，多级表头会变成一级表头，列也错乱了
### 2、报错信息

![image](https://user-images.githubusercontent.com/26377237/65735835-69f40380-e10b-11e9-83c8-609c84ba35df.png)
![image](https://user-images.githubusercontent.com/26377237/65735839-6f514e00-e10b-11e9-8876-1fbb06f6505a.png)

**Comment by yangchch6** [comment]
- bee-table@2.2.13
    - [Fixbug]Grid 多级表头在点隐藏按钮时，多级表头变成了一级表头。

项目中重新安装下 bee-complex-grid 即可，注意检查下node_modules中 bee-table 版本
