### ISSUE TITLE
radio 在第二次初始值为0 不会被选中

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#361]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、代码
这radio的选项值

        options: [{ 'key': 1,'value':"是" }, { "key": 0 ,'value':"否"}],        

在第一次渲染初始值设置为0时 ’否‘会被选中
当做了数据处理 第二次渲染 让radio的初始值为0  是 否 都不会选中

**Comment by yangchch6** [comment]
- bee-radio@2.0.17
    - [Fixbug]解决 radio 在第二次初始值为0 不会被选中的问题。
