### ISSUE TITLE
pap参照组件添加清空（X）按钮

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#362]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
pap-refer@1.0.8

- 当前项目中`react`的版本号：

- 所使用的操作系统：
win7

- 所使用的浏览器：
Google Chrome 
版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
用友金融非银产品研发部，杨志会

## 描述这个问题:
iuap生成的参照组件，组件上没有清空按钮，若想清空参照内容只能重新打开参照才能清空，这种操作方式给开发和客户的体验不是很好，所以麻烦集团相关开发人员将pap参照组件加上清空按钮

**Comment by XYooo** [comment]
删除node_module和package-lock.json,然后重新install,然后clearBut=true
