### ISSUE TITLE
bee-message 样式问题，提示信息竖着展示且，关闭按钮样式错乱

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#363]
## 环境及版本信息

@GuoYongfeng  @wangyajing 
- `tinper-bee` 版本号:  tinper-bee@2.2.0

- 若使用单个组件，请标明该组件版本号：bee-message@2.1.4

**Comment by wangkimi** [comment]
![捕获](https://user-images.githubusercontent.com/17866900/65812036-2aedad00-e1f4-11e9-828d-fbb54c85f0f4.JPG)

**Comment by yangchch6** [comment]
- bee-message@2.1.6
    - [Fixbug]解决新老版本样式冲突问题，主要是关闭按钮样式问题。
