### ISSUE TITLE
树参照组件反选问题

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#365]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
pap树参照组件多选
2.0.2

- 当前项目中`react`的版本号：

- 所使用的操作系统：
windows

- 所使用的浏览器：
 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
用友金融 非银产品部 王娟娟  电话：18811398098

## 描述这个问题:
树参照组件多选，当选中父节点的多选之后，父节点下的所有子节点也会被选中，但是不能再次点击父节点的多选框来取消选中这些节点
![Uploading image.png…]()

**Comment by XYooo** [comment]
pap-refer安装1.0.9版本
