### ISSUE TITLE
表参照 RefMultipleTable 分页问题

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#366]
## 环境及版本信息

- `tinper-bee` 版本号:  tinper-bee@2.0.7

- 若使用单个组件，请标明该组件版本号：pap-refer@1.0.8

## 描述这个问题:
点击每页显示几条的时候，如果我选择五条界面就显示5条，如果我选择15条，界面就显示15条。
但是分也不组件一直显示的是10条，感觉是没有根据pageSize 更新dataNum
### 1、代码
没有问题的版本截图：
![捕获](https://user-images.githubusercontent.com/17866900/65829631-ff44f280-e2d9-11e9-8961-4b693bf9818f.JPG)

有问题的版本截图：
![捕获](https://user-images.githubusercontent.com/17866900/65829643-11269580-e2da-11e9-93a0-57471bd7f8ad.JPG)

**Comment by XYooo** [comment]
重新安装，bee-pagination已经更新到2.0.11解决这个问题
