### ISSUE TITLE
日期时间范围控件开始时间赋值不了

### ISSUE THREAD

**Issue by Zzhufeichao** [iuap-design/tinper-bee#367]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.0

- 若使用单个组件，请标明该组件版本号：
2.2.7

- 当前项目中`react`的版本号：
16.8.6

- 所使用的操作系统：
win10

- 所使用的浏览器：
chrom

## 您所在的领域、行业或项目组：

智能制造事业部--NC设备云 ----朱飞超

## 描述这个问题:
使用日期时间范围控件，加上showTime参数。结果选择日期范围时，开始时间没有赋值

### 1、代码

![image](https://user-images.githubusercontent.com/30830131/65862951-d8ea8a00-e3a1-11e9-9af0-0c2be4d908a1.png)

![image](https://user-images.githubusercontent.com/30830131/65862969-e273f200-e3a1-11e9-998d-1457a73492be.png)

## 期望的行为:

开始时间能够赋值

**Comment by yangchch6** [comment]
- bee-datepicker@2.2.11
    - [Fixbug]日期时间范围控件开始时间赋值不了。
