### ISSUE TITLE
affix 设置无效

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#368]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、代码

                <Affix offsetTop={120}>
                    test
                </Affix>

还是会被滚动条滚上去

**Comment by yangchch6** [comment]
修改两处：
1、
![image](https://user-images.githubusercontent.com/33412781/67257480-bdfdc800-f4be-11e9-84f2-4e5e7bbf7ce0.png)

2、
![image](https://user-images.githubusercontent.com/33412781/67257487-ca822080-f4be-11e9-92ab-a37a5541be8f.png)

原因：滚动事件是绑定在 window 上的，window 没有滚动条了，就监听不到事件了。
