### ISSUE TITLE
下拉参照,限制参照宽度后, 由于选项文字较长,溢出文字显示为省略号. 鼠标悬浮每个选项后可以显示全部内容,类似超链接A标签的title属性

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#369]
## 环境及版本信息

- `tinper-bee` 版本号:  
  "tinper-bee": "^2.1.5",
   "pap-refer": "^1.0.8",

- 当前项目中`react`的版本号：
   "react": "16.6.3",
- 所使用的操作系统：
  Windows/Mac

- 所使用的浏览器：

 chrome    firefox

## 描述这个问题:
      **下拉参照,限制参照宽度后, 由于选项文字较长,溢出文字显示为省略号. 鼠标悬浮每个选项后可以显示全部内容,类似超链接A标签的title属性**
### 1、代码
   import RefComboBox, { ComboStore } from 'pap-refer/lib/pap-common-combobox/src/index';​
![image](https://user-images.githubusercontent.com/10356530/66392068-6c0a6c00-ea01-11e9-94ce-fd42172c862f.png)
![image](https://user-images.githubusercontent.com/10356530/66392094-7cbae200-ea01-11e9-9239-daa480c7a5cc.png)

## 期望的行为:
参照下拉部分宽度固定调整为280px; 高度最大8条数据的高度 超出去后 出现滚动条.
内容过多时,溢出的文字显示为省略号;
鼠标悬浮后显示全部文字
类似 超链接的 title 属性 title="要显示的文字"

**Comment by XYooo** [comment]
你直接在ComboItem外面加个li 上面带上title就可以
![image](https://user-images.githubusercontent.com/21334863/66622453-3ee4d600-ec1a-11e9-9029-cd1b9eaeb3b6.png)
![image](https://user-images.githubusercontent.com/21334863/66622469-473d1100-ec1a-11e9-8076-78e3eb1517aa.png)
