### ISSUE TITLE
InputNumber组件相关问题汇总

### ISSUE THREAD

**Issue by kvkens** [iuap-design/tinper-bee#37]
### Bug 报告
- 这边需求是做汇率调整，必须可以输入小数，进行微调。

- 目前可以微调，但是不支持输入小数进行微调。

- __Package version(s)__: (版本号)0.6.2

#### 描述这个问题:
- 这边需求是做汇率调整，必须可以输入小数，进行微调。

- 目前可以微调，但是不支持输入小数进行微调。

#### 当前的行为:
不能够输入小数微调

#### 期望的行为:
能够输入小数微调

**Comment by BoyuZhou** [comment]
发布了bee-input-number 1.0.2版本，修复了这个bug

**Comment by kvkens** [comment]
@BoyuZhou 发现几点问题。可以输入小数了，但是发现以下问题，恢复主题！咳咳。

组件：`bee-input-number 1.0.2`

发现了几处BUG：

1. 当设置默认值`value={0}`并且`min={0}`的时候，发现界面不显示内容了，
![image](https://user-images.githubusercontent.com/3817644/32474483-a99b749c-c3a7-11e7-90c7-1a8238b817ff.png)

2. ~~还有一个就是JS的问题，在此组件下表现非常突出，就是浮点型的那个BUG，这里能给一个第三方的库去解决吗？~~
发现antd是有这些支持的，包括设置小数精度等问题，这些都是资金云目前需要的
[参考](https://ant.design/components/input-number-cn/)
![image](https://user-images.githubusercontent.com/3817644/32474622-677020a8-c3a8-11e7-9232-e695f92b95a1.png)
![image](https://user-images.githubusercontent.com/3817644/32480837-9cd6f3b6-c3cb-11e7-8665-1432c150c916.png)


> 当我们的`step={0.1}`那么步进的话就会出现精度损失的那个问题，具体场景代码如下：

```js
import React ,{ Component } from "react";
import InputNumber from "bee-input-number";

export default class WorkType extends Component{
  constructor(props){
    super(props);
    this.state = {
      value : 0
    }
  }
  componentDidMount(){

  }

  handleChange = (value) => {
    this.setState({
      value
    });
  }
  render(){
    return (<div>
      <InputNumber value={0} onChange={ this.handleChange } max={100} min={0} step={0.1} />
      </div>)
  }
}

```

**Comment by kvkens** [comment]
又发现一个BUG：

初始化是这样的：
step=1，min=0 max=10 参数，当我点击+的时候，然后再-的话，就会超过我设置的大小范围，并且鼠标禁用的图标也会丢失了。

复现图片：

![image](https://user-images.githubusercontent.com/3817644/32480161-4e6374aa-c3c8-11e7-9bb7-e075905b19d4.png)

我们点击下`+`
![image](https://user-images.githubusercontent.com/3817644/32480172-59464398-c3c8-11e7-8c54-5355fd073f03.png)

`+`完后，我们在`-`一下
这时候出现了BUG

![image](https://user-images.githubusercontent.com/3817644/32480195-6f2be6c2-c3c8-11e7-9092-ea32ec1a8b29.png)

![image](https://user-images.githubusercontent.com/3817644/32480254-ad2097c0-c3c8-11e7-834e-b464284821dd.png)

**Comment by kvkens** [comment]
还有一个建议性的问题：当我们鼠标按住`+`按钮的时候，应该匀速的帮我们增加。目前我们的是不支持的。

具体效果参考：[antd](https://ant.design/components/input-number-cn/)

**Comment by kvkens** [comment]
召唤神周 @BoyuZhou 
> 以下内容是未发布的`bee-input-number`本地测试发现的问题记录，不作为发布版本的问题：

1. 设置好最大12与最小5参数后，点击`+`后可以正常加，当我点`-`到5的时候，`-`这个按钮还是可以显示点击的，当我点击后，发现按钮才不可以点击，多操作一次!demo3里面的例子也是这样。

![image](https://user-images.githubusercontent.com/3817644/32529201-1fd02872-c472-11e7-9679-5c20b22edece.png)

当我点击`-`的时候才出现了不可用：
![image](https://user-images.githubusercontent.com/3817644/32529242-62a7c7f4-c472-11e7-8957-3b6ca55bf746.png)

2. 默认是0，点击`+`的时候变成1.00的问题
![image](https://user-images.githubusercontent.com/3817644/32529303-c5b3b506-c472-11e7-9cff-13c68721fd66.png)
点击一下:
![image](https://user-images.githubusercontent.com/3817644/32529312-d07f58fa-c472-11e7-88de-7319e039bdda.png)
在`-`一下：
![image](https://user-images.githubusercontent.com/3817644/32529390-5320ac96-c473-11e7-9faa-26949f974c28.png)

**Comment by BoyuZhou** [comment]
已发布bee-input-number@1.0.3,解决相关问题

**Comment by kvkens** [comment]
@BoyuZhou OK，验证通过没问题了！赞
