### ISSUE TITLE
【bug】form和MonthPicker同时使用时出错

### ISSUE THREAD

**Issue by HuaYJ1996** [iuap-design/tinper-bee#370]
版本：
bee-datepicker@2.2.9
bee-form@2.0.12

描述：
1 在form中使用DatePicker的MonthPicker时，报错。
在某些地方改变了内部传递的value值，将其格式化为字符串格式，导致无法使用value.year()方法。怀疑是form组件的问题
2 locale文件中缺少monthFormat字段。【已解决】
3. 在monthPicker里面，点击 << 和 >> 按钮无效。

**Comment by lucian55** [comment]
已解决
