### ISSUE TITLE
DatePicker组件使用报错

### ISSUE THREAD

**Issue by ZhoodJ** [iuap-design/tinper-bee#371]
## 环境及版本信息

- `tinper-bee` 版本号:  ^2.2.1

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：^16.9.0

- 所使用的操作系统：Windows

- 所使用的浏览器：谷歌

### 1、代码

![image](https://user-images.githubusercontent.com/25977873/66536662-49d33400-eb50-11e9-86d3-f8d1ad5bb6c7.png)

**Comment by yangchch6** [comment]
value 传 moment 类型的值
