### ISSUE TITLE
ref-refer参照组件搜索问题

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#372]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.3

- 若使用单个组件，请标明该组件版本号：

+-- ref-multiple-table@2.0.1
+-- ref-tree@2.1.1
`-- ref-tree-table@2.1.0

- 当前项目中`react`的版本号：
16.3.2

- 所使用的操作系统：
win7

- 所使用的浏览器：
Google Chrome 已是最新版本
版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
用友金融

## 描述这个问题:
ref参照组件输入框第一次点击的时候还没有输入值，NOT FOUND应该不显示，等我输入值进行查询的时候如果没查到值再显示NOT FOUND

## 期望的行为:
等我输入值进行查询的时候如果没查到值再显示NOT FOUND

**Comment by XYooo** [comment]
重新装包 删除包和package-lock.json
