### ISSUE TITLE
上传 Upload 的 onRemove 方法 return false 不生效

### ISSUE THREAD

**Issue by ranyanchuan** [iuap-design/tinper-bee#373]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by yangchch6** [comment]
- bee-upload@2.0.4
    - [Fixbug]`onRemove` 返回值为 false 时，依然可以删除。
