### ISSUE TITLE
希望树表参照右侧的表双击选中

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#374]
## 环境及版本信息

- `tinper-bee` 版本号:  
   2.0.3

- 若使用单个组件，请标明该组件版本号：
   ref-tree-table@2.1.0

- 当前项目中`react`的版本号：
   "react": "^16.3.2",

- 所使用的操作系统：
   win7

- 所使用的浏览器：
   Google Chrome
版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：
   用友金融，杨志会

## 描述这个问题:
    ref树表参照,右侧的树不能双击进行选择，只能先单击选择之后再点击确认进行选择

## 期望的行为:
    希望能通过双击直接确认选择相应数据

**Comment by XYooo** [comment]
2.1.1版本

**Comment by yangzhhc** [comment]
已解决
