### ISSUE TITLE
Table组件 层级树场景使用 onRowHover功能返回当前数据异常

### ISSUE THREAD

**Issue by siriuscandy** [iuap-design/tinper-bee#376]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：2.2.12

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:

Table组件 层级树场景使用 
 onRowHover=(index,record)=>{
    this.currentIndex = index;
    this.currentRecord = record;
  }
一级树数据 从第二条开始 返回的index 和 record出错

**Comment by yangchch6** [comment]
- bee-table@2.2.15
    - [Fixbug]树形表，`onRowHover` 方法返回参数异常。
