### ISSUE TITLE
多页签问题

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#377]
## 环境及版本信息

- `tinper-bee` 版本号:  
   "tinper-bee": "2.0.10"

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
   react@16.6.3

- 所使用的操作系统：
   win7

- 所使用的浏览器：
   Google Chrome 已是最新版本
   版本 77.0.3865.120（正式版本） （64 位）

## 您所在的领域、行业或项目组：
   用友金融  非银产品部，杨志会

## 描述这个问题:
   当iuap系统同时打开两个或两个以上的页签时，在其中一个页签F5刷新后，再切换到其他的页签，那么其他页签的页面布局会错乱

## 当前的行为：效果（可截图说明）及动作描述
![image](https://user-images.githubusercontent.com/53893374/66974739-ae513e80-f0ce-11e9-99b8-afb10180e219.png)
![image](https://user-images.githubusercontent.com/53893374/66974807-efe1e980-f0ce-11e9-8bca-0596e619ad90.png)

**Comment by yangchch6** [comment]
你们是把页面集成到 portal 了吗？

**Comment by yangzhhc** [comment]
没有，就是iuap平台

**Comment by yangchch6** [comment]
![image](https://user-images.githubusercontent.com/33412781/68836505-7f41e300-06f5-11ea-95ea-7cc185c4440b.png)

**Comment by yangchch6** [comment]
1、尝试升级
2、计算表格容器宽度
