### ISSUE TITLE
树和表参照多选--点击输入框筛选列数据只会出发一次方法

### ISSUE THREAD

**Issue by Zzhufeichao** [iuap-design/tinper-bee#378]
## 环境及版本信息

- `tinper-bee` 版本号:  ^2.2.0

- 若使用单个组件，请标明该组件版本号： 
"ref-multiple-table": "2.1.0",
"ref-tree": "^2.0.14",

- 当前项目中`react`的版本号：

"react": "^16.8.6",
- 所使用的操作系统：
 win10

- 所使用的浏览器：
chrome

## 描述这个问题:
组织树参照(单选)、部门树参照(多选)、设备表参照(多选)
部门、设备是选择组织通过组织ID,筛选出来的数据，当第一次选择组织，然后点击部门、设备的输入框会有列数据。当清空选择的组织时，所对应的部门、设备列数据和树数据都会被清空，组织不被清空。在重新选择另一个组织时，再次点击部门和设备输入框时，没有触发方法。列数据加载不出来。但是点击设备、部门的menu按钮时。所对应的树形数据是有的。
### 1、代码

![1571296797(1)](https://user-images.githubusercontent.com/30830131/66986515-a787f300-f0f1-11e9-9cb0-9fb156f046a9.jpg)
![1571296772(1)](https://user-images.githubusercontent.com/30830131/66986522-ab1b7a00-f0f1-11e9-8a71-df5e98f9aa42.jpg)
![1571296860(1)](https://user-images.githubusercontent.com/30830131/66986613-d1411a00-f0f1-11e9-90b7-ebdbcd0b83c1.jpg)
![1571296885(1)](https://user-images.githubusercontent.com/30830131/66986621-d4d4a100-f0f1-11e9-88f2-fb566077a782.jpg)

### 2、报错信息

![1](https://user-images.githubusercontent.com/30830131/66987426-5aa51c00-f0f3-11e9-94e6-1117d1f45506.jpg)
![2](https://user-images.githubusercontent.com/30830131/66987432-609afd00-f0f3-11e9-9838-52ab51b6b8f4.jpg)
![3](https://user-images.githubusercontent.com/30830131/66987438-62fd5700-f0f3-11e9-9586-2250ce585bfd.jpg)
![4](https://user-images.githubusercontent.com/30830131/66987442-655fb100-f0f3-11e9-9573-b7b13b14e6d6.jpg)

## 期望的行为:

期望点击输入框会重新触发方法，不是只触发一次

**Comment by XYooo** [comment]
点击输入框不会触发filterUrlFunc，只有修改input的值才会触发这个操作。
所以重新选择组织之后，部门的filterData应该修改，这样点击部门参照才会有下拉数据

**Comment by XYooo** [comment]
点击输入框会触发filterUrlFunc

**Comment by XYooo** [comment]
filterUrlFunc 只有在第一次加载完然后不输入任何内容下点击会触发，其他时候得输入过滤内容才触发。建议你在清空组织的时候，修改传给部门树参照(多选)、设备表参照(多选)的filterUrlData
