### ISSUE TITLE
树参照默认节点全展开,收起一个节点,操作别的节点时,收起的节点又展开了

### ISSUE THREAD

**Issue by Sunfloweres** [iuap-design/tinper-bee#379]
## 环境及版本信息
http://172.20.47.55/wbalone/index.html#/      用户名:mdmadmin001  密码:123qwe
- `tinper-bee` 版本号:  

ref-tree的RefTreeWithInput组件,最新的和2.0.13的版本都有同样的问题
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：

专属云平台部的主数据项目, 名字:孙玉婷
### 1、代码

#
![Uploading image.png…]()
## 期望的行为:

收起的节点,不要随着别的操作展开

**Comment by yangchch6** [comment]
- bee-tree@2.1.9
    - [Fixbug]解决设置 defaultExpandedAll 时，树参照节点自动收起的问题。
