### ISSUE TITLE
官网没有提供CDN的引入地址

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#38]
### Bug 报告

- __Package version(s)__: (版本号) 1.0.2

#### 描述这个问题:

1、 当一个新手，指定引入几个组件后，样式不知道如何引入？
在官网上没有提供css的CDN 地址的引入说明？
(当前只是说明了，安装了tinper-bee 后，直接进入css的方法。)
2、1.0.2的版本，没有min版本的css样式。

#### 期望的行为:

需要说明CDN的css引入地址？以及css的使用方法？

**Comment by kvkens** [comment]
文档需要更新.

**Comment by kvkens** [comment]
@HuYuee CDN需要更新.

**Comment by BoyuZhou** [comment]
已增加
