### ISSUE TITLE
tinper-bee 下的table组件colums数量较少时 width不能100%显示

### ISSUE THREAD

**Issue by likegs9** [iuap-design/tinper-bee#380]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：

营销云 crm标准产品  高姗 前端开发

### 1、代码

![image](https://user-images.githubusercontent.com/10152771/66995065-f4bf9100-f100-11e9-9976-31e912181a56.png)

- table的colums 如果只有几项 而且每项都有设置width的时候 第一次渲染 不能100%显示
- table 组件  默认会读取 每列的宽度 然后算值

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/10152771/66995386-80392200-f101-11e9-8e86-eab3b52b2294.png)
![image](https://user-images.githubusercontent.com/10152771/66995405-89c28a00-f101-11e9-820c-4baab4a380b2.png)

## 期望的行为:

- 默认加载table时  如果列数量叫较少  table宽度能自动撑开到100%
![image](https://user-images.githubusercontent.com/10152771/66995644-f3429880-f101-11e9-988a-83e6e202a16a.png)

**Comment by yangchch6** [comment]
升级 bee-table@2.2.18
