### ISSUE TITLE
保存 form表单获取不到参照通过下拉选中的值，偶发

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#381]
## 环境及版本信息

- `tinper-bee` 版本号:  

"ref-multiple-table": "^2.1.4",
    "ref-tree": "^2.1.2",
    "ref-tree-table": "^2.0.9",

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by XYooo** [comment]
不知道表单提交的具体代码，但是表单是可以获取到选中的下拉数据的。代码入下
![image](https://user-images.githubusercontent.com/21334863/68445895-2d411f00-0216-11ea-9671-0eac8e3fe2c8.png)
![image](https://user-images.githubusercontent.com/21334863/68445904-33370000-0216-11ea-9b86-0734c7c06595.png)

**Comment by XYooo** [comment]
上述用法，没有不触发的情形存在

**Comment by XYooo** [comment]
经测试，使用下列方法也是可以获取到全部的表单数据

` 

{
          ...getFieldProps('table3', {
            initialValue: value,
            rules: [{
              message: '请输入姓名',
              pattern: /[^{"refname":"","refpk":""}|{"refpk":"","refname":""}]/
            }],
          })
          }
        />
        <Button onClick={()=>{alert(JSON.stringify(this.props.form.getFieldsValue(['table3'])))}}>提交</Button>

`
