### ISSUE TITLE
引用ref-multiple-table组件项目启动报错

### ISSUE THREAD

**Issue by ZhoodJ** [iuap-design/tinper-bee#382]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.1

- 若使用单个组件，请标明该组件版本号：ref-multiple-table：2.1.4

- 当前项目中`react`的版本号：16.9.0

- 所使用的操作系统：Windows

- 所使用的浏览器：谷歌77

## 描述这个问题:
当引用这个组件时，项目就起不来了
### 1、代码

以下是webpack.dev.config.js配置
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const ExtractTextPlugin = require('extract-text-webpack-plugin');
module.exports = {
 
    entry: {
		app:[
			path.join(__dirname, 'src/index.js')
		],
		vendor: ['react', 'react-router-dom', 'redux', 'react-dom', 'react-redux']
	},

	mode:'development',
    
    output: {
        path: path.join(__dirname, 'build'),
		filename: '[name].[hash].js',
		chunkFilename: '[name].[chunkhash].js'
    },
	module: {
		rules: [{
			test: /\.js$/,
			use: ['babel-loader?cacheDirectory=true'],
			include: path.join(__dirname, 'src')
		},
		{
			test: /\.css$/,
			use: [{loader: MiniCssExtractPlugin.loader}, {
				loader:'css-loader',
				options: {
					modules: true,
					localIdentName: '[local]--[hash:base64:5]'
				}
			}, 'postcss-loader']
		 },
		 //识别less文件
		 {
			test: /\.less$/,
			use: ExtractTextPlugin.extract({
			  use: [{
				loader: 'css-loader',
				options: {
				  modules: false
				}
			  }, 'postcss-loader', 'less-loader'],
			  fallback: 'style-loader'
			})
		  },
		{
			test: /\.(png|jpg|gif)$/,
			use: [{
				loader: 'url-loader',
				options: {
					limit: 8192
				}
			}]
		}

		]
	},
	// webpack-dev-server
	devServer: {
		contentBase: path.join(__dirname, 'build'), 
		compress: true,  // gzip
		host: '0.0.0.0', 
		hot:true, 
		historyApiFallback:true, 
		proxy: {
            '/api': {
                 target: 'http://localhost:8000',
                 pathRewrite: {'^/api' : ''}, 
                 changeOrigin:true
            }
        },
		port: 8000 
	},
	devtool: 'inline-source-map',
	resolve: {
		alias: {
			pages: path.join(__dirname, 'src/pages'),
			components: path.join(__dirname, 'src/components'),
			router: path.join(__dirname, 'src/router'),
			actions: path.join(__dirname, 'src/redux/actions'),
			reducers: path.join(__dirname, 'src/redux/reducers'),
			static: path.resolve(__dirname, 'src/static'),
			utils: path.resolve(__dirname, 'src/utils'),
		}
	},

	plugins: [
		new HtmlWebpackPlugin({
			filename: 'index.html',
			template: path.join(__dirname, 'src/index.html')
		}),
		new MiniCssExtractPlugin({
			filename: "[name].[contenthash].css",
			chunkFilename: "[id].[contenthash].css"
		}),
		//解析less文件插件
		new ExtractTextPlugin({
			filename: '[name].[hash:8].css'
		  })
	]

};

package.js配置
{
  "name": "react-cli-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "webpack --config ./webpack.dev.config.js",
    "start": "webpack-dev-server --config ./webpack.dev.config.js",
    "preview": "cross-env PUBLIC_URL='/mtldebugger/solr/7c3f7fd7ffad4f2fab4dc4e2d0802c63' npm run start"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "file-loader": "^4.2.0",
    "mini-css-extract-plugin": "^0.8.0",
    "postcss-cssnext": "^3.1.0",
    "postcss-loader": "^3.0.0",
    "react-loadable": "^5.5.0",
    "react-redux": "^7.1.0",
    "url-loader": "^2.1.0",
    "webpack": "^4.39.2",
    "webpack-cli": "^3.3.6"
  },
  "dependencies": {
    "@babel/core": "^7.5.5",
    "@babel/plugin-proposal-class-properties": "^7.5.5",
    "@babel/plugin-transform-runtime": "^7.6.2",
    "@babel/preset-env": "^7.5.5",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.6",
    "css-loader": "^3.2.0",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",
    "html-webpack-plugin": "^3.2.0",
    "i": "^0.3.6",
    "install": "^0.13.0",
    "less": "^3.10.3",
    "less-loader": "^5.0.0",
    "mtl-js-sdk": "^1.0.1",
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-router-dom": "^5.0.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "ref-multiple-table": "^2.1.4",
    "style-loader": "^1.0.0",
    "tinper-bee": "^2.2.1",
    "webpack-dev-server": "^3.8.1"
  }
}

babel.config.js配置
const babelConfig = {
   presets: ["@babel/preset-react", "@babel/preset-env"],
   plugins: ["@babel/plugin-syntax-dynamic-import","@babel/plugin-proposal-class-properties","@babel/plugin-transform-runtime"]
}

module.exports = babelConfig;

### 2、报错信息

![image](https://user-images.githubusercontent.com/25977873/67261578-ecd26900-f4d3-11e9-91cb-bc0a4e242c20.png)

**Comment by XYooo** [comment]
css-loader使用 "css-loader": "^1.0.0"
