### ISSUE TITLE
树形参照展开收起问题 树组件异步渲染树节点，设置 defaultExpandAll 属性失效

### ISSUE THREAD

**Issue by ssboll** [iuap-design/tinper-bee#383]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

ref-tree@2.1.3
bee-tree@2.0.11
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：

快消行业与CRM业务部  邵帅
### 1、代码

![image](https://user-images.githubusercontent.com/30584512/67350509-81dd6c80-f57d-11e9-9f62-4dadf591e608.png)
## 当前的行为：效果（可截图说明）及动作描述

一个树形参照选中值保存后，再打开另一个树形参照，该参照树形结构收起了

![image](https://user-images.githubusercontent.com/30584512/67350441-5f4b5380-f57d-11e9-97cc-5003c47bb020.png)
![image](https://user-images.githubusercontent.com/30584512/67350449-63777100-f57d-11e9-8f85-d6c3f4c91b26.png)

## 期望的行为:

![image](https://user-images.githubusercontent.com/30584512/67350465-68d4bb80-f57d-11e9-9dba-09ba74384aea.png)

**Comment by yangchch6** [comment]
发了新包 bee-tree@2.1.12
