### ISSUE TITLE
该组件没有componentWillReceiveProps方法，当将该组件置于父子组件嵌套的情况下，show状态不会更新

### ISSUE THREAD

**Issue by BIZZEW** [iuap-design/tinper-bee#384]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by yangchch6** [comment]
什么组件？

**Comment by yangchch6** [comment]
未描述清楚问题组件，视为无效issue
