### ISSUE TITLE
数字输入框第一次输入的时候无法输入负数的负号

### ISSUE THREAD

**Issue by crazy-lulu-edu** [iuap-design/tinper-bee#385]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
InputNumber控件

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 当前的行为：效果（可截图说明）及动作描述
InputNumber控件在第一次输入的时候无法输入负数符号,需要先输入数字才能输入符号.已经在
http://bee.tinper.org/tinper-acs/ref-tree 网站的数字输入框上做了验证.

## 期望的行为:
可以输入负数符号再插入数字

**Comment by yangchch6** [comment]
- bee-input-number@2.1.7
    - [Fixbug]输入框为空时，无法输入负号的问题。
