### ISSUE TITLE
tinper-bee@2.2.2 行点击事件,急

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#387]
## 环境及版本信息
- `tinper-bee` 版本号:  

tinper-bee@2.2.2
bee-table@2.2.14
## 您所在的领域、行业或项目组：

ISCP中兴项目组
## 描述这个问题:
(1)table 行点击事件勾选不上
(2)行点击事件自动重新渲染,导致可编辑行中有请求接口的地方自动发送了请求
(3)最严重的是,当用了Tabs且有多个TabPane,当在任何一个页签点击表格多选情况下的复选框,就会自动调用tabs的onChange方法并且往里传了个参数,传入的参数是个对象(合成事件SyntheticEvent),客户现场没办法上传文件

**Comment by ZhiCYue** [comment]
解决方法：
问题1：可以设置table 组件autoCheckedByClickRows = true 来实现自动勾选；
问题3：更新bee-tabs 组件为 2.1.6

**Comment by wangkimi** [comment]
好的.我测试下.谢谢啦
