### ISSUE TITLE
日期范围选择控件

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#388]
## 环境及版本信息
- `tinper-bee` 版本号:  

tinper-bee@2.0.7
## 您所在的领域、行业或项目组：

ISCP中兴采购云项目组
## 描述这个问题:
应客户需求:需要选择日期的同时选择时间,可否更新一下组件以提供此功能.如果当前控件已经满足,还请告知.谢谢啦

**Comment by yangchch6** [comment]
组件已支持，设置 showTime={ true }

**Comment by wangkimi** [comment]
我已经加了showTime   ,没有生效

**Comment by wangkimi** [comment]
如果我用的是 :import DatePicker from 'bee-datepicker'; 就没有作用
如果用的是 import DatePicker from "tinper-bee/lib/Datepicker"; 就起作用,是不是没有同步更新

**Comment by wangkimi** [comment]
目前试了一下,bee-datepicker@2.2.7 可以,bee-datepicker@2.2.12不行.可以排查下
