### ISSUE TITLE
Button添加loading效果

### ISSUE THREAD

**Issue by wt07060210** [iuap-design/tinper-bee#39]
### Button添加loading效果

- __Package version(s)__: (版本号)

#### 描述这个问题:

在做类似表单提交的时候，button按钮不能设置loading效果

#### 当前的行为:

当前点击button按钮的时候不能设置loading效果

#### 期望的行为:

在点击button的时候，可以设置loading的效果，避免二(多)次点击

**Comment by BoyuZhou** [comment]
增加了bee-loading-state@1.0.0组件，满足这个功能需求

**Comment by HuYuee** [comment]
你好！该组件已经添加。可以参见https://github.com/tinper-bee/bee-loading-state
