### ISSUE TITLE
树形参照快速过滤没有效果 

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#390]
## 环境及版本信息

- `tinper-bee` 版本号:  

"ref-multiple-table": "^2.1.4",
    "ref-tree": "^2.1.2",
    "ref-tree-table": "^2.1.2",
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
官网例子 搜索效果没有
自己写的代码 当查询一个没有存在的数据 尽管数据是空数组，参照还是显示全部数据

**Comment by XYooo** [comment]
确定使用的参数是filterUrl、filterUrlFunc、和filterData，他们的关系参考官网文档，本地测试没有问题

**Comment by XYooo** [comment]
![image](https://user-images.githubusercontent.com/21334863/68445474-fb7b8880-0214-11ea-92e5-e184f8701384.png)
![image](https://user-images.githubusercontent.com/21334863/68445485-02a29680-0215-11ea-9c8f-07222c19f348.png)
