### ISSUE TITLE
TimePicker组件使用normalize调用value.format时报错

### ISSUE THREAD

**Issue by wangxinyu666666** [iuap-design/tinper-bee#391]
## 环境及版本信息

- `TimePicker` 版本号:  
2.0.5

### 1、代码
![image](https://user-images.githubusercontent.com/26834996/67734038-f8c1ac00-fa3a-11e9-9233-7310aa7cebc7.png)

### 2、报错信息
![image](https://user-images.githubusercontent.com/26834996/67734095-1727a780-fa3b-11e9-8412-f77046dbdafe.png)

**Comment by lucian55** [comment]
bee-timepicker@2.0.6      已解决，参考示例 4
