### ISSUE TITLE
TimePicker组件中使用moment时出现invalid date

### ISSUE THREAD

**Issue by wangxinyu666666** [iuap-design/tinper-bee#392]
## 环境及版本信息

- `TimePicker` 版本号:  
2.0.6

### 1、代码
![image](https://user-images.githubusercontent.com/26834996/67734230-6ff74000-fa3b-11e9-8a9a-eda46f0de39b.png)

### 2、报错信息
默认值显示为invalid date

**Comment by lucian55** [comment]
bee-timepicker@2.0.7       已解决
