### ISSUE TITLE
acCitySelect控件多语环境下有问题

### ISSUE THREAD

**Issue by lidwt721** [iuap-design/tinper-bee#394]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、代码

![image](https://user-images.githubusercontent.com/20960402/67766467-73b1b380-fa89-11e9-8a54-087007fdc077.png)

### 2、报错信息

![Uploading image.png…]()

## 当前的行为：效果（可截图说明）及动作描述

![Uploading image.png…]()

**Comment by jonyshi** [comment]
报错信息看不到，麻烦补全一下，或者直接联系我。
@li-dw
