### ISSUE TITLE
左树右表参照 在设置了右表显示查询框后 再设置左边树查询框隐藏无效

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#395]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"ref-multiple-table": "^2.1.4",
    "ref-tree": "^2.1.2",
    "ref-tree-table": "^2.1.2",

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、代码

![Uploading 1111.png…]()

**Comment by XYooo** [comment]
查看代码没有问题，描述问题的代码图片不展示，请重新上传

**Comment by XYooo** [comment]
searchable={false}

**Comment by XYooo** [comment]
![image](https://user-images.githubusercontent.com/21334863/68447073-99715200-0219-11ea-8989-8737a8157720.png)
