### ISSUE TITLE
日期控件禁用bug

### ISSUE THREAD

**Issue by atianchen** [iuap-design/tinper-bee#398]
## 环境及版本信息

- `tinper-bee` 版本号:  ^2.1.5

- 若使用单个组件，请标明该组件版本号：2.2.7

- 当前项目中`react`的版本号：^4.8.3

- 所使用的操作系统：Windows

- 所使用的浏览器：Google Chrome  版本 77.0.3865.90（正式版本） （64 位）

## 您所在的领域、行业或项目组：

用友香港分公司 

## 描述这个问题:
tinper日期控件，设置了禁用日期，当天后都为禁用日期，日勤期新增正常，回显时上面日期控件当天不可选，底下今天按钮日期可选，删掉重选，当天日期又可选
### 1、代码

<DatePicker disabledDate={disabledDate} disabled={this.isReadOnlyField('establishRelationshipDate')}
                                {
                                    ...getFieldProps('establishRelationshipDate', {
                                    initialValue: clientItemInfo.establishRelationshipDate,
                                    // validateTrigger: 'onChange',
                                    rules: [{
                                        required: !this.isReadOnlyField('establishRelationshipDate'), message: '请选择建立关系日期',
                                    }],
                                }

                                )}
                                placeholder={'请选择建立关系日期'}
                                format={format}
                            />
function disabledDate(current) {
    return current && current.valueOf() > Date.now();
}

**Comment by atianchen** [comment]
11

**Comment by lucian55** [comment]
设置 disabledDate 函数错误。 Date.now()和current.valueOf() 是毫秒数。如果需要设置今天及以前不可选，可参考如下：

```js
let nowDay =Math.floor(moment().valueOf()/100/60/60/24);

function disabledDate(current) {
  return current && Math.floor(current.valueOf()/100/60/60/24) <= nowDay;
}

```
