### ISSUE TITLE
bee-select中的例子当下面的空间不够的时候会闪动两下

### ISSUE THREAD

**Issue by HuYuee** [iuap-design/tinper-bee#40]
![image](https://user-images.githubusercontent.com/12147318/32526903-bb598a1a-c466-11e7-979c-138556538041.png)

![image](https://user-images.githubusercontent.com/12147318/32526924-d603405e-c466-11e7-9cef-fb3b1bde3eb7.png)

**Comment by kvkens** [comment]
demo里面有debugger 去掉下！

**Comment by kvkens** [comment]
@JonyShiw

**Comment by HuYuee** [comment]
v1.0.4已支持！
