### ISSUE TITLE
在<FilterColumnTable>组件中加入 bodyDisplayInRow属性为true不生效

### ISSUE THREAD

**Issue by Zzhufeichao** [iuap-design/tinper-bee#402]
## 环境及版本信息

- `tinper-bee` 版本号:  ^2.2.0

- 若使用单个组件，请标明该组件版本号：
"bee-table": "^2.0.24",

- 当前项目中`react`的版本号：^16.8.6

- 所使用的操作系统：

- 所使用的浏览器：

### 1、代码

自己使用filterColumn封装了一个组件，然后在组件中加入 bodyDisplayInRow属性为true不生效。

### 2、报错信息

![image](https://user-images.githubusercontent.com/30830131/68201349-977e7780-fffc-11e9-8bea-eaad096ac98f.png)
![image](https://user-images.githubusercontent.com/30830131/68201378-a402d000-fffc-11e9-85e4-e2ffbaf42d69.png)
![image](https://user-images.githubusercontent.com/30830131/68201411-b1b85580-fffc-11e9-80e6-8e6d5dd6462f.png)

## 当前的行为：效果（可截图说明）及动作描述

加上属性没有出现省略号

## 期望的行为:

希望加上属性有省略号列数据

**Comment by yangchch6** [comment]
在控制台 source 面板中，`Ctrl + P`，搜索 `TableCell.js`，在该文件中，搜索 `return (` ，查看一下 render 里面的内容，是否如下：

```
<td
        colSpan={colSpan}
        rowSpan={rowSpan}
        className={className}
        onClick={this.handleClick}
        title={title}
        style={{maxWidth:column.width, color:fontColor, backgroundColor:bgColor, ...column.style}}
 >
        {indentText}
        {expandIcon}
        {text}
        {colMenu}
 </td>
```

重点看一下，`style` 属性的值，是否有设置 `maxWidth:column.width`，如果有，请在此回复

**Comment by Zzhufeichao** [comment]
有maxWidth:column.width
![image](https://user-images.githubusercontent.com/30830131/68264619-5fbb1280-0084-11ea-8671-63c239208e63.png)

**Comment by yangchch6** [comment]
已解决
