### ISSUE TITLE
日历中文显示

### ISSUE THREAD

**Issue by a982027400** [iuap-design/tinper-bee#404]
## 环境及版本信息

- `tinper-bee` 版本号:  
tinper-bee@2.1.5

- 若使用单个组件，请标明该组件版本号：
bee-calendar@2.0.4

- 当前项目中`react`的版本号：
react@16.6.3

- 所使用的操作系统：
Windows

- 所使用的浏览器：
Chrome  78

### 1、代码
![image](https://user-images.githubusercontent.com/25918335/68353865-c9e7bc00-0145-11ea-9b65-569f2160bb25.png)
![image](https://user-images.githubusercontent.com/25918335/68353921-f6033d00-0145-11ea-8118-0372c4b70f6e.png)

### 2、报错信息
无报错

## 当前的行为：效果（可截图说明）及动作描述
![image](https://user-images.githubusercontent.com/25918335/68357611-dfaeae80-0150-11ea-8117-c5f296c5b53c.png)

## 期望的行为:
![image](https://user-images.githubusercontent.com/25918335/68357638-f35a1500-0150-11ea-80ce-ae3ab8e9206f.png)
月份与周显示为中文

**Comment by lucian55** [comment]
使用最新版本  @2.1.0
引入方式： `import Calendar from 'bee-calendar';`
多语设置参考示例：http://bee.tinper.org/tinper-bee/bee-calendar#%E5%A4%9A%E8%AF%AD%E7%A4%BA%E4%BE%8B
