### ISSUE TITLE
同时存在两个不同的时间选择器，getFieldsValue时取值不对，都取的第一个选择器的值

### ISSUE THREAD

**Issue by skylerswy** [iuap-design/tinper-bee#407]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
win10

- 所使用的浏览器：
谷歌

## 您所在的领域、行业或项目组：
苏婉玉，香港海外部

### 1、代码
↓↓↓，time里两个值一样，明明选了两个不一样的
   timesend = (rule, value, callback) =>{
        console.log(value)
        if(value){
            let time = this.props.form.getFieldsValue(['callReportStart','callReportEnd'])
            console.log(time)
            let start = time.callReportStart
            let end = time.callReportEnd
            console.log(start)
            console.log(end)
            if((start =='')||(end =='')){
                callback() 
            }else{
                let start1 = moment(start).format("HH:mm")
                let end1 = moment(end).format("HH:mm")
                if(start1 == end1 || moment(start).isBefore(end)){
                    callback() 
                }else{
                    callback("结束时间不得早于开始时间")
                }
            }
            console.log(moment(start.callReportStart).isBefore(end.callReportEnd))
            
        }else{
            callback("请选择拜访结束时间")  
        }
        
    }

 <Col md={4} xs={4} sm={4} >
                                    <FormItemPro errorMsg={getFieldError('callReportStart')}>
                                        <Label className="label-basic label-required">
                                            拜访开始时间
                                        </Label>
                                        <Timepicker className="timewid" style={{ width: '60%' }}
                                        {...getFieldProps('callReportStart', {
                                            
                                            initialValue: (JSON.stringify(visitInfoData)=="{}")||(visitInfoData.callReportStart=='')||!visitInfoData.callReportStart?'':moment(visitInfoData.callReportStart),
                                            rules: [{
                                                required: true, message: <span>请选择拜访开始时间</span>,
                                            }]
                                        }
                                        )}
                                        // defaultValue={visitInfoData=={}||visitInfoData.callReportStart==''?'':moment(visitInfoData.callReportStart)}
                                        // getPopupContainer={this.getPopupContainer} 
                                        placeholder="选择开始时间" 
                                        allowEmpty
                                        // use12Hours
                                        // format={dateFormat}
                                        // onChange={this.onChange.bind(this)} 
                                        showSecond={false}
                                        onClose={this.distime.bind(this)}
                                        // onChange={this.distime.bind(this)}
                                        />
                                    </FormItemPro>
                                </Col>
                                <Col md={4} xs={4} sm={4} >
                                    <FormItemPro errorMsg={getFieldError('callReportEnd')}>
                                        <Label className="label-basic label-required">
                                            拜访结束时间
                                        </Label>
                                        <Timepicker className="timewid" style={{ width: '60%' }}
                                        {...getFieldProps('callReportEnd', {
                                            initialValue: (JSON.stringify(visitInfoData)=="{}")||(visitInfoData.callReportEnd=='')||!visitInfoData.callReportEnd?'':moment(visitInfoData.callReportEnd),
                                            rules: [{
                                                // required: true, message: <span>请选择拜访结束时间</span>,
                                                validator:this.timesend.bind(this)
                                            }]
                                        }
                                        )}
                                        // defaultValue={visitInfoData=={}||visitInfoData.callReportEnd==''?'':moment(visitInfoData.callReportEnd)}
                                        // getPopupContainer={this.getPopupContainer} 
                                        placeholder="选择结束时间" 
                                        disabledHours={()=>this.flitimehour()}
                                        // disabledMinutes={()=>this.flitimemoment()}
                                        allowEmpty
                                        // use12Hours
                                        // format={dateFormat}
                                        showSecond={false}
                                        // onChange={this.endtimeonChange.bind(this)} 
                                        />
                                    </FormItemPro>
                                </Col>

### 2、报错信息
getFieldsValue获取的开始时间和结束时间的值一样，我选的是两个不一样的

## 期望的行为:
在线等，很急

**Comment by skylerswy** [comment]
```
  timesend = (rule, value, callback) =>{
        console.log(value)
        if(value){
            let time = this.props.form.getFieldsValue(['callReportStart','callReportEnd'])
            console.log(time)
            let start = time.callReportStart
            let end = time.callReportEnd
            console.log(start)
            console.log(end)
            if((start =='')||(end =='')){
                callback() 
            }else{
                let start1 = moment(start).format("HH:mm")
                let end1 = moment(end).format("HH:mm")
                if(start1 == end1 || moment(start).isBefore(end)){
                    callback() 
                }else{
                    callback("结束时间不得早于开始时间")
                }
            }
            console.log(moment(start.callReportStart).isBefore(end.callReportEnd))
            
        }else{
            callback("请选择拜访结束时间")  
        }
        
    }
```

**Comment by skylerswy** [comment]
```
  <Col md={4} xs={4} sm={4} >
                                    <FormItemPro errorMsg={getFieldError('callReportStart')}>
                                        <Label className="label-basic label-required">
                                            拜访开始时间
                                        </Label>
                                        <Timepicker className="timewid" style={{ width: '60%' }}
                                        {...getFieldProps('callReportStart', {
                                            
                                            initialValue: (JSON.stringify(visitInfoData)=="{}")||(visitInfoData.callReportStart=='')||!visitInfoData.callReportStart?'':moment(visitInfoData.callReportStart),
                                            rules: [{
                                                required: true, message: <span>请选择拜访开始时间</span>,
                                            }]
                                        }
                                        )}
                                        // defaultValue={visitInfoData=={}||visitInfoData.callReportStart==''?'':moment(visitInfoData.callReportStart)}
                                        // getPopupContainer={this.getPopupContainer} 
                                        placeholder="选择开始时间" 
                                        allowEmpty
                                        // use12Hours
                                        // format={dateFormat}
                                        // onChange={this.onChange.bind(this)} 
                                        showSecond={false}
                                        onClose={this.distime.bind(this)}
                                        // onChange={this.distime.bind(this)}
                                        />
                                    </FormItemPro>
                                </Col>
                                <Col md={4} xs={4} sm={4} >
                                    <FormItemPro errorMsg={getFieldError('callReportEnd')}>
                                        <Label className="label-basic label-required">
                                            拜访结束时间
                                        </Label>
                                        <Timepicker className="timewid" style={{ width: '60%' }}
                                        {...getFieldProps('callReportEnd', {
                                            initialValue: (JSON.stringify(visitInfoData)=="{}")||(visitInfoData.callReportEnd=='')||!visitInfoData.callReportEnd?'':moment(visitInfoData.callReportEnd),
                                            rules: [{
                                                // required: true, message: <span>请选择拜访结束时间</span>,
                                                validator:this.timesend.bind(this)
                                            }]
                                        }
                                        )}
                                        // defaultValue={visitInfoData=={}||visitInfoData.callReportEnd==''?'':moment(visitInfoData.callReportEnd)}
                                        // getPopupContainer={this.getPopupContainer} 
                                        placeholder="选择结束时间" 
                                        disabledHours={()=>this.flitimehour()}
                                        // disabledMinutes={()=>this.flitimemoment()}
                                        allowEmpty
                                        // use12Hours
                                        // format={dateFormat}
                                        showSecond={false}
                                        // onChange={this.endtimeonChange.bind(this)} 
                                        />
                                    </FormItemPro>
                                </Col>
```

**Comment by lucian55** [comment]
已解决
