### ISSUE TITLE
MonthPicker 在form中通过form.reset方法无法将MonthPicker组件的input值清空

### ISSUE THREAD

**Issue by gebinbin** [iuap-design/tinper-bee#410]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 若使用单个组件，请标明该组件版本号： ^2.0.34

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：windows

- 所使用的浏览器：谷歌

## 描述这个问题:
MonthPicker 在form中通过form.reset方法无法将MonthPicker组件的input值清空.
并且使用form.setFeildValue也会报错

### 1、代码

import React, {Component} from 'react'
import {actions} from 'mirrorx';
import { InputGroup, Upload, Icon, Button, Label, CitySelect, Rate, InputNumber, Slider, Switch, Checkbox, Radio, Select,  Col,Row , FormControl, Form } from 'tinper-bee';
// import Fomula from 'components/Fomula';
import DatePicker from 'bee-datepicker';

import {deepClone, success, Error,getPageParam} from "utils";

import './index.less';
const { YearPicker } = DatePicker;
const { MonthPicker } = DatePicker;
import moment from 'moment';
const FormItem = Form.FormItem;
const Option = Select.Option;
const CheckboxGroup = Checkbox.CheckboxGroup;

let Index = Form.createForm()(class IndexView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            delModalVisible: false,
            dataVal: ''
        }
    }

    reset = () => {
        let _this = this;
        // this.setState({dataVal: ''})
        this.props.form.resetFields();
        // this.props.form.setFieldsValue('period', '2000-1');//这行报错
    }

    render() {
        const { getFieldProps, getFieldError } = this.props.form;
        const { rowData } = this.props;
        const self = this;
        const _this = this;
        
        return (
            <div className="master-detail-one">
            
            <Form className='demo4'>
                    <FormItem>
                        <Label><Icon type="uf-mi" className='mast'></Icon>年月</Label>
                        <MonthPicker
                            // ref={(el)}
                            ref="mp"
                            format="YYYY-MM"
                            onSelect={this.onSelect}
                            onChange={this.onChange}
                            defaultValue={moment()}
                            showClose={false}
                            {
                            ...getFieldProps('period', {
                                initialValue: moment(),
                            }
                            )}
                            // value={this.state.dataVal}
                        />
                        <span className='error'>
                            {getFieldError('phone')}
                        </span>
                    </FormItem>
                    <FormItem style={{'paddingLeft':'106px'}}>
                        <Button shape="border" className="reset" onClick={this.reset} style={{"marginRight":"8px"}}>清空</Button>
                    </FormItem>
                </Form>
            </div>

        )

    }
})

export default Index;

**Comment by lucian55** [comment]
贴一下使用代码

**Comment by gebinbin** [comment]
import React, {Component} from 'react'
import {actions} from 'mirrorx';
import { InputGroup, Upload, Icon, Button, Label, CitySelect, Rate, InputNumber, Slider, Switch, Checkbox, Radio, Select,  Col,Row , FormControl, Form } from 'tinper-bee';
// import Fomula from 'components/Fomula';
import DatePicker from 'bee-datepicker';

import {deepClone, success, Error,getPageParam} from "utils";

import './index.less';
const { YearPicker } = DatePicker;
const { MonthPicker } = DatePicker;
import moment from 'moment';
const FormItem = Form.FormItem;
const Option = Select.Option;
const CheckboxGroup = Checkbox.CheckboxGroup;

let Index = Form.createForm()(class IndexView extends Component {
    constructor(props) {
        super(props);
        this.state = {
            delModalVisible: false,
            dataVal: ''
        }
    }

    reset = () => {
        let _this = this;
        // this.setState({dataVal: ''})
        this.props.form.resetFields();
        // this.props.form.setFieldsValue('period', '2000-1');//这行报错
    }

    render() {
        const { getFieldProps, getFieldError } = this.props.form;
        const { rowData } = this.props;
        const self = this;
        const _this = this;
        
        return (
            <div className="master-detail-one">
            
            <Form className='demo4'>
                    <FormItem>
                        <Label><Icon type="uf-mi" className='mast'></Icon>年月</Label>
                        <MonthPicker
                            // ref={(el)}
                            ref="mp"
                            format="YYYY-MM"
                            onSelect={this.onSelect}
                            onChange={this.onChange}
                            defaultValue={moment()}
                            showClose={false}
                            {
                            ...getFieldProps('period', {
                                initialValue: moment(),
                            }
                            )}
                            // value={this.state.dataVal}
                        />
                        <span className='error'>
                            {getFieldError('phone')}
                        </span>
                    </FormItem>
                    <FormItem style={{'paddingLeft':'106px'}}>
                        <Button shape="border" className="reset" onClick={this.reset} style={{"marginRight":"8px"}}>清空</Button>
                    </FormItem>
                </Form>
            </div>

        )

    }
})

export default Index;

**Comment by lucian55** [comment]
使用错误：
- this.props.form.resetFields(); 是将组件的值设置为初始值，也就是 initialValue的值，并不一定能清空。 
> 解决方案：你代码中可以将 initialValue 设置为 null 
- this.props.form.setFieldsValue('period', '2000-1')   ^2.0.34版本的MonthPicker值只可以设置为moment对象，你这里将字符串赋值给MonthPicker一定会报错。   
> 解决方案：第一种：给MonthPicker赋moment对象的值。  第二种：升级最新版 bee-datepicker@2.2.14，此版本可支持赋string类型的值
