### ISSUE TITLE
钉耙的（table组件）的（全表格编辑）是否能提供保存时候的非空校验。自己写的校验无效。。。

### ISSUE THREAD

**Issue by skylerswy** [iuap-design/tinper-bee#411]
## 环境及版本信息

- `tinper-bee` 版本号:  
^2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
win10

- 所使用的浏览器：
google

## 您所在的领域、行业或项目组：
香港海外部，苏婉玉

## 描述这个问题:
钉耙的（table组件）的（全表格编辑）是否能提供保存时候的非空校验。（参照默认值为空，不进行选择，直接保存）。

我在钉耙“全表格编辑”组件的基础上，自己加了一下表单的校验方法，但是在refvalue=‘’的情况下，err=null，无法正常校验（可能我写方法的不对？。。但是其他的表单校验没问题，就这个表格的校验不出来，不知道哪里写错了）

###  {/* <FormItemPro> */}
                <RefDropDown 
                    {...getFieldProps('refValue', {
                        initialValue: JSON.stringify({ 'refname': refname, 'refpk': refpk })||'',
                        rules: [{
                            required: true, message: (
                                <Tooltip
                                inverse
                                className="u-editable-table-tp"
                                placement="bottom"
                                overlay={
                                  <div className="tp-content">
                                    {"请选择" + this.props.colName}
                                  </div>
                                }
                              >
                                <Icon className="uf-exc-t required-icon" />
                              </Tooltip>
                            )
                        }]
                    })}
                    refCode = {refCode}
                    // multiple = {true}
                    onSelectorChange={this.handleSelect}
                />
                <span className="error">{getFieldError("refValue")}</span>
                {/* </FormItemPro> */}

### 2、报错信息
![image](https://user-images.githubusercontent.com/37760050/68557148-ed757400-046f-11ea-8ca0-3f67d477e0d3.png)
![image](https://user-images.githubusercontent.com/37760050/68557164-f9613600-046f-11ea-8616-fb915cc97ef7.png)
![image](https://user-images.githubusercontent.com/37760050/68557397-a3d95900-0470-11ea-8973-2200b98ba05c.png)

## 期望的行为:
能不能提供一个全表格编辑后的提交校验方法。。。谢谢

**Comment by yangchch6** [comment]
写的校验规则不对，参照的非空校验可以参考[参照示例](http://bee.tinper.org/tinper-acs/ref-tree)。
要定义校验的正则，即 pattern，大概代码如下：
```
{...getFieldProps('tree3', {
      initialValue:value,
      rules: [{
             message: '请选择', pattern: /[^{"refname":"","refpk":""}|{"refpk":"","refname":""}]/
      }]
})}
```

**Comment by yangchch6** [comment]
按上面回复的方法修改一下，还不行的话通知我

**Comment by skylerswy** [comment]
可以了谢谢
