### ISSUE TITLE
在表单中使用AutoComplete组件，并且配置了校验规则时，遇到该组件失去焦点，值被清空的问题。

### ISSUE THREAD

**Issue by wcheng-victor** [iuap-design/tinper-bee#412]
## 环境及版本信息

- `tinper-bee` 版本号:  2.0.11

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：windows 10

- 所使用的浏览器：chrome 78.0.3904.87

### 代码
在表单中使用AutoComplete组件，代码如下：
`					<FormItem label={"账号"} required>`
`                        <AutoComplete`
`                            placeholder='账号'`
`                            className={'acct-autocomplete'}`
`                            disabled={typeof btnFlag !== 'undefined' && btnFlag == 2}`
`                            options={options}`
`                            {...getFieldProps('acctno', {`
`                                initialValue: (typeof rowData === 'undefined' || typeof rowData.acctno === 'undefined') ? "" : String(rowData.acctno),`
`                                validateTrigger: 'onBlur',`
`                                rules: [`
`                                    // {`
`                                    //     validator: (rule, value, callback) => {`
`                                    //         console.log(callback);`
`                                    //     }`
`                                    // }`
`                                    { required: true, message: '请输入账号'},`
`                                    // {max: 200, message: "超出最大长度"}`
`                                ],`
`                            })}`
`                        />`
`                        <FormError errorMsg={getFieldError('acctno')}/>`
`                    </FormItem>`

## 当前的行为：效果（可截图说明）及动作描述
进行录入的时候，如果输入随机内容，并不从下拉框内选择的话，失去焦点时会清空输入框的值。
![1573441226(1)](https://user-images.githubusercontent.com/13311024/68558157-367af780-0473-11ea-9c19-e343805c4886.png)
![1573441247(1)](https://user-images.githubusercontent.com/13311024/68558159-38dd5180-0473-11ea-8cd3-cdf519876368.png)
如果从下拉框内选择内容，失去焦点时不会清空输入框内的值，但仍然通不过非空校验，此时用getFieldValue方法来获取此表单项的值，返回的是 undefined.
![1573441283(1)](https://user-images.githubusercontent.com/13311024/68558223-7e018380-0473-11ea-9886-fcb4c004c5b9.png)
![1573441296(1)](https://user-images.githubusercontent.com/13311024/68558225-80fc7400-0473-11ea-942c-180b78f4c205.png)

**Comment by lucian55** [comment]
bee-autocomplete@2.0.4 已解决
