### ISSUE TITLE
bee-datepicker 无值时 today classname 问题

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#413]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：bee-datepicker@2.2.7

- 当前项目中`react`的版本号：16.9.0

- 所使用的操作系统：mac

- 所使用的浏览器：chrome 78

## 描述这个问题:

当日期组件无值时，打开日期面板，选中的今日的cell格 calssname是 ‘rc-calendar-today rc-calendar-selected-day’ 导致今日样式变为选中样式 
看下了datetbody.jsx 好像是这里处理了 加上了selectedClass 
### 2、报错信息

![image](https://user-images.githubusercontent.com/16048628/68635140-94badf80-0532-11ea-812f-59280e6d580f.png)

**Comment by lucian55** [comment]
不支持。没有值的时候所有日期时间选择组件面板默认选中当前日期时间
