### ISSUE TITLE
InputNumber组件不支持size属性

### ISSUE THREAD

**Issue by lilicoder** [iuap-design/tinper-bee#414]
## 环境及版本信息

- `tinper-bee` 版本号:  
 2.2.1

- bee-input-number：
 2.1.4 

- 当前项目中`react`的版本号：
16.10.2

- 所使用的操作系统：
 Windows

- 所使用的浏览器：
Google Chrome 
版本 78.0.3904.97（正式版本） （64 位）

## 您所在的领域、行业或项目组：
离散制造与U9开发部 梁莉莉

### 1、代码
![image](https://user-images.githubusercontent.com/24731304/68644375-c4c4ab80-054f-11ea-9861-cf0c5975020f.png)

### 2、报错信息
无
## 当前的行为：效果（可截图说明）及动作描述
不支持size属性

## 期望的行为:
添加size属性 支持size=”sm“等，与Input相关组件保持一致

**Comment by SLA0630** [comment]
目前已经更新，bee-input-number@2.2.2 版本已经支持该属性。
