### ISSUE TITLE
树表参照，左侧的树添加默认值控制参数

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#415]
## 环境及版本信息

- `tinper-bee` 版本号:  
  "tinper-bee": "2.2.3",

- 若使用单个组件，请标明该组件版本号：
  "ref-tree-table":"2.1.1"

- 当前项目中`react`的版本号：
  "react":"16.6.3"

- 所使用的操作系统：
  win7

- 所使用的浏览器：
  Google Chrome 已是最新版本
  版本 78.0.3904.97（正式版本） （64 位）

## 您所在的领域、行业或项目组：
  用友金融-非银产品部-杨志会

## 描述这个问题:
  树表参照希望通过传递参数给左侧的树设置默认选中值

## 期望的行为:
  树表参照希望通过传递参数给左侧的树设置默认选中值

**Comment by XYooo** [comment]
ref-tree-table@2.1.3
checkedTreeArray | `array` | [] |  左树默认选中的节点，每项至少包含valueField指定字段，比如valueFiled='refpk',checedTreeArray=[{refpk:'yonyou'},...]
