### ISSUE TITLE
多选表格=>单个数据的操作点击事件出现鼠标移动即可出发改事件输出值

### ISSUE THREAD

**Issue by Chestnutlili** [iuap-design/tinper-bee#416]
## 环境及版本信息
- `tinper-bee` 版本号:  

 "tinper-bee": "^2.2.0",

- 当前项目中`react`的版本号：

 "react": "^16.7.0",
- 所使用的操作系统：

windows 10 
- 所使用的浏览器：

谷歌
## 您所在的领域、行业或项目组：

用友-美丽田园项目组-吴梦莉
## 描述这个问题:
在具有多选功能的表格MultiSelectTable 中 给予每行数据有单个删除操作（通过点击事件触发单个删除事件，目前只是让其输出单个点击的元素内容），但是鼠标一接触表格，不分是哪一行数据都会触发该点击事件
### 1、代码

1.每行操作===删除事件
![image](https://user-images.githubusercontent.com/44279959/68652000-8c2ecd00-0563-11ea-8b3c-4df391704fd0.png)
2.删除事件输出
![image](https://user-images.githubusercontent.com/44279959/68652122-c304e300-0563-11ea-9a2c-a015fba635ad.png)
3.表
![image](https://user-images.githubusercontent.com/44279959/68652186-e334a200-0563-11ea-9992-55fc10ae9b7a.png)

### 2、报错信息

不点击该行 鼠标一碰表就会输出
![image](https://user-images.githubusercontent.com/44279959/68652249-ffd0da00-0563-11ea-944b-15b58b6965d9.png)
4.鼠标悬停所有数据行都会有悬停效果样式（这个可能是所有问题出现的原因）
![image](https://user-images.githubusercontent.com/44279959/68652302-242cb680-0564-11ea-9b27-25eb844e6ef8.png)

## 期望的行为:

希望鼠标悬停在哪一行哪一行才会出现悬停效果(即变成灰色的数据行)，触发该行的删除操作的点击事件才会输出该行的数据内容！
![image](https://user-images.githubusercontent.com/44279959/68652422-60f8ad80-0564-11ea-82bd-f1d58fddfb0f.png)

**Comment by Chestnutlili** [comment]
请大佬看到了 给予我宝贵建议  感恩

**Comment by yangchch6** [comment]
1、render 里面的监听事件，不能写立即执行函数，这是导致错误的原因。这是 React 规则。
2、表格每行应有唯一的 key 标识，要么data 里有 key，要么传 rowKey
