### ISSUE TITLE
拖拽后更新表头后，过滤列面板过滤列报错

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#417]
[##](url
[index.js.zip](https://github.com/iuap-design/tinper-bee/files/3845143/index.js.zip)

) 环境及版本信息

- `tinper-bee` 版本号:  2.1.5

- 若使用单个组件，请标明该组件版本号：2.1.5

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：mac os

- 所使用的浏览器：Chrome版本 78.0.3904.87（正式版本） （64 位）

### 1、代码

![image](https://user-images.githubusercontent.com/37610457/68654855-d3b85780-0569-11ea-9c1a-dd73777149f7.png)
![image](https://user-images.githubusercontent.com/37610457/68654892-e6cb2780-0569-11ea-812d-2e316c0da7ef.png)

### 2、报错信息

拖拽后更新表头后，过滤列面板过滤列报错
![image](https://user-images.githubusercontent.com/37610457/68654929-f9ddf780-0569-11ea-89ab-b5f7c9e2b76d.png)

## 当前的行为：效果（可截图说明）及动作描述

拖拽完后通过回调更新了表头后，点击列过滤面板，过滤列时报错

## 期望的行为:

拖拽完后通过回调更新了表头后，点击列过滤面板，可以准确过滤列

**Comment by yangchch6** [comment]
截图中涉及的变量太多，不太理解在做什么，可以把完整的 js 文件发过来，好复现问题。

**Comment by KaneSunk** [comment]
[index.js.zip](https://github.com/iuap-design/tinper-bee/files/3856654/index.js.zip)

**Comment by yangchch6** [comment]
本地没有复现，要不你直接提供一个可以调试的测试环境吧，或者远程调试下也行，友空间回复我一下

**Comment by KaneSunk** [comment]
现在这个问题本地又没有出现了，我们这边再看看，感谢老师支持，辛苦了
