### ISSUE TITLE
InputNumber组件设置min属性为3时，无法手动输入1、2开头的数字，例如10，11，22

### ISSUE THREAD

**Issue by houmengc** [iuap-design/tinper-bee#418]
![image](https://user-images.githubusercontent.com/37865137/68726908-dd8b9a80-05fd-11ea-8c07-1e7774462eb4.png)
![image](https://user-images.githubusercontent.com/37865137/68726953-01e77700-05fe-11ea-8884-1eda61279233.png)
InputNumber组件设置min属性为3时，无法手动输入1、2开头的数字，例如10，11，22

**Comment by lucian55** [comment]
bee-input-number@2.2.0 已解决
