### ISSUE TITLE
前端导出带小数的数字与excel中的不一致

### ISSUE THREAD

**Issue by crazy-lulu-edu** [iuap-design/tinper-bee#420]
## 环境及版本信息

- 若使用单个组件，请标明该组件版本号：
ac-grid

- 所使用的浏览器：
chrome

## 您所在的领域、行业或项目组：
金融项目

## 描述这个问题:
使用ac-grid的前端导出的时候小数位在导出后在打开的excel中默认不显示出来,需要在导出的excel上修改单元格格式才可以.
## 当前的行为：效果（可截图说明）及动作描述
![image](https://user-images.githubusercontent.com/30369310/68745693-1a718480-0632-11ea-89fd-3c9540315633.png)
![image](https://user-images.githubusercontent.com/30369310/68745709-22312900-0632-11ea-8316-bac6b16548f0.png)

## 期望的行为:
希望导出的excel与页面看到的数据一致.

**Comment by yangchch6** [comment]
需要看下 exportData 属性设置成啥了

**Comment by jonyshi** [comment]
excel 有科学计数法，所以导出需要设置本地excel即刻
