### ISSUE TITLE
对数字进行修改，输入位置会自动弹到最后一位

### ISSUE THREAD

**Issue by skylerswy** [iuap-design/tinper-bee#422]
## 环境及版本信息

- `tinper-bee` 版本号:  
^2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
win10

- 所使用的浏览器：
google

### 1、代码

![image](https://user-images.githubusercontent.com/37760050/68749838-de422200-0639-11ea-9133-a7578a7e9ade.png)
这个组件有问题，如果对已有数字进行修改，修改一次后，输入位置自动变成最后一位

**Comment by lucian55** [comment]
bee-input-number@2.2.4 已修改
