### ISSUE TITLE
分页器，跳转，一共几页等没出来

### ISSUE THREAD

**Issue by contryPresident** [iuap-design/tinper-bee#423]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

{
  "name": "fe",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "build": "cross-env NODE_ENV=production FE_ENV=release uba build",
    "package": "sh build-docker-image.sh",
    "mock": "json-server -p 8083 mock-data/db.json --watch",
    "start": "cross-env NODE_ENV=development FE_ENV=location  uba-server",
    "build:dev": "cross-env NODE_ENV=development FE_ENV=develop uba build",
    "build:private": "gulp && cross-env NODE_ENV=production FE_ENV=private uba build && node replace.js",
    "build:core": "cross-env NODE_ENV=production FE_ENV=core uba build && node replace.js",
    "build:pre": "cross-env NODE_ENV=production FE_ENV=pre uba build",
    "build:msplatform": "cross-env NODE_ENV=production FE_ENV=ms-platform uba build",
    "uba-dev": "uba server",
    "uba-build": "cross-env NODE_ENV=location uba build",
    "start:pri": "gulp && cross-env NODE_ENV=development FE_ENV=private TOTAL_ENV=location uba-server",
    "fix-memory-limit": "cross-env LIMIT=4096 increase-memory-limit"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@antv/g6": "^3.0.4",
    "@antv/hierarchy": "^0.5.0",
    "antd": "^2.11.1",
    "babel-plugin-dynamic-import-webpack": "^1.0.2",
    "babel-runtime": "6.x",
    "bee-button": "^1.0.6",
    "bee-button-group": "^2.0.1",
    "bee-checkbox": "^1.1.0",
    "bee-collapse": "^1.0.2",
    "bee-datepicker": "^1.0.35",
    "bee-dnd": "^1.0.0",
    "bee-drawer": "0.0.5",
    "bee-dropdown": "^2.0.10",
    "bee-form": "2.0.6",
    "bee-form-control": "^1.1.3",
    "bee-icon": "^1.0.5",
    "bee-input-group": "^1.0.7",
    "bee-input-number": "^2.1.4",
    "bee-label": "^1.0.0",
    "bee-layout": "^1.2.7",
    "bee-loading": "^1.0.3",
    "bee-loading-state": "^1.0.0",
    "bee-menu": "^0.1.9",
    "bee-message": "^1.0.13",
    "bee-modal": "^2.0.20",
    "bee-overlay": "^0.2.0",
    "bee-pagination": "^2.0.8",
    "bee-popconfirm": "^2.0.0",
    "bee-popover": "^1.0.6",
    "bee-radio": "^1.0.3",
    "bee-rate": "^1.0.3",
    "bee-search-panel": "^3.0.1",
    "bee-select": "^1.0.4",
    "bee-step": "^1.0.2",
    "bee-switch": "2.0.4",
    "bee-table": "^1.4.21",
    "bee-tabs": "^1.0.10",
    "bee-timeline": "0.0.4",
    "bee-timepicker": "1.0.1",
    "bee-tooltip": "^2.1.2",
    "bee-transfer": "^1.0.6",
    "bee-tree": "^1.1.4",
    "bee-tree-select": "^0.0.2",
    "classnames": "^2.2.5",
    "component-raf": "^1.2.0",
    "component-tween": "^1.2.0",
    "crypto-js": "^3.1.9-1",
    "d3": "4.10.0",
    "dagre": "^0.8.4",
    "echarts": "^3.6.2",
    "echarts-for-react": "1.1.6",
    "gg-editor": "2.0.4",
    "immutable": "^4.0.0-rc.12",
    "js-base64": "^2.1.9",
    "js-cookie": "^2.2.0",
    "marked": "^0.3.6",
    "mirrorx": "^0.2.10",
    "moment": "^2.21.0",
    "postcss-flexbugs-fixes": "^4.1.0",
    "qs": "^6.4.0",
    "query-string": "^5.0.1",
    "rc-calendar": "^8.4.7",
    "rc-checkbox": "^1.5.0",
    "rc-slider": "^6.2.0",
    "rc-tabs": "^7.1.1",
    "rc-tooltip": "^3.4.2",
    "react-addons-update": "^15.6.2",
    "react-cookie": "^2.1.2",
    "react-custom-scrollbars": "^4.2.1",
    "react-gojs": "^4.1.0",
    "react-json-editor-ajrm": "^2.5.9",
    "react-loadable": "^5.5.0",
    "react-swipe": "^5.0.6",
    "yyuap-ref": "^1.1.2"
  },
  "peerDependencies": {
    "prop-types": "^15.6.0"
  },
  "devDependencies": {
    "argv": "0.0.2",
    "autoprefixer": "^7.1.6",
    "babel-core": "6.26.0",
    "babel-eslint": "7.x",
    "babel-loader": "^7.1.2",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-plugin-transform-object-rest-spread": "^6.23.0",
    "babel-plugin-transform-runtime": "6.x",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "browser-sync": "^2.18.7",
    "browser-sync-webpack-plugin": "^1.1.4",
    "clean-webpack-plugin": "^0.1.17",
    "commitizen": "^2.9.3",
    "connect-history-api-fallback": "^1.3.0",
    "conventional-changelog-cli": "1.x",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.0.0",
    "css-loader": "^0.28.7",
    "cssnano": "^4.0.0-rc.2",
    "cz-conventional-changelog": "^1.2.0",
    "d3-cloud": "^1.2.4",
    "ejs-compiled-loader": "^1.1.0",
    "ejs-loader": "^0.3.0",
    "es6-promise": "^4.0.5",
    "eslint": "^4.0.0",
    "eslint-config-airbnb": "^15.0.1",
    "eslint-plugin-import": "^2.5.0",
    "eslint-plugin-jsx-a11y": "^2.2.3",
    "eslint-plugin-react": "^7.1.0",
    "extract-text-webpack-plugin": "^2.1.2",
    "fast-uglifyjs-plugin": "^0.3.0",
    "file-loader": "^1.1.5",
    "glob": "^7.1.2",
    "gulp": "^3.9.1",
    "gulp-autoprefixer": "^3.1.1",
    "gulp-concat": "^2.6.1",
    "happypack": "^3.0.2",
    "html-webpack-plugin": "^2.30.1",
    "husky": "^0.12.0",
    "increase-memory-limit": "^1.0.7",
    "json-server": "^0.9.5",
    "less": "^2.7.3",
    "less-loader": "^4.0.5",
    "namespace-css-module-loader": "^0.4.1",
    "open-browser-webpack-plugin": "^0.0.5",
    "postcss-loader": "^2.0.8",
    "rc-tree-select": "^1.12.9",
    "style-loader": "^0.19.0",
    "uba": "2.2.3-bugfix",
    "uba-server": "1.0.0-bugfix",
    "url-loader": "^0.6.2",
    "validate-commit-msg": "2.x",
    "webpack-hot-middleware": "^2.21.0",
    "webpack-jarvis": "^0.2.2",
    "webpack-merge": "^4.1.1"
  }
}

- 所使用的操作系统：

- 所使用的浏览器：

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/22953889/68752005-89080f80-063d-11ea-9286-e8d57edf1846.png)

## 期望的行为:
![image](https://user-images.githubusercontent.com/22953889/68752048-a210c080-063d-11ea-81af-da99fc692cf7.png)

**Comment by yangchch6** [comment]
补充以下信息：
1、执行 npm list bee-pagination 后的截图
2、使用 Pagination 组件的代码

**Comment by contryPresident** [comment]
> 补充以下信息：
> 1、执行 npm list bee-pagination 后的截图
![image](https://user-images.githubusercontent.com/22953889/68764782-4d2d7400-0656-11ea-9035-56de62079e2c.png)

> 2、使用 Pagination 组件的代码
<Pagination
                    first
                    last
                    prev
                    next
                    maxButtons={5}
                    boundaryLinks
                    activePage={this.state.activePage}
                    onSelect={this.handleSelect.bind(this)}
                    onDataNumSelect={this.dataNumSelect}
                    showJump={true}
                    total={100}
                    dataNum={1}
                    />

**Comment by contryPresident** [comment]
<Pagination
                    first
                    last
                    prev
                    next
                    maxButtons={5}
                    boundaryLinks
                    activePage={this.state.activePage}
                    onSelect={this.handleSelect.bind(this)}
                    onDataNumSelect={this.dataNumSelect}
                    showJump={true}
                    total={100}
                    dataNum={1}
                    />

**Comment by yangchch6** [comment]
代码？，先升级至新版本试下吧，bee-pagination 最新版本是 v2.0.12 ，还不行的话通知我。

**Comment by contryPresident** [comment]
怎么升级？

**Comment by yangchch6** [comment]
@contryPresident  你先执行下 npm list bee-pagination，看下目前使用的具体版本号吧，因为你 package.json 里面，没有锁死固定版本，所以不确定具体使用的是哪一个。或者你也可以把 node_modules 和 package-lock.json 文件删掉，然后重新 npm install。
