### ISSUE TITLE
样例引入了相对路径js文件

### ISSUE THREAD

**Issue by contryPresident** [iuap-design/tinper-bee#424]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
样例中不该含有带路径js
### 1、代码

![image](https://user-images.githubusercontent.com/22953889/68752535-717d5680-063e-11ea-98f0-3709eb7e251a.png)

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/22953889/68752415-3ed35e00-063e-11ea-936c-f5e29f11bb1b.png)

**Comment by lucian55** [comment]
已解决
