### ISSUE TITLE
form表单的时间范围控件，手动输入一个值，页面变成空白页，报错

### ISSUE THREAD

**Issue by Zzhufeichao** [iuap-design/tinper-bee#428]
## 环境及版本信息

- `tinper-bee` 版本号:  "tinper-bee": "^2.2.0",

- 若使用单个组件，请标明该组件版本号： "bee-datepicker": "^2.2.17",

- 当前项目中`react`的版本号："react": "^16.8.6",

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
form表单的时间范围控件，手动输入一个值，页面变成空白页，报错
### 1、代码

![image](https://user-images.githubusercontent.com/30830131/68822843-f911a680-06cc-11ea-86bb-f2dd20131d19.png)
![image](https://user-images.githubusercontent.com/30830131/68822850-0333a500-06cd-11ea-951b-eac582eddc3b.png)
![image](https://user-images.githubusercontent.com/30830131/68822863-0af34980-06cd-11ea-9cad-a7477717e0af.png)

### 2、报错信息

![image](https://user-images.githubusercontent.com/30830131/68822879-15adde80-06cd-11ea-9297-e94c47b92ddd.png)

## 期望的行为:

希望手动输入，不会报错，清空手动输入的值，类似于单独的日期一样

**Comment by lucian55** [comment]
bee-datepicker@2.2.19  已解决
