### ISSUE TITLE
时间组件报错

### ISSUE THREAD

**Issue by Sunfloweres** [iuap-design/tinper-bee#429]
## 环境及版本信息

- `tinper-bee` 版本号:  

bee-timepicker 2.0.7
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

**Comment by lucian55** [comment]
bee-timepicker@2.0.8  已解决   适配传字符串的value
