### ISSUE TITLE
bee-pagination

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#430]
## bee-pagination 

- `bee-pagination` 版本号:  2.0.12

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：MAC

- 所使用的浏览器：Chrome

## 描述这个问题:
 react NODE_ENV=development 时 两个wraning
### 2、报错信息

![image](https://user-images.githubusercontent.com/20429458/68841248-3b53db80-06ff-11ea-86cb-bce4106115c6.png)
![image](https://user-images.githubusercontent.com/20429458/68841480-aa313480-06ff-11ea-9014-c7843f471095.png)

**Comment by yangchch6** [comment]
发了新包 bee-pagination@2.0.13
