### ISSUE TITLE
bee-modal 

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#432]
## bee-modal@2.1.2 react NODE_ENV=development 环境下

- `bee-moda` 版本号:  2.1.2

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：Mac

- 所使用的浏览器：

## 描述这个问题:
react调试环境下回爆出一个warning
![image](https://user-images.githubusercontent.com/20429458/68910559-2aea4200-078d-11ea-8584-c17642d665f2.png)
看了一下代码是因为 Modal.js中 bounds参数的PropTypes校验 将PropTypes.object写成了PropTypes.Object
![image](https://user-images.githubusercontent.com/20429458/68910667-92a08d00-078d-11ea-98db-bbc7fa71fbb3.png)

**Comment by yangchch6** [comment]
发了新包 tinper-bee@2.3.0( bee-modal@2.1.3 )
