### ISSUE TITLE
子表参照字段模糊查询时，会被外层容器遮挡，显示不全

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#433]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.1

- 组件版本号：”ref-tree“：”2.0.2“；"bee-complex-grid": "2.0.21"

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：chrome

## 描述这个问题: 嵌入到表格内的输入框，在模糊查询时出现的下拉框会被表格体遮挡

![image](https://user-images.githubusercontent.com/22900344/68930701-e6c96280-07c9-11ea-9d17-beec7631374c.png)

**Comment by yangchch6** [comment]
可能是参照版本老，下拉面板的实现方式不一样导致的。这个问题定位的时候，发现下拉面板的 dom 元素放在了 `<td>` 标签中，才导致面板被遮盖。正常的渲染方式，应该像 Select 下拉框一样，放在 body 标签下。 @XYooo

![image](https://user-images.githubusercontent.com/33412781/69213688-c7eb1780-0b9f-11ea-8dab-7c32b0d48fd9.png)

**Comment by MINGXINICE** [comment]
这个问题在我们官方的案例中也存在，我当前用的参照版本是"pap-refer": "^1.1.0-beta.3"。
![WechatIMG670](https://user-images.githubusercontent.com/22900344/69218331-75aff380-0bab-11ea-9add-cfe16a5ba123.png)

**Comment by MINGXINICE** [comment]
这是我们项目中的截图
![image](https://user-images.githubusercontent.com/22900344/69220708-975fa980-0bb0-11ea-93a8-1a87dc7512f1.png)

**Comment by XYooo** [comment]
.ref-input-wrap-filter-panel{position:fixed} 可以决绝这个问题

**Comment by MINGXINICE** [comment]
> .ref-input-wrap-filter-panel{position:fixed} 可以决绝这个问题
fiexd之后，它的宽度会基于视口，而不是所在的参照宽度
![image](https://user-images.githubusercontent.com/22900344/69291977-c1ac7800-0c3f-11ea-987f-4a2b76872606.png)

**Comment by MINGXINICE** [comment]
fiexd之后，它的宽度会基于视口，而不是所在的参照宽度

![image](https://user-images.githubusercontent.com/22900344/69292327-cde50500-0c40-11ea-937b-8fd4ada194bf.png)

**Comment by XYooo** [comment]
建议使用ref-tree的2.0.15版本，因为2.0.15版本的参照过滤面板添加max-width：200px,或者你本地覆盖样式
![image](https://user-images.githubusercontent.com/21334863/69517711-702e2100-0f90-11ea-9549-2e4c6b68d12c.png)
