### ISSUE TITLE
子表中的必输项校验已去掉，并且达到不校验效果，但必须输提醒标识符仍存在。

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#434]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.1

- 若使用单个组件，请标明该组件版本号："pap-refer": "^1.1.0-beta.3"

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：Chrome

## 描述这个问题: 子表中的必输项校验已去掉，并且达到不校验效果，但必须输提醒标识符仍存在。

![image](https://user-images.githubusercontent.com/22900344/68931448-82a79e00-07cb-11ea-85cb-a6d9797f1f9b.png)

**Comment by lucian55** [comment]
贴代码看一下

**Comment by MINGXINICE** [comment]
非组件问题，已解决
