### ISSUE TITLE
需求：table的列操作过滤需要指定列禁止隐藏的功能。

### ISSUE THREAD

**Issue by MurphyPF** [iuap-design/tinper-bee#435]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.2

- 若使用单个组件，请标明该组件版本号：
bee-table：2.2.14

- 当前项目中`react`的版本号：
16.11.0

- 所使用的操作系统：
Windows

- 所使用的浏览器：
chrome: 77.0.3865.75（正式版本） （64 位）

## 您所在的领域、行业或项目组：
制造中台与NCC开发部-林鹏飞

## 描述这个问题:
  表格行编辑时，有部分列属于必填项，希望在列过滤面板中，指定这些列是不允许隐藏。
### 1、代码
![image](https://user-images.githubusercontent.com/32762619/69041782-08755480-0a2b-11ea-9149-cb8134d0b002.png)
通过重写afterFilter可以实现列隐藏操作失效，但如上图所示，列显示与过滤面板选中关系不对应。
    afterFilter = (optData, columns) => {
        if (optData.alwaysShow) {
            optData.ifshow = true;
            optData.isShow = true;
        }
    }
其中alwaysShow是自定义属性。
## 期望的行为:
希望column里面有个属性，可以指定列在过滤面板中是否禁用。如下图‘操作’列效果。
![image](https://user-images.githubusercontent.com/32762619/69043238-a9fda580-0a2d-11ea-9740-48ea04da1d44.png)

**Comment by yangchch6** [comment]
发了新包 bee-table@2.2.18，必输列禁止设置隐藏。使用方法：给 column 设置 ```required: true```
