### ISSUE TITLE
图片上传无法获取fileList

### ISSUE THREAD

**Issue by Jacksonhan** [iuap-design/tinper-bee#436]
## 环境及版本信息

- `tinper-bee` 版本号:  
 2.0.10

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：
windows

- 所使用的浏览器：
谷歌

## 您所在的领域、行业或项目组：
能源

### 1、代码
图片上传的时候  使用beforeUpload方法 无法返回fileList已上传列表

## 当前的行为：效果（可截图说明）及动作描述
只能返回file文件

## 期望的行为:
beforeUpload能获取到fileList

**Comment by lucian55** [comment]
bee-upload@2.0.6 版本已解决
