### ISSUE TITLE
RangePicker支持在一个输入框显示开始和结束日期

### ISSUE THREAD

**Issue by wt07060210** [iuap-design/tinper-bee#44]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

当前RangePicker的开始日期和结束日期在俩个输入框中显示

#### 当前的行为:

当前RangePicker的开始日期和结束日期在俩个输入框中显示

#### 期望的行为:

RangePicker的开始日期和结束日期在同一个输入框中显示

**Comment by HuYuee** [comment]
v1.0.8已支持改功能！可以参见[在线示例](https://codesandbox.io/s/18myyq6wwj)
