### ISSUE TITLE
AC-Grid组件添加 showHeaderMenu={false} 在safira浏览器会出现表头错位

### ISSUE THREAD

**Issue by lilicoder** [iuap-design/tinper-bee#441]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.1

- 若使用单个组件，请标明该组件版本号：
ac-grids@0.2.3 

- 当前项目中`react`的版本号：

- 所使用的操作系统：
Mac

- 所使用的浏览器：
Safari 浏览器版本 12.0.3 (14606.4.5)

## 您所在的领域、行业或项目组：
离散制造与U9开发部 梁莉莉

### 2、报错信息
![image](https://user-images.githubusercontent.com/24731304/69524807-d5d6d900-0fa1-11ea-9b93-d58c531c0e7c.png)

## 当前的行为：效果（可截图说明）及动作描述
添加 showHeaderMenu={false}会出现表头错位问题。
去除此参数则正常。默认此参数为true
 <AcGrids
        columnFilterAble={true}
        columns={props.columns}
        data={props.data}
        loading={props.loading}
        getSelectedDataFunc={props.getSelectedDataFunc}
        showPagination={!props.hidePagination}
        paginationObj={paginationObj}
        showHeaderMenu={false}
        multiSelect={props.multiSelect || false}
        draggable={false}
      />

## 期望的行为:
表头不错位

**Comment by yangchch6** [comment]
样式中的 height: 35px 在 safari 中没生效，可以通过 headerHeight={35} 设置表头行高。

**Comment by lilicoder** [comment]
![image](https://user-images.githubusercontent.com/24731304/69613197-1dc23280-106c-11ea-8aef-15385ff08a89.png)
![image](https://user-images.githubusercontent.com/24731304/69613210-26b30400-106c-11ea-8cc9-c5ebe0e5a228.png)
暂未生效......

**Comment by yangchch6** [comment]
应该是 ac-grids 里面没接收，我确认下

**Comment by lilicoder** [comment]
好嘞 辛苦

**Comment by yangchch6** [comment]
发了新包 ac-grids@0.2.4，解决添加 showHeaderMenu={false} 在 safari 浏览器出现表头错位的问题。
