### ISSUE TITLE
InputNumber超出js最大精度范围如何解决

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#442]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.3

- 组件版本号："bee-input-number": "^2.2.1",

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：Chrome

## 描述这个问题: 当数值超过16位数时，会丢失精度。

![image](https://user-images.githubusercontent.com/22900344/69715997-29812800-1144-11ea-97fe-88aa12540910.png)

**Comment by yangchch6** [comment]
1、建议给 InputNumber 设置 max 最大值，限制合理的输入范围
2、js 的 number 类型最大值是 9007 1992 5474 0992。JavaScript 权威指南 中说 js 数字 number 的最长长度是16位，如果数值类变量长度超过 16 位，可以采用 string 字符串拼接的方法传递变量。如果真实业务场景确实需要输入这么大的数字，可以使用 FormControl 组件或者向上封装一个支持字符串类型的数字框组件。
