### ISSUE TITLE
AcEditor readOnly no working

### ISSUE THREAD

**Issue by zhangcanfeng612** [iuap-design/tinper-bee#443]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.0.10

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
Mac

- 所使用的浏览器：
chrome 

## 描述这个问题:
AcEditor 设置readonly失效
### 1、组件相关代码
``
<AcEditor
   readOnly = {true}
/>
``

## 当前的行为：效果（可截图说明）及动作描述
添加了readOnly = {true}后仍然可以编辑

## 期望的行为:
添加了readOnly = {true}后不可编辑

**Comment by lucian55** [comment]
ac-editor@1.0.1  没有复现

**Comment by yangchch6** [comment]
发了新包 ac-editor@1.0.2
