### ISSUE TITLE
树形控件 Tree  TreeNode 使用  `disabled`  属性导致展开/收起节点功能失效

### ISSUE THREAD

**Issue by ALittleFox** [iuap-design/tinper-bee#444]
## 环境及版本信息

- 单个组件：
树形控件 Tree 版本：2.1.12

- 当前项目中`react`的版本号：
16.8.4

- 所使用的操作系统：
mac

- 所使用的浏览器：
chrome 版本 78.0.3904.108（正式版本） （64 位）

## 描述这个问题:
树形组件，TreeNode 使用  `disabled`  属性导致展开/收起节点功能失效

## 期望的行为:
TreeNode 使用  `disabled`  属性之后依旧可以展开/收起节点

**Comment by yangchch6** [comment]
![image](https://user-images.githubusercontent.com/33412781/69806056-fc547880-121c-11ea-87c5-ef70949e1dd7.png)

**Comment by ALittleFox** [comment]
close
