### ISSUE TITLE
弹窗拖拽问题

### ISSUE THREAD

**Issue by wanghobby** [iuap-design/tinper-bee#445]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.1.3

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

Mac

- 所使用的浏览器：

chorme

## 描述这个问题:

我在tinper上发现的，拖拽时，footer反应很慢，总是跟不上拖拽，不知道是不是问题，只是提个意见。

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/26377237/69925930-483d4100-14ed-11ea-9627-fbe0fe82de76.png)

**Comment by yangchch6** [comment]
问题已经修复，官网可见。
