### ISSUE TITLE
grid表格+嵌套，expandIconAsCell={true}时，手动页面上调整每列宽度，被调整的总是前一列

### ISSUE THREAD

**Issue by skylerswy** [iuap-design/tinper-bee#446]
## 环境及版本信息

- `tinper-bee` 版本号:  
^2.1.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
win10

- 所使用的浏览器：
google
### 1、组件相关代码
用的是grid表格，并且有嵌套表格，当添加属性expandIconAsCell={true}，让展开icon单独一列的时候，在页面上手动修改每列宽度时，被调整的总是前一列
不添加那个属性时，则正常

代码粘贴区域：
### <Grid
                                    ref={(grid) => { this.grid = grid;}}
                                    columns={grid1_columns} 
                                    // columns={this.state.grid1_columns} 
                                    //noReplaceColumns={true}
                                    //拖拽改变顺序事件
                                    //onDragEnd={this.grid1_onDragEnd}
                                    //改变列宽事件
                                    //onDropBorder ={this.grid1_onDropBorder}
                                    //列过滤事件
                                    afterFilter={this.grid1_afterFilter}
                                    data={this.getdata(this.props.clientLists)} 
                                    multiSelect={multiObj}
                                    onRowClick={(record, index, event)=>_this.goClientInfo(record,"1")}
                                    sort = {sortObj}
                                    onRowDoubleClick={(record,index,indent)=>_this.gojump(record.id)}
                                    rowClassName={(record,index,indent)=>{
                                        if (record._checked) {
                                            return 'selected';
                                        } else {
                                            return '';
                                        }
                                    }}
                                    // getSelectedDataFunc={this.getSelectedDataFunc}
                                    expandedRowKeys={this.state.expandearr}
                                    paginationObj = {{verticalPosition:'none'}} 
                                    onExpand={this.getData}
                                    expandedRowRender={this.expandedRowRender}
                                    haveExpandIcon={this.haveExpandIcon}
                                    // expandIconAsCell={true}
                                    collapsedIcon={<Icon type='uf-anglearrowpointingtoright'/>}
                                    expandedIcon={<Icon type='uf-treearrow-down'/>}
                                />

**Comment by yangchch6** [comment]
已解决，升级 grid 组件即可
