### ISSUE TITLE
时间控件需要支持显示输入框右侧的图标按钮

### ISSUE THREAD

**Issue by liDan-Dan** [iuap-design/tinper-bee#447]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
TimePicker 的输入框可以显示和 DatePicker 一样的图标按钮
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
TimePicker 支持设置输入框中的图标，可以设置 inputIcon 属性，具体使用方法如下

![image](https://user-images.githubusercontent.com/33412781/70489359-87dfda80-1b36-11ea-84fd-4064e9f7a3b7.png)


生成的效果：

![image](https://user-images.githubusercontent.com/33412781/70489397-aa71f380-1b36-11ea-970a-65a08754d66b.png)
