### ISSUE TITLE
Form表单在Modal弹框第一次加载显示空数据

### ISSUE THREAD

**Issue by a582725606** [iuap-design/tinper-bee#448]
## 环境及版本信息

- `tinper-bee` 版本号:  

    1.5.0

- 若使用单个组件，请标明该组件版本号：

    bee-form    2.0.0

- 当前项目中`react`的版本号：

    16.3.2

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：

    云通信研发部    朱建

### 1、组件相关代码

我有个查询按钮，只有先点一次查询按钮，查询到所有数据，再选中某一条，点编辑，Modal是第一
次显示，问题现象：加了校验的输入框和下拉框没有数据；但是在这之后，就一直有数据了；如果不点查询按钮，直接选中某一条，点编辑，Modal第一次显示，是有数据的，之后也一直有数据；

代码粘贴区域：
```
/** 查询数据
 * @param {*} error 校验是否成功
 * @param {*} values 表单数据
 */
search = (error, values) => {
    const { pageIndex, pageSize} = this.props;
    this.props.form.validateFields(async (err, values) => {
        actions.agent.updateState({
            searchParam:values
        });
        //查询携带分页参数
        values.pageIndex = pageIndex || 0;
        values.pageSize = pageSize || 10;
        await actions.agent.loadAgentList(values);
    });
    //操作完毕之后清空选中项
    this.setState({ selectData:[] });
}
<!-- Modal内的FormControl输入框，省略Row、Col  -->
<FormItem>
    <Label>分机号</Label>
    <FormControl placeholder=""
        {
            ...getFieldProps('extensionNumber', {
                validateTrigger: 'onBlur',
                initialValue: selectShowData && selectShowData.extensionNumber || '',
                rules: [{
                    type: 'string',  required: false, max: 16, pattern: /^[0-9]*$/, message: '最多可输入16个整数',
                }]
            })
        }
    />
    <span className='error'>
        {getFieldError('extensionNumber')}
    </span>
</FormItem>
<FormItem>
    <Label>外呼出局号<span className="not-empty-tag">*</span></Label>
    <Select
        {
            ...getFieldProps('telephoneNumId', {
                initialValue: selectShowData && selectShowData.telephoneNumId || '',
                rules: [{
                    required: true,  message: '请选择',
                }]
            })
        }
    >
        {Children}
    </Select>
    <span className='error'>
        {getFieldError('telephoneNumId')}
    </span>
</FormItem>
```

### 2、报错信息

没有报错

## 当前的行为：效果（可截图说明）及动作描述

前提条件：输入框和下拉框加上校验规则，校验规则：rules数组里，至少有个空对象；
复现步骤：页面刷新，任意搜索条件，只要能查到数据，先点查询按钮，查询到所有数据，再选中某 一条，点编辑，Modal是第一次显示，问题现象：加了校验的输入框和下拉框没有数据；但是在这之后，就一直有数据了；
如果不点查询按钮，直接选中某一条点编辑，Modal第一次显示是有数据的，之后也一直有数据；输入框和下拉框加上校验规则，第一次不显示数据，只是第一次没有数据（显示空数据）；rules数组里有个空对象也不能显示，但是只是空数组就能显示，把校验规则rules去掉也可以；没有数据（显示空数据）：包括打断点，console.log打印，在控制台都是能看到有数据，数据都是正确的，但是输入框和下拉框内是空的，并且校验生效；

    刷新页面后，点击查询，选中某一条数据，再点编辑：
<img width="957" alt="操作过程" src="https://user-images.githubusercontent.com/55735670/70418504-7b0fa800-1a9e-11ea-97fa-4e77f993d058.png">

    Modal第一次显示，有问题的截图：
<img width="1059" alt="第一次没数据" src="https://user-images.githubusercontent.com/55735670/70417343-fcb20680-1a9b-11ea-8a2d-28766c9ebbbf.png">

    关闭后直接点编辑，没问题的截图：
<img width="1098" alt="第二次正常" src="https://user-images.githubusercontent.com/55735670/70417397-1c492f00-1a9c-11ea-9609-e4b1a8ea19a3.png">

## 期望的行为:

第一次也能正常显示数据

**Comment by lucian55** [comment]
1、获得数据时，在 componentWillMount获得
2、打印 selectShowData 看是否有值

**Comment by a582725606** [comment]
搜索条件和编辑弹框公用同一个form，this.props.form.validateFields方法在查询和编辑的时候都调用，影响了form表单存的值。我把编辑弹框拆成一个组件，搜索和编辑拆成两个form就好了

**Comment by lucian55** [comment]
可以可以。你那边已经接近的话，我关了哈
