### ISSUE TITLE
ref-multiple-table组件,选中以后,清空就直接报错.

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#450]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.3

- 若使用单个组件，请标明该组件版本号：
ref-multiple-table @2.0.5
ref-multiple-table @2.1.x

### 1、问题描述
版本为:2.0.5时  我选中一条数据以后,点击清空按钮,控制台报错:Cannot create property '_checked' on string '{'
报错代码位置如下:
checkedArray.forEach(function (item) {
      item._checked = true;
 });
checkedArray的值为  Array(31) ["{", """, "r", "e", "f", "n", "a", "m", "e", """, ":", """, "南", "京", "市", """, ",", """, "r", "e", "f", "p", "k", """, ":", """, "7", "9", "6", """, "}"]
版本为2.1.x 时:选中一条数据后,清空再选数据.一直显示的都是{refname}

**Comment by wangkimi** [comment]
这是render 里面的内容:
 let { showLoading, showModal, matchData} = this.state,
            { tableData, page } = this,
            props = this.props;
        let { value, required } = props;
        this.options = {
            title: '地址',
            miniSearch: true,
            multiple: false,
            valueField: "deliveryId",
            displayField: "{cityName}",
        }
        
        let childrenProps = Object.assign({}, this.options, {
            showModal: showModal,
            showLoading: showLoading,
            columnsData: this.columnsData,
            tableData: props.tableData || tableData || [],
            ...page,
            matchData,
            value,
            onChange: this.onSave,
            onCancel: this.onCancel,
        });

        return (
            <div className="refTable-addressLift">
                <div className="triangle-flag">
                    {required && <div className="triangle-redline"></div>}
                    <RefMultipleTableWithInput
                        {...props}
                        {...childrenProps}
                    />
                </div>
            </div>
        )
    }

这是使用的时候:
<RefTableAddressLift
                        {...this.props}
                        style={{ width: 140 }}
                        tableData={baAdresses}
                        displayField={"{cityName}"}
                        value={JSON.stringify({"refname": `${cityName}`,"refpk":`${deliveryId}`})}
                        // value={`{"refname": "${cityName}","refpk":"${deliveryId}"}`}
                    />

**Comment by XYooo** [comment]
建议将displayField不传入，看是否还会有同样的问题
