### ISSUE TITLE
pap树参照组件无法触发onSave事件

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#451]
## 环境及版本信息

- `tinper-bee` 版本号:  
   "tinper-bee": "^2.0.3",

- 若使用单个组件，请标明该组件版本号：
   "ref-tree": "^2.0.14",

- 当前项目中`react`的版本号：
   "react": "16.6.3",

- 所使用的操作系统：
   win7

- 所使用的浏览器：
   Google Chrome 已是最新版本
   版本 78.0.3904.108（正式版本） （64 位）
## 您所在的领域、行业或项目组：
   用友金融-非银产品部-杨志会

## 描述这个问题:
   树参照组件，选中数据点击确定时和模糊搜索选择数据时无法触发onSave事件，使得我无法获取选中的数据

### 1、组件相关代码

代码粘贴区域：
```
  <RefTreeWithInput
        emptyBut={true}
        strictMode={true}
        modalProps={{animation:false}}
        disabled={btnFlag === 2}
        placeholder={placeHolderTrue==1?'':`请选择${title}`}
        onSave= {() => {
          alert(1)
        }}
        //onChange={this.onChange}
        backdrop={false}
        title={title}
        param= {param}
        searchable= {true}
        multiple={false}
        checkStrictly={true}
        treeNodeDisabledFunc={this.treeNodeDisabledFunc}
        treeProps={{mustExpandable:true}}
        displayField='{refname}'
        valueField='refpk'
        refModelUrl= {{
          treeUrl: `/${refPath}/blobRefTree`, //树请求
        }}
        matchUrl={`/${refPath}/matchPKRefJSON`}
        filterUrl={`/${refPath}/filterRefJSON`}
        {...this.props}
      >
      </RefTreeWithInput>


```

**Comment by XYooo** [comment]
代码粘贴区域明显没有使用 参照，也没有传递onsave方法

**Comment by yangzhhc** [comment]
![image](https://user-images.githubusercontent.com/53893374/70673838-edf76980-1cbe-11ea-9ca8-06978267869d.png)
![image](https://user-images.githubusercontent.com/53893374/70673846-f94a9500-1cbe-11ea-999a-2257d2a9a4d3.png)
