### ISSUE TITLE
分页

### ISSUE THREAD

**Issue by xaioheiniu** [iuap-design/tinper-bee#452]
## 环境及版本信息

- `tinper-bee` 版本号:  

     tinper-bee: "^2.0.10",
- 若使用单个组件，请标明该组件版本号：

    bee-pagination: "^2.0.14",
- 当前项目中`react`的版本号：

    react: "16.6.3",
- 所使用的操作系统：

    Windows
- 所使用的浏览器：

    Chrome
## 您所在的领域、行业或项目组：

     华能置业
## 描述这个问题:
这个分页的当前条数一直都是25，但是内容是可以根据条数显示的。而且这个问题有的电脑有，有的电脑就没有这个问题
### 1、组件相关代码

代码粘贴区域：
 <PopupModal
                    editModelVisible={editModelVisible}
                    onCloseEdit={this.onCloseEdit}
                    currentIndex={selectedIndex}
                    btnFlag={btnFlag}
                    list={list}
                />

## 当前的行为：效果（可截图说明）及动作描述

https://user-images.githubusercontent.com/20662956/70587530-220e5400-1c05-11ea-8edb-c354bfb967c9.png

**Comment by yangchch6** [comment]
1、版本不明确，在有问题的电脑和没问题的电脑上分别执行 ```npm list bee-pagination``` ，看下结果，粘贴在此
2、“分页的当前条数一直都是25，但是内容是可以根据条数显示的”，这个问题不是很懂，意思是说点击分页的下拉框，切换不了页码（即条数）是吗？

![image](https://user-images.githubusercontent.com/33412781/70589335-6d773100-1c0a-11ea-829f-527f286d70ff.png)

3、截图说明的截图也打不开
4、粘代码，粘代码，粘代码！！！

**Comment by yangchch6** [comment]
问题描述不明确，先关了
