### ISSUE TITLE
Table的expandedRowRender属性不可用

### ISSUE THREAD

**Issue by gy190** [iuap-design/tinper-bee#457]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.1

- 若使用单个组件，请标明该组件版本号：
bee-table@2.2.1-beta.2

- 当前项目中`react`的版本号：
16.9.0

- 所使用的操作系统：
Mac

- 所使用的浏览器：
chrome@78.0.3904.108

## 您所在的领域、行业或项目组：
NCC 共享服务部 郭扬

## 描述这个问题:
Table的expandedRowRender  属性配置后没效果。只有展开图标，但点击图标后，没反应。
### 1、组件相关代码

代码粘贴区域：
```
<Table
                                columns={this.state.sscTaskHistoryTpl}
                                data={this.state.sscTaskHistoryData}
                                showRowNum={true}
                                expandIconAsCell={true}
                                expandedRowRender= {() => {
                                    return (
                                        <div>888</div>
                                    )
                                }}
                            />

```

## 期望的行为:
Table的expandedRowRender属性正常可用

**Comment by yangchch6** [comment]
我这边用 bee-table@2.2.1-beta.2 版本测试，使用上面提供代码，展开收起功能都能正常使用。请确认是否是 NCTable 的问题。

**Comment by gy190** [comment]
> 

>
