### ISSUE TITLE
table中单选功能 选中该行的时候 radio能同时被选中

### ISSUE THREAD

**Issue by huangdandan** [iuap-design/tinper-bee#458]
## 环境及版本信息

- `tinper-bee` 版本号:  

V2.2.2

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

react 16.6.3
- 所使用的操作系统：

- 所使用的浏览器：

chrome 版本 78.0.3904.108（正式版本） （64 位）
## 您所在的领域、行业或项目组：

互联网政务事业部--江西数字民政
## 描述这个问题:
table中单选功能
选中该行的时候 radio不能同时被选中，需要点击radio才可以选中该行
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/9463495/70717185-cb9a3600-1d28-11ea-891a-58fc99f96cd9.png)

## 期望的行为:

选中该行的时候 radio能同时被选中

**Comment by yangchch6** [comment]
已经添加上了，发了新版本 bee-table@2.2.23，升级组件即可

**Comment by huangdandan** [comment]
谢谢
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yangchch6"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月13日(星期五) 下午2:23
收件人:&nbsp;"iuap-design/tinper-bee"<tinper-bee@noreply.github.com&gt;;
抄送:&nbsp;"黄忒忒"<459659039@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iuap-design/tinper-bee] table中单选功能 选中该行的时候 radio能同时被选中 (#458)




已经添加上了，发了新版本 bee-table@2.2.23，升级组件即可
