### ISSUE TITLE
carousel在modal中不能正常使用

### ISSUE THREAD

**Issue by seavenpublic** [iuap-design/tinper-bee#459]
## 环境及版本信息
mac & chrome
- `tinper-bee` 版本号:  

tinper-bee@2.2.0

- 若使用单个组件，请标明该组件版本号：

bee-carousel@1.0.1

- 当前项目中`react`的版本号：

react@16.8.6
- 所使用的操作系统：

Mac
- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

畅捷通 T+ 陈文海
## 描述这个问题:
走马灯的效果在弹出的对话框层不能正确实现
如果在其他层中可以正常显示，比如drawer中。
### 1、组件相关代码

无须特殊代码，使用例子代码就可重现。
代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

pagination不显示，不能正常切换
## 期望的行为:

期望可以正常显示和交互。

**Comment by liushaozhen** [comment]
报错信息和期望行为是写错了么？

**Comment by seavenpublic** [comment]
没有报错，就是不能正常交互。写的很清楚啊。😄

**Comment by yangchch6** [comment]
可以使用这个组件：http://bee.tinper.org/tinper-bee/bee-carousel-figure
