### ISSUE TITLE
"bee-table": "2.2.11"   宽度不能自适应，一旦设置单元格内不换行，即使设置宽度也不起作用

### ISSUE THREAD

**Issue by eagleLiying** [iuap-design/tinper-bee#463]
![image](https://user-images.githubusercontent.com/39879019/70968385-0d81fe00-20d4-11ea-82ba-ffe8c8da2e5e.png)

**Comment by yangchch6** [comment]
设置单元格不换行，不需要加样式，直接设置 bodyDisplayInRow={false} 。

![image](https://user-images.githubusercontent.com/33412781/70971738-9735c980-20dc-11ea-8acb-d8dc3aa5af80.png)

**Comment by yangchch6** [comment]
问题先关了，有问题联系我或点 Reopen issue
