### ISSUE TITLE
modal里，modal.confirm的默认的“确定”和“取消”不支持多语。

### ISSUE THREAD

**Issue by wangxinyu666666** [iuap-design/tinper-bee#465]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.1

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
Windows

## 描述这个问题:
![image](https://user-images.githubusercontent.com/26834996/71064613-7340b980-21aa-11ea-84aa-f811fd82edf2.png)

**Comment by lucian55** [comment]
使用  okText  和 cancelText 即可
