### ISSUE TITLE
ac-grids 组件设置 rowSpan报错

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#467]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "~2.0.10"
- 若使用单个组件，请标明该组件版本号：

 'ac-grids' 
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome
## 描述这个问题:
使用ac-grids 组件设置 rowSpan报错，  基础组件中的Table没有问题

### 1、组件相关代码

代码粘贴区域：

![image](https://user-images.githubusercontent.com/14276812/71232226-0fde9500-232c-11ea-910c-da7debe8e749.png)
```
{
        title: "方案编号",
        dataIndex: "schemeName",
        key: "schemeName",
        width: 100,
        render: (value, row, index) => {
          const obj = {
            children: value,
            props: {}
          };
          if (index == 0) {
            obj.props.rowSpan = this.state.count;
          } else {
            obj.props.rowSpan = 0;
          }
          return obj;
        }
      },

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/14276812/71232241-1f5dde00-232c-11ea-9cc1-a73d6e40005a.png)

**Comment by lucian55** [comment]
ac-grids@0.2.9  已解决
