### ISSUE TITLE
bee-complex-grid,设置单选,选不中.选中没有加上 is-checked 的样式,其实是选中了,但是没有样式

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#468]
## 环境及版本信息
- `tinper-bee` 版本号:  
"tinper-bee": "2.2.3"
- 若使用单个组件，请标明该组件版本号：
 "bee-complex-grid": "2.0.20",
- 当前项目中`react`的版本号：
 "react": "16.8.2",

### 1、组件相关代码

 "react": "16.8.2",
代码粘贴区域：
```
<Grid
                                ref={(grid) => { this.grid = grid }}
                                rowKey={(r, i) => i}
                                columns={this.checkModelCol}
                                data={this.templateData}
                                multiSelect={{ type:"radio" }}
                                paginationObj = {
                                    {verticalPosition:'none'}
                                }
                                showRowNum={false}
                                getSelectedDataFunc={this.getSelectedTemplate}
                            />
```

## 当前的行为：效果（可截图说明）及动作描述
gird 设置当选,数据选中物料,但是没有样式,选中没有加上 is-checked 的样式,

## 期望的行为:
选中数据的同事加上样式

**Comment by yangchch6** [comment]
检查下 bee-table 的版本，我这里没有复现。

![581576750817_ pic](https://user-images.githubusercontent.com/33412781/71330535-8e277b00-2568-11ea-9d3e-54b221553762.jpg)

![571576750788_ pic](https://user-images.githubusercontent.com/33412781/71330566-b44d1b00-2568-11ea-9d35-269dfc661347.jpg)

**Comment by wangkimi** [comment]
bee-table 的版本和你的一样,是2.2.26.还有就是参照的单选,以前可以的.现在都选不上了.装了2.2.26的版本以后.

**Comment by yangchch6** [comment]
那就不对了，表参照的单选用的不是 table 的功能，你这个问题应该是自己复写了 radio 了逻辑吧。你项目中其他的单选按钮应该也会有问题，检查下项目中对 Radio 组件的相关处理吧

**Comment by wangkimi** [comment]
bee-radio倒是没有做任何处理,我们这边一共有八个工程,基本用了单选的都选不上.不过,我自己可以再看看.

**Comment by yangchch6** [comment]
可以安装下老版本 ``` npm install bee-table@2.2.21 ```，看看还有没有 radio 选不中的问题。如果还有问题，就不是升级 Table 导致的了，就需要看下你们近期修改了什么

**Comment by wangkimi** [comment]
好的.

**Comment by yangchch6** [comment]
确认下 getSelectedDataFunc 方法有没有触发，点一次 radio 触发了几次 getSelectedDataFunc

**Comment by wangkimi** [comment]
我发现他们在getSelectedDataFunc方法中调用了setState({}),这样会重新render()方法,所以导致单选不上.单选的情况下,没有说我给选中的一条记录加上一个选中的标识(类似于多选的_checked),然后重新渲染的时候就自动选中.

**Comment by yangchch6** [comment]
升级下 bee-complex-grid@2.1.0 这个版本试下

**Comment by wangkimi** [comment]
升级测试了.没问题.样式都对了.谢谢啦.
