### ISSUE TITLE
bee-loading 组件

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#47]
### Bug 报告

    loading  在某个div中使用，希望弹出单个div的loading ，很多时候就变成全局的了。代码是按照demo中写的。

- __Package version(s)__: (版本号)

#### 期望的行为:
  在单个div或者容器中 弹出loading 处理。

**Comment by BoyuZhou** [comment]
两种方式一个要求，
要求：容器布局为position：absolute或者relative
方式1：如果容器是单独组件，将Loading写在组件内，设置container为this
方式2：设置container= { （）=> { document.getElementById('xxx')}}
