### ISSUE TITLE
单独使用bee-complex-grid部分css没有引入

### ISSUE THREAD

**Issue by huangming** [iuap-design/tinper-bee#471]
## 环境及版本信息

- 若使用单个组件，请标明该组件版本号：
`bee-complex-grid 2.0.28`

- 当前项目中`react`的版本号：
`16.11.0`

- 所使用的操作系统：
`fedora 30`

- 所使用的浏览器：
`firefox68`

## 描述这个问题:
(官方例子)[https://design.yonyoucloud.com/tinper-acs/bee-complex-grid]
中含有ToolBar的复杂表格 在我本地环境中发现class`grid-toolbar`的css不存在，导致toolbar跟表格没有空格，查看了官网的是有`padding: 7px 12px 7px 4px;`的。
另外尝试过`import 'bee-complex-grid/build/Grid.css';`发现会导致表头每列的标题最多只有两个汉字长度，然后是省略号显示。

**Comment by yangchch6** [comment]
1、使用 Grid 组件，需要引入 Grid.css

![image](https://user-images.githubusercontent.com/33412781/71330738-8ddbaf80-2569-11ea-92c8-b1a99dccaf70.png)


2、表头每列的 width 设置宽一点，就不会出现你说的问题

**Comment by huangming** [comment]
> 1、使用 Grid 组件，需要引入 Grid.css
> 
> ![image](https://user-images.githubusercontent.com/33412781/71330738-8ddbaf80-2569-11ea-92c8-b1a99dccaf70.png)
> 
> 2、表头每列的 width 设置宽一点，就不会出现你说的问题

你好，宽度问题不是width引起的，经过测试，引入Grid.css后，设置showHeaderMenu={false}就不会有描述问题的出现，如果显示表头下选项就会触发。

另外发现表头右侧的选择列的弹出框会变透明。
引入下面的`bee-complex-grid-fix.scss`可以显示，但是弹框会出现滚动条，这种方法应该是不可取的，还是希望能解决。
`import '../../styles/bee-complex-grid-fix.scss'`

```//file:bee-complex-grid-fix.scss 解决表格头右侧列筛选器透明问题
.fade:not(.show) {
    opacity: 1;
}
.u-table-filter-column-pop-cont {
  overflow-y: hidden;
}
```

也有可能是因为其他组件引起的，因为我是在[其他项目中](https://github.com/flatlogic/react-dashboard)的子路由使用Grid

p.s.很感谢你们团队分享的bee-complex-grid组件，很漂亮很实用

**Comment by yangchch6** [comment]
column 的宽度写大一点，就不会只显示两个字了
![image](https://user-images.githubusercontent.com/33412781/71391718-5429a800-2640-11ea-8dee-1f5e5d515572.png)

您是哪个项目组的？我们没有提供 ` ../../styles/bee-complex-grid-fix.scss` 这个文件呀
