### ISSUE TITLE
grid 点击行内按钮跳转后会报warning

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#473]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "^2.0.13",
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
![2](https://user-images.githubusercontent.com/19704104/71338363-91cbf980-258a-11ea-9a0e-e940f79761d4.png)
![1](https://user-images.githubusercontent.com/19704104/71338468-030bac80-258b-11ea-998e-387c052d1ece.png)

### 2、报错信息

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

## 期望的行为:

我在grid 的表头最后一个column配置了跳到详情的按钮
跟代码发现 一点击按钮就会走到onRowClick里的setState
但是此时我已经跳转到下个页面
所以会报这个warning

**Comment by yangchch6** [comment]
可以阻止下按钮点击事件冒泡
