### ISSUE TITLE
在表格内使用 bee-tooltip ，页面出现滚动时定位不准

### ISSUE THREAD

**Issue by sunnyfish** [iuap-design/tinper-bee#474]
![image](https://user-images.githubusercontent.com/5301450/71344503-a4036300-259d-11ea-8bd2-676a4bfcc4fd.png)

## 环境及版本信息

- `tinper-bee` 版本号:  
bee-tooltip: 2.1.4
bee-table: 2.1.3

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：
15.3.2

- 所使用的操作系统：
Windows

- 所使用的浏览器：
chrome

## 您所在的领域、行业或项目组：
用友友户通运营部

## 描述这个问题:

    {
      title: <FormattedMessage id='externalUserType.memo' />, width: '150px',
      dataIndex: "status", key: "status", render: (text, rec, index) => {
        /** status: 整型，0:可用  1:已加入 2:待补充资料 */
        switch (text) {
          case 1:
            return <FormattedMessage id='entgroup.invitedStatus' />
          case 2:
            return  <span className='font-warning' >
                <Tooltip inverse placement="right"  
              className={'invite-list-tooltip'} rootClose={true}
              container={this.container ? ReactDOM.findDOMNode(this.container).querySelector(".u-table-tbody") : null}
              overlay={<div className='text'><FormattedMessage id='entgourp.supplierInfoTips' /></div>}
              >
                <span className='cl cl-notice-p'/>
                </Tooltip>
                <FormattedMessage id='entgourp.supplierInfoIncomp' /></span>
        }

      }
    }

### 2、报错信息
页面滚动条处于最上方时tooltip定位准确，某一个滚动点时，定位不准确，如上截图。bottom和bottomRight等在某个滚动位置也会有定位问题

**Comment by yangchch6** [comment]
如果是 YonSuite 风格的话，左树右表场景，应该是表头固定，表体滚动吧。


<img width="1679" alt="WechatIMG2" src="https://user-images.githubusercontent.com/33412781/71397114-8bf01a00-2657-11ea-8daa-5d4e5548d05d.png">

**Comment by yangchch6** [comment]
把 container 注释掉吧，我这样写没有问题：
```
{
    title: "部门", width: '150px',
    dataIndex: "status", key: "status", render: (text, rec, index) => {
      return (
        <span className='font-warning' >
          <Tooltip 
          inverse 
          placement="left" 
          // container={document.querySelector(".u-table-tbody") ? document.querySelector(".u-table-tbody") : null}
          overlay={<div className='text'>缺少联系人信息，请将供应商档案中的默认联系人信息（手机号、邮箱等）补充完整</div>}
          >
          <i className="uf uf-exc-c-o" />
          </Tooltip>
          资料不完善
        </span>
      )
    }
  }
```
