### ISSUE TITLE
menu 的SubMenu 显示问题

### ISSUE THREAD

**Issue by summerboys** [iuap-design/tinper-bee#477]
## 环境及版本信息

- `tinper-bee` 版本号: 

- 若使用单个组件，请标明该组件版本号：bee-menus@2.0.9

- 当前项目中`react`的版本号：16.9

- 所使用的操作系统：Mac

- 所使用的浏览器：Chrome

## 描述这个问题:
5
### 1、组件相关代码

menu 的SubMenu 在右侧空间不足时 出现在左侧的时候 会遮住menu一部分

![image](https://user-images.githubusercontent.com/16048628/71390489-900e3e80-263b-11ea-9ccc-d0d62f284ba7.png)

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 期望的行为:

1、SubMenu不遮挡menu 
2、或者提供属性控制向右或者向左弹出

**Comment by lucian55** [comment]
bee-menu@2.0.12 支持 SubMenu 自定义位置

|参数|说明|类型|默认值|
|:---|:----|:---|:------|
|position|`mode=='vertical'` 条件下，菜单显示位置，可选 `'horizontal', 'vertical', 'vertical-left', 'vertical-right', 'inline'`|string|-|
