### ISSUE TITLE
使用上传组件，已上传的附件无法下载

### ISSUE THREAD

**Issue by huangdandan** [iuap-design/tinper-bee#478]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"bee-upload": "^2.0.6",
- 当前项目中`react`的版本号：

 "react": "16.6.3",
- 所使用的操作系统：

all
- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

互联网政务事业部，江西数字民政
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

官网上的demo上传后，返回的数据有<a>标签，

现在项目中没有
![image](https://user-images.githubusercontent.com/9463495/71402122-03797580-2667-11ea-9a7f-4e2c2ee81011.png)

**Comment by lucian55** [comment]
1、上传组件不支持下载功能。 下载要根据不同项目做。

2、不显示上传列表的问题，写使用代码
