### ISSUE TITLE
input组件blur事件阻止其他元素的click事件触发

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#48]
情景：使用input组件输入内容，在他失去焦点的时候校验输入是否合法，点击button进行提交。
bug：当我焦点在input上时，直接点击button，触发input的blur事件，click事件不触发。失去焦点后，点击btn，click事件触发。一开始怀疑是JS本身的问题，自己使用原生的JS去验证是否JS是这样的事件机制，发现，在demo中先触发blur，后触发click，click并不会被阻止。请问，应当如何解决

**Comment by lucian55** [comment]
你那边用的是bee-form的校验么？

**Comment by 791045873** [comment]
不是，是我自己写的校验函数，传给了input组件

**Comment by lucian55** [comment]
加我微信  804199994
