### ISSUE TITLE
inputNumber

### ISSUE THREAD

**Issue by jingjing-zhou** [iuap-design/tinper-bee#480]
## 环境及版本信息

- `tinper-bee` 版本号:  
- 若使用单个组件，请标明该组件版本号：
- 当前项目中`react`的版本号：^16.0.0
- 所使用的操作系统： Windows/Mac 
- 所使用的浏览器：chrome
## 您所在的领域、行业或项目组：
营销云-公共开发部，周静静

### 1、组件相关代码

代码粘贴区域：

**Comment by lucian55** [comment]
版本，代码没有。无法定位。
组件支持 onKeyDown
