### ISSUE TITLE
MonthPicker类型的日期组件placement属性不生效

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#481]
## 环境及版本信息

- `tinper-bee` 版本号:  
"tinper-bee": "^2.0.3"

- 若使用单个组件，请标明该组件版本号：
 "bee-datepicker：“2.2.10”

- 当前项目中`react`的版本号：
"react": "^16.3.2",

- 所使用的操作系统：
   win7

- 所使用的浏览器：
 Google Chrome 已是最新版本
 版本 79.0.3945.88（正式版本） （64 位）

## 您所在的领域、行业或项目组：
  用友金融-非银产品部-杨志会

## 描述这个问题:
  行编辑 使用MonthPicker类型的日期组件，想要通过placement属性设置下拉框浮动的位置，但是该属性不生效

### 1、组件相关代码
   
![image](https://user-images.githubusercontent.com/53893374/71455045-4b66dc80-27ce-11ea-9e28-7429090fe7e5.png)
![image](https://user-images.githubusercontent.com/53893374/71455064-5faad980-27ce-11ea-8890-47354c85f682.png)

![image](https://user-images.githubusercontent.com/53893374/71455057-57eb3500-27ce-11ea-829c-21aa6aae0f58.png)

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by lucian55** [comment]
bee-datepicerk@2.3.9  已解决
