### ISSUE TITLE
文件上传照片墙，图片支持旋转

### ISSUE THREAD

**Issue by huangdandan** [iuap-design/tinper-bee#483]
## 环境及版本信息
all
- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

 Upload
- 当前项目中`react`的版本号：

16
- 所使用的操作系统：

all
- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

江西数字民政
## 描述这个问题:
upload上传文件照片墙，图片预览不可以旋转，放大 缩小
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 期望的行为:

upload上传文件照片墙，图片预览可以旋转，放大 缩小

**Comment by yangchch6** [comment]
建议直接使用 bee-upload 的照片墙功能，示例：http://bee.tinper.org/tinper-bee/bee-upload#%E7%85%A7%E7%89%87%E5%A2%99

或者结合 bee-viewer 和 bee-upload 组件，自己向上封装一个个性化业务组件
