### ISSUE TITLE
RangePicker,在输入框或者日期面板输入框,输入任意值报错,页面崩溃

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#485]
## 环境及版本信息

- `tinper-bee` 版本号:  
tinper-bee@2.2.3

- 若使用单个组件，请标明该组件版本号：

"bee-datepicker": "2.3.5",

- 当前项目中`react`的版本号：

   "react": "16.8.2",
    "react-dom": "16.8.2",
    "react-inline-css": "2.3.1",
    "react-intl": "2.8.0",
- 所使用的操作系统：

Windows
## 描述这个问题:
在输入框或者日期面板输入框,输入任意值报错,页面崩溃
### 1、组件相关代码

代码粘贴区域：
```

<RangePicker
                                    placeholder={'开始 ~ 结束'}
                                    dateInputPlaceholder={['开始', '结束']}
                                    showClear={true}
                                    onPanelChange={(v) => { console.log('onPanelChange', v) }}
                                    showClose={false}
                                    {...getFieldProps('subDateTime', { initialValue: [] })}
                                />

```

## 期望的行为:

输入任意值不导致页面空白.

**Comment by yangchch6** [comment]
升级至 bee-datepicker@2.3.9 就可以了
