### ISSUE TITLE
日期组件在行编辑状态下，页面上下滚动时日期选择框不能跟上原组件的位置一起移动

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#486]
## 环境及版本信息

- `tinper-bee` 版本号:  
   "tinper-bee": "^2.0.3",

- 若使用单个组件，请标明该组件版本号：
   "bee-datepicker"：“2.3.9”

- 当前项目中`react`的版本号：
   "react"："16.6.3"

- 所使用的操作系统：
   win7

- 所使用的浏览器：
   Google Chrome 已是最新版本
   版本 79.0.3945.88（正式版本） （64 位）

## 您所在的领域、行业或项目组：
   用友金融-非银产品部-杨志会

## 描述这个问题:
   行编辑时，当页面滚动时，日期组件的日期选择框不能跟着原组件进行一起滚动
![image](https://user-images.githubusercontent.com/53893374/71510290-56eafe00-28c9-11ea-8751-ac1eb8a32444.png)
![image](https://user-images.githubusercontent.com/53893374/71510301-623e2980-28c9-11ea-879b-98bd158115cc.png)

### 1、组件相关代码

代码粘贴区域：

![image](https://user-images.githubusercontent.com/53893374/71510329-7a15ad80-28c9-11ea-96cc-0d7ce86d6abd.png)

```
<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
![image](https://user-images.githubusercontent.com/33412781/71566237-f4744680-2af0-11ea-8325-4afbaec93b7a.png)

图片失效了。

**Comment by yangchch6** [comment]
设置 getCalendarContainer 属性试一下：

![image](https://user-images.githubusercontent.com/33412781/71649176-82496f00-2d47-11ea-9a64-4a246c791b9b.png)

**Comment by yangchch6** [comment]
升级组件 bee-datepicker@2.3.10，然后设置 `getCalendarContainer={trigger => trigger.parentNode} `，参考官网示例：

![image](https://user-images.githubusercontent.com/33412781/71965538-d61df180-323a-11ea-9f30-f4dd4c35a9d8.png)
