### ISSUE TITLE
图片查看器 Viewer

### ISSUE THREAD

**Issue by canghaihengliu** [iuap-design/tinper-bee#487]
## 环境及版本信息
nodejs v10.15.3
- `tinper-bee` 版本号:  

 "tinper-bee": "2.0.10",
- 若使用单个组件，请标明该组件版本号：

图片查看器 Viewer  v0.1.6
- 当前项目中`react`的版本号：

 "react": "16.6.3",
- 所使用的操作系统：

windows7
- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

江西数字民政项目
## 描述这个问题:
引入包时报错，重启项目"bee-complex-grid": "^2.0.28"报错
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/51563840/71523930-2a090c00-2906-11ea-949f-348e46659450.png)
![image](https://user-images.githubusercontent.com/51563840/71523936-342b0a80-2906-11ea-85e2-4b2291ff7d94.png)

**Comment by canghaihengliu** [comment]
期望能帮忙解决

**Comment by yangchch6** [comment]
没有相关代码，无法复现场景，请补充

**Comment by yangchch6** [comment]
重新执行 npm install 就好了，截图的错误是丢包了
