### ISSUE TITLE
modal组件 加载 dropdown组件 ，弹出下拉菜单层级被灰色蒙版盖住 无法选择。

### ISSUE THREAD

**Issue by tian6411602** [iuap-design/tinper-bee#489]
## 环境及版本信息

- `tinper-bee` 版本号:   "tinper-bee": "^2.1.0",

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
请在此填写您所在的部门或项目名称，最好能留下真实姓名，方便我们及时向您反馈问题处理结果

**Comment by yangchch6** [comment]
使用错误，需要给 Dropdown 组件设置  getPopupContainer 属性，指定其渲染在 Modal 容器内，就不会出现上诉问题。

![image](https://user-images.githubusercontent.com/33412781/71649021-3fd36280-2d46-11ea-9ccc-a261a5e26339.png)
