### ISSUE TITLE
ButtonGroup 选中后样式设置

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#49]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

使用ButtonGroup 的时候，我选中一个按钮后，选中的按钮没有设置选中样式

**Comment by BoyuZhou** [comment]
buttonGroup主要提供的功能，是作为工具按钮组，你的需求增加active，一般是tab做的事情
