### ISSUE TITLE
下拉按钮

### ISSUE THREAD

**Issue by xaioheiniu** [iuap-design/tinper-bee#491]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.0.10",
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

"react": "16.6.3",
- 所使用的操作系统：

windows
- 所使用的浏览器：

谷歌
## 您所在的领域、行业或项目组：

华能置业
## 描述这个问题:
点击选中的下拉菜单后，再次点击下拉按钮，第一次点击之前选中的值不清空
### 1、组件相关代码

代码粘贴区域：
```

<Dropdown
    trigger={['click']} 
    overlay={menu1}
    animation="slide-up">
    <Button colors='primary'>食堂菜谱</Button>
</Dropdown> 		
const menu1 = (
		<Menu onSelect={this.onSelectaa}>	
			<Item key={this.state.meunNull}>全部</Item>
			{menuDate.map(da=><Item key={da.pk_mdm} data={da} >{da.name}</Item> )}
		</Menu>
	)
onSelectaa =({key,item}) =>{ 
	if(key =='meunNull'){
		key = ''
	}
	console.log(key+'---key');
	let paramM ={
		menudate: this.state.clickTime,
		mealtype: key,
		type:this.state.menuType
	}
	 actions.diningroom.getListData(paramM); // 菜品分类
  }
```

### 2、报错信息

![image](https://user-images.githubusercontent.com/20662956/71574986-1cca6800-2b26-11ea-96de-fe411818ac9d.png)

## 当前的行为：效果（可截图说明）及动作描述

点击选中的下拉菜单后。再次点击，下拉之前选中的值不清空
## 期望的行为:

期望第二次点击下拉菜单，清空第一次点击选中的值

**Comment by yangchch6** [comment]
点击选项之后，不保留选中状态的意思吗？

**Comment by yangchch6** [comment]
组件已经支持该交互，给 Menu 加 selectedKeys={[]} 即可。 

![image](https://user-images.githubusercontent.com/33412781/71802475-bb137c00-3098-11ea-8c31-c24b34bab531.png)
