### ISSUE TITLE
气泡卡片 Popover设置placement为bottom 显示的位置不对

### ISSUE THREAD

**Issue by lwd777** [iuap-design/tinper-bee#492]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.3.2"
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

Chrome
## 您所在的领域、行业或项目组：
离散制造-刘稳舵

### 1、组件相关代码

代码粘贴区域：
```

<div>
        <Popover
          id="demo2"
          placement="bottom"
          title={<h3>元素配比</h3>}
          content={content}
          show={this.state.show}
          onVisibleChange={this.onVisibleChange}
        >
          {/* <Btns btns={btns} /> */}
          <Button bordered onClick={this.show}>
            ...
          </Button>
        </Popover>
      </div>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/14276812/71580505-ebf52d80-2b3b-11ea-9b6b-70dca5b4e492.png)

![image](https://user-images.githubusercontent.com/14276812/71580599-5312e200-2b3c-11ea-81c7-fcf5f7394d9c.png)

**Comment by yangchch6** [comment]
本地没有复现，有没有可调试的测试环境，友空间发我一下
