### ISSUE TITLE
升级组件bee-complex-grid表格获取勾选行的回调函数无效

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#493]
## 环境及版本信息

- `tinper-bee` 版本号:  
"tinper-bee": "^2.1.5",

- 若使用单个组件，请标明该组件版本号：
"bee-complex-grid": "^2.1.1",

- 当前项目中`react`的版本号：
"react": "16.6.3",

- 所使用的操作系统：
macos

- 所使用的浏览器：
chrome 79.0.3945.88（正式版本） （64 位）

## 您所在的领域、行业或项目组：
香港用友icbc项目组孙康

### 1、组件相关代码

代码粘贴区域：
```

 <Grid
                            ref={(grid) => { this.grid = grid;}}
                            paginationObj = {{verticalPosition:'none'}} 
                            columns={grid3_columns}
                            sort = {sortObj}
                            multiSelect={{type: "checkbox"}}
                            getSelectedDataFunc={this.getSelectedDatachoose3}
                            onRowDoubleClick={(record, index, event)=>_this.goClientInfo(record,"2")}
                            data={this.getdata(this.props.contactLists)}
                            onRowClick={(record,index,indent)=>{this.goContactInfo(record.id)}}
                        />

```

### 2、报错信息

升级组件bee-complex-grid到2.1.1表格获取勾选行的回调函数无效

## 当前的行为：效果（可截图说明）及动作描述

升级组件bee-complex-grid到2.1.1表格获取勾选行的回调函数无效

## 期望的行为:

升级组件bee-complex-grid到2.1.1表格获取勾选行的回调函数有效

**Comment by yangchch6** [comment]
这个问题已经解决了，还需要升级下～ bee-complex-grid@2.1.2
