### ISSUE TITLE
Ac-grids可编辑表格支持自定义动态控制每一个单元格的编辑状态

### ISSUE THREAD

**Issue by laonier** [iuap-design/tinper-bee#495]
![image](https://user-images.githubusercontent.com/22088495/71607350-82b10100-2bb3-11ea-9a27-36e2f16141cc.png)

如图，类型选了单选，这一列后面的最大值和最小值是不能编辑，待选项和说明是可以编辑，
如果选择了数值，这一列后面最大值最小值可以编辑，待选项和说明是不可以编辑，

**Comment by yangchch6** [comment]
请在此填写您所在的部门或项目名称，最好能留下真实姓名，方便我们及时向您反馈问题处理结果

**Comment by laonier** [comment]
> 请在此填写您所在的部门或项目名称，最好能留下真实姓名，方便我们及时向您反馈问题处理结果

智能制造-张田田

**Comment by yangchch6** [comment]
发了新包 ac-grids@0.2.9，fieldProps 增加 disabled 属性。

![image](https://user-images.githubusercontent.com/33412781/71653904-ccdbe300-2d69-11ea-94a6-4a4994e0a521.png)
