### ISSUE TITLE
RefMultipleTableWithInput参照弹出的模态框内，左上角搜索输入框：数据量较大时，连续两次的实时查询结果，第二次的结果未生效

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#498]
## 环境及版本信息
- `tinper-bee` 版本号:   ^2.2.3,
- `pap-refer` 版本号:   ^1.0.9,

- 若使用单个组件，请标明该组件版本号：
-- "ref-multiple-table": "2.0.1", 中的 RefMultipleTableWithInput 组件

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：当前主流浏览器

## 描述这个问题: 
<img width="486" alt="WX20191231-144812@2x" src="https://user-images.githubusercontent.com/22900344/71612628-9ae94600-2bdc-11ea-8283-8589c52018ea.png">

<img width="1266" alt="WX20191231-143324@2x" src="https://user-images.githubusercontent.com/22900344/71612677-f3204800-2bdc-11ea-9278-32ed0aa8e429.png">

**Comment by XYooo** [comment]
pap-refer@1.1.0-beta.4

解决大数据下渲染不正确的问题，如果正常请通知我，发正式版本

**Comment by MINGXINICE** [comment]
@XYooo 测试结束，可以正常使用，请发正式版本
