### ISSUE TITLE
tinper-bee 组件库开发计划

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper-bee#5]
# tinper-bee 页面目录讨论

- 第一阶段：先讨论确定整体的页面目录，然后把现有的组件完善，加上去，达到可用好用的阶段。（**备注：暂时没有的组件或是文档都先置灰展示。**）
- 第二阶段：根据项目或是讨论制定的开发计划，确定下一批组件的开发计划。
- 使用推广：根据不同阶段所拥有的组件，都开发相应的场景功能页面和开发文档，形成实践案例。这块工作需要持续推进，不分阶段。

## 目录

- [x] 介绍
- [x] 安装
- [x] 快速上手
- [x] 参与贡献
- [x] 整体概览
- [x] 更新日志
- [x] Fork On GitHub
- 组件
	- Basic 基础性组件
		- [x] [Color 色彩]()
		- [ ] [Font 字体]()
		- [x] [Button 按钮]()
		- [x] [Icon 图标]()
	- Layout 布局
		- [x] [Layout 栅格布局]()
	- Form 表单类组件
		- [x] [Input 输入框]()
       - [x] [InputGroup 输入框容器]()
       - [x] [FormGroup 表单容器]()
		- [x] [Radio 单选框]()
		- [x] [Checkbox 多选框]()
		- [x] [Switch 开关]()
		- [x] [Select 选择器]()
		- [x] [Slider 滑块]()
		- [x] [Cascader 级联选择]()
		- [x] [Transfer 穿梭框]()
		- [x] [ InputNumber 数字输入框]()
		- [x] [TimePicker 时间选择器]()
		- [x] [DatePicker 日期选择器]()
		- [x] [DateTimePicker 日期时间选择器]()
		- [x] [Upload 上传]()
		- [x] [Rate 评分]()
		- [x] [Form 表单]()
	- View 视图类组件
		- [x] [Tile 卡片]()
         - [x] [Panel 展示板]()
		- [x] [Badge 标记]()
		- [x] [Collapse 折叠面板]()
	    - [x] [Timeline 时间轴]()
		- [x] [ Tag 标签]()
		- [x] [Carousel 走马灯]()
		- [x] [ Calendar 日历]()
		- [x] [Table 表格]()
		- [x] [Tree 树形控件]()
        - [x] [Tile 磁贴]()
       - [x] [Loadingstate 状态按钮]()
	- Navigation 导航类组件
		- [x] [NavMenu 导航菜单]()
		- [x] [Tabs 标签页]()
		- [x] [Dropdown 下拉菜单]()
		- [x] [Breadcrumb 面包屑]()
		- [x] [Steps 步骤条]()
		- [x] [Affix 固钉]()
		- [x] [Anchor 锚点]()
		- [x] [BackTop 回到顶部]()
		- [x] [Pagination 分页]()
	- Feedback 反馈类组件
		- [x] [Alert 提醒]()
		- [x] [Message 消息]()
		- [x] [Modal 对话框]()
		- [x] [Notification 通知]()
		- [x] [Popconfirm 气泡确认框]()
		- [x] [ProgressBar 进度条]() 
		- [x] [Loading 进度指示器]()
		- [x] [Tooltip 文字提示]()

**Comment by cavenliu** [comment]
Badge 徽标－－－－－－统一修改为－－－－－Badge 标记

**Comment by cavenliu** [comment]
View 视图类组件－－－－增加－－－－tile 磁贴

**Comment by cavenliu** [comment]
Menu 导航菜单－－－－建议修改为－－－－－NavMenu 导航菜单

**Comment by cavenliu** [comment]
Tooltip 文字提示
Poptip 气泡提示---------建议合并一下-------只保留Tooltip 文字提示

**Comment by GuoYongfeng** [comment]
@cavenliu 以上，已合并调整

**Comment by ahua52** [comment]
![image](https://cloud.githubusercontent.com/assets/19704104/21379592/2e52fe00-c78a-11e6-85ed-3a145cc62489.png)

**Comment by ahua52** [comment]
进度条组件 我们叫 ProgressBar

**Comment by GuoYongfeng** [comment]
@ahua52 已调整，删除Page

**Comment by cavenliu** [comment]
Feedback 反馈类组件－－
Alert 提醒
modal对话框
Message 消息
Notification通知
Popconfirm气泡确认框
loadingProgress 进度指示器

**Comment by GuoYongfeng** [comment]
@cavenliu 已调整更新
