### ISSUE TITLE
tinper-bee.css文件中没有树形组件的相关样式

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#50]
如题，请问从哪里引用，树形组件不属于tinper-bee组件库中的一员吗？

**Comment by BoyuZhou** [comment]
@791045873 你是如何引入的样式

**Comment by 791045873** [comment]
import '../node_modules/tinper-bee/assets/tinper-bee.css';

**Comment by 791045873** [comment]
@BoyuZhou 您好，明天要展示一阶段的工作结果，比较着急，麻烦您重点解决以下

**Comment by BoyuZhou** [comment]
@791045873  你是哪一个版本的tinper-bee

**Comment by BoyuZhou** [comment]
@791045873  可以先使用这个cdn地址，来修复这个问题
```
<link href="//design.yonyoucloud.com/static/tinper-bee/1.1.0/assets/tinper-bee.css">
```

**Comment by 791045873** [comment]
@BoyuZhou 版本是1.1.1

**Comment by 791045873** [comment]
"tinper-bee": "^1.1.1"

**Comment by BoyuZhou** [comment]
@791045873  如果单独安装了bee-tree组件的话，也可以这样引用样式
```
import ‘bee-tree/build/Tree.css‘
```
