### ISSUE TITLE
参照树项目级多选树参照 ，选择之后展示的时候前面多了个分号

### ISSUE THREAD

**Issue by wlLeblanc** [iuap-design/tinper-bee#502]
项目级多选树参照 ，选择之后展示的时候前面多了个分号

![image](https://user-images.githubusercontent.com/22288871/71765106-6ef6f900-2f2b-11ea-9f27-5429cf4db8c6.png)

**Comment by XYooo** [comment]
需要提供一下参照包名和版本号。一般出现这个问题是初始值设置成value=JSON.stringify({refname:'',refpk:''})

**Comment by wlLeblanc** [comment]
参照包名RefTreeWithInput  "tinper-bee": "2.0.11",  

没有设置初始值哦！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xyooo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 上午10:19
收件人:&nbsp;"iuap-design/tinper-bee"<tinper-bee@noreply.github.com&gt;;
抄送:&nbsp;"‰⑩枂⑩鈤♂ "<1228004606@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iuap-design/tinper-bee] 参照树项目级多选树参照 ，选择之后展示的时候前面多了个分号 (#502)




需要提供一下参照包名和版本号。一般出现这个问题是初始值设置成value=JSON.stringify({refname:'',refpk:''})

**Comment by XYooo** [comment]
tinper-bee中没有参照，也没有包名RefTreeWithInput 。这边按照正确的issue格式提个issue吧说下使用参照的项目，负责人。

**Comment by wlLeblanc** [comment]
大佬，这就给我关闭了啊，是组件不是包名，我说错了，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xyooo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月7日(星期二) 晚上7:41
收件人:&nbsp;"iuap-design/tinper-bee"<tinper-bee@noreply.github.com&gt;;
抄送:&nbsp;"‰⑩枂⑩鈤♂ "<1228004606@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [iuap-design/tinper-bee] 参照树项目级多选树参照 ，选择之后展示的时候前面多了个分号 (#502)




tinper-bee中没有参照，也没有包名RefTreeWithInput 。这边按照正确的issue格式提个issue吧说下使用参照的项目，负责人。
