### ISSUE TITLE
参照的简单搜索期望能够点击搜索图标再触发搜索事件

### ISSUE THREAD

**Issue by yangzhhc** [iuap-design/tinper-bee#503]
## 环境及版本信息

- `tinper-bee` 版本号:  
   "tinper-bee": "^2.0.3",

- 若使用单个组件，请标明该组件版本号：
   "ref-multiple-table": "^2.0.4"

- 当前项目中`react`的版本号：
   "react" ： "16.6.3",

- 所使用的操作系统：
   win7

- 所使用的浏览器：
   Google Chrome 已是最新版本
   版本 79.0.3945.88（正式版本） （64 位）

## 您所在的领域、行业或项目组：
   用友金融-非银产品部-杨志会

## 描述这个问题:
![image](https://user-images.githubusercontent.com/53893374/71865524-0469d700-313e-11ea-9b17-22f5d6b5eff7.png)

   表参照的简单搜索目前是只有输入框的值改变就会触发搜索事件
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述
![image](https://user-images.githubusercontent.com/53893374/71867344-bc9a7e00-3144-11ea-8f9c-a7ac71c2ebc1.png)
现在是输入框的值只要一改变就会触发搜索事件，这样的话进行数据请求的操作台频繁，影响用户体验，并存在性能问题

## 期望的行为:
![image](https://user-images.githubusercontent.com/53893374/71867436-fff4ec80-3144-11ea-9ca2-96e3d238c7bf.png)

期望：点击搜索图标时再触发搜索事件，或者给输入框绑定enter事件

**Comment by XYooo** [comment]
参照版本"ref-multiple-table": "^2.0.4"，2.0x的交互不能修改，数据渲染出现的问题没有说明

**Comment by XYooo** [comment]
上述没有提到任何参照bug级的问题，而是对搜索交互提出修改，是这样吗

**Comment by XYooo** [comment]
如果这样，考虑升级2.1.x版本。因为2.0.x版本的交互是产品定好的，2.1.x是后续开放版本
