### ISSUE TITLE
使用树参照RefTreeWithInput组件，多选后保存显示多了一个分号？

### ISSUE THREAD

**Issue by wlLeblanc** [iuap-design/tinper-bee#504]
目前如下图，多选显示会多分号
![image](https://user-images.githubusercontent.com/22288871/71943369-6b999100-31fb-11ea-868c-e9e4b892f38a.png)

期望
![image](https://user-images.githubusercontent.com/22288871/71943354-56246700-31fb-11ea-9e96-1e1d684ece7b.png)

**Comment by XYooo** [comment]
首先，请按照规范的issue格式提出问题
其次，树参照RefTreeWithInput组件，在包pap-refer和包ref-tree中都是提供这个组件的，所以请问你是哪个包以及版本号
再者，请先说明下自己是哪个项目中在使用
