### ISSUE TITLE
ac-city-select组件报错问题

### ISSUE THREAD

**Issue by limingk** [iuap-design/tinper-bee#506]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.3.2
- 若使用单个组件，请标明该组件版本号：

0.0.5
- 当前项目中`react`的版本号：

- 所使用的操作系统：

windows
- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

智能制造事业部-设备服务开发
## 描述这个问题:
这个组件，如果赋值时跟预置数据有差别（比如“北京”和“北京市”），那就会报错导致整个页面空白，这个可否处理一下，数据不符不要报错，这里显示空就行
### 1、组件相关代码

代码粘贴区域：
```
报错位置在以下代码
  index = _this3.getIndex('province', value);
            citesInitArr = _this3.buildInitDataArr(provinceData[index].city, disabledCityArr, lang);
            areasInitData = _this3.buildAreaInitData(citesInitArr[0].area, citesInitArr[0].name, disabledAreaObj, lang);
<Demo className="demo1-input"/>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/53895503/71955715-0d34d880-3224-11ea-873f-2ae37096769d.png)

## 期望的行为:

数据不符不要报错，这里显示空就行

**Comment by yangchch6** [comment]
这样设置没有报错，请说明下复现步骤，并粘贴相关代码。

```
const defaultValue = { province:'北京市',city:'北京',area:'东城区'};
const provinceData = [{ "name": "北京", "city":[{"name":"北京", "area":["东城区","西城区","崇文区","宣武区","朝阳区","丰台区","石景山区","海淀区","门头沟区","房山区","通州区","顺义区","昌平区","大兴区","平谷区","怀柔区","密云县","延庆县"]}]}, { "name": "天津", "city":[{"name":"天津", "area":["和平区","河东区","河西区","南开区","河北区","红桥区","塘沽区","汉沽区","大港区","东丽区","西青区","津南区","北辰区","武清区","宝坻区","宁河县","静海县","蓟 县"]}]}]

<ACCitySelect 
ref='city' 
defaultValue={this.state.defaultValue} 
provinceData={provinceData} 
onChange={this.onChange} 
/>
```

**Comment by limingk** [comment]
我们是从列表点编辑进入卡片画面，进入的卡片画面的时候报错

 



 

报错信息如下



 

 

 

 

代码如下：

 

    let { currrentRow: record, btnFlag, form } = _this.props;

    let { getFieldProps, getFieldError } = form;

 

    let defaultRegion = { province: "", city: "", area: "" };

    if (record && record.province) {

      defaultRegion.province = record.province;

      defaultRegion.city = record.city;

      defaultRegion.area = record.district;

    }

 

 

 

          <FormItem label={"所属区域"}>

            <AcCitySelect

              ref="city"

              // disabled={true}

              value={defaultRegion}

              {...getFieldProps("region", {

                initialValue: defaultRegion,

                getValueProps: value => {

                  return `${value.province},${value.city},${value.area}`;

                }

              })}

            />

            {/* <FormError errorMsg={getFieldError("region")} /> */}

          </FormItem>

 

 

发件人: noreply@github.com [mailto:noreply@github.com] 代表 yangchch6
发送时间: 2020年1月16日 19:37
收件人: iuap-design/tinper-bee
抄送: limingk; Author
主题: Re: [iuap-design/tinper-bee] ac-city-select组件报错问题 (#506)

 

这样设置没有报错，请说明下复现步骤，并粘贴相关代码。

const defaultValue = { province:'北京市',city:'北京',area:'东城区'};
const provinceData = [{ "name": "北京", "city":[{"name":"北京", "area":["东城区","西城区","崇文区","宣武区","朝阳区","丰台区","石景山区","海淀区","门头沟区","房山区","通州区","顺义区","昌平区","大兴区","平谷区","怀柔区","密云县","延庆县"]}]}, { "name": "天津", "city":[{"name":"天津", "area":["和平区","河东区","河西区","南开区","河北区","红桥区","塘沽区","汉沽区","大港区","东丽区","西青区","津南区","北辰区","武清区","宝坻区","宁河县","静海县","蓟 县"]}]}]
 
<ACCitySelect 
ref='city' 
defaultValue={this.state.defaultValue} 
provinceData={provinceData} 
onChange={this.onChange} 
/>

**Comment by yangchch6** [comment]
版本：ac-city-select@0.0.5
按照你提供的代码，仍未复现，麻烦看下：


importAcCitySelectfrom'ac-city-select';
importFormfrom'bee-form';
const { FormItem } = Form;
classDemo1extendsComponent {
render () {
let { getFieldProps } = this.props.form;
letdefaultRegion = { province:"", city:"", area:"" };
constrecord = {
province:'北京市aaa',
city:'北京市',
district:'东城区'
}
if (record && record.province) {
defaultRegion.province = record.province;
defaultRegion.city = record.city;
defaultRegion.area = record.district;
}
return (
<FormItemlabel={"所属区域"}>
<AcCitySelect
ref="city"
value={defaultRegion}
{...getFieldProps("region", {
initialValue:defaultRegion,
getValueProps:value=> {
return`${value.province},${value.city},${value.area}`;
}
})}
/>
</FormItem>
)}
}
exportdefaultForm.createForm()(Demo1);











在 2020-01-17 08:40:54，"limingk" <notifications@github.com> 写道：

我们是从列表点编辑进入卡片画面，进入的卡片画面的时候报错







报错信息如下











代码如下：



let { currrentRow: record, btnFlag, form } = _this.props;

let { getFieldProps, getFieldError } = form;



let defaultRegion = { province: "", city: "", area: "" };

if (record && record.province) {

defaultRegion.province = record.province;

defaultRegion.city = record.city;

defaultRegion.area = record.district;

}







<FormItem label={"所属区域"}>

<AcCitySelect

ref="city"

// disabled={true}

value={defaultRegion}

{...getFieldProps("region", {

initialValue: defaultRegion,

getValueProps: value => {

return `${value.province},${value.city},${value.area}`;

}

})}

/>

{/* <FormError errorMsg={getFieldError("region")} /> */}

</FormItem>





发件人: noreply@github.com [mailto:noreply@github.com] 代表 yangchch6
发送时间: 2020年1月16日 19:37
收件人: iuap-design/tinper-bee
抄送: limingk; Author
主题: Re: [iuap-design/tinper-bee] ac-city-select组件报错问题 (#506)



这样设置没有报错，请说明下复现步骤，并粘贴相关代码。

const defaultValue = { province:'北京市',city:'北京',area:'东城区'};
const provinceData = [{ "name": "北京", "city":[{"name":"北京", "area":["东城区","西城区","崇文区","宣武区","朝阳区","丰台区","石景山区","海淀区","门头沟区","房山区","通州区","顺义区","昌平区","大兴区","平谷区","怀柔区","密云县","延庆县"]}]}, { "name": "天津", "city":[{"name":"天津", "area":["和平区","河东区","河西区","南开区","河北区","红桥区","塘沽区","汉沽区","大港区","东丽区","西青区","津南区","北辰区","武清区","宝坻区","宁河县","静海县","蓟 县"]}]}]

<ACCitySelect
ref='city'
defaultValue={this.state.defaultValue}
provinceData={provinceData}
onChange={this.onChange}
/>

**Comment by yangchch6** [comment]
版本：ac-city-select@0.0.5
按照你提供的代码，仍未复现，麻烦看下：
``` jsx
import AcCitySelect from 'ac-city-select';
import Form from 'bee-form';
const { FormItem } = Form;

class Demo1 extends Component {
  render () {
    let { getFieldProps } = this.props.form;
    let defaultRegion = { province: "", city: "", area: "" };
    const record = {
      province: '北京市aaa',
      city: '北京市',
      district: '东城区'
    }
    if (record && record.province) {
      defaultRegion.province = record.province;
      defaultRegion.city = record.city;
      defaultRegion.area = record.district;
    }
    return (
      <FormItem label={"所属区域"}>
        <AcCitySelect
        ref="city"
        value={defaultRegion}
        {...getFieldProps("region", {
          initialValue: defaultRegion,
          getValueProps: value => {
            return `${value.province},${value.city},${value.area}`;
          }
        })}
        />
      </FormItem>
  )}
}
export default Form.createForm()(Demo1);
```

**Comment by yangchch6** [comment]
发了新包 ac-city-select@0.0.6，升级即可。
