### ISSUE TITLE
Table组件表格内容超出显示长度，后面加省略号，鼠标移动上去提示全部信息。若没有超出长度，不用提示信息   

### ISSUE THREAD

**Issue by majfd** [iuap-design/tinper-bee#51]
### Bug 报告

- __Package version(s)__: (版本号)

#### 当前的行为:
通过修改样式，使超出长度显示为...  

#### 期望的行为:
若超出长度，鼠标接触，title提示信息，若没有超出，则不用提示

**Comment by HuYuee** [comment]
这个自己设置title属相来实现此功能！
