### ISSUE TITLE
当页面滚动时Tooltip fixed在当前位置

### ISSUE THREAD

**Issue by huangdandan** [iuap-design/tinper-bee#510]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.2.3
- 若使用单个组件，请标明该组件版本号：

Tooltip
2.0.3
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

chrome
## 您所在的领域、行业或项目组：

江西数字民政项目
### 1、组件相关代码

代码粘贴区域：
```

	<Tooltip inverse placement='right' overlay={content}>
									<Icon type='uf-eye-o'></Icon>
								</Tooltip>

```

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/9463495/72071269-59684180-3326-11ea-8871-083e83789673.png)

## 期望的行为:

Tooltip 定位正确

**Comment by yangchch6** [comment]
本地没有复现问题，可以提供一个测试环境

**Comment by yangchch6** [comment]
无法复现。
