### ISSUE TITLE
bee-complex-grid升级到2.1.2后过滤表头按钮点击没有反应

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#511]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.1.5
- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "^2.1.2"
- 当前项目中`react`的版本号：

16.6.3
- 所使用的操作系统：

macos
- 所使用的浏览器：

chrome 79.0.3945.88（正式版本） （64 位）
## 您所在的领域、行业或项目组：

用友香港icbc孙康
## 描述这个问题:
bee-complex-grid升级到2.1.2后过滤表头按钮点击没有反应
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```
<Grid2
                                    columns={this.state.grid2_columns} 
                                    data={this.getdata(this.props.clientLists)} 
                                    noReplaceColumns={true}
                                    //拖拽改变顺序事件
                                    //onDragEnd={this.grid2_onDragEnd}
                                    onDrop={this.grid2_onDragEnd}
                                    //改变列宽事件
                                    onDropBorder ={this.grid2_onDropBorder}
                                    //列过滤事件
                                    afterFilter={this.grid2_afterFilter}
                                    multiSelect={multiObj}
                                    sort = {sortObj}
                                    paginationObj = 'none'
                                    bordered = {false}
                                    onRowDoubleClick={(record, index, event)=>_this.goClientInfo(record,"1")}
                                    onRowClick={(record,index,indent)=>_this.gojump(record.id)}
                                    rowClassName={(record,index,indent)=>{
                                        if (record._checked) {
                                            return 'selected';
                                        } else {
                                            return '';
                                        }
                                    }}
                                    showFilterMenu
                                /> 
### 2、报错信息

![image](https://user-images.githubusercontent.com/37610457/72119354-21e1af80-338f-11ea-884c-ae9d6aa53365.png)

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/37610457/72119354-21e1af80-338f-11ea-884c-ae9d6aa53365.png)

## 期望的行为:

bee-complex-grid升级到2.1.2后过滤表头按钮点击有反应

**Comment by yangchch6** [comment]
需要引入Grid样式 ` import "bee-complex-grid/build/Grid.css";`
