### ISSUE TITLE
FormControl@2.0.10-bug

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#514]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.3.3

- 若使用单个组件，请标明该组件版本号：
2.0.10

- 当前项目中`react`的版本号：

- 所使用的操作系统：
16.8.6

- 所使用的浏览器：
Chrome最新版

## 您所在的领域、行业或项目组：
混合云及开放平台产品部
## 描述这个问题:

当FormControl没有传入value参数，页面调用FormControl再次render时，当前FormControl的的value会被清空，而不是前一次输入的值, componentWillReceiveProps应该判断 value是否存在
```
 componentWillReceiveProps(nextProp) {
        if (nextProp.value !== this.state.value) {
            this.setState({value: nextProp.value});
        }
    }
```
### 1、组件相关代码

代码粘贴区域：
```
 <FormControl
          className="ucg-ma-header-search"
          type="search"
          defaultValue={searchName}
          onSearch={onSearch}
        />

```

**Comment by lucian55** [comment]
bee-form-control@2.0.11  已解决
