### ISSUE TITLE
table defaultExpandAllRows 设置成 true 没效果

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#516]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.1.0"

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Table 
                    columns = {columns}
                    defaultExpandAllRows={true}
                    // defaultExpandedRowKeys={[2,3]}
                    data={data} />

```

**Comment by yangchch6** [comment]
未复现，效果如下：
![image](https://user-images.githubusercontent.com/33412781/72522585-fe3fcd00-3898-11ea-8586-1471a13d9a44.png)

版本如下：
![image](https://user-images.githubusercontent.com/33412781/72522617-131c6080-3899-11ea-9e6e-ca479a4be665.png)

代码如下：
http://bee.tinper.org/tinper-bee/bee-table#%E6%A0%91%E5%9E%8B%E8%A1%A8%E6%A0%BC%E6%95%B0%E6%8D%AE%E5%B1%95%E7%A4%BA
