### ISSUE TITLE
bee-input-number  问题

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#518]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

2.2.10

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/21353460/72339652-a28f0b80-3701-11ea-91e4-5b1e4e96c4aa.png)

**Comment by jonyshi** [comment]
第二个问题：

设置     precision={8}  的时候，无法在输入值了。

**Comment by ablence** [comment]
第三个问题：
设置toThousands={true}时，输入框只能输入4位数，上万的数字输入不进去

**Comment by yangchch6** [comment]
问题1、2已解决
问题3：toThousands 属性已废弃，请使用 format 自定义格式，参考官网示例：http://bee.tinper.org/tinper-bee/bee-input-number#%E5%A4%9A%E6%A0%BC%E5%BC%8F%E7%BB%84%E4%BB%B6
