### ISSUE TITLE
tinper-bee中LoadingState组件图标和文档示例中的不一样

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#519]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.0

- 若使用单个组件，请标明该组件版本号：bee-loading-state：2.0.2

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：当前主流浏览器

## 描述这个问题: tinper-bee中LoadingState组件图标和文档示例中的不一样，如图所示

![image](https://user-images.githubusercontent.com/22900344/72341277-ca33a300-3704-11ea-8704-4c6cb0fa03b9.png)
![image](https://user-images.githubusercontent.com/22900344/72340914-09152900-3704-11ea-81d0-60183412f473.png)
### 1、组件相关代码

代码粘贴区域：
我自己自定义了一个组件：
```
import React, { Component, Fragment } from 'react';
import { Button as BeeButton, Icon, LoadingState } from 'tinper-bee';
import './index.less'

class StateButton extends Component {

    constructor(props){
        super(props);
        this.state = {
            show: true
        }
    }

    handleClick = () => {
        this.setState({
            show: true
        })
        setTimeout(() => {
            this.setState({
                show: false
            })
        }, 3000)
    }

    render() {
        return (
            <LoadingState
                onClick={ this.handleClick }
                colors="primary"
                size="sm"
                show={ this.state.show }
                loadingText="waiting..."
            >
                {this.props.children}
            </LoadingState>
        )
    }
}

export default StateButton;

```
然后直接引用了它

```
<StateButton>异步按钮</StateButton>
```

**Comment by yangchch6** [comment]
1、如果是这样使用的：import { LoadingState } from 'tinper-bee';
执行 `npm list tinper-bee` ，把结果贴在这。
然后把如何引入 css 文件的，也说明以下。

2、如果是这样使用的：import LoadingState from 'bee-loading-state';
执行 `npm list bee-loading-state`，把结果贴在这。
然后把如何引入 css 文件的，也说明以下。

**Comment by MINGXINICE** [comment]
@yangchch6 我用的这种方式import { LoadingState } from 'tinper-bee';
![image](https://user-images.githubusercontent.com/22900344/72576037-704ffa80-3909-11ea-8573-574dfade33fc.png)
是在开发者平台生成的功能节点代码，直接放到项目中来，在index.html的位置
引入的样式
![image](https://user-images.githubusercontent.com/22900344/72576361-709cc580-390a-11ea-8f38-af81e68d992a.png)

**Comment by MINGXINICE** [comment]
@yangchch6 问题已解决，更新了index.html对应的tinper-bee资源包就好了
