### ISSUE TITLE
树表参照需要支持 footerBtnDom 属性

### ISSUE THREAD

**Issue by likegs9** [iuap-design/tinper-bee#527]
## 环境及版本信息

- `tinper-bee` 版本号:  
"tinper-bee": "^2.1.0"

- 若使用单个组件，请标明该组件版本号 ：
树表参照 "ref-tree-table@2.1.3"

- 当前项目中`react`的版本号：
 "react": "16.6.3" 

- 所使用的操作系统：
 Mac 

- 所使用的浏览器：
谷歌 

## 您所在的领域、行业或项目组：
 营销云crm 高姗 

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by XYooo** [comment]
提供下树表参照是哪个包中的。pap-refer还是ref-tree-table

**Comment by XYooo** [comment]
ref-tree-table@2.1.4
