### ISSUE TITLE
RefMultipleTableWithInput带关键字搜索的表格参照，选择每页显示条数时，并未按照关键词重新加载表格。

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#529]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.0

- 若使用单个组件，请标明该组件版本号："pap-refer" : "1.1.0-beta.4"

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows、Mac

- 所使用的浏览器：当前主流浏览器

## 描述这个问题:
RefMultipleTableWithInput带关键字搜索的表格参照，选择每页显示条数时，并未按照关键词重新加载表格。
如图为切换页签时的效果，表格数据正确
<img width="1711" alt="切换页签" src="https://user-images.githubusercontent.com/22900344/74136370-dee25880-4c28-11ea-9aa7-05497e9122bf.png">
如图为选择每页显示条数效果，表格数据不正确
<img width="1703" alt="切换显示条数" src="https://user-images.githubusercontent.com/22900344/74206201-4ba33480-4cb5-11ea-8440-79d48be1a521.png">

**Comment by lucian55** [comment]
pap-refer@1.1.1 已解决

**Comment by MINGXINICE** [comment]
安装完这个版本后项目起不来了，这里少东西吧
![image](https://user-images.githubusercontent.com/22900344/82115006-c0917900-9792-11ea-9634-0fcd6f17bf7d.png)
@liushaozhen
