### ISSUE TITLE
Select组件，滑动滚轮时，显示的下拉框也会随着滚轮动，不会停留在页面正确位置上

### ISSUE THREAD

**Issue by majfd** [iuap-design/tinper-bee#53]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:
滑动滚轮时，显示的下拉框也会随着滚轮动，不会停留在页面正确位置上

#### 当前的行为:
import Select from 'bee-select';

**Comment by BoyuZhou** [comment]
@majfd  Select有一个getPopupContainer的props，提供要显示的容器，如果是单独的模态框，可以使用给模态框增加id。

```
getPopupContainer = {（）=> document.querySelector('#modalId')}
```
这样的形式。来解决
