### ISSUE TITLE
bigDataTable组件expandRowByClick设置为true变整行展开箭头不应消失

### ISSUE THREAD

**Issue by mapkab** [iuap-design/tinper-bee#530]
## 环境及版本信息

- `tinper-bee` 版本号:  2.2.1

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16

- 所使用的操作系统：Windows/Mac OS

- 所使用的浏览器：Chrome

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by lucian55** [comment]
bee-table@2.2.36
已解决
