### ISSUE TITLE
Clipboard 组件复制提示文本位置显示错误

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#533]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.4

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：16.8.6

- 所使用的操作系统：Mac

- 所使用的浏览器：Chrome 79.0.3945.130

### 1、组件相关代码
代码粘贴区域：
```

<Clipboard text={trigUrl}>{trigUrl}</Clipboard>

```

### 2、报错信息

组件源码中使用 Tooltip 组件时，传入安 positionTop="20px" 属性会导致 复制 提示文本位置显示错误

![image](https://user-images.githubusercontent.com/20429458/74803860-732f7800-5319-11ea-8c51-a13f4a6de322.png)

**Comment by yangchch6** [comment]
- bee-clipboard@2.0.5
    - [Fixbug] 复制提示文本位置显示错误

稍后发布 tinper-bee
