### ISSUE TITLE
Select下拉组件的placeHolder不显示

### ISSUE THREAD

**Issue by wangxinyu666666** [iuap-design/tinper-bee#536]
### 1、组件相关代码

代码粘贴区域：
<Select
                                placeholder={item.placeHolder}
                                onChange={(value, options) => this.handleSelect(value, options, code, index)}
                                defaultValue={item.defaultValue}
                                value={record[item.code]}
                                multiple={item.mutiFlag}
                                disabled={data.length ? false : true}
                                allowClear
 >
<Select
                            placeholder={item.placeHolder}
                            {
                                ...getFieldProps(item.code, {
                                    onChange: (value, options) => this.formHandleSelect(value, options, code),
                                    validateTrigger: 'onChange',
                                    initialValue: formData[item.code] || i_default,
                                    rules: rules,
                                })
                            }
                            data={data}
                            disabled={data.length ? false : true}
                            multiple={item.mutiFlag}
                            allowClear
 />
### 2、报错信息

![image](https://user-images.githubusercontent.com/26834996/75222078-4e864500-57de-11ea-8843-dc056f75372f.png)

![image](https://user-images.githubusercontent.com/26834996/75222049-41695600-57de-11ea-8ae4-b1aeb02381a9.png)
这两个图中defaultValue是null的时候，下拉框不能正常显示placeHolder，第一张图中的value是空字符串。

**Comment by yangchch6** [comment]
- bee-select@2.0.26
    - [Fixbug] 修复 placeholder 显示问题

稍后发布 tinper-bee
