### ISSUE TITLE
树参照异步懒加载后有children但不展开

### ISSUE THREAD

**Issue by likegs9** [iuap-design/tinper-bee#539]
## 环境及版本信息

- `tinper-bee` 版本号:  

使用组件版本号
 "bee-tree@2.0.11"
"ref-tree@2.1.3"

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：
crm 营销云 高姗

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
有没有环境看下
