### ISSUE TITLE
树形组件onSelect事件bug

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#54]
单层树形组件，无checkbox，设置onSelect事件。
对同一叶子节点点击两次，第二次触发的onSelect事件传入参数为空，无法获取到key值

**Comment by BoyuZhou** [comment]
@791045873  不知道你是什么样的需求，这个地方，我们是这么处理逻辑的，第一次点击为选中，第二次点击为取消选中。onSelect返回的参数是，第一个参数为当前选中的数组，所以第二次点击为空数组，第二个参数是对象，可以获取是否被选中，当前选中的数组等信息，你可以console出来看一下。
