### ISSUE TITLE
参照 数据显示不出来

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#545]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.1.0",
- 若使用单个组件，请标明该组件版本号：

"ref-multiple-table": "^2.1.4",

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

某个参照的数据
cvendoridId: "0haA0mKkiSIiWh8kb8mZ"
cvendoridCode: "GYS201912317475"
cvendoridName: "ITOCHU PLASTICS PTE.,LTD."

注意 cvendoridName 有个英文逗号
这个名称显示不出来
## 期望的行为:

希望能作为一个值显示出来  感觉是被当做多选处理了

**Comment by ranyanchuan** [comment]
那个版本参照？那个类型参照？ 具体一些，好定位
