### ISSUE TITLE
消息提醒，设置了position:'topRight' ,位置不对,显示在了左上角

### ISSUE THREAD

**Issue by Zzhufeichao** [iuap-design/tinper-bee#547]
## 环境及版本信息

- `tinper-bee` 版本号:   "tinper-bee": "^2.3.4"

- 若使用单个组件，请标明该组件版本号：

 import Message from 'bee-message';
import 'bee-message/build/Message.css';

- 当前项目中`react`的版本号：

"react": "^16.8.6",
- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

  Message.destroy();
  Message.create({content: '请选择取样点', position: 'topRight', color: 'warning', duration: 30});
```
## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/30830131/76600026-236f5580-6541-11ea-83b6-5bd9481c9856.png)
![Uploading image.png…]()

**Comment by yangchch6** [comment]
tinper-bee@2.3.4 未复现问题
