### ISSUE TITLE
分页组件bug

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#55]
当分页组件items为11的时候：
不显示第一个页签，且激活页签样式也不显示。
当我修改items为12，就可以正常显示。
在其他页面将正确显示的分页组件items改为11，同样出现问题。
有可能是一个特殊的bug。

**Comment by HuYuee** [comment]
能否给出使用的代码，看你使用哪些参数。我这边测试了是没有问题的！可以参考我这边的[在线示例](https://codesandbox.io/s/2kz4v4qjn)

**Comment by 791045873** [comment]
items={this.props.totalPage}
					activePage={this.state.activePage + 1}
					pre
					next
					first
					last
					onSelect={this.handleSelect}
					maxButtons={10}
					size="sm"
					ellipsis={true}

**Comment by HuYuee** [comment]
请下载最新版V1.0.2即可解决上面的问题，并将参数`pre`=>`prev`。文档api书写错误，可以参考示例中的代码。

**Comment by 791045873** [comment]
"tinper-bee": "^1.1.1"，我的版本是1.1.1，

**Comment by BoyuZhou** [comment]
@791045873  可以下载最新的1.2.1版本

**Comment by HuYuee** [comment]
@791045873 你可以单独引入bee-pagination，可以参考[在线示例](https://codesandbox.io/s/2kz4v4qjn)
