### ISSUE TITLE
在模态框组件（bee-modal）里面引用剪贴板组件（bee-clipboard），这个剪切板不起作用，还是我上一次复制的内容，但是点击复制确实已经触发了success方法了。

### ISSUE THREAD

**Issue by 21duxue** [iuap-design/tinper-bee#550]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"bee-modal": "^2.1.11",
 "bee-clipboard": "^2.0.3",

- 当前项目中`react`的版本号：

React v15.4.2
- 所使用的操作系统：

Windows
- 所使用的浏览器：

谷歌
### 1、组件相关代码

在模态框组件（bee-modal）里面引用剪贴板组件（bee-clipboard），这个剪切板不起作用，还是我上一次复制的内容，但是点击复制确实已经触发了success方法了。
代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
没看到代码描述，猜测是 action 属性使用错误。
action="cut" 只支持 textarea。可以改为 action="copy"。

![image](https://user-images.githubusercontent.com/33412781/87512528-c1b72780-c6a9-11ea-8a11-4e8052e0b0e8.png)
