### ISSUE TITLE
嵌套使用Tabs无法设置tabBarPosition

### ISSUE THREAD

**Issue by wade555** [iuap-design/tinper-bee#554]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号：2.1.6

- 当前项目中`react`的版本号：16.9.0

- 所使用的操作系统：
Mac

- 所使用的浏览器：
谷歌

## 您所在的领域、行业或项目组：
NC公共产品部 NCCLOUD

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述
当嵌套使用时，无法设置当前Tab的tabBarPosition，一直跟它的上一级的Tab相同

![image](https://user-images.githubusercontent.com/22613582/77992677-2186fe00-7359-11ea-8217-bb6e1877df4a.png)

## 期望的行为:

外层横向排列，嵌套Tab竖向排列

**Comment by yangchch6** [comment]
问题已解决，升级 bee-tabs@2.1.6-nc.0 即可
