### ISSUE TITLE
表格参照RefMultipleTable表格选择每页显示的条数时，不支持根据已有查询条件过滤数据

### ISSUE THREAD

**Issue by xiaolanzi** [iuap-design/tinper-bee#555]
## 环境及版本信息

"tinper-bee": "2.2.3",

- 若使用单个组件，请标明该组件版本号：
"pap-refer":"1.0.8"

- 当前项目中`react`的版本号：
"react": "16.6.3",

- 所使用的操作系统：
win7

- 所使用的浏览器：
版本 79.0.3945.88（正式版本） （64 位）

## 您所在的领域、行业或项目组：
深圳用友-中兴项目组

## 描述这个问题:
RefMultipleTable所在的路径为'pap-refer/lib/pap-common-table/src/index.js'，该参照在进行一页显示多少条的条数切换时，并没有根据已有的查询条件过滤数据
### 1、组件相关代码

代码粘贴区域：
```
RefMultipleTableBase.js
_this2.dataNumSelect = function (index, pageSize) {
	var filterInfo = _this2.filterInfo;

	(0, _keys2["default"])(filterInfo).forEach(function (key) {
		if (!filterInfo[key]) {
			delete filterInfo[key];
		}
	});
	_this2.currPageIndex = 1; //激活页码
	var param = {
		'refClientPageInfo.currPageIndex': 0,
		'refClientPageInfo.pageSize': pageSize
	};
	if ((0, _keys2["default"])(filterInfo) > 0) {
		param.content = (0, _stringify2["default"])(filterInfo);
	}
	_this2.pageSize = pageSize;
	_this2.loadTableData(param);
};
//param的参数缺少查询条件content
```

### 2、报错信息
当输入查询条件，选择切换每页选择的条数时，忽略了查询条件的过滤

## 当前的行为：效果（可截图说明）及动作描述
当输入查询条件，选择切换每页选择的条数时，忽略了查询条件的过滤

## 期望的行为:
当输入查询条件，选择切换每页选择的条数时，支持查询条件的过滤

**Comment by lucian55** [comment]
pap-refer@1.1.1
[ bugfix ] 点击分页查询没有带上查询条件
