### ISSUE TITLE
无数据的时候能否不要显示not found

### ISSUE THREAD

**Issue by limingk** [iuap-design/tinper-bee#556]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
  "ac-city-select": "0.0.6"

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
无数据的时候下拉框里能否不显示not found，显示为空或者可以自定义

![image](https://user-images.githubusercontent.com/53895503/78227975-aeb88700-7500-11ea-9738-4e2af9fe4a48.png)

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 期望的行为:
显示为空或者可以自定义

**Comment by liushaozhen** [comment]
emptyText 可以自定义

**Comment by yangchch6** [comment]
升级 ac-city-select@0.0.7，支持设置 `notFoundContent`，自定义无数据时显示内容。
