### ISSUE TITLE
表头改变列宽回调有时获取列key为空

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#557]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.1.5"
- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "^2.1.4",
- 当前项目中`react`的版本号：

"react": "16.6.3",
- 所使用的操作系统：

windows10
- 所使用的浏览器：

Google Chrome 80.0.3987.162（正式版本）
## 您所在的领域、行业或项目组：

icbc孙康
### 1、组件相关代码

代码粘贴区域：
```

//改变列宽事件
    onDropBorder = (e,width)=>{
        console.log(e,"e")
        console.log(width,"width")
        let onDropBorder_key = e.target.getAttribute("data-line-key")
        console.log(onDropBorder_key,"onDropBorder_key")
    }

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/37610457/78337033-e556d600-75c2-11ea-8547-5694a17d20c1.png)
![image](https://user-images.githubusercontent.com/37610457/78337070-fb649680-75c2-11ea-8dcd-e212a9e7842c.png)
![image](https://user-images.githubusercontent.com/37610457/78337107-10412a00-75c3-11ea-9dbe-f096e39f265e.png)

## 当前的行为：效果（可截图说明）及动作描述

改变表头宽度时，有时获取的表头key为空
## 期望的行为:

因需求需要将表头的宽度存入后台，没有key无法定位到是哪一列，需要更改列宽时能准确获取列的key值

**Comment by yangchch6** [comment]
bug 未复现。可以查看 e.target 是否正确：

![image](https://user-images.githubusercontent.com/33412781/87654295-43ca4d80-c789-11ea-80c1-320e18169626.png)
