### ISSUE TITLE
表头隐藏列后再进行拖拽，会将隐藏的字段排到最后面

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#558]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.1.5",
- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "^2.1.4",
- 当前项目中`react`的版本号：

"react": "16.6.3",
- 所使用的操作系统：

window10
- 所使用的浏览器：

Google Chrome  80.0.3987.162（正式版本）
## 您所在的领域、行业或项目组：

icbc 孙康
### 1、组件相关代码

代码粘贴区域：
```

 //拖拽改变顺序事件
    onDragEnd = (event,data,columns) => {
        console.log(columns,"columns")
    }

```

### 2、报错信息

隐藏列
![image](https://user-images.githubusercontent.com/37610457/78337847-416e2a00-75c4-11ea-9dd0-bceaaf021b27.png)
隐藏完后拖拽，改变列顺序
![image](https://user-images.githubusercontent.com/37610457/78337937-6b275100-75c4-11ea-9b58-1f8f594f6f5b.png)
![image](https://user-images.githubusercontent.com/37610457/78337965-7c705d80-75c4-11ea-8984-b91f1d1e6400.png)

## 期望的行为:

希望，隐藏列在拖拽完后还能在原来的位置

**Comment by yangchch6** [comment]
设计如此
