### ISSUE TITLE
表头初始化可以 设置升序降序图标和升序降序的状态

### ISSUE THREAD

**Issue by KaneSunk** [iuap-design/tinper-bee#559]
## 环境及版本信息

- `tinper-bee` 版本号:  

"tinper-bee": "^2.1.5"
- 若使用单个组件，请标明该组件版本号：

"bee-complex-grid": "^2.1.3"
- 当前项目中`react`的版本号：

"react": "16.6.3"
- 所使用的操作系统：

mac
- 所使用的浏览器：

Google Chrome80.0.3987.149
## 您所在的领域、行业或项目组：

icbc孙康
## 描述这个问题:
表头初始化可以设置升序降序图标和升序降序的状态；
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

表头初始化不可以设置升序降序图标和升序降序的状态；
## 期望的行为:

表头初始化可以设置升序降序图标和升序降序的状态

**Comment by yangchch6** [comment]
设计如此，多列排序场景，后一列依赖于前一列的排序结果，无法作为初始状态渲染。该需求只适用于单列排序，不具备通用性。
