### ISSUE TITLE
上传控件相关问题

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#56]
我们在上传一个文件的同时，希望能够在请求体里携带文件的相关信息。
查看了文档后，发现有data这个参数可以设置上传参数，但是后台接收不到内容。
请问一下这个参数的正确用法。

**Comment by BoyuZhou** [comment]
@791045873  data会以form的形式提交给后台

**Comment by 791045873** [comment]
@BoyuZhou data携带的数据必须手动转换成JSON的格式，不然无法正确携带，希望能默认自动处理

**Comment by BoyuZhou** [comment]
@791045873  你的问题解决了是吗？这块我们尽快优化
