### ISSUE TITLE
在移动端的时候，没有阻止事件冒泡

### ISSUE THREAD

**Issue by MissEcho** [iuap-design/tinper-bee#560]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.3.5

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

16.8.6
- 所使用的操作系统：

window

- 所使用的浏览器：

谷歌， 80.0.3987.163
## 您所在的领域、行业或项目组：

明日集团，业务中台项目

## 描述这个问题:
在移动端，监听echarts的点击事件，进行弹窗modal操作的时候，会出现闪现。
《点击柱状图的item，显示modal，会一闪而过。代码排查发现modal先show，然后继续调用modal的onHide事件》
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
传 `backdropClosable={false}`
