### ISSUE TITLE
想使用filterUrlFunc实现表参照旁边那个输入框简单搜索功能，文档没有介绍如何使用。

### ISSUE THREAD

**Issue by zhanp0304** [iuap-design/tinper-bee#561]
## 环境及版本信息

- `tinper-bee` 版本号:  

    "tinper-bee": "2.3.5",
- 若使用单个组件，请标明该组件版本号：

    "tinper-bee": "2.3.5",
- 当前项目中`react`的版本号：

    "react": "^16.7.0",
- 所使用的操作系统：

Windows
- 所使用的浏览器：

Google Chrome  80.0.3987.163
## 您所在的领域、行业或项目组：

Toncent IT 江展鹏
## 描述这个问题:
表格参照RefMultipleTable组件，想要替代例子中的filterUrl,改用filterUrlFunc，因为要实现带token查询。但是filterUrlFunc不知道怎么写，官方文档没有使用示例。
### 1、组件相关代码

  filterUrlFunc = (value)=>{
    // console.log(`value:${value}`);
    return request(`/api/blade-record/custom/detail/queryFormBody?content=${value}`);
  };
代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
1、filterUrl 实现快捷搜索
input 中输入的内容，会作为过滤参数请求 filterUrl 接口，取回数据自动更新下拉面板的过滤结果

2、filterUrlFunc+filterData 实现快捷搜索
在没有 filterUrl 的情况下，input 中输入的过程中，会调用 filterUrlFunc 回调，参数是 input 中输入的内容。用户可在 filterUrlFunc 方法中自定义请求，将处理后的过滤结果（filterData）存储起来。然后更新传给参照的 filterData 属性，这样同样会更新下拉过滤面板内容

```
filterUrlFunc = (value) => {
    fetch(requestUrl, {
      content: value,
      token: 'xxxxx'
    }).then((response) => {
      let { data } = response;
      this.setState({
        filterData:data,
      });
    });
 }
render(){
   <RefMultipleTableWithInput
          {...childrenProps}
          valueField={valueField}
          inputDisplay={inputDisplay}
          displayField={displayField}

          filterUrlFunc={this.filterUrlFunc}
          filterData={this.state.filterData}
    />
}
```
