### ISSUE TITLE
单选表格的表头不能实现多功能操作例如（拖拽表头伸缩表格横向大小）

### ISSUE THREAD

**Issue by jamin44** [iuap-design/tinper-bee#567]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
可以实现，参考示例：http://bee.tinper.org/tinper-acs/bee-complex-grid#%E9%AB%98%E7%BA%A7%E8%A1%A8%E6%A0%BC(%E5%8D%95%E9%80%89)%E5%BA%94%E7%94%A8
