### ISSUE TITLE
Table组件合计功能无法使用

### ISSUE THREAD

**Issue by guluowuhen** [iuap-design/tinper-bee#57]
### Bug 报告

- __Package version(s)__: "bee-table": "^1.0.6"

#### 描述这个问题:

我想对表格中的金额使用合计功能，这是Table的参数。
```
<Table
    className="bd-table"
    bordered 
    columns={ensureColumns} 
    data={expenseData} 
    scroll={{x: 1500}}
    rowKey={record => record.id.value}
/>
```
金额的column使用了render进行了格式化（保留两位小数）。
```
{ 
    title: '担保金额', 
    key: 'guaamount', 
    dataIndex: 'guaamount.value', 
    width: 120,
    render: (text, record,index) => {
        return (
            <span>{Number(record.guaamount.value).formatMoney(2,'')}</span>
        );
    } 
} 
```
我按照文档中表格合并demo的写法。
```
import Table from 'bee-table';
import Sum from "../../.../utils/sum.js";
const SumTable = Sum(Table);
class Demo13 extends Component {
...
render(){
    return (
    	<SumTable
    	    className="bd-table"
            bordered 
            columns={ensureColumns} 
	    data={expenseData} 
	    scroll={{x: 1500}}
    	/>
    );
}
}
```

然而并没有起作用（合计行倒是出来了，但是金额没有进行计算），而且横向滚动也没有了。

#### 当前的行为:

我看了下sum.js的源码，最后return的Table组件没有把props放进去。
```
sum.js
--------------
render() {
      return (
        <Table
          columns={this.props.columns}
          data={this.props.data}
          footer={this.currentFooter}
        />
      );
    }
```

#### 期望的行为:

多测几个使用场景保证无明显bug，还有希望简化新增功能的调用方法，例如直接在columns增加字段，就不需要引其他js

**Comment by HuYuee** [comment]
@guluowuhen 可以参考此[在线示例](https://codesandbox.io/s/kmllk6144r)

**Comment by guluowuhen** [comment]
@HuYuee 我知道简单Table合计是可以显示出来，但是给Table加一些参数比如：scroll:{{x:1000}}之后合计就不生效了，而且横向滚动也没有了。bug原因我写在问题描述里了，你们可以再检查下sum.js

**Comment by HuYuee** [comment]
@guluowuhen 针对于你提到的问题，现在最新版已修复。可以下载v1.0.7进行使用。针对你之前提到的调用方式，在这里我说明下，现在这些新增的功能就是考虑通过以插件的方式来维护，以达到热插拔，并且功能相互独立，以便于以后的维护和管。不过在使用中，你可以在整个工程中定义好自己需要的复合型table的功能，之后直接使用你组装的复合型table组件就好了。
