### ISSUE TITLE
弹出框使用tabs的下划线长度计算错误，下划线无法正常展示

### ISSUE THREAD

**Issue by lizhixiu** [iuap-design/tinper-bee#570]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.3.6
- 若使用单个组件，请标明该组件版本号：

页签 Tabs，3.0.0
- 当前项目中`react`的版本号：

^16.8.6
- 所使用的操作系统：

mac
- 所使用的浏览器：

Chrome
## 您所在的领域、行业或项目组：

tinper-bee初学者。
联系邮箱:82015742@qq.com

### 1、组件相关代码

代码粘贴区域：
```

      <Tabs
            defaultActiveKey="1"
            onChange={this.onChange}
            className="demo1-tabs"
        >
            <TabPane tab='Tab 1' key="1">Content of Tab Pane 1</TabPane>
            <TabPane tab='Tab 2' key="2">Content of Tab Pane 2</TabPane>
            <TabPane tab='Tab 3' key="3">Content of Tab Pane 3</TabPane>
        </Tabs>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/7358936/80005993-e1014700-84f6-11ea-8eeb-d3dfa05ee524.png)

## 当前的行为：效果（可截图说明）及动作描述

1、在列表页面，添加点击事件，弹窗页面，tabBar使用默认simple因为无法计算下划线宽度导致。

## 期望的行为:

弹窗使用tabs的默认样式也能如下图展示。
![image](https://user-images.githubusercontent.com/7358936/80006378-62f17000-84f7-11ea-93e2-a4e0cb58f0a5.png)

**Comment by yangchch6** [comment]
bug 未复现

![image](https://user-images.githubusercontent.com/33412781/87635168-30ab8380-c771-11ea-9f6a-25bc5c5e35cb.png)
