### ISSUE TITLE
Popover没有标识是否展开的类名

### ISSUE THREAD

**Issue by Toxic12138** [iuap-design/tinper-bee#574]
## 环境及版本信息

- `tinper-bee` 版本号:  "bee-popover": "3.1.0",

- 若使用单个组件，请标明该组件版本号："bee-popover": "3.1.0",

- 当前项目中`react`的版本号："react": "^16.9.0",

- 所使用的操作系统：Windows

- 所使用的浏览器：Google Chrome 版本 81.0.4044.129（正式版本） （64 位）

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by lucian55** [comment]
无法定位，关闭
