### ISSUE TITLE
树参照RefTree设置了Value的值，无法生效

### ISSUE THREAD

**Issue by zhanp0304** [iuap-design/tinper-bee#577]
## 环境及版本信息

- `tinper-bee` 版本号:  

2.3.5
- 若使用单个组件，请标明该组件版本号：

2.0.15 ref-tree
- 当前项目中`react`的版本号：

16.7.0
- 所使用的操作系统：

Win 10
- 所使用的浏览器：

谷歌最新版
### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
无效问题
