### ISSUE TITLE
RefTree不支持mustExpandable（展开不可用的节点）

### ISSUE THREAD

**Issue by limingk** [iuap-design/tinper-bee#578]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.3.2

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：
windows

- 所使用的浏览器：
chrome

## 您所在的领域、行业或项目组：
用友网络 智能制造事业部

### 1、组件相关代码
区域组件，只允许选中叶子节点，但是默认是不展开的，所以上级节点需要不可选，但是要允许展开。目前如果设置了treeNodeDisabledKey属性，上级节点变成不可选，但是不能展开了。需要支持展开。
 根据杨晨晨说的设置mustExpandable ={true}，但是不起作用

## 期望的行为:
设置mustExpandable ={true}，可以展开上级节点

**Comment by yangchch6** [comment]
mustExpandable 是 bee-tree 的属性，tree 相关的属性在 treeProps 属性中传入，API 中有说明。
不可选的节点支持展开收起，正确的设置如下：
```
treeProps={{mustExpandable:true}}
```
