### ISSUE TITLE
Tooltip onVisibleChange单独使用不生效，需同时控制visible

### ISSUE THREAD

**Issue by Toxic12138** [iuap-design/tinper-bee#579]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号："bee-tooltip@2.1.7"

- 当前项目中`react`的版本号："react": "^16.9.0",

- 所使用的操作系统：Windows

- 所使用的浏览器：Google Chrome 版本 81.0.4044.129（正式版本） （64 位）

### 1、组件相关代码

代码粘贴区域：
```
<Tooltip onVisibleChange={this.handleTooltipVisible} inverse placement='bottom' overlay={this.getTooltip('图形展示')}>
          <Button className='chart-svg-icon'>图形展示</Button>
        </Tooltip>

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/31759928/81534407-9149c900-939a-11ea-97a0-a7a5fae9db4a.png)

## 当前的行为：效果（可截图说明）及动作描述

onVisibleChange单独使用不生效，需同时控制visible

## 期望的行为:

并不想控制visible 只想使用其状态

**Comment by yangchch6** [comment]
问题已修复，需要升级 bee-tooltip@2.1.8
