### ISSUE TITLE
Table多选组件支持初始化时默认选中某几行

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#58]
目前的场景：
做一个权限分配的页面，用table组件显示了所有的权限，用户自己勾选所需要的权限，然后分配。
现在需要在初次渲染的时候，给定一个默认的选中值。就像Tree组件一样，默认勾选哪几个

**Comment by HuYuee** [comment]
现在V1.0.9已支持，使用selectedRow参数即可
