### ISSUE TITLE
树参照的搜索框无法设置placerholder

### ISSUE THREAD

**Issue by yadxzxf** [iuap-design/tinper-bee#583]
## 环境及版本信息

- `tinper-bee` 版本号:  

"ref-tree": "2.1.1",
 "tinper-bee": "^2.3.2",
- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

Windows
- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
- ref-tree@2.1.4
    - [Feature] 增加 searchPlaceholder 参数，设置搜索框的默认显示文字
