### ISSUE TITLE
Ac-Grid组件的渲染的select类型传入showSearch属性做成支持搜索的不生效；以及datePicker传入的datePicker默认值moment()会报错

### ISSUE THREAD

**Issue by zhanp0304** [iuap-design/tinper-bee#584]
## 环境及版本信息
Win 10 ; 
- `tinper-bee` 版本号:  

v2.3.5
- 若使用单个组件，请标明该组件版本号：

Ac-grid 0.2.12； bee-datepicker 2.3.24
- 当前项目中`react`的版本号：

React 16.7.0
- 所使用的操作系统：

Win10
- 所使用的浏览器：

谷歌
## 您所在的领域、行业或项目组：

IT行业   用友代理  江展鹏
## 描述这个问题:
1. Ac-Grid组件的渲染的select类型传入showSearch属性做成支持搜索的不生效；
2. Ac-Grid组件渲染得DatePicker往filedProps里传入的默认值defaultValue:moment()会报错

![image](https://user-images.githubusercontent.com/38825329/82188608-b3a29000-9920-11ea-85bb-86d4e6cf0fd7.png)

### 1、组件相关代码

![image](https://user-images.githubusercontent.com/38825329/82188624-b8674400-9920-11ea-8ab3-756961a710b9.png)

代码粘贴区域：
```
1.         {
          dataIndex: 'aaa',
          key:"aaa",
          width:"200px",
          textAlign:'center',
          renderType:'select',
          required:true,
          validate:true,
          filedProps:{
            showSearch:true,
            options:[],
            optionFilterProp:"children",
          }
        },
2. {
          dataIndex: 'ccc',
          key:"ccc",
          width:"200px",
          textAlign:'center',
          renderType: 'datepicker',
          required:true,
          validate:true,
          filedProps:{
            defaultValue:moment()
          }
        }
```

### 2、报错信息

![image](https://user-images.githubusercontent.com/38825329/82188719-e2206b00-9920-11ea-9630-8546c281e10e.png)

**Comment by yangchch6** [comment]
- ac-grids@0.2.17
    - [Fixbug] select类型支持showSearch属性
