### ISSUE TITLE
AcGrid组件如果初始化表格是没数据的，或者全部删掉了，那么选中时，是没序号的（内部没index值），会报错！

### ISSUE THREAD

**Issue by zhanp0304** [iuap-design/tinper-bee#586]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

AcGrid 0.2.11
- 当前项目中`react`的版本号：

- 所使用的操作系统：

Win 10
- 所使用的浏览器：

## 您所在的领域、行业或项目组：

IT行业 用友代理 江展鹏
### 1、组件相关代码

代码粘贴区域：
```

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/38825329/82193691-50b4f700-9928-11ea-9a7c-142f97cbc511.png)

**Comment by lucian55** [comment]
ac-grids@0.2.13 已解决
