### ISSUE TITLE
上传列表 AcAttachment批量下载问题

### ISSUE THREAD

**Issue by yanhuanl** [iuap-design/tinper-bee#589]
## 环境及版本信息
version": "0.3.7",
"resolved": "https://registry.npm.taobao.org/ac-attachment/download/ac-attachment-0.3.7.tgz",
代码
<AcAttachment                                  
    className="upload-box"
    disabled={PriceInfoForbid || submitForbid || authority }
    recordId={id}
    groupname='abc'
    onDelete={(attach) => {
        _this.setState({delPicModalVisible: true});
        _this.attach = attach;
     }}
>
	<Button
		data-btn="upload"
        className="ml8"
        colors="primary" size='sm'
        >上传</Button>
    <Button
        data-btn="download"
        className="ml8"
        shape="border"
        size='sm'>下载</Button>
    <Button
        data-btn="delete"
        className="ml8"
        shape="border"
        size='sm'
    >删除</Button>
</AcAttachment>
问题：
批量下载存在问题，勾选多行依旧下载第一条
上传下载按钮权限可以分开控制？

**Comment by yangchch6** [comment]
请标明项目名称

**Comment by yangchch6** [comment]
ac-attachment 支持批量下载，是循环打开页面下载 ，不是下载 zip。可以查看下载多条的时候，是否被浏览器拦截，如果拦截，点下允许下载就行了。
