### ISSUE TITLE
Menu组件主题为dark，点开一级目录后，鼠标从一级目录移出，该目录有闪烁

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#59]
Menu组件主题为dark，点开一级目录后，鼠标从一级目录移出，该目录有闪烁。
![demo](https://user-images.githubusercontent.com/12742472/34510828-3cf3a978-f092-11e7-930a-4c28b632740e.gif)

**Comment by HuYuee** [comment]
V1.0.5已修复
