### ISSUE TITLE
树表参照 选择完数据 再次点击参照点击已选时  已选数据不显示 编码名称 【项目着急麻烦尽快看下谢谢】

### ISSUE THREAD

**Issue by likegs9** [iuap-design/tinper-bee#590]
## 环境及版本信息

- `tinper-bee` 版本号:  "tinper-bee": "^2.1.0"

- 若使用单个组件，请标明该组件版本号： "ref-tree-table": "^2.1.3",

- 当前项目中`react`的版本号："react": "16.6.3",

- 所使用的操作系统：mac

- 所使用的浏览器：谷歌

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

第一次选择
![image](https://user-images.githubusercontent.com/10152771/82971856-4a004100-a006-11ea-9337-c13d3982c2d1.png)
第二次打开参照 查看已选
![image](https://user-images.githubusercontent.com/10152771/82971883-5d131100-a006-11ea-81cb-5c70d4574745.png)

**Comment by yangchch6** [comment]
已解决
