### ISSUE TITLE
下拉里面带滚动条的情况下，没法正常滚动到下方进行选值操作

### ISSUE THREAD

**Issue by Dio-Zhu** [iuap-design/tinper-bee#595]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的领域、行业或项目组：
低代码平台-设计器 ，可以联系 李英 。

### 1、组件相关代码

登录：
u8c-daily。
13146634152  yonyou123

访问设计器地址：
https://build.yyuap.com/apps/quickdev/#/onepage/design/GT1542AT41/GT2249PT302/ysmdd

![image](https://user-images.githubusercontent.com/20452648/84637734-a3ce9980-af28-11ea-8811-ca2b9999b2a7.png)

代码粘贴区域：
```


```

**Comment by yangchch6** [comment]
下拉选项的 option 中 value 重复时会出现此问题，渲染 option 时，需要保证数据 value 的唯一性
