### ISSUE TITLE
配合form使用的MonthPicker， initialValue为string，就报错

### ISSUE THREAD

**Issue by huangdandan** [iuap-design/tinper-bee#596]
## 环境及版本信息

- `tinper-bee` 版本号:  

 "tinper-bee": "2.2.3",
- 若使用单个组件，请标明该组件版本号：

"bee-datepicker": "^2.3.24",
- 当前项目中`react`的版本号：

"react": "16.6.3",
- 所使用的操作系统：

mac
- 所使用的浏览器：

all
## 您所在的领域、行业或项目组：

江西数字民政--黄丹丹
## 描述这个问题:
使用的MonthPicker回显时间格式为''2020-10'，然后就报错，DatePicker版本是2.3.24
### 1、组件相关代码

代码粘贴区域：
```
  <MonthPicker
                        format='YYYY-MM'
                        {
                            ...getFieldProps('execDate',{
                               // initialValue:execDate,
                                initialValue:'2020-10',
                                normalize:(value)=>{
                                    if(value&&value.format){
                                        return value.format('YYYY-MM')
                                    }else{
                                        return value
                                    }
                                },
                            })
                        }
                    />

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/9463495/84985906-314ffa80-b170-11ea-8f6d-163ab321fc96.png)
![image](https://user-images.githubusercontent.com/9463495/84985916-357c1800-b170-11ea-9c1a-042db88658e0.png)

## 当前的行为：效果（可截图说明）及动作描述

能正常使用
## 期望的行为:

能正常使用

**Comment by yangchch6** [comment]
bee-datepicker@2.3.24 未复现，确认是否存在多个版本互相影响
