### ISSUE TITLE
表格中没有内容填充时，拖拽列宽很难进行，希望能优化一下。

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#597]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
表体没有内容，至少要有表头撑开列宽。表头/表体均无内容的情况下，建议隐藏该列
