### ISSUE TITLE
V1.3 版本工作任务

### ISSUE THREAD

**Issue by GuoYongfeng** [iuap-design/tinper-bee#60]
## 独立组件任务

| # | 组件名 | 问题描述 | 负责人 | 进度 |
| --- | --- | --- | --- | --- |
| 1 | bee-table | 增加index列 | huyue | 不进行开发 | 
| 2 | bee-table | 单元格宽度设置（先了解下现有能否满足） | huyue | 支持 | 
| 3 | bee-affix | 定位不准 | yaoxin | 提了iusse | 
| 4 | bee-tabs | 增加tab头可配置样式| zby | 已支持，需要增加示例和文档 |
| 5 | bee-datepicker | 多语设置问题 | - | 已支持，需要增加文档 |
| 6 | bee-datepicker | 可输入功能有时不可用 | - | 不好复现，延后 |
| 7 | bee-layout | row和padding的间距问题 | zby | 暂时延后 |
| 8 | bee-form | 易用性修改 | shaozhen | 开发中 |

## 组件库公共任务

| # | 公共任务 | 问题描述 | 负责人 | 进度 |
| --- | --- | --- | --- | --- |
| 1 | 官网文档机制修改 | xx | 胡玥 | 已完成 | 
| 2 | 官网文档增加版本和github链接 | xx | 胡玥 | 已完成 |
| 3 | 官网文档可修改（通过链接到github上面，提交pr的方式） | xx | 胡玥 | 已完成 |
| 4 | 官网文档可上传示例 | xx | 胡玥 | 暂时延后 |
| 5 | 官网菜单和文档分离 | xx | 周博宇 | 开发中 |
| 6 | 所有组件api验证和样式修改 | xx | - | 开发中 |
| 7 | 组件库增加theme功能 | - | 周博宇 | 延后 |

**Comment by BoyuZhou** [comment]
# 问题记录

### 整体问题

- 样式问题

问题：样式覆盖频繁
方案：提供theme主题替换功能，暴露相关可配置

问题：样式覆盖困难（无classname接口，样式包含import，含有内连样式）
方案：所有组件增加classname，去掉样式中的import，去掉内连样式，对于内部样式可修改的暴露相关api

样式，在修改的同时，提取可配置变量。然后我们可以进行西瓜UI适配。


- 文档

问题：文档例子覆盖不全面
方案： 增加各个主要场景和api的使用示例（需评估）

问题： api不全，错别字，描述不清晰（因为本身写的不全，更新不及时）
方案：检查每一个组件api列举。对文档更新做自动化。并且文档弱化单个组件，强调整体tinper-bee包。

问题：资源引用问题，包含组件引用，样式引用，例子单独样式展示
方案：对现有例子系统进行修改，使用markdown书写示例，改变展示和编译脚本。

问题：文档同步问题
方案： 以后不提供单一组件，统一出tinper-bee整体组件库，组件库每周四发版。统计所有修改。对于项目着急的，随时修改，随时发版组件库。

- 官网

问题：菜单栏和内容区域展示不和谐
方案：分离菜单栏和内容区域

问题：使用版本和现有版本不一样
方案：对bee.tinper.org进行版本管理，每一个新版增加tag，对于大版本修改。部署新的版本文档站点

问题：缺少文档直接修改机制
方案：增加链接到github，提供相应版本号，增加示例上传机制

### 单个组件问题

- Affix 定位问题
- 布局组件

问题： 间距设置问题
方案：提供修改间距的配置

讨论是否需要支持24栅格

- 复选框和单选框使用label时，对不齐。也涉及label和input配置的对齐方式。
- datepicker：
   - 多语设置问题。
   - 有的无法删除。
- table问题：
    - table宽度问题。 （定宽和百分比混用）
    - 增加index列
- tabs表头样式问题，增加锚点tabs
- form表单问题：
  - 整体机制需要在讨论
  - input value显示滞后性（试一试onkeydown时限制长度）
  - 校验和校验的布局，校验定制显示
  - 检验和格式化！
  - 设置和取值！
  - 功能不可用，校验有问题。如何批量set值和get值，表单和布局。支持自定义 format 。

 - loading 组件的属性？
 - 日期组件，padding问题？

**Comment by HuYuee** [comment]
[单个组件的链接和changelog](https://github.com/iuap-design/tinper-bee/issues/31)
