### ISSUE TITLE
bee-table 组件的列复制和列粘贴

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#601]
## 您所在的领域、行业或项目组：
您好,我是金融公司的租赁部门中建投项目组, 现在使用tinper-bee 进行前端开发,  现在有一个使用bee-table组件实现 列复制和列粘贴的场景. 
向您咨询一下是否有类似的实现方案.
另外,如果我们想要实现,请您提供宝贵的建议.
我的邮箱: 15117983457@163.com
tinper-bee  版本  2.3.7
react   版本 16.6.3

1、场景一：由系统复制粘贴到excel（复制出来的需要带表头数据项名称），如截图所示
![image](https://user-images.githubusercontent.com/10356530/86073645-c62eee00-bab6-11ea-8a4d-dd94f9d27401.png)
原系统场景补充说明：
![image](https://user-images.githubusercontent.com/10356530/86073676-d5ae3700-bab6-11ea-9010-962f80cfed37.png)
复制所选行结果：
![image](https://user-images.githubusercontent.com/10356530/86073697-e199f900-bab6-11ea-8369-136b06817e61.png)
其他的全选，就是复制所有，同时会把表头均复制出来。
2、场景二：由excel复制粘贴到系统中
①支持单列粘贴
![image](https://user-images.githubusercontent.com/10356530/86073764-09895c80-bab7-11ea-8a12-0a5fa6d84321.png)
![image](https://user-images.githubusercontent.com/10356530/86073790-14dc8800-bab7-11ea-8e71-a498d45405eb.png)
支持多列粘贴；
![image](https://user-images.githubusercontent.com/10356530/86073805-202fb380-bab7-11ea-8151-dc06cffa6ff6.png)
![image](https://user-images.githubusercontent.com/10356530/86073814-245bd100-bab7-11ea-8fa1-dc7ddb116a62.png)
日期格式不是完全匹配，也能导入成功。
③支持参照（如事件类别字段，参照：租金，首付款），数值（租金），日期（收取日期）等数据类型格式粘贴；
![image](https://user-images.githubusercontent.com/10356530/86073837-32115680-bab7-11ea-97c7-89c1d8ba07b1.png)
![image](https://user-images.githubusercontent.com/10356530/86073846-376ea100-bab7-11ea-9b9a-a642904aeafd.png)
![image](https://user-images.githubusercontent.com/10356530/86073851-3a699180-bab7-11ea-8f62-1d11f546e80b.png)

**Comment by yangchch6** [comment]
已处理
