### ISSUE TITLE
2.2.49版本的bee-table的拖拽列宽度，报错

### ISSUE THREAD

**Issue by T95tongT** [iuap-design/tinper-bee#603]
## 环境及版本信息

- `tinper-bee` 版本号:  

tinper-bee@2.3.8
bee-table@2.2.49

- 若使用单个组件，请标明该组件版本号：

是从tinper-bee里引用的table

- 当前项目中`react`的版本号：

react@16.13.1

- 所使用的操作系统：

Windows

- 所使用的浏览器：

谷歌

## 您所在的领域、行业或项目组：

工程云研发部

## 描述这个问题:

当我左右拖拽的时候， 报style为undefined

### 1、组件相关代码

代码粘贴区域：
```

<DragColumnTable  
	style={{width: "48%"}} 
	data={ item.scheduleItemVOS && item.scheduleItemVOS.length ? item.scheduleItemVOS :[]} 
	columns={this.getColumns()}
	onExpand = { (expanded, record)=>{
		this.setState({
			expanded, 
			expandRecord: record,
		})
	}}
	dragborder={true} 
		onDropBorder ={(e,width)=>{
		console.log(width+"--调整列宽后触发事件",e.target);
	}}
></DragColumnTable >

```

### 2、报错信息

[](url)
![image](https://user-images.githubusercontent.com/31124751/86102552-3c9b1280-baee-11ea-876d-5311a6fb71da.png)

**Comment by yangchch6** [comment]
确认 columns 中的每一项是否有 key 值并唯一
![image](https://user-images.githubusercontent.com/33412781/87004288-c84c2780-c1ef-11ea-8b10-baf4e27182a4.png)

**Comment by yangchch6** [comment]
按如上代码尝试 未复现问题
