### ISSUE TITLE
bee-complex-grid合计

### ISSUE THREAD

**Issue by xqk1** [iuap-design/tinper-bee#604]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.7

- 若使用单个组件，请标明该组件版本号：bee-complex-grid@2.1.7

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Mac

- 所使用的浏览器：Chrome 83.0.4103.116

### 1、组件相关代码

代码粘贴区域：
```

```

## 当前的行为：效果（可截图说明）及动作描述

![pastedImage](https://user-images.githubusercontent.com/30168674/86506229-16cc8100-be00-11ea-84f1-b9d72a0cf0fa.png)
合计无法自定义，金额无法增加前位符，百分比等符号，当前只有精度配置的接口。
## 期望的行为:

可以在column上增加一个参数，接收一个函数，去解析合计的值。

**Comment by lucian55** [comment]
bee-table@2.2.53
column传参
sumRender:(value)=>{
      return '1231'
    }
