### ISSUE TITLE
表格过滤交互

### ISSUE THREAD

**Issue by wade555** [iuap-design/tinper-bee#605]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号："bee-table": "2.2.48"

- 当前项目中`react`的版本号："react": "16.9.0",

- 所使用的操作系统：
 Mac

- 所使用的浏览器：
 谷歌83

## 您所在的领域、行业或项目组：
 NC公共产品部-赵继孟

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

**Comment by yangchch6** [comment]
- bee-table@2.2.57
    - [Feature] 条件过滤，输入框输入即查询。filterDelay 设置过滤输入的时候的ms延迟时间。
