### ISSUE TITLE
bee-table rowDraggAble行拖拽排序 需要只能通过前面的把手 拖动

### ISSUE THREAD

**Issue by siriuscandy** [iuap-design/tinper-bee#607]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

bee-table 2.2.49
- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/10221072/87003494-56bfa980-c1ee-11ea-8dc1-2f058072252f.png)

## 期望的行为:

希望能通过参数设置，行不能拖拽，只能通过行最左侧的把手拖拽。 因为行上有编辑input，行拖拽 导致不能用鼠标复制内容

**Comment by yangchch6** [comment]
bee-table@2.2.54 
设置 `useDragHandle={true}`，可使用行把手拖拽行排序
