### ISSUE TITLE
InputNumber组件,输入负数且保留两位小数时,如果不满足两位小数,回显为0.00

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#610]
## 描述这个问题:
在当前tinper官网上,InputNumber组件, 输入负数,且保留两位小数的情况下: 如果,输入数据不满足两位小数时,光标离开,数据变为 0.00 ;
比如输入: -0.10  结果显示为 0.00  期望是: -0.10    
比如输入: -1.00  结果显示为0.00   期望是: -1.00

**Comment by yangchch6** [comment]
bee-input-number@2.2.36 已修复
