### ISSUE TITLE
Table组件多选跟筛选功能同用时报错

### ISSUE THREAD

**Issue by wade555** [iuap-design/tinper-bee#611]
## 环境及版本信息

- `tinper-bee` 版本号:  1.6.3

- 若使用单个组件，请标明该组件版本号："bee-table": "2.2.48"

- 当前项目中`react`的版本号："16.9.0"

- 所使用的操作系统：
 Mac

- 所使用的浏览器：Chrome

### 1、组件相关代码

代码粘贴区域：
```

<Demo className="demo1-input"/>

```

### 2、报错信息

使用： 
![image](https://user-images.githubusercontent.com/22613582/87494815-8b19e680-c682-11ea-9573-c173f7b0b115.png)

![image](https://user-images.githubusercontent.com/22613582/87495024-ffed2080-c682-11ea-81c3-1a8d06309bc2.png)

在onFilterChange时报错信息：
![image](https://user-images.githubusercontent.com/22613582/87495161-45a9e900-c683-11ea-86ca-2dd3fe9be2ce.png)
![image](https://user-images.githubusercontent.com/22613582/87495182-535f6e80-c683-11ea-887e-342d6d6bda2c.png)

## 当前的行为：效果（可截图说明）及动作描述
onFilterChange时，直接报错了，如截图说明中图片

**Comment by yangchch6** [comment]
bee-table@2.2.48 版本未复现bug。确认下是否依赖了老版本
