### ISSUE TITLE
bee-complex-grid组件的分页paginationObj里面改变total参数,总条数数变,分页按钮不变

### ISSUE THREAD

**Issue by lilicoder** [iuap-design/tinper-bee#613]
## 环境及版本信息

- `tinper-bee` 版本号:  
├── tinper-bee@2.3.2 
├─┬ u9-iot-basic-template@0.7.1
│ └── tinper-bee@2.3.2  deduped
└─┬ ucf-fe@0.1.0
  └── tinper-bee@1.5.0 

- 若使用单个组件，请标明该组件版本号：
├─┬ ac-grids@0.2.11
│ └── bee-complex-grid@2.0.28  deduped
├── bee-complex-grid@2.0.28 
├─┬ tinper-bee@2.3.2
│ └── bee-complex-grid@2.0.28  deduped
└─┬ u9-iot-basic-template@0.7.1
  └── bee-complex-grid@2.0.28
- 当前项目中`react`的版本号：
16.12.0 

- 所使用的操作系统：
MAC

- 所使用的浏览器：
![image](https://user-images.githubusercontent.com/24731304/88642312-e7edb600-d0f2-11ea-901d-5dfb9d051eea.png)

## 您所在的领域、行业或项目组：
离散制造与u9开发部 A2 梁莉莉

## 描述这个问题:
bee-complex-grid组件的分页paginationObj里面改变total参数,总条数数变,分页按钮不变。
在didmount里面写定时器更改total参数，总条数更改了，按钮未更改

![image](https://user-images.githubusercontent.com/24731304/88642526-2e431500-d0f3-11ea-88d9-ae5a8d427187.png)

### 1、组件相关代码

```
  constructor(props) {
    super(props);
    this.state = {
        xxx:100
    };
  }

  componentDidMount() {
    this.setState({xxx:200})
}

 <Grid
      className="main-grid"
      columns={props.columns || []}
      rowKey={"equSn"}
      multiSelect={false}
      columnFilterAble={true}
      headerHeight={30}
      showHeaderMenu={false}
      data={props.data || []}
      paginationObj={{ 
                    total: this.state.xxx, //总共多少条
                    activePage: dialogTableParams.pageIndex - 0 + 1,
                    freshData: this.freshData, //点击下一页刷新的数据
                    onDataNumSelect: this.onDataNumSelect, //每页大小改变触发的事件
                    noBorder: true,
                    horizontalPosition: "center",}}
      loadLazy={true}
      heigth={40}
      scroll={{ y: 260 }}
      loading={props.loading}
    />

```

### 2、报错信息
![image](https://user-images.githubusercontent.com/24731304/88643044-cb05b280-d0f3-11ea-9124-028f44aa41c7.png)
200/10应该是总共20页

## 当前的行为：效果（可截图说明）及动作描述
在didmount里面写定时器更改total参数

## 期望的行为:
更改了total参数，按钮也变化

**Comment by yangchch6** [comment]
已修复，删除 node_modules、package-lock.json，重新装包即可
