### ISSUE TITLE
InputNumber组件的最小值控制（min属性）设置为0时，仍然可以输入负数

### ISSUE THREAD

**Issue by wcheng-victor** [iuap-design/tinper-bee#614]
## 环境及版本信息

- 若使用单个组件，请标明该组件版本号：
"bee-input-number": "^2.2.38"

- 当前项目中`react`的版本号：
16.6.3

- 所使用的操作系统：
Windows 10

- 所使用的浏览器：
chrome 84.0.4147.105

## 您所在的领域、行业或项目组：
用友金融，王成

## 描述这个问题:
InputNumber组件将min属性设置为0，仍然可以输入负数
### 1、组件相关代码
代码粘贴区域：
```
import InputNumber from 'bee-input-number';

<InputNumber
    precision={2}
    min={0}
    max={100}
    iconStyle="one"
    className={"input-number"}
/>

```

## 当前的行为：效果（可截图说明）及动作描述
仍然可以输入负数

## 附注：
max属性设为0也会出现仍然能输入正数的问题

**Comment by yangchch6** [comment]
- bee-input-number@2.2.39
    - [Fixbug] 最小值控制（min属性）设置为0时，仍然可以输入负数

升级组件即可
