### ISSUE TITLE
期望参照组件input过滤框中的条目，鼠标悬浮时可以显示全部文字，或加一个title属性

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#615]
## 环境及版本信息

- `tinper-bee` 版本号:   tinper-bee: "^2.2.3"

- 若使用单个组件，请标明该组件版本号：pap-refer: "1.1.0-beta.6"

- 当前项目中`react`的版本号：react: "16.6.3"

- 所使用的操作系统：Windows/Mac

- 所使用的浏览器：当前主流浏览器

## 描述这个问题:  
<img width="328" alt="WechatIMG32" src="https://user-images.githubusercontent.com/22900344/89005459-152aa600-d337-11ea-843a-42cb1a9bbc10.png">

## 期望的行为: 
期望参照组件input过滤框中的条目，鼠标悬浮时可以显示全部文字，或加一个title属性

**Comment by yangchch6** [comment]
已加 title，删除 node_modules、package-lock.json，重新装包即可

**Comment by MINGXINICE** [comment]
@yangchch6 尝试很多次依然没效果，我的引入方式是这样的
![image](https://user-images.githubusercontent.com/22900344/92444333-4b383100-f1e5-11ea-8446-0cc29bd66285.png)

![image](https://user-images.githubusercontent.com/22900344/92446926-2776ea00-f1e9-11ea-81ff-bb1b36ca6696.png)

![image](https://user-images.githubusercontent.com/22900344/92446845-031b0d80-f1e9-11ea-9fe0-53e14e748177.png)
