### ISSUE TITLE
日期组件bee-datepicker,开启了keyboardInput={true} ，使用（日期A）带不出（日期B）的值

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#617]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号："bee-datepicker": "2.3.25"

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:

日期组件bee-datepicker,开启了keyboardInput={true} ，使用（日期A）带不出（日期B）的值

### 1、组件相关代码

```

代码粘贴区域

```

**Comment by yangchch6** [comment]
已修复，升级新版本 bee-datepicker@2.3.27
