### ISSUE TITLE
参照组件及参照修改默认选中问题

### ISSUE THREAD

**Issue by DYKGUILTY** [iuap-design/tinper-bee#619]
## 环境及版本信息

- `tinper-bee` 版本号:  
3.5.6

- 所使用的操作系统：
Windows

## 您所在的部门或项目名称：
mes项目

## 描述这个问题:

1.使用参照组件RefCommon  type只能使用树及表格，也就是1,2类型，其余type全是表格，
2.表格类型参照弹窗，当修改数据时，参照弹窗第一次弹出，默认数据并不会选中，关闭后再次点击修改弹出窗口才会默认选中已有选择，不能达到修改时弹出自动加载数据

第一，只有两种参照类型弹窗，修改type值并不能打开树表，穿梭或者下拉参照
![image](https://user-images.githubusercontent.com/56719856/89281016-06682a00-d67c-11ea-81fa-45b9fc737ff5.png)
第二，修改数据时不能加载默认值，第一次打开不会加载，第二次才会选中
![image](https://user-images.githubusercontent.com/56719856/89281348-87bfbc80-d67c-11ea-9569-1daf79adbfb9.png)
![image](https://user-images.githubusercontent.com/56719856/89281417-a6be4e80-d67c-11ea-93d4-0adcca994ff9.png)
![image](https://user-images.githubusercontent.com/56719856/89281688-074d8b80-d67d-11ea-9a7e-2c4d8e1ee606.png)

## 期望的行为:
希望修改时默认选中已有数据

**Comment by yangchch6** [comment]
没有 refCommon 参照

**Comment by DYKGUILTY** [comment]
是使用代码生成器也就是开发者中心生成的代码，封装的组件，import RefCommon from 'components/RefCommon';这个组件是你们做的吧，但是只能用树和表格，这是第一个问题，我通过原生组件可以做出来，主要是我上面那个第二个问题，默认选中那个

**Comment by yangchch6** [comment]
ucf-common 下的组件是各项目根据业务需要封装的组件，代码生成器只是提供默认功能，里面的逻辑可以根据场景自行修改，我们维护的是原生组件-发布到 npm 上的包，默认选中那个问题，直接使用原生组件没有问题，需要你排查下 refCommon 代码

**Comment by DYKGUILTY** [comment]
![image](https://user-images.githubusercontent.com/56719856/89366682-e97a3800-d709-11ea-8cdb-13798431974a.png)
我用的3.5.6版本的，你说的是通用UI版本的，那个样例全是写的死数据

**Comment by yangchch6** [comment]
使用3.5.6版本的 matchUrl，第一次打开就能选中表格数据，没有复现你的问题。
```
class Demo1 extends Component {
    render () {
        return (
            <div className="demoPadding">
                <RefMultipleTableWithInput
                    title='职级'
                    strictMode={true}
                    backdrop = {false}
                    param = {{//url请求参数
                        refCode:'post_level',//test_common||test_grid||test_tree||test_treeTable
                    }}
                    refModelUrl = {{
                        tableBodyUrl:`https://mock.yonyoucloud.com/mock/1264/pap_basedoc/common-ref/blobRefTreeGrid`,//表体请求
                        refInfo:`https://mock.yonyoucloud.com/mock/1264/pap_basedoc/common-ref/refInfo`,//表头请求
                    }}
                    matchUrl={`https://mock.yonyoucloud.com/mock/13949/pap_ref/ommon-ref`}
                    valueField="refpk"
                    displayField="refpk"
                    emptyBut
                    value={'{"refname":"ITOCHU PLASTICS PTE.,LTD","refpk":"cc791b77-bd18-49ab-b3ec-ee83cd40012a"}'}
                >
                </RefMultipleTableWithInput>
            </div>
        )
    }
}

export default Demo1;

```

**Comment by DYKGUILTY** [comment]
找到原因了，你们代码生成器生成的RefCommon组件封装里面引入的原因
![image](https://user-images.githubusercontent.com/56719856/89374978-4c29fe80-d71f-11ea-8c67-5f9846bded3c.png)
生成的代码引入是这个dist文件夹下的，后来对比官网引入的是下面这个
![image](https://user-images.githubusercontent.com/56719856/89375089-898e8c00-d71f-11ea-82a7-bcabff6ebd99.png)
我不是前端，这两个其实是在一个包里不同文件夹下，不知道是不是哪里有问题，希望你们可以参考一下，换了import后打开已经可以默认选中了
