### ISSUE TITLE
npm or yarn cannot be downloaded

### ISSUE THREAD

**Issue by huffyq** [iuap-design/tinper-bee#621]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for bee-tree@2.1.22
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'tinper-bee'
npm ERR! notarget 

ps: the specified version does not work

**Comment by yangchch6** [comment]
使用 taobao 镜像下载不到 bee-tree@2.1.22 版本的问题已经解决了，如果以后再遇到类似问题，可以尝试通过以下方法解决：
1、使用 npm 官网镜像下载
```
npm config set registry https://registry.npmjs.org
```
2、手动从NPM同步包至CNPM
操作方法参考：https://blog.csdn.net/baozhang007/article/details/89486111
