### ISSUE TITLE
DatePicker组件，在开启keyboardInput为true时，无法正常录入日期。

### ISSUE THREAD

**Issue by liyzb** [iuap-design/tinper-bee#623]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：
DatePicker2.3.28

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
DatePicker组件，在开启keyboardInput为true时，无法正常录入日期。
### 1、组件相关代码

```

代码粘贴区域

```

**Comment by whizbz11** [comment]
问题处理，可以更新版本验证
