### ISSUE TITLE
iuap 3.5.6 树形参照如何控制某些节点不可选

### ISSUE THREAD

**Issue by DYKGUILTY** [iuap-design/tinper-bee#624]
## 环境及版本信息

- `tinper-bee` 版本号:  
iuap 3.5.6

- 若使用单个组件，请标明该组件版本号：
iuap 3.5.6

- 所使用的操作系统：
 Windows

## 您所在的部门或项目名称：
mes

## 描述这个问题:
树形参照所有节点均可点击选择,不论是子节点还是父节点

## 期望的行为:
只想让其选择子节点或者某一部分节点怎么做

**Comment by yangchch6** [comment]
参考 ref-tree 的 `treeNodeDisabledKey` 属性说明：http://bee.tinper.org/tinper-acs/ref-tree#RefTreeWithInput
![image](https://user-images.githubusercontent.com/33412781/91127960-dee40a80-e6d9-11ea-9a5d-b313459d4568.png)

**Comment by XYooo** [comment]
pap-refer的版本号是1.1.1 才能支持treeNodeDisabledKey和treeNodeDisabledFunc
