### ISSUE TITLE
bee-datepicker中使用getCalendarContainer属性，展示日期面板的小按钮点击无反应

### ISSUE THREAD

**Issue by MINGXINICE** [iuap-design/tinper-bee#625]
## 环境及版本信息

- `tinper-bee` 版本号:  tinper-bee: "^2.2.1",

- 若使用单个组件，请标明该组件版本号：bee-datepicker: "^2.3.9",

- 当前项目中`react`的版本号：16.6.3

- 所使用的操作系统：Windows/Mac

- 所使用的浏览器：Chrome

## 描述这个问题: 想在表格字段中使用getCalendarContainer这个属性，参照示例这样写后，发现日框那个小按钮点击就没反应了，日期面板无法弹出

![image](https://user-images.githubusercontent.com/22900344/91151564-65a3e200-e6f0-11ea-8d49-2c0cbda9eef7.png)

**Comment by yangchch6** [comment]
调试看下 getCalendarContainer 的返回值是否有效

**Comment by MINGXINICE** [comment]
> 是否 @yangchch6 

![image](https://user-images.githubusercontent.com/22900344/91673659-be97ce00-eb67-11ea-99d7-0c6f465656c3.png)
![image](https://user-images.githubusercontent.com/22900344/91673671-d0797100-eb67-11ea-83a8-a91d8ba69f88.png)
