### ISSUE TITLE
Transfer组件,希望可以实现双击添加,双击移除的功能,或者开放双击的API

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#626]
## 环境及版本信息

- `tinper-bee` 版本号:  

  2.3.7
- 当前项目中`react`的版本号：

16.6.3
- 所使用的操作系统：
Windows/Mac

- 所使用的浏览器：

Chrome
## 您所在的部门或项目名称：
用友金融-租赁与链融云
## 描述这个问题:
   使用 Transfer组件的时候,目前只能一个一个的点击选中,因为需要选择的选项比较多, 客户一直习惯双击选择. 但是目前组件不支持双击选择;

## 期望的行为:
    1.希望可以实现双击添加和双击移除的功能,
    2. 或者提供双击API也行.

**Comment by whizbz11** [comment]
功能已经实现了，版本为2.0.20
