### ISSUE TITLE
穿梭框期望能支持批量拖拽

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#627]
## 环境及版本信息

- `tinper-bee` 版本号:  
最新版

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：
mac

- 所使用的浏览器：
chrome

## 描述这个问题:
期望结果
1.穿梭框能支持批量的从左边拖拽到右边

2.当设置dragger=true  中间可以有穿梭按钮  右边框的内容支持拖拽排序

### 1、组件相关代码

```

代码粘贴区域

```

**Comment by Gaox2025f** [comment]
请试一下2.0.20版本的穿梭框 @ahua52
