### ISSUE TITLE
bee-complex-grid动态加载columns时空白显示问题

### ISSUE THREAD

**Issue by riseshining** [iuap-design/tinper-bee#628]
## 环境及版本信息

- `tinper-bee` 版本号:  2.4.0

- 若使用单个组件，请标明该组件版本号："bee-complex-grid": "^2.2.1"

- 当前项目中`react`的版本号："react": "^16.8.6"

- 所使用的操作系统：Mac

- 所使用的浏览器：chrom 84

## 描述这个问题:
bee-complex-grid 组件不能动态设置columns

### 1、组件相关代码

使用 bee-complex-grid 时无法实现动态加载columns，页面表格区域会出现空白显示

```
        {showGridType ? (
          <Grid
            className="gird-parent"
            columns={this.gridColumns}
            onRowHover={this.onRowHover}
            hoverContent={renderHoverBtns}
            data={queryObj.list}
            rowKey={(r, i) => 'showGridType' + i} //生成行的key
            paginationObj={paginationObj} //分页
            multiSelect={false} //false 单选，默认多选
            scroll={{ y: listTableHeight }}
          />
        ) : (
          <Grid
            className="gird-parent"
            columns={this.gridColumns1}
            data={queryObj.list}
            rowKey={(r, i) => 'showGType' + i} //生成行的key
            paginationObj={paginationObj} //分页
            multiSelect={false} //false 单选，默认多选
            scroll={{ y: listTableHeight }}
          />
        )}
```

### 2、报错信息
页面打开默认加载正常，默认加载gridColumns
![image](https://user-images.githubusercontent.com/19453091/91388001-11703d80-e869-11ea-98b3-026938ec4223.png)

修改筛选条件后点击查询，需要加载另一个gridColumns1时显示空白
![image](https://user-images.githubusercontent.com/19453091/91388025-1b923c00-e869-11ea-8d11-f30603664a2d.png)

将该组件换为tinper的Table组件，无此问题

**Comment by yangchch6** [comment]
添加参数 `noReplaceColumns={true}` 试一下

**Comment by riseshining** [comment]
> 添加参数 `noReplaceColumns={true}` 试一下

看文档不仔细了，可以了，谢谢
