### ISSUE TITLE
穿梭框数据没有跟新

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#629]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 描述这个问题:
![image](https://user-images.githubusercontent.com/19704104/91411550-1211cf80-e87b-11ea-9f89-ab913914c289.png)

场景还原
我切换左边的数据来源  会把数据带到穿梭框  
当我带回新的数据到已选框内   已选框的数据没有更新
### 1、组件相关代码

```

代码粘贴区域

```

**Comment by whizbz11** [comment]
升级新版本验证
