### ISSUE TITLE
bee-upload上传组件^2.1.2上传Networkcancled

### ISSUE THREAD

**Issue by WHY7797** [iuap-design/tinper-bee#631]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码
引入bee-upload :
import Upload from "bee-upload";
上传到平台服务器
 const fileProps = {
        action: "/iuap-saas-filesystem-service/file/upload",
        multiple: false,
        data: {
          filepath: formatedUUID(),
          groupname: "SocialOrganization",
          url: true,
          isreplace: false
        }
      };
调用上传组件
{receiptFileList.length==0?<Upload
                      {...fileProps}
                      fileList={receiptFileList}
                      accept='.pdf'
                      onChange={({ ...info }) => {
                        this.handleFileChange("receiptFileList", info);
                      }}
                     // customRequest={this.customRequest()}
                >
                <Button shape="border">
                  <Icon type="uf-upload" />上传
                </Button>
                </Upload>
在onchange方法中把文件更改：
handleFileChange = (type, info) => {
      let fileList = info.fileList;
      ProgressBar.start()
        actions.AdminiPunish.updateState({ [type]: fileList })
      ProgressBar.done()
    };
在页面中点击上传，选择文件后，Network报cancled错误，在组件的info信息中，
status为uploading,response为undefined,

### 2、报错信息
在页面中点击上传，选择文件后，Network报cancled错误，在组件的info信息中，
status为uploading,response为undefined,

![image](https://user-images.githubusercontent.com/47022131/91629320-8d4dbf80-e9fa-11ea-8737-a8396586bf63.png)
![image](https://user-images.githubusercontent.com/47022131/91629333-bbcb9a80-e9fa-11ea-9c66-ce2e036b853f.png)
![image](https://user-images.githubusercontent.com/47022131/91629340-c9812000-e9fa-11ea-9d55-4ab3f9ad3fca.png)

**Comment by Gaox2025f** [comment]
@WHY7797 有和服务端同学商定好接受文件的方式了吗（文件流）？如果后端不支持的话，就是有问题的。可以让后端同学mock一下，让ta给你看到他的接口确实可以这样接收文件流。以及，检查一下那些定时器的使用有没有问题。
