### ISSUE TITLE
Grid组件,导出excel数据时, 能够自定义导出的excel的样式

### ISSUE THREAD

**Issue by liangyongming** [iuap-design/tinper-bee#633]
## 环境及版本信息

期望实现的功能:
使用 tinper-bee的grid组件实现导出数据到excel中, 期望能够自定义导出后的样式,
例如, 1. 导出的列宽,  
         2. 导出数字时,能够实现 右对齐, 保留两位小数, 千分位. 等 会计专用格式;

**Comment by whizbz11** [comment]
可以设置column的width，可以实现列宽的自定义，其余特殊样式依赖的底层xlsx目前还没有对外开源支持
