### ISSUE TITLE
bee-table组件ie11兼容问题

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#634]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.5

- 若使用单个组件，请标明该组件版本号：bee-table@2.2.41

- 当前项目中`react`的版本号：16.13.0

- 所使用的操作系统：Window

- 所使用的浏览器：IE11

## 描述这个问题:

bee-table 组件里面有用到 querySelectorAll 去取元素列表， 然后用了 forEach 方法直接遍历，这个在ie11下面有兼容问题，需要先把获取的NodeList 转换 数组、

**Comment by whizbz11** [comment]
![image](https://user-images.githubusercontent.com/13316317/92547954-76c02780-f288-11ea-999f-e5bf4f7a2467.png)
IE11下可以正常渲染官网的示例，可以先升级最新table(2.2.63)试下。如果还有报错，请标注具体的代码，谢谢

**Comment by loongMa** [comment]
ok,更新完了以后解决了
