### ISSUE TITLE
bee-modal组件 flex布局 ie11兼容问题

### ISSUE THREAD

**Issue by loongMa** [iuap-design/tinper-bee#635]
## 环境及版本信息

- `tinper-bee` 版本号:  2.3.5

- 若使用单个组件，请标明该组件版本号：bee-modal@2.1.11

- 当前项目中`react`的版本号：16.13.0

- 所使用的操作系统：Window

- 所使用的浏览器：ie11

## 描述这个问题:
  flex 布局在ie11下的兼容问题，u-modal-content 使用了flex布局， class类 .u-modal-body 中使用的flex：1在ie11下会被
的默认解析为 flex： 1 1 0px; 从而造成 Modal.Body 内容塌陷, 需改为 flex: 1 0 auto;

![image](https://user-images.githubusercontent.com/20429458/92546249-b258f280-f284-11ea-981e-1bc7ebda3d4a.png)

**Comment by Gaox2025f** [comment]
2.2.9版本已经解决了这个问题
