### ISSUE TITLE
你好，这个库有vue库吗。

### ISSUE THREAD

**Issue by sixsfish** [iuap-design/tinper-bee#646]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

```

代码粘贴区域

```

**Comment by wandercode125** [comment]
没有vue库，统一技术栈是react
