### ISSUE TITLE
Form表单的resetFields钩子函数，没办法清空MonthPicker，实际值已经清空，但是显示值没有清除

### ISSUE THREAD

**Issue by wangkimi** [iuap-design/tinper-bee#649]
## 环境及版本信息

- `tinper-bee` 版本号:  

tinper-bee@2.2.3

- 若使用单个组件，请标明该组件版本号：

bee-form@2.0.14
- 当前项目中`react`的版本号：

 "react": "16.8.2",
    "react-dom": "16.8.2",
    "react-intl": "2.8.0",
- 所使用的操作系统：

Windows
- 所使用的浏览器：

Chrome 80
## 您所在的部门或项目名称：

中兴项目组
## 描述这个问题:
Form表单的resetFields钩子函数，没办法清空MonthPicker，实际值已经清空，但是显示值没有清除
### 1、组件相关代码

```
  <LocaleMonthPicker
                                            placeholder=''
                                            {...getFieldProps('month', {
                                                initialValue: ''
                                            })}
                                        />
 reset = () => {
        this.props.form.resetFields();
        this.props.reset();
    }

```

## 期望的行为:

重置表单，同时清空实际值和显示的值

**Comment by niceHou** [comment]
bee-datapicker升指最新版本
