### ISSUE TITLE
RefTreeWithInput  组件 disabledKey 当出现在父节点 收起展开三角按钮用不了 希望文字不能点 按钮还能用

### ISSUE THREAD

**Issue by ahua52** [iuap-design/tinper-bee#652]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

"ref-tree": "2.1.0",

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

```

代码粘贴区域

```

### 2、报错信息

![image](https://user-images.githubusercontent.com/19704104/103071837-6ba6c280-45ff-11eb-8656-61e032f670c6.png)

**Comment by Gaox2025f** [comment]
![image](https://user-images.githubusercontent.com/57103391/103611299-f4f1b980-4f5c-11eb-983b-4093d00a86bb.png)
@ahua52  请在使用该组件的时候加上截图中的这个属性treeProps={{mustExpandable:true}}，可以达到效果
