### ISSUE TITLE
bee-tabs中很多layout trash，建议使用fastdom优化，或重构

### ISSUE THREAD

**Issue by banyudu** [iuap-design/tinper-bee#653]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

bee-tabs@3.0.0

- 当前项目中`react`的版本号：

react@16.14.0

- 所使用的操作系统：

Mac

- 所使用的浏览器：

Chrome 87.0.4280.88

### 1、组件相关代码

在bee-tabs中多处在render中获取layout的操作，如 https://github.com/tinper-bee/bee-tabs/blob/6a287c546eec6527c84d21ef5767cd338984e559/src/utils.js#L75 ，这样会导致产生layout transh，在大的工程中特别浪费性能。

![image](https://user-images.githubusercontent.com/2416493/103112025-71e38000-468d-11eb-988c-ec5b4234dae4.png)

如上图所示，在YS项目的列表进卡片操作中，仅 utils.js 中的 `getStyle`函数一项就消耗了12%的总时间。虽然这与Tabs多次渲染也有关系，但是同时也说明了bee-tabs自身性能极差。

```javascript

export function getStyle(el, property) {
  return +getComputedStyle(el).getPropertyValue(property).replace('px', '');
}


```

## 当前的行为：效果（可截图说明）及动作描述

当前性能过差，在渲染过程中查询layout

## 期望的行为:

期望能够优化掉这种代码，使用`fastdom`延时处理layout操作，或者干脆重构相关代码。

**Comment by Gaox2025f** [comment]
done
