### ISSUE TITLE
表格行拖拽，没办法替换第一行

### ISSUE THREAD

**Issue by GoodPigWa** [iuap-design/tinper-bee#654]
## 环境及版本信息

- `tinper-bee` 版本号:  

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

### 1、组件相关代码

```

代码粘贴区域

```

## 当前的行为：效果（可截图说明）及动作描述

当拖拽第三行数据，想拖拽到第一行是没办法的

![image](https://user-images.githubusercontent.com/25141736/103392062-0569f480-4b57-11eb-9119-883422a03337.png)

## 期望的行为:

![image](https://user-images.githubusercontent.com/25141736/103392044-f2efbb00-4b56-11eb-9d82-6b92606895f1.png)

**Comment by whizbz11** [comment]
bee-table v2.3.1
