### ISSUE TITLE
这个表格拖拽没办法拖拽到第一行

### ISSUE THREAD

**Issue by GoodPigWa** [iuap-design/tinper-bee#655]
## 环境及版本信息

- `tinper-bee` 版本号:  
2.2.61

- 若使用单个组件，请标明该组件版本号：

- 当前项目中`react`的版本号：

- 所使用的操作系统：

- 所使用的浏览器：

## 您所在的部门或项目名称：

香港用友  HCM   段娜
## 描述这个问题:
这个表格拖拽没办法拖拽到第一行
### 1、组件相关代码

```

代码粘贴区域

```

## 当前的行为：效果（可截图说明）及动作描述

![image](https://user-images.githubusercontent.com/25141736/103392968-4237ea80-4b5b-11eb-817b-0f87dfd341b0.png)

**Comment by whizbz11** [comment]
bee-table v2.3.1
