### ISSUE TITLE
table

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#67]
使用全选表格的时候，一开始，给表体数据数组的内的每一行对象加入了key值，用来保证循环渲染。之后发现table组件上有rowKey这个接口，我就放弃手动加key了，给rowKey接口了一个pk字段名，渲染时不警告，不报错。可是当我选中表内任意一行的时候，表格都会全选。这种情况在我没有为表体数据传入key值的时候出现过，所以想问一下，会不会是rowKey这个接口有些问题

**Comment by HuYuee** [comment]
问题已修复，请下载v1.0.12
