### ISSUE TITLE
 使用FormItem时对其添加inputAfter，在不同的分辨率下会出现错位的情况

### ISSUE THREAD

**Issue by BoyuZhou** [iuap-design/tinper-bee#70]
### Bug 报告

- __Package version(s)__: bee-form----->"~1.0.21"

#### 描述这个问题:

使用FormItem时对其添加inputAfter，在不同的分辨率下会出现错位的情况

#### 当前的行为:

![_20180120161533](https://user-images.githubusercontent.com/29479771/35181482-49db1022-fdfd-11e7-88a0-26f29b62bf46.png)

#### 期望的行为:

在任何分辨率的情况下都不会出现错位的情况
![_20180120161656](https://user-images.githubusercontent.com/29479771/35181487-6259fb68-fdfd-11e7-8824-3d043c916725.png)

**Comment by lucian55** [comment]
转到本主
