### ISSUE TITLE
Table组件横向滚动问题

### ISSUE THREAD

**Issue by wt07060210** [iuap-design/tinper-bee#72]
### Table组件横向滚动问题

- __Package version(s)__: (版本号)

#### 描述这个问题:

当浏览器分辨率大的时候，会出现最后面的固定列重复出现的问题，相关截图已微信给胡玥了

#### 当前的行为:

当浏览器分辨率大的时候，会出现最后面的固定列重复出现的问题

#### 期望的行为:

当浏览器分辨率大的时候，也不出现这种问题

**Comment by wt07060210** [comment]
![1516696311 1](https://user-images.githubusercontent.com/24653539/35265405-f4f5ff1c-005a-11e8-9348-d886c729eaaa.jpg)

**Comment by HuYuee** [comment]
不要每一列都设置宽度，可以留一列或者两列让其自动伸展
