### ISSUE TITLE
Modal显示后固定整个body，不让其滚动

### ISSUE THREAD

**Issue by wt07060210** [iuap-design/tinper-bee#75]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

Modal组件显示后，希望整个body是不可以滚动的

#### 当前的行为:

当前Modal组件显示后，整个body是可以滚动的，我们这边要是一个个去给body加overflow:hidden太麻烦，希望平台给从源头上加一下

#### 期望的行为:

当Modal组件显示后，整个body是不可以滚动的。而且我们现在Modal都是从整个tinper-bee(0.6.2)引入的，希望改进后，看看能不能把整个tinper-bee("^0.6.2")里的modal改成这种，谢谢！

**Comment by HuYuee** [comment]
具体问题可以发下在线地址我们查看下，现在最新版本我们这边提供的就是不可以滚动的，可以参见如下[地址](http://bee.tinper.org/bee-modal)
