### ISSUE TITLE
有关Table每列信息显示的问题

### ISSUE THREAD

**Issue by wt07060210** [iuap-design/tinper-bee#76]
### Bug 报告

- __Package version(s)__: (版本号)

#### 描述这个问题:

场景：整个项目布局采用最小宽度1260，然后超过1260后100%自适应，我们现在是按照百分比去给每列分配宽度的。
假如现在table中有10条数，其中5条的某一列的文字特别长，我们希望超出部分是  ...  形式，鼠标hover的时候气泡框显示全部内容。而另外5条数据因为其本身文字就比较少，所以hover的时候，不出现气泡框。

#### 当前的行为:
当前没有什么好的方案，希望平台可以给与我们提供相应的方案或者其他类似解决方案的技术上的支持，谢谢！
#### 期望的行为:
提供相应的方案或者其他类似解决方案的技术上的支持，谢谢！
![1516696172](https://user-images.githubusercontent.com/24653539/35265293-aeb74722-005a-11e8-91ee-6ab8d9e4f5aa.png)

**Comment by HuYuee** [comment]
该功能只能业务上面自己去处理
