### ISSUE TITLE
bee-dropdown 中的item能否自定义

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#84]
### Bug 报告

- __Package version(s)__: (版本号)  1.2.9 

#### 描述这个问题:

比如现在的item的内容，是确定好的，文字、icon。

#### 当前的行为:

我需要在里面显示多个字段，而且自己布局。

#### 期望的行为:

希望下拉中的item自己定义。 效果如下：

![image](https://user-images.githubusercontent.com/21353460/36637727-b4258746-1a1d-11e8-83f5-81ccd4b091e2.png)

**Comment by BoyuZhou** [comment]
每个Item是可以自己编辑内容的，
![image](https://user-images.githubusercontent.com/14073759/36655532-30f612fa-1afe-11e8-993a-4f48d79afe36.png)
