### ISSUE TITLE
bee-tree组件需求（急！）

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#86]
### 需求列表
       1、树组件需要加入区块的概念，意思就是点击树旁边的所属的区块也能触发事件。
![image](https://user-images.githubusercontent.com/17383237/36715986-ae8d43b6-1bd3-11e8-9833-4ac7bc0103e7.png)
       2、树的子节点点击，获得父节点的一些信息的渠道。
![image](https://user-images.githubusercontent.com/17383237/36716068-f072726a-1bd3-11e8-8474-2016985bf4c0.png)
      3、onSelect方法只能获取一个属性的属性值，可不可以加入多个属性的值。
目前采用刘绍振提供的 ‘字符串拼接方案’ 暂时代替。

**Comment by ahua52** [comment]
第一个问题： 你只需要自定义点击节点的a标签的宽度就行，设置成你想要的宽度。比如 .u-tree li a{width：100%}    因为每个人的对树的宽度需求不一，目前节点的宽度自适应与节点文本的长度。

第二个问题  点击当前节点会触发的回调 onSelect方法 有两个参数。第一个参数：当前点击的节点key。第二个参数：可获取整个tree的信息    onSelect(selectedKeys, newSt)

**Comment by whizbz11** [comment]
关于第一个问题：
 目前select选中方法对应节点中的a标签，可以修改a标签的宽度即可扩大范围
```
.u-tree li a {
  width: calc(100% - 30px);

   margin-left: -20px;

   padding-left: 20px;
}
```
第二三个问题：
可以在节点上自定义属性例如
![image](https://user-images.githubusercontent.com/13316317/36773109-ea8cddc6-1c92-11e8-834e-cef9a0b05349.png)
在onSelect上的方法获取自定义的属性
```
 onSelect(selectedKeys, info) {
    console.log('我定义的属性', info.node.props.attr);
    this.setState({ selectedKeys });
  }
```

**Comment by yang123guo** [comment]
1和3问题解决了，但是获取父元素信息还得自己手动遍历。多谢！
