### ISSUE TITLE
嵌套子表格，子表数据冲突问题

### ISSUE THREAD

**Issue by wangshhj** [iuap-design/tinper-bee#87]
### Bug 报告
嵌套子表格，当第一行表格展开时，再点第二行表格展开，第一行子表格的数据会变成和第二行子表格一样。

- __Package version(s)__: (版本号)

#### 描述这个问题:

嵌套子表格，当第一行表格展开时，再点第二行表格展开，第一行子表格的数据会变成和第二行子表格一样。

#### 期望的行为:

每行子表格数据互不影响

**Comment by HuYuee** [comment]
可以根据此api3个参数灵活应用即可
```javascript
expandedRowRender = (record, index, indent)=>{}
```

**Comment by wangshhj** [comment]
这个组件使用量较多，希望能尽快修复这个问题

**Comment by HuYuee** [comment]
@wangshhj 通过下图方式即可


![image](https://user-images.githubusercontent.com/12147318/37510839-78620922-2937-11e8-9da0-54d6244e93f4.png)

**Comment by HuYuee** [comment]
这样吧，我这边重新更新下官网demo
