### ISSUE TITLE
逻辑合理性需求（业务组提出） 模块：bee-pagination

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#88]
### 需求说明
-lastest (版本号)

#### 描述这个问题:
如图
![image](https://user-images.githubusercontent.com/17383237/36966169-d2e7ffea-2096-11e8-9c56-61be2bb6fad2.png)
5和6之间有无效的  ...  业务组在使用的过程中有反馈。

#### 期望的行为:
... 出现的时机 需要做个判断

**Comment by HuYuee** [comment]
你的这个组件的参数是多少？

**Comment by yang123guo** [comment]
items={n}    n得出数据此时为6
maxButtons={5}

**Comment by GuoYongfeng** [comment]
目前已解决
