### ISSUE TITLE
多选表格getSelectedDataFunc接口回调参数不正确

### ISSUE THREAD

**Issue by 791045873** [iuap-design/tinper-bee#91]
### Bug 报告

- __Package version(s)__: (版本号)"bee-table": "^1.0.12",

#### 当前的行为:
我有一个这样的需求，界面上有两个表格，表格A与表格B（B的所有项被默认勾选），A是B的超集，当我在A中勾选了一行数据，B会得到这条数据，当我从A中将数据去掉勾选，B就会相应的去掉自己的相关数据。如果在B中取消勾选某一行，则B中这行数据消失。A中对应行数据取消勾选。

所以我在A上同时使用了getSelectedDataFunc，selectedRow。这两个接口。
这导致了我在A上勾选多条数据时，getSelectedDataFunc接口调用回调所传入的参数，只是当前刚刚勾选的这一项，而不是勾选的所有项

**Comment by GuoYongfeng** [comment]
1、我理解的是：`这个需求还不是主子表，是表数据选中在另外一个表中展示，有点类似表数据的穿梭框。`
2、TODO：你的要求是 `getSelectedDataFunc` 方法除了要传入所选的当前行数据外，还需要传入当前所选的所有行数据，是这样吧，如：

```
getSelectedDataFunc = ( currentSlectedData, allSeclectData) => {}

```

@791045873

**Comment by HuYuee** [comment]
@791045873 bee-table最新版已解决，可以下载bee-tableV1.0.14版本
