### ISSUE TITLE
在ie9 下面 bee-tabs组件显示不对

### ISSUE THREAD

**Issue by jonyshi** [iuap-design/tinper-bee#92]
### Bug 报告

- __Package version(s)__: (版本号)

在ie9 下面 bee-tabs组件显示不对

![image](https://user-images.githubusercontent.com/21353460/37744717-ae37a35e-2dab-11e8-904c-621a8bd6f061.png)

**Comment by kvkens** [comment]
加Tabs组件上

```js

 <Tabs
                destroyInactiveTabPane
              >
</Tabs>
```
