### ISSUE TITLE
Transfer放在模态框里不显示数据

### ISSUE THREAD

**Issue by jrt8** [iuap-design/tinper-bee#94]
### Bug 报告

- __Package version(s)__: 1.3.2

#### 描述这个问题:
使用react组件库的穿梭框Transfer，Transfer放在模态框里不显示数据。该怎么处理。貌似好像是和懒加载有关。
![image](https://user-images.githubusercontent.com/16360402/38290219-c99ca584-380c-11e8-9967-1b5b0a77cca3.png)

#### 当前的行为:
 只有当把页面缩放的时候，模态框的Transfer才会显示出数据。

#### 期望的行为:
 在模态框里可以正常显示出Transfer里的数据

**Comment by ahua52** [comment]
添加 lazy={{container:"modal"}}  参数到Transfer组件  <Transfer   lazy={{container:"modal"}}  />   请下载1.0.6或以上版本

**Comment by jonyshi** [comment]
次问题，是由于bee-modal 和transfer渲染顺序导致。
解决办法：
bee-transfer 升级新的1.0.6版本。
在bee-modal中不要使用lazy属性。

**Comment by jrt8** [comment]
可以正常使用了
