### ISSUE TITLE
Table组件出现重复列

### ISSUE THREAD

**Issue by jrt8** [iuap-design/tinper-bee#96]
### Bug 报告

- __Package version(s)__: (1.3.2)

#### 描述这个问题:
在Table组件的columns设置的列在渲染的时候，重复出现。如下图的方向与辅助核算列。
![image](https://user-images.githubusercontent.com/16360402/38540526-c95495fc-3cce-11e8-9ca0-ecca93bfd5be.png)

![image](https://user-images.githubusercontent.com/16360402/38540645-2f93a826-3ccf-11e8-878a-2bf50d990a74.png)

**Comment by jonyshi** [comment]
你把其中一列的width去掉试试。

**Comment by jrt8** [comment]
试过了，还是出现重复列

**Comment by jonyshi** [comment]
表格的columns 里面，必须有一个列不设置width，对重复的那一列设置成width:100  就可以了。

**Comment by jrt8** [comment]
这个问题还是没有解决，等电脑升级配置后再研究
