### ISSUE TITLE
bee-table需求和bug

### ISSUE THREAD

**Issue by yang123guo** [iuap-design/tinper-bee#97]
### bug描述：
1、当有固定列，并且列的数目不够多的时候，固定列会重复渲染。

2、有固定列，同时有行内expandedRowRende嵌套字表，需要把固定列的高度扩大来使得固定列这一行和左侧 行+嵌套内容同高度。否则有错位。

#### 需求：
1、固定列且使用scroll属性出现了滚动条，需要一个控制到滚动条禁止滚动的功能，如果已经滚动了滚动条，那么可以使得滚动条回到最左侧。

**Comment by jonyshi** [comment]
1. 当有固定列，并且列的数目不够多的时候，固定列会重复渲染。
  此问题需要设置 
const columns = [ 
  { title: "Column 1", dataIndex: "address", key: "1" },
  { title: "Column 2", dataIndex: "address", key: "2" },
  { title: "Column 3", dataIndex: "address", key: "3" },
  { title: "Column 4", dataIndex: "address", key: "4" },
  { title: "Column 7", dataIndex: "address", key: "7" },
  { title: "Column 8", dataIndex: "address", key: "8" , fixed: "right",width:120}  //最后这一列需要设置一个width即可解决。
];

**Comment by jonyshi** [comment]
2.固定列设置高度即可

```
 expandedRowRender = (record, index, indent) => {
    return (
      <Table
        columns={columns16}
        style={{height:200}} 
        data={this.state.data_obj[record.key]} 
        title={currentData => <div>标题: 这是一个标题</div>}
        footer={currentData => <div>表尾: 我是小尾巴</div>}
      />
    );
  };

```

 style={{height:200}}

**Comment by BoyuZhou** [comment]
2、有固定列，同时有行内expandedRowRende嵌套字表，需要把固定列的高度扩大来使得固定列这一行和左侧 行+嵌套内容同高度。否则有错位。 @jonyshi  解决一下这个

**Comment by whizbz11** [comment]
1、固定列且使用scroll属性出现了滚动条，需要一个控制到滚动条禁止滚动的功能，如果已经滚动了滚动条，那么可以使得滚动条回到最左侧。这个问题已经解决，如果传入resetScroll属性，就会重置
